"""
Django settings for reignitehome project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG",cast=bool, default=False)

# Behind DO App Platform / proxies
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

ALLOWED_HOSTS = [
    "tryagaintext-app-k6uby.ondigitalocean.app",
    "tryagaintext.com",
    "www.tryagaintext.com"
]

CSRF_TRUSTED_ORIGINS = [
        "https://tryagaintext.com",
        "https://www.tryagaintext.com",
        "https://tryagaintext-app-k6uby.ondigitalocean.app",
]

# HTTPS hardening
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

if DEBUG:
    ALLOWED_HOSTS += [
        "127.0.0.1",
        "localhost"
    ]
    
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost",
        "http://127.0.0.1",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "https://tryagaintext-app-k6uby.ondigitalocean.app",
        "http://tryagaintext.com",
    ]
    
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'allauth',
    'allauth.account',
    
    'reignitehome',
    'conversation',
    'mobileapi',
    'pricing',
    
    'rest_framework',
    'rest_framework.authtoken',

    'cloudinary_storage',
    'cloudinary',
    'community',
]

# Cloudinary (image storage for community posts)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
}

# settings.py
# Mobile API public endpoint rate limits (Phase 1).
MOBILE_RATELIMIT_REGISTER_IP = config("MOBILE_RATELIMIT_REGISTER_IP", default="5/10m")
MOBILE_RATELIMIT_REGISTER_EMAIL = config("MOBILE_RATELIMIT_REGISTER_EMAIL", default="3/10m")
MOBILE_RATELIMIT_LOGIN_IP = config("MOBILE_RATELIMIT_LOGIN_IP", default="20/10m")
MOBILE_RATELIMIT_LOGIN_USERNAME = config("MOBILE_RATELIMIT_LOGIN_USERNAME", default="10/10m")
MOBILE_RATELIMIT_PASSWORD_RESET_IP = config("MOBILE_RATELIMIT_PASSWORD_RESET_IP", default="5/10m")
MOBILE_RATELIMIT_PASSWORD_RESET_EMAIL = config("MOBILE_RATELIMIT_PASSWORD_RESET_EMAIL", default="3/10m")
MOBILE_RATELIMIT_REPORT_IP = config("MOBILE_RATELIMIT_REPORT_IP", default="20/10m")
MOBILE_RATELIMIT_GENERATE_IP = config("MOBILE_RATELIMIT_GENERATE_IP", default="60/10m")
MOBILE_RATELIMIT_GENERATE_DEVICE = config("MOBILE_RATELIMIT_GENERATE_DEVICE", default="60/10m")
MOBILE_RATELIMIT_GENERATE_OPENERS_IP = config("MOBILE_RATELIMIT_GENERATE_OPENERS_IP", default="20/10m")
MOBILE_RATELIMIT_GENERATE_OPENERS_DEVICE = config("MOBILE_RATELIMIT_GENERATE_OPENERS_DEVICE", default="20/10m")
MOBILE_RATELIMIT_EXTRACT_IP = config("MOBILE_RATELIMIT_EXTRACT_IP", default="20/10m")
MOBILE_RATELIMIT_EXTRACT_DEVICE = config("MOBILE_RATELIMIT_EXTRACT_DEVICE", default="20/10m")
MOBILE_RATELIMIT_EXTRACT_STREAM_IP = config("MOBILE_RATELIMIT_EXTRACT_STREAM_IP", default="20/10m")
MOBILE_RATELIMIT_EXTRACT_STREAM_DEVICE = config("MOBILE_RATELIMIT_EXTRACT_STREAM_DEVICE", default="20/10m")
MOBILE_RATELIMIT_ANALYZE_IP = config("MOBILE_RATELIMIT_ANALYZE_IP", default="20/10m")
MOBILE_RATELIMIT_ANALYZE_DEVICE = config("MOBILE_RATELIMIT_ANALYZE_DEVICE", default="20/10m")
MOBILE_RATELIMIT_ANALYZE_STREAM_IP = config("MOBILE_RATELIMIT_ANALYZE_STREAM_IP", default="20/10m")
MOBILE_RATELIMIT_ANALYZE_STREAM_DEVICE = config("MOBILE_RATELIMIT_ANALYZE_STREAM_DEVICE", default="20/10m")
MOBILE_RATELIMIT_RECOMMENDED_OPENERS_IP = config(
    "MOBILE_RATELIMIT_RECOMMENDED_OPENERS_IP",
    default="60/10m",
)

# Community rate limits
COMMUNITY_RATELIMIT_POST_CREATE = config("COMMUNITY_RATELIMIT_POST_CREATE", default="10/1h")
COMMUNITY_RATELIMIT_COMMENT_CREATE = config("COMMUNITY_RATELIMIT_COMMENT_CREATE", default="30/1h")

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'mobileapi.auth.LenientTokenAuthentication',  # First - for mobile API
        'rest_framework.authentication.SessionAuthentication',  # Second - for web browsable API
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",  # for screenshot uploads
        "rest_framework.parsers.FormParser",
    ],
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_ratelimit.middleware.RatelimitMiddleware',
    
    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]

RATELIMIT_VIEW = "reignitehome.views.ratelimited_error"

ROOT_URLCONF = 'reignitehome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reignitehome.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

CONN_MAX_AGE = config("CONN_MAX_AGE",cast=int,default=30)
DATABASE_URL = config("DATABASE_URL",default=None)

if DATABASE_URL is not None:
    import dj_database_url
    DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_health_checks=True,
        conn_max_age=CONN_MAX_AGE
        )
}

# Required for allauth
SITE_ID = 1

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# AllAuth settings
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET = True

# Custom account adapter for mobile/web email branding
ACCOUNT_ADAPTER = "reignitehome.adapters.AccountAdapter"

# Email (Mailgun)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("MAILGUN_SMTP_HOST", default="smtp.mailgun.org")
EMAIL_PORT = config("MAILGUN_SMTP_PORT", cast=int, default=587)
EMAIL_HOST_USER = config("MAILGUN_SMTP_USER")
EMAIL_HOST_PASSWORD = config("MAILGUN_SMTP_PASS")
EMAIL_USE_TLS = config("MAILGUN_SMTP_USE_TLS", cast=bool, default=True)
DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default="TryAgainText <no-reply@tryagaintext.com>",
)

# Google Play Billing (server verification)
GOOGLE_PLAY_PACKAGE_NAME = config(
    "GOOGLE_PLAY_PACKAGE_NAME",
    default="com.tryagaintext.flirtfix",
)
GOOGLE_PLAY_SERVICE_ACCOUNT_JSON = config(
    "GOOGLE_PLAY_SERVICE_ACCOUNT_JSON",
    default=str(BASE_DIR / "secrets" / "google-play-service-account.json"),
)
GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_CONTENT = config(
    "GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_CONTENT",
    default="",
)

# Redirect URLs
LOGIN_REDIRECT_URL = '/conversations'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
