DATA = {
    "category_slug": "astrology-placements",
    "category_name": "Astrology Placements",
    "sort_order": 11,
    "topics": [
        {
            "slug": "aries-moon",
            "keyword": "Aries Moon",
            "h1": "The Best Aries Moon Pickup Lines (For When Her Emotions Are Bold and Direct).",
            "title": "Best Aries Moon Pickup Lines | TryAgainText",
            "meta_description": "Use niche Aries moon pickup lines that feel passionate, direct, and emotionally bold. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Aries moon means her emotional nature is bold, reactive, and fiery. She feels things intensely and expresses them quickly. These lines match her passionate emotional landscape.",
            "witty_lines": [
                "Your profile has Aries moon energy — your emotions are vivid, direct, and impossible to miss.",
                "I can tell you feel things intensely and express them immediately. That raw honesty is magnetic.",
                "You seem like someone whose emotional reactions are as passionate as everything else about you.",
            ],
            "flirty_lines": [
                "Your emotional intensity is one of the most attractive things about you.",
                "Something about your energy tells me you need someone who can match your passion.",
                "You carry yourself with this emotional fire and it is genuinely captivating.",
            ],
            "cheesy_lines": [
                "Are you Aries moon? Because your emotions just ignited something in me.",
                "Your profile tells me feelings are not negotiable with you and I respect that.",
                "I want to be someone brave enough for your emotional intensity.",
            ],
            "prefill_text": "She has Aries moon energy. Write an opener that matches her passionate emotional nature.",
            "upload_hint": "Upload a screenshot of her profile so the intensity is actually reciprocal.",
            "her_info_prefill": "She has Aries moon energy. Emotionally bold, reactive, expresses feelings quickly and intensely.",
        },
        {
            "slug": "taurus-moon",
            "keyword": "Taurus Moon",
            "h1": "The Best Taurus Moon Pickup Lines (For When Her Emotions Are Grounded and Loyal).",
            "title": "Best Taurus Moon Pickup Lines | TryAgainText",
            "meta_description": "Use niche Taurus moon pickup lines that feel stable, sensual, and emotionally reliable. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Taurus moon means her emotional nature is grounded, stable, and comfort-seeking. She builds slowly but loyally. These lines match her earthy emotional resilience.",
            "witty_lines": [
                "Your profile has Taurus moon energy — grounded, stable, and worth the slow build.",
                "I can tell you need emotional stability and security as a foundation.",
                "You seem like someone whose feelings develop slowly but are incredibly deep.",
            ],
            "flirty_lines": [
                "Your emotional stability is actually really attractive and calming.",
                "Something about your grounded energy tells me you are looking for something real and lasting.",
                "You carry yourself with this quiet emotional strength that is genuinely magnetic.",
            ],
            "cheesy_lines": [
                "Are you Taurus moon? Because I want to build something stable with you.",
                "Your profile tells me you are worth the slow process.",
                "I promise to be as emotionally constant as your need for stability.",
            ],
            "prefill_text": "She has Taurus moon energy. Write an opener that respects her need for emotional stability.",
            "upload_hint": "Upload a screenshot of her profile so the stability commitment is actual.",
            "her_info_prefill": "She has Taurus moon energy. Emotionally grounded, needs stability, develops feelings slowly.",
        },
        {
            "slug": "gemini-moon",
            "keyword": "Gemini Moon",
            "h1": "The Best Gemini Moon Pickup Lines (For When Her Emotions Are Curious and Changeable).",
            "title": "Best Gemini Moon Pickup Lines | TryAgainText",
            "meta_description": "Use niche Gemini moon pickup lines that feel witty, curious, and emotionally flexible. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Gemini moon means her emotional nature is curious, communicative, and changes like the wind. She needs mental stimulation alongside emotional connection.",
            "witty_lines": [
                "Your profile has Gemini moon energy — emotionally curious, witty, and always asking the next question.",
                "I can tell you need someone who can keep up intellectually with your emotions.",
                "You seem like someone whose feelings are expressed through clever conversation.",
            ],
            "flirty_lines": [
                "Your emotional playfulness is so attractive and I love how you express feelings through wit.",
                "Something about your energy tells me you need mental stimulation as much as emotional depth.",
                "You carry yourself with this charming emotional flexibility that is genuinely fascinating.",
            ],
            "cheesy_lines": [
                "Are you Gemini moon? Because I want to have interesting conversations about your feelings.",
                "Your profile tells me you need someone who engages your mind emotionally.",
                "I promise to never get bored with your emotional landscape.",
            ],
            "prefill_text": "She has Gemini moon energy. Write an opener that appeals to her emotional curiosity.",
            "upload_hint": "Upload a screenshot of her profile so the conversation can match her wit.",
            "her_info_prefill": "She has Gemini moon energy. Emotionally curious, communicative, needs mental and emotional stimulation.",
        },
        {
            "slug": "cancer-moon",
            "keyword": "Cancer Moon",
            "h1": "The Best Cancer Moon Pickup Lines (For When Her Emotions Are Deep and Nurturing).",
            "title": "Best Cancer Moon Pickup Lines | TryAgainText",
            "meta_description": "Use niche Cancer moon pickup lines that feel warm, family-oriented, and emotionally nurturing. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Cancer moon means her emotional nature is deep, sensitive, and family-oriented. She gives emotional care freely. These lines honor her nurturing capacity.",
            "witty_lines": [
                "Your profile has Cancer moon energy — emotionally deep, genuinely caring, and family-focused.",
                "I can tell you feel everything and take care of everyone around you emotionally.",
                "You seem like someone whose emotional intelligence is one of your greatest strengths.",
            ],
            "flirty_lines": [
                "Your emotional depth and capacity for care is one of the most attractive things about you.",
                "Something about your energy tells me you are looking for true emotional intimacy.",
                "You carry yourself with this warm emotional presence that makes people feel safe.",
            ],
            "cheesy_lines": [
                "Are you Cancer moon? Because I want to let you take care of me emotionally.",
                "Your profile tells me you have room for someone in your deeply feeling heart.",
                "I promise to cherish the emotional intimacy you offer.",
            ],
            "prefill_text": "She has Cancer moon energy. Write an opener that honors her emotional depth and care.",
            "upload_hint": "Upload a screenshot of her profile so the emotional safety is reciprocal.",
            "her_info_prefill": "She has Cancer moon energy. Emotionally deep, nurturing, family-oriented, sensitive.",
        },
        {
            "slug": "leo-moon",
            "keyword": "Leo Moon",
            "h1": "The Best Leo Moon Pickup Lines (For When Her Emotions Are Dramatic and Generous).",
            "title": "Best Leo Moon Pickup Lines | TryAgainText",
            "meta_description": "Use niche Leo moon pickup lines that feel celebratory, affectionate, and emotionally generous. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Leo moon means her emotional nature is dramatic, generous, and seeks admiration. She loves big and wants to be loved big. These lines match her emotional grandiosity.",
            "witty_lines": [
                "Your profile has Leo moon energy — emotionally generous, dramatic, and wants to be adored.",
                "I can tell you feel things theatrically and love with your whole heart.",
                "You seem like someone whose emotional expression is as creative as everything else.",
            ],
            "flirty_lines": [
                "Your emotional generosity is so attractive and I love how openly you express care.",
                "Something about your energy tells me you want to be someone's favorite person.",
                "You carry yourself with this emotionally confident presence that is genuinely magnetic.",
            ],
            "cheesy_lines": [
                "Are you Leo moon? Because I want to shower you with emotional affection.",
                "Your profile tells me your heart is as golden as your emotional energy.",
                "I promise to make sure you know you are my favorite person.",
            ],
            "prefill_text": "She has Leo moon energy. Write an opener that celebrates her emotional generosity.",
            "upload_hint": "Upload a screenshot of her profile so the admiration is specific and genuine.",
            "her_info_prefill": "She has Leo moon energy. Emotionally dramatic, generous, wants to be emotionally adored.",
        },
        {
            "slug": "virgo-moon",
            "keyword": "Virgo Moon",
            "h1": "The Best Virgo Moon Pickup Lines (For When Her Emotions Are Analytical and Refined).",
            "title": "Best Virgo Moon Pickup Lines | TryAgainText",
            "meta_description": "Use niche Virgo moon pickup lines that feel thoughtful, detail-oriented, and emotionally intelligent. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Virgo moon means her emotional nature is analytical, detail-focused, and constantly self-improving. She processes feelings through logic. These lines honor her need for understanding.",
            "witty_lines": [
                "Your profile has Virgo moon energy — emotionally analytical, thoughtful, and always improving.",
                "I can tell you process feelings carefully and appreciate when someone understands the details.",
                "You seem like someone whose emotional intelligence is expressed through analysis and care.",
            ],
            "flirty_lines": [
                "Your emotional thoughtfulness is really attractive and I appreciate how carefully you feel.",
                "Something about your energy tells me you need someone who understands nuance emotionally.",
                "You carry yourself with this refined emotional awareness that is genuinely impressive.",
            ],
            "cheesy_lines": [
                "Are you Virgo moon? Because I want to understand every detail of your emotional landscape.",
                "Your profile tells me your feelings deserve careful analysis and I am here for that.",
                "I promise to pay attention to every emotional nuance with you.",
            ],
            "prefill_text": "She has Virgo moon energy. Write an opener that honors her analytical emotional nature.",
            "upload_hint": "Upload a screenshot of her profile so the emotional understanding can be detailed.",
            "her_info_prefill": "She has Virgo moon energy. Emotionally analytical, detail-oriented, self-improving, thoughtful.",
        },
        {
            "slug": "libra-moon",
            "keyword": "Libra Moon",
            "h1": "The Best Libra Moon Pickup Lines (For When Her Emotions Are Balanced and Diplomatic).",
            "title": "Best Libra Moon Pickup Lines | TryAgainText",
            "meta_description": "Use niche Libra moon pickup lines that feel harmonious, romantic, and balanced. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Libra moon means her emotional nature is seeking balance, beauty, and harmony. She processes emotions relationally. These lines appeal to her romantic idealism.",
            "witty_lines": [
                "Your profile has Libra moon energy — emotionally balanced, romantic, and seeking harmony.",
                "I can tell you need emotional equilibrium and appreciate beautiful relationship dynamics.",
                "You seem like someone whose emotional expression values peace and partnership.",
            ],
            "flirty_lines": [
                "Your emotional balance is really attractive and I love how you approach feelings diplomatically.",
                "Something about your energy tells me you are looking for true emotional partnership.",
                "You carry yourself with this graceful emotional presence that is genuinely magnetic.",
            ],
            "cheesy_lines": [
                "Are you Libra moon? Because I want our emotional dynamic to be perfectly balanced.",
                "Your profile tells me you are looking for someone who values relationship harmony.",
                "I promise to create emotional balance and beauty with you.",
            ],
            "prefill_text": "She has Libra moon energy. Write an opener that appeals to her romantic and balanced nature.",
            "upload_hint": "Upload a screenshot of her profile so the harmony promise feels genuine.",
            "her_info_prefill": "She has Libra moon energy. Emotionally balanced, romantic, seeks harmony in relationships.",
        },
        {
            "slug": "scorpio-moon",
            "keyword": "Scorpio Moon",
            "h1": "The Best Scorpio Moon Pickup Lines (For When Her Emotions Are Intense and Transformative).",
            "title": "Best Scorpio Moon Pickup Lines | TryAgainText",
            "meta_description": "Use niche Scorpio moon pickup lines that feel raw, deep, and emotionally fearless. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Scorpio moon means her emotional nature is intense, secretive, and transformative. She feels everything at the deepest level. These lines honor her emotional depth.",
            "witty_lines": [
                "Your profile has Scorpio moon energy — emotionally intense, secretive, and profoundly deep.",
                "I can tell you feel things at the deepest level and do not let people see all of it.",
                "You seem like someone whose emotional world is complex, private, and absolutely fascinating.",
            ],
            "flirty_lines": [
                "Your emotional intensity is one of the most attractive things about you.",
                "Something about your energy tells me you are looking for someone brave enough for your feelings.",
                "You carry yourself with this magnetic emotional mystery that is genuinely captivating.",
            ],
            "cheesy_lines": [
                "Are you Scorpio moon? Because I want to dive into the depths of your emotional world.",
                "Your profile tells me your feelings are intense and I am ready for that.",
                "I promise to honor the emotional depths you do not show everyone.",
            ],
            "prefill_text": "She has Scorpio moon energy. Write an opener that respects her intense emotional nature.",
            "upload_hint": "Upload a screenshot of her profile so the emotional intimacy can be real.",
            "her_info_prefill": "She has Scorpio moon energy. Emotionally intense, private, transformative, deeply feeling.",
        },
        {
            "slug": "sagittarius-moon",
            "keyword": "Sagittarius Moon",
            "h1": "The Best Sagittarius Moon Pickup Lines (For When Her Emotions Are Adventurous and Free).",
            "title": "Best Sagittarius Moon Pickup Lines | TryAgainText",
            "meta_description": "Use niche Sagittarius moon pickup lines that feel optimistic, adventurous, and emotionally independent. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Sagittarius moon means her emotional nature is optimistic, freedom-loving, and always seeking growth. She processes feelings through adventure. These lines honor her wanderlust.",
            "witty_lines": [
                "Your profile has Sagittarius moon energy — emotionally adventurous, optimistic, and freedom-loving.",
                "I can tell you process feelings through exploration and need emotional room to roam.",
                "You seem like someone whose emotional expression is tied to growth and adventure.",
            ],
            "flirty_lines": [
                "Your emotional optimism is really attractive and I love your adventurous spirit.",
                "Something about your energy tells me you are looking for someone brave enough for emotional growth.",
                "You carry yourself with this exciting emotional energy that makes life feel more expansive.",
            ],
            "cheesy_lines": [
                "Are you Sagittarius moon? Because I want to explore your emotional landscape.",
                "Your profile tells me you are looking for emotional growth and adventure.",
                "I promise to support your emotional independence and freedom.",
            ],
            "prefill_text": "She has Sagittarius moon energy. Write an opener that celebrates her adventurous emotions.",
            "upload_hint": "Upload a screenshot of her profile so the adventure promise can be shared.",
            "her_info_prefill": "She has Sagittarius moon energy. Emotionally optimistic, freedom-loving, adventurous, growth-oriented.",
        },
        {
            "slug": "capricorn-moon",
            "keyword": "Capricorn Moon",
            "h1": "The Best Capricorn Moon Pickup Lines (For When Her Emotions Are Restrained and Ambitious).",
            "title": "Best Capricorn Moon Pickup Lines | TryAgainText",
            "meta_description": "Use niche Capricorn moon pickup lines that feel respectful, ambitious, and emotionally responsible. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Capricorn moon means her emotional nature is controlled, ambitious, and serious. She builds emotional walls. These lines respect her need for structure and achievement.",
            "witty_lines": [
                "Your profile has Capricorn moon energy — emotionally controlled, ambitious, and deeply reliable.",
                "I can tell you do not waste emotional energy and appreciate when people are serious.",
                "You seem like someone whose emotional maturity is expressed through responsibility.",
            ],
            "flirty_lines": [
                "Your emotional restraint is actually really attractive and shows genuine depth.",
                "Something about your energy tells me you are looking for someone who can earn your emotional trust.",
                "You carry yourself with this dignified emotional presence that is genuinely impressive.",
            ],
            "cheesy_lines": [
                "Are you Capricorn moon? Because I want to earn your emotional trust over time.",
                "Your profile tells me your feelings are serious and I respect that.",
                "I promise to be emotionally responsible and worthy of your trust.",
            ],
            "prefill_text": "She has Capricorn moon energy. Write an opener that shows you respect her emotional seriousness.",
            "upload_hint": "Upload a screenshot of her profile so the emotional respect is genuine.",
            "her_info_prefill": "She has Capricorn moon energy. Emotionally controlled, ambitious, serious, reliable, responsible.",
        },
        {
            "slug": "aquarius-moon",
            "keyword": "Aquarius Moon",
            "h1": "The Best Aquarius Moon Pickup Lines (For When Her Emotions Are Detached and Intellectual).",
            "title": "Best Aquarius Moon Pickup Lines | TryAgainText",
            "meta_description": "Use niche Aquarius moon pickup lines that feel intellectual, unconventional, and emotionally independent. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Aquarius moon means her emotional nature is detached, intellectual, and unconventional. She processes feelings mentally. These lines honor her need for independence.",
            "witty_lines": [
                "Your profile has Aquarius moon energy — emotionally intellectual, detached, and authentically weird.",
                "I can tell you feel things differently than most people and do not conform to emotional norms.",
                "You seem like someone whose emotional expression is filtered through philosophy.",
            ],
            "flirty_lines": [
                "Your emotional independence is really attractive and I love your unconventional perspective.",
                "Something about your energy tells me you need someone who respects your emotional freedom.",
                "You carry yourself with this intellectually stimulating emotional presence that is fascinating.",
            ],
            "cheesy_lines": [
                "Are you Aquarius moon? Because I want to explore your unique emotional wavelength.",
                "Your profile tells me you experience emotions in totally different ways and I respect that.",
                "I promise to give you the emotional freedom and space you need.",
            ],
            "prefill_text": "She has Aquarius moon energy. Write an opener that celebrates her intellectual and independent emotions.",
            "upload_hint": "Upload a screenshot of her profile so the emotional understanding can be unconventional.",
            "her_info_prefill": "She has Aquarius moon energy. Emotionally intellectual, detached, independent, unconventional.",
        },
        {
            "slug": "pisces-moon",
            "keyword": "Pisces Moon",
            "h1": "The Best Pisces Moon Pickup Lines (For When Her Emotions Are Dreamy and Intuitive).",
            "title": "Best Pisces Moon Pickup Lines | TryAgainText",
            "meta_description": "Use niche Pisces moon pickup lines that feel dreamy, intuitive, and emotionally transcendent. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Pisces moon means her emotional nature is dreamy, intuitive, and spiritually connected. She feels everything and everyone. These lines honor her emotional sensitivity.",
            "witty_lines": [
                "Your profile has Pisces moon energy — emotionally dreamy, intuitive, and spiritually aware.",
                "I can tell you feel things intuitively and are sensitive to emotional frequencies.",
                "You seem like someone whose emotional world is rich, imaginative, and deeply spiritual.",
            ],
            "flirty_lines": [
                "Your emotional sensitivity is really attractive and I appreciate your intuitive nature.",
                "Something about your energy tells me you are looking for deep emotional and spiritual connection.",
                "You carry yourself with this dreamy emotional presence that is genuinely magical.",
            ],
            "cheesy_lines": [
                "Are you Pisces moon? Because I want to merge our emotional worlds.",
                "Your profile tells me you feel everything and I am ready for that depth.",
                "I promise to honor your emotional sensitivity and spiritual intuition.",
            ],
            "prefill_text": "She has Pisces moon energy. Write an opener that celebrates her intuitive and dreamy nature.",
            "upload_hint": "Upload a screenshot of her profile so the emotional transcendence is real.",
            "her_info_prefill": "She has Pisces moon energy. Emotionally dreamy, intuitive, spiritual, sensitive, imaginative.",
        },
        {
            "slug": "scorpio-rising",
            "keyword": "Scorpio Rising",
            "h1": "The Best Scorpio Rising Pickup Lines (For When Her First Impression Is Intense).",
            "title": "Best Scorpio Rising Pickup Lines | TryAgainText",
            "meta_description": "Use niche Scorpio rising pickup lines that feel mysterious, magnetic, and deeply intriguing. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Scorpio rising means she presents intensely and mysteriously to the world. Her first impression is powerful and secretive. These lines acknowledge her magnetic mystery.",
            "witty_lines": [
                "Your profile has Scorpio rising energy — your first impression is intensely magnetic.",
                "I can tell people are immediately drawn to your mysterious energy.",
                "You seem like someone whose presence commands attention without trying.",
            ],
            "flirty_lines": [
                "Your mysterious energy is absolutely magnetic and I am fully drawn in.",
                "Something about the way you present yourself tells me there is much more beneath the surface.",
                "You carry yourself with this powerful, secretive energy that is genuinely captivating.",
            ],
            "cheesy_lines": [
                "Are you Scorpio rising? Because my first impression is that you are irresistible.",
                "Your profile tells me your presence is intense and I am here for it.",
                "I promise to respect the mystery that makes you so magnetic.",
            ],
            "prefill_text": "She has Scorpio rising energy. Write an opener that acknowledges her powerful first impression.",
            "upload_hint": "Upload a screenshot of her profile so the intensity is reciprocated.",
            "her_info_prefill": "She has Scorpio rising energy. Presents intensely, mysterious first impression, magnetic presence.",
        },
        {
            "slug": "leo-rising",
            "keyword": "Leo Rising",
            "h1": "The Best Leo Rising Pickup Lines (For When She Commands Every Room).",
            "title": "Best Leo Rising Pickup Lines | TryAgainText",
            "meta_description": "Use niche Leo rising pickup lines that feel celebratory, confident, and genuinely admiring. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Leo rising means she presents confidently and charmingly to the world. She naturally commands attention. These lines honor her magnetic presence.",
            "witty_lines": [
                "Your profile has Leo rising energy — you naturally command every space you enter.",
                "I can tell you are comfortable being the center of attention and you wear it well.",
                "You seem like someone whose confidence is genuinely magnetic and inspiring.",
            ],
            "flirty_lines": [
                "Your confident presence is absolutely attractive and I love how naturally you shine.",
                "Something about the way you present yourself tells me you are meant to be admired.",
                "You carry yourself like a star and I am genuinely drawn to your light.",
            ],
            "cheesy_lines": [
                "Are you Leo rising? Because my first impression is that you are a star.",
                "Your profile tells me you are the kind of person everyone gravitates toward.",
                "I promise to make sure you know you are the most interesting person in any room.",
            ],
            "prefill_text": "She has Leo rising energy. Write an opener that celebrates her commanding presence.",
            "upload_hint": "Upload a screenshot of her profile so the admiration is specific and genuine.",
            "her_info_prefill": "She has Leo rising energy. Confident, charismatic, commands attention, naturally magnetic.",
        },
        {
            "slug": "virgo-rising",
            "keyword": "Virgo Rising",
            "h1": "The Best Virgo Rising Pickup Lines (For When She Seems Composed and Thoughtful).",
            "title": "Best Virgo Rising Pickup Lines | TryAgainText",
            "meta_description": "Use niche Virgo rising pickup lines that feel respectful, thoughtful, and appreciative of her careful nature. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Virgo rising means she presents carefully and thoughtfully to the world. Her first impression is composed and observant. These lines honor her analytical presence.",
            "witty_lines": [
                "Your profile has Virgo rising energy — your first impression is thoughtful and composed.",
                "I can tell you pay attention to details and notice things others miss.",
                "You seem like someone whose careful approach to life is genuinely attractive.",
            ],
            "flirty_lines": [
                "Your thoughtful presence is really attractive and I appreciate your careful nature.",
                "Something about the way you present yourself tells me you are observant and intelligent.",
                "You carry yourself with this composed, intelligent energy that is genuinely impressive.",
            ],
            "cheesy_lines": [
                "Are you Virgo rising? Because my first impression is that you are exceptional.",
                "Your profile tells me you are someone worth paying attention to.",
                "I promise to appreciate the thoughtful details you put into everything.",
            ],
            "prefill_text": "She has Virgo rising energy. Write an opener that respects her thoughtful first impression.",
            "upload_hint": "Upload a screenshot of her profile so the appreciation is detailed.",
            "her_info_prefill": "She has Virgo rising energy. Presents thoughtfully, composed, observant, intelligent, careful.",
        },
    ],
}

