DATA = {
    "category_slug": "attachment-styles",
    "category_name": "Attachment Styles",
    "sort_order": 9,
    "topics": [
        {
            "slug": "anxious-attachment",
            "keyword": "Anxious Attachment",
            "h1": "The Best Anxious Attachment Pickup Lines (For When She Needs Reassurance and Deep Connection).",
            "title": "Best Anxious Attachment Pickup Lines | TryAgainText",
            "meta_description": "Use niche anxious attachment pickup lines that feel genuine, constant, and emotionally available. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she has anxious attachment energy, she values reassurance, consistency, and deep emotional connection. She wants someone who shows up fully. These lines match that need.",
            "witty_lines": [
                "Your profile tells me you care deeply about connection and I respect the vulnerability that takes.",
                "I can tell you are someone who values presence over perfection. That authenticity is rare.",
                "Your vibe says you need to know where you stand and I appreciate that level of honesty.",
            ],
            "flirty_lines": [
                "Your emotional openness is one of the most attractive things about you.",
                "Something about your energy tells me you are looking for someone who actually shows up. I will.",
                "You seem like the kind of person who needs real commitment, not just vibes. I can offer that.",
            ],
            "cheesy_lines": [
                "Are you anxious attachment? Because I am here to provide the consistency you deserve.",
                "Your profile just made me want to be the secure base you are looking for.",
                "I promise I will not ghost you — your profile makes that promise easy to keep.",
            ],
            "prefill_text": "She has anxious attachment energy. Write a genuine, reassuring opener that shows consistency and emotional availability.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual emotional needs, not just theory.",
            "her_info_prefill": "She has anxious attachment energy. Values deep connection, reassurance, and consistency. Needs emotional availability.",
        },
        {
            "slug": "avoidant-attachment",
            "keyword": "Avoidant Attachment",
            "h1": "The Best Avoidant Attachment Pickup Lines (For When She Values Her Space and Independence).",
            "title": "Best Avoidant Attachment Pickup Lines | TryAgainText",
            "meta_description": "Use niche avoidant attachment pickup lines that feel low-pressure, independent, and respectful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she has avoidant attachment energy, she values independence and space more than constant reassurance. A clingy opener will backfire. These lines give her room to breathe.",
            "witty_lines": [
                "Your profile has independent energy and I respect that you do not need someone to complete you.",
                "I can tell you are the type who needs her own space and I am genuinely fine with that.",
                "You seem like someone who values freedom in a relationship and I am not interested in cages either.",
            ],
            "flirty_lines": [
                "Your confidence in being alone is attractive and I am not threatened by it.",
                "Something about your vibe tells me you are looking for a partner, not a crutch. I get it.",
                "You carry yourself like someone who has her whole life together and I am here to enhance it, not complete it.",
            ],
            "cheesy_lines": [
                "Are you avoidant attachment? Because I will give you all the space you need.",
                "Your profile tells me you value independence and I respect the hell out of that.",
                "I promise not to be clingy — your energy already told me that would not work anyway.",
            ],
            "prefill_text": "She has avoidant attachment energy. Write a low-pressure opener that respects her independence and need for space.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual autonomy, not just the attachment style.",
            "her_info_prefill": "She has avoidant attachment energy. Values independence, space, freedom. Does not need constant reassurance.",
        },
        {
            "slug": "secure-attachment",
            "keyword": "Secure Attachment",
            "h1": "The Best Secure Attachment Pickup Lines (For When She Is Emotionally Healthy and Direct).",
            "title": "Best Secure Attachment Pickup Lines | TryAgainText",
            "meta_description": "Use niche secure attachment pickup lines that feel genuine, balanced, and emotionally intelligent. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she has secure attachment energy, she is emotionally healthy, communicative, and balanced. She wants genuine connection without games. These lines match that maturity.",
            "witty_lines": [
                "Your profile has secure attachment energy — balanced, genuine, and refreshingly straightforward.",
                "I can tell you are the type who communicates clearly and does not play games. That is incredibly attractive.",
                "You seem like someone who knows what she wants and is not afraid to ask for it. Respect.",
            ],
            "flirty_lines": [
                "Your emotional maturity comes through in everything and it is one of the most attractive things about you.",
                "Something about your vibe tells me you are looking for real partnership, not just surface-level connection.",
                "You carry yourself with this balanced confidence that says you do not need me but want me. Perfect.",
            ],
            "cheesy_lines": [
                "Are you secure attachment? Because you just made healthy relationships sound incredibly appealing.",
                "Your profile is proof that emotional maturity is the sexiest quality.",
                "I think I just found someone who actually communicates like a healthy adult. This is rare.",
            ],
            "prefill_text": "She has secure attachment energy. Write a genuine, balanced opener that matches her emotional maturity.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual emotional health, not just theory.",
            "her_info_prefill": "She has secure attachment energy. Emotionally healthy, communicative, balanced. Wants real partnership and genuine connection.",
        },
        {
            "slug": "disorganized-attachment",
            "keyword": "Disorganized Attachment",
            "h1": "The Best Disorganized Attachment Pickup Lines (For When She Is Contradictory and Complex).",
            "title": "Best Disorganized Attachment Pickup Lines | TryAgainText",
            "meta_description": "Use niche disorganized attachment pickup lines that feel understanding, patient, and compassionate. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she has disorganized attachment energy, she is complex, sometimes contradictory, and often dealing with unresolved trauma. Patience and understanding are essential. These lines show you see her.",
            "witty_lines": [
                "Your profile has that beautiful complexity that comes from actually living and feeling things deeply.",
                "I can tell you are someone with layers and I am genuinely interested in understanding all of them.",
                "You seem like someone who has been through some things and come out thoughtful. That takes strength.",
            ],
            "flirty_lines": [
                "Your honesty about being complicated is more attractive than anyone pretending to be simple.",
                "Something about your energy tells me you are looking for someone patient enough to understand nuance.",
                "You carry yourself with this fascinating contradiction and I want to know more.",
            ],
            "cheesy_lines": [
                "Are you disorganized attachment? Because your contradictions make perfect sense to me.",
                "Your profile tells me you are complex and I think that is your superpower.",
                "I promise to be patient with your process — you are worth the wait.",
            ],
            "prefill_text": "She has disorganized attachment energy. Write a patient, compassionate opener that sees her complexity.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual emotional landscape.",
            "her_info_prefill": "She has disorganized attachment energy. Complex, sometimes contradictory. Values patience and genuine understanding.",
        },
        {
            "slug": "fearful-avoidant",
            "keyword": "Fearful-Avoidant",
            "h1": "The Best Fearful-Avoidant Pickup Lines (For When She Wants Connection and Freedom Simultaneously).",
            "title": "Best Fearful-Avoidant Pickup Lines | TryAgainText",
            "meta_description": "Use niche fearful-avoidant pickup lines that feel understanding of her push-pull dynamic. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she has fearful-avoidant energy, she wants connection but fears it. She will pull close then push away. These lines acknowledge that dance without judgment.",
            "witty_lines": [
                "Your profile tells me you are someone who wants closeness and freedom in equal measure.",
                "I can tell you are the type who runs toward and away from people and I understand why.",
                "You seem like someone with a push-pull pattern and honestly, that is more relatable than people admit.",
            ],
            "flirty_lines": [
                "Your honesty about wanting both connection and space is actually really attractive.",
                "Something about your energy tells me you are looking for someone secure enough to stay during the fear.",
                "You carry yourself with this fascinating tension and I am genuinely interested in understanding it.",
            ],
            "cheesy_lines": [
                "Are you fearful-avoidant? Because I am ready to stay even when you run.",
                "Your profile tells me you want to get close and pull away and I can work with that.",
                "I promise not to take it personally when you need space — I will be here when you want back in.",
            ],
            "prefill_text": "She has fearful-avoidant energy. Write an opener that understands her push-pull dynamic with compassion.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual emotional pattern.",
            "her_info_prefill": "She has fearful-avoidant energy. Wants connection and fears it. Needs someone secure enough to stay.",
        },
    ],
}
