DATA = {
    "category_slug": "book-genres",
    "category_name": "Book Genres",
    "sort_order": 12,
    "topics": [
        {
            "slug": "romance-reader",
            "keyword": "Romance Reader",
            "h1": "The Best Romance Reader Pickup Lines (For When She Believes in Love Stories).",
            "title": "Best Romance Reader Pickup Lines | TryAgainText",
            "meta_description": "Use niche romance reader pickup lines that feel romantic, hopeful, and genuinely invested in love. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she reads romance novels, she believes in love stories and happy endings. She wants someone who will treat her like a main character. These lines deliver that energy.",
            "witty_lines": [
                "Your profile has romance reader energy — you believe in love stories and deserve to be in one.",
                "I can tell you have read enough books to know what a good love story looks like.",
                "You seem like someone who has imagined a thousand versions of meeting the right person.",
            ],
            "flirty_lines": [
                "Your romantic optimism is really attractive and I want to be your love story.",
                "Something about your energy tells me you are looking for the kind of connection only romance novels understand.",
                "You carry yourself like a main character and I want to be your co-lead.",
            ],
            "cheesy_lines": [
                "Are you a romance reader? Because I want to write our love story together.",
                "Your profile tells me you believe in happily ever afters and so do I.",
                "I promise to be the kind of love story you have read a thousand times.",
            ],
            "prefill_text": "She is a romance reader. Write an opener that feels like the beginning of a love story.",
            "upload_hint": "Upload a screenshot of her profile so the romance is actually believable.",
            "her_info_prefill": "She is a romance reader. Believes in love stories, values romance, expects a happy ending.",
        },
        {
            "slug": "fantasy-reader",
            "keyword": "Fantasy Reader",
            "h1": "The Best Fantasy Reader Pickup Lines (For When She Loves Epic Worlds).",
            "title": "Best Fantasy Reader Pickup Lines | TryAgainText",
            "meta_description": "Use niche fantasy reader pickup lines that feel epic, magical, and wonderfully imaginative. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she reads fantasy, she loves epic worlds, magic, and imagination. She wants someone who can keep up with her creativity. These lines honor her magical thinking.",
            "witty_lines": [
                "Your profile has fantasy reader energy — you are attracted to epic stories and magical possibilities.",
                "I can tell you spend time in imaginary worlds and come back to reality reluctantly.",
                "You seem like someone whose imagination is bigger than most people's actual lives.",
            ],
            "flirty_lines": [
                "Your imaginative energy is really attractive and I love how creatively you see the world.",
                "Something about your vibe tells me you are looking for an epic adventure, not just a date.",
                "You carry yourself like someone living in a story worth reading.",
            ],
            "cheesy_lines": [
                "Are you a fantasy reader? Because I want to be your epic love story.",
                "Your profile tells me you deserve a world as magical as you are.",
                "I promise to make our story feel like the fantasy books you love.",
            ],
            "prefill_text": "She is a fantasy reader. Write an opener that feels epic and magical.",
            "upload_hint": "Upload a screenshot of her profile so the fantasy is creatively shared.",
            "her_info_prefill": "She is a fantasy reader. Loves epic stories, imagination, magic, creative worlds.",
        },
        {
            "slug": "thriller-reader",
            "keyword": "Thriller Reader",
            "h1": "The Best Thriller Reader Pickup Lines (For When She Loves Edge-of-Your-Seat Tension).",
            "title": "Best Thriller Reader Pickup Lines | TryAgainText",
            "meta_description": "Use niche thriller reader pickup lines that feel intense, clever, and filled with intrigue. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she reads thrillers, she appreciates intensity, complexity, and edge-of-your-seat tension. A boring opener will bore her. These lines bring the intrigue.",
            "witty_lines": [
                "Your profile has thriller reader energy — you are attracted to complexity and cannot predict the ending.",
                "I can tell you appreciate a good plot twist and nothing is ever what it seems.",
                "You seem like someone who always suspects there is more to the story.",
            ],
            "flirty_lines": [
                "Your appreciation for intrigue and complexity is really attractive.",
                "Something about your energy tells me you are looking for someone you cannot completely figure out.",
                "You carry yourself with this mysterious intensity that keeps me intrigued.",
            ],
            "cheesy_lines": [
                "Are you a thriller reader? Because my intentions toward you are positively intense.",
                "Your profile tells me you are looking for genuine tension and excitement.",
                "I promise our story will be anything but predictable.",
            ],
            "prefill_text": "She is a thriller reader. Write an opener filled with intrigue and tension.",
            "upload_hint": "Upload a screenshot of her profile so the complexity is real.",
            "her_info_prefill": "She is a thriller reader. Loves intensity, complexity, plot twists, intrigue.",
        },
        {
            "slug": "mystery-reader",
            "keyword": "Mystery Reader",
            "h1": "The Best Mystery Reader Pickup Lines (For When She Loves Solving Puzzles).",
            "title": "Best Mystery Reader Pickup Lines | TryAgainText",
            "meta_description": "Use niche mystery reader pickup lines that feel clever, detail-oriented, and intellectually engaging. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she reads mysteries, she loves puzzles, clues, and solving complex problems. She notices details others miss. These lines appeal to her detective mind.",
            "witty_lines": [
                "Your profile has mystery reader energy — you are attracted to puzzles and details.",
                "I can tell you notice things other people completely miss.",
                "You seem like someone who is always one step ahead and figuring people out.",
            ],
            "flirty_lines": [
                "Your attention to detail is really attractive and I love how observant you are.",
                "Something about your energy tells me you would solve me like a good mystery.",
                "You carry yourself with this clever awareness that is genuinely impressive.",
            ],
            "cheesy_lines": [
                "Are you a mystery reader? Because I want you to uncover all my secrets.",
                "Your profile tells me you are the type who solves puzzles others cannot see.",
                "I promise to be genuinely interesting to figure out.",
            ],
            "prefill_text": "She is a mystery reader. Write an opener that appeals to her puzzle-solving mind.",
            "upload_hint": "Upload a screenshot of her profile so the intellectual engagement is mutual.",
            "her_info_prefill": "She is a mystery reader. Loves puzzles, detail-oriented, observant, intelligent.",
        },
        {
            "slug": "sci-fi-reader",
            "keyword": "Sci-Fi Reader",
            "h1": "The Best Sci-Fi Reader Pickup Lines (For When She Thinks About the Future).",
            "title": "Best Sci-Fi Reader Pickup Lines | TryAgainText",
            "meta_description": "Use niche sci-fi reader pickup lines that feel futuristic, intellectually stimulating, and cosmically aware. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she reads sci-fi, she thinks about the future, big ideas, and possibilities. She wants someone who can discuss concepts. These lines appeal to her cosmic mind.",
            "witty_lines": [
                "Your profile has sci-fi reader energy — you are thinking about the future and big ideas.",
                "I can tell you are comfortable with complex concepts and futuristic thinking.",
                "You seem like someone whose mind works across time and possibilities.",
            ],
            "flirty_lines": [
                "Your intellectual curiosity is really attractive and I love how you think about the future.",
                "Something about your energy tells me you are looking for someone on your intellectual wavelength.",
                "You carry yourself with this cosmic awareness that is genuinely fascinating.",
            ],
            "cheesy_lines": [
                "Are you a sci-fi reader? Because you make me believe in the future.",
                "Your profile tells me you are thinking years ahead and I want to join that vision.",
                "I promise our story will be something worth imagining.",
            ],
            "prefill_text": "She is a sci-fi reader. Write an opener that appeals to her futuristic thinking.",
            "upload_hint": "Upload a screenshot of her profile so the cosmic connection is real.",
            "her_info_prefill": "She is a sci-fi reader. Thinks about the future, big ideas, intellectually curious.",
        },
        {
            "slug": "self-help-reader",
            "keyword": "Self-Help Reader",
            "h1": "The Best Self-Help Reader Pickup Lines (For When She Is Always Improving).",
            "title": "Best Self-Help Reader Pickup Lines | TryAgainText",
            "meta_description": "Use niche self-help reader pickup lines that feel growth-oriented, supportive, and genuinely invested in becoming better. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she reads self-help, she is focused on personal growth and self-improvement. She wants someone who also wants to level up. These lines honor her development.",
            "witty_lines": [
                "Your profile has self-help reader energy — you are always working on becoming the best version of yourself.",
                "I can tell you invest in your growth and appreciate when others do the same.",
                "You seem like someone who sees relationships as an opportunity to grow together.",
            ],
            "flirty_lines": [
                "Your commitment to growth is really attractive and I want to grow with you.",
                "Something about your energy tells me you are looking for someone who also values self-improvement.",
                "You carry yourself with this purpose-driven energy that is genuinely inspiring.",
            ],
            "cheesy_lines": [
                "Are you a self-help reader? Because meeting you feels like personal growth.",
                "Your profile tells me you are leveling up and I want to be part of that journey.",
                "I promise to grow alongside you and never stop improving.",
            ],
            "prefill_text": "She is a self-help reader. Write an opener that celebrates growth and improvement.",
            "upload_hint": "Upload a screenshot of her profile so the growth commitment is genuine.",
            "her_info_prefill": "She is a self-help reader. Values growth, self-improvement, personal development.",
        },
        {
            "slug": "historical-fiction",
            "keyword": "Historical Fiction",
            "h1": "The Best Historical Fiction Reader Pickup Lines (For When She Loves the Past).",
            "title": "Best Historical Fiction Reader Pickup Lines | TryAgainText",
            "meta_description": "Use niche historical fiction reader pickup lines that feel nostalgic, romantic, and appreciative of context. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she reads historical fiction, she loves understanding context, appreciates the past, and finds romance in history. These lines honor her historical sensibility.",
            "witty_lines": [
                "Your profile has historical fiction reader energy — you appreciate context and love good stories.",
                "I can tell you understand that people and events are shaped by their time period.",
                "You seem like someone who finds romance in the past and lessons in history.",
            ],
            "flirty_lines": [
                "Your appreciation for history and context is really attractive.",
                "Something about your energy tells me you value understanding where people come from.",
                "You carry yourself with this grounded historical awareness that is genuinely wise.",
            ],
            "cheesy_lines": [
                "Are you a historical fiction reader? Because I want our story to become history.",
                "Your profile tells me you appreciate stories that have lasted through time.",
                "I promise to be someone worth writing into your story.",
            ],
            "prefill_text": "She reads historical fiction. Write an opener that celebrates history and context.",
            "upload_hint": "Upload a screenshot of her profile so the nostalgia is shared.",
            "her_info_prefill": "She reads historical fiction. Appreciates history, context, romance in the past.",
        },
        {
            "slug": "literary-fiction",
            "keyword": "Literary Fiction",
            "h1": "The Best Literary Fiction Reader Pickup Lines (For When She Appreciates Prose).",
            "title": "Best Literary Fiction Reader Pickup Lines | TryAgainText",
            "meta_description": "Use niche literary fiction reader pickup lines that feel thoughtful, nuanced, and appreciative of beautiful writing. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she reads literary fiction, she appreciates beautiful prose, complex characters, and emotional depth. She notices writing quality. These lines honor her literary taste.",
            "witty_lines": [
                "Your profile has literary fiction reader energy — you appreciate beautiful prose and complex characters.",
                "I can tell you notice the quality of writing and expect depth from stories.",
                "You seem like someone who reads between the lines and finds meaning everywhere.",
            ],
            "flirty_lines": [
                "Your appreciation for nuance and beautiful language is really attractive.",
                "Something about your energy tells me you notice emotional complexity in people.",
                "You carry yourself with this thoughtful literary awareness that is genuinely impressive.",
            ],
            "cheesy_lines": [
                "Are you a literary fiction reader? Because our story deserves beautiful prose.",
                "Your profile tells me you appreciate depth and meaningful connection.",
                "I promise to be interesting enough to write about.",
            ],
            "prefill_text": "She reads literary fiction. Write an opener with beautiful, thoughtful language.",
            "upload_hint": "Upload a screenshot of her profile so the writing quality matches her taste.",
            "her_info_prefill": "She reads literary fiction. Appreciates prose quality, complex characters, emotional depth.",
        },
        {
            "slug": "horror-reader",
            "keyword": "Horror Reader",
            "h1": "The Best Horror Reader Pickup Lines (For When She Loves the Thrill).",
            "title": "Best Horror Reader Pickup Lines | TryAgainText",
            "meta_description": "Use niche horror reader pickup lines that feel intense, thrilling, and genuinely daring. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she reads horror, she loves intensity, adrenaline, and facing fears. She is braver than most. These lines honor her fearless nature.",
            "witty_lines": [
                "Your profile has horror reader energy — you are comfortable with intensity and not afraid of darkness.",
                "I can tell you face fear directly and find it fascinating rather than paralyzing.",
                "You seem like someone who is not easily scared and appreciates that in others too.",
            ],
            "flirty_lines": [
                "Your fearless energy is really attractive and I love your bravery.",
                "Something about your intensity tells me you are looking for someone equally unflinching.",
                "You carry yourself with this daring confidence that is genuinely magnetic.",
            ],
            "cheesy_lines": [
                "Are you a horror reader? Because you just gave me chills in the best way.",
                "Your profile tells me you are not afraid of the dark parts of life.",
                "I promise to be brave alongside you.",
            ],
            "prefill_text": "She is a horror reader. Write an opener that celebrates her fearless intensity.",
            "upload_hint": "Upload a screenshot of her profile so the thrills are shared.",
            "her_info_prefill": "She is a horror reader. Fearless, intense, appreciates facing darkness.",
        },
        {
            "slug": "ya-reader",
            "keyword": "YA Reader",
            "h1": "The Best YA Reader Pickup Lines (For When She Still Believes in Magic).",
            "title": "Best YA Reader Pickup Lines | TryAgainText",
            "meta_description": "Use niche YA reader pickup lines that feel youthful, romantic, and genuinely magical. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she reads YA, she still believes in magic, adventure, and that love can change everything. She is young at heart. These lines celebrate her wonder.",
            "witty_lines": [
                "Your profile has YA reader energy — you still believe in magic and adventure.",
                "I can tell you have not lost the wonder of believing in true love.",
                "You seem like someone whose heart is still young enough to believe in everything.",
            ],
            "flirty_lines": [
                "Your romantic idealism is really attractive and I love your belief in magic.",
                "Something about your energy tells me you are looking for a love story that feels destined.",
                "You carry yourself with this youthful wonder that is genuinely captivating.",
            ],
            "cheesy_lines": [
                "Are you a YA reader? Because meeting you feels like destiny.",
                "Your profile tells me you still believe in true love and so do I.",
                "I promise our story will feel like young adult magic.",
            ],
            "prefill_text": "She is a YA reader. Write an opener that celebrates her romantic idealism.",
            "upload_hint": "Upload a screenshot of her profile so the magic is mutual.",
            "her_info_prefill": "She is a YA reader. Romantic, believes in magic, young at heart.",
        },
        {
            "slug": "poetry-lover",
            "keyword": "Poetry Lover",
            "h1": "The Best Poetry Lover Pickup Lines (For When She Notices Every Word).",
            "title": "Best Poetry Lover Pickup Lines | TryAgainText",
            "meta_description": "Use niche poetry lover pickup lines that feel lyrical, meaningful, and beautifully crafted. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she loves poetry, she notices word choice, meaning, and beauty in language. Empty phrases will not impress. These lines are carefully chosen.",
            "witty_lines": [
                "Your profile has poetry lover energy — you notice every word and appreciate when they matter.",
                "I can tell you appreciate language that is crafted with intention and beauty.",
                "You seem like someone who reads between lines and finds meaning in silence.",
            ],
            "flirty_lines": [
                "Your sensitivity to language and meaning is really attractive.",
                "Something about your energy tells me you hear poetry in everyday moments.",
                "You carry yourself with this lyrical awareness that is genuinely beautiful.",
            ],
            "cheesy_lines": [
                "Are you a poetry lover? Because you deserve words that matter.",
                "Your profile tells me I need to choose my words very carefully with you.",
                "I promise to speak to your heart in language that moves you.",
            ],
            "prefill_text": "She is a poetry lover. Write an opener with beautiful, meaningful language.",
            "upload_hint": "Upload a screenshot of her profile so the poetry is actually relevant.",
            "her_info_prefill": "She is a poetry lover. Notices language, appreciates meaning, loves beauty in words.",
        },
        {
            "slug": "audiobook-listener",
            "keyword": "Audiobook Listener",
            "h1": "The Best Audiobook Listener Pickup Lines (For When She Reads While Living).",
            "title": "Best Audiobook Listener Pickup Lines | TryAgainText",
            "meta_description": "Use niche audiobook listener pickup lines that feel practical, engaging, and genuinely conversational. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she listens to audiobooks, she is always growing and learning while living. She values efficiency and engagement. These lines honor her active mind.",
            "witty_lines": [
                "Your profile has audiobook listener energy — you are always learning while living.",
                "I can tell you maximize your time and appreciate good stories.",
                "You seem like someone who grows through listening and staying engaged.",
            ],
            "flirty_lines": [
                "Your commitment to constant growth is really attractive.",
                "Something about your energy tells me you are looking for someone equally engaged with life.",
                "You carry yourself with this dynamic awareness that is genuinely inspiring.",
            ],
            "cheesy_lines": [
                "Are you an audiobook listener? Because I could listen to you all day.",
                "Your profile tells me you are the kind of person worth talking to constantly.",
                "I promise our conversations will be worth your time.",
            ],
            "prefill_text": "She is an audiobook listener. Write an opener that is engaging and conversational.",
            "upload_hint": "Upload a screenshot of her profile so the conversation quality is real.",
            "her_info_prefill": "She is an audiobook listener. Always learning, efficient, appreciates good stories.",
        },
        {
            "slug": "graphic-novel-reader",
            "keyword": "Graphic Novel Reader",
            "h1": "The Best Graphic Novel Reader Pickup Lines (For When She Appreciates Art and Story).",
            "title": "Best Graphic Novel Pickup Lines | TryAgainText",
            "meta_description": "Use niche graphic novel reader pickup lines that feel creative, visually aware, and genuinely artistic. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she reads graphic novels, she appreciates both art and story equally. She is visually literate and creatively minded. These lines honor her artistic sensibility.",
            "witty_lines": [
                "Your profile has graphic novel reader energy — you appreciate both art and story.",
                "I can tell you notice visual details and creative expression.",
                "You seem like someone whose aesthetic sense is just as important as your story sense.",
            ],
            "flirty_lines": [
                "Your artistic appreciation is really attractive and I love how you see the world.",
                "Something about your energy tells me you are visually stimulated and creatively minded.",
                "You carry yourself with this creative awareness that is genuinely inspiring.",
            ],
            "cheesy_lines": [
                "Are you a graphic novel reader? Because our story deserves beautiful panels.",
                "Your profile tells me you appreciate art and meaning in equal measure.",
                "I promise to see the beauty in every moment with you.",
            ],
            "prefill_text": "She is a graphic novel reader. Write an opener that appreciates both art and story.",
            "upload_hint": "Upload a screenshot of her profile so the creative connection is visual.",
            "her_info_prefill": "She reads graphic novels. Appreciates art and story, visually literate, creative.",
        },
        {
            "slug": "non-fiction-reader",
            "keyword": "Non-Fiction Reader",
            "h1": "The Best Non-Fiction Reader Pickup Lines (For When She Values Truth).",
            "title": "Best Non-Fiction Reader Pickup Lines | TryAgainText",
            "meta_description": "Use niche non-fiction reader pickup lines that feel genuine, grounded, and factually honest. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she reads non-fiction, she values truth and reality over fiction. She wants genuine connection. These lines are honest and straightforward.",
            "witty_lines": [
                "Your profile has non-fiction reader energy — you value truth and grounded reality.",
                "I can tell you appreciate honesty and want people to be real with you.",
                "You seem like someone who prefers genuine stories to made-up ones.",
            ],
            "flirty_lines": [
                "Your commitment to truth and reality is really attractive.",
                "Something about your energy tells me you are looking for genuine, honest connection.",
                "You carry yourself with this grounded authenticity that is genuinely impressive.",
            ],
            "cheesy_lines": [
                "Are you a non-fiction reader? Because our story deserves to be real.",
                "Your profile tells me you want facts, not fiction.",
                "I promise complete honesty and genuine connection with you.",
            ],
            "prefill_text": "She is a non-fiction reader. Write an opener that is genuine and factually honest.",
            "upload_hint": "Upload a screenshot of her profile so the truth is actual.",
            "her_info_prefill": "She is a non-fiction reader. Values truth, grounded, wants genuineness.",
        },
        {
            "slug": "booktok-girl",
            "keyword": "BookTok Girl",
            "h1": "The Best BookTok Girl Pickup Lines (For When She Shares Her Reads).",
            "title": "Best BookTok Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche BookTok girl pickup lines that feel community-oriented, enthusiastic, and genuinely passionate. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a BookTok girl, she shares her reads publicly, builds community, and is enthusiastically vocal about books. She wants someone who understands the hype.",
            "witty_lines": [
                "Your profile has BookTok girl energy — you share what you love and build community around books.",
                "I can tell you are passionate about what you read and not afraid to talk about it.",
                "You seem like someone whose recommendations actually matter and people listen.",
            ],
            "flirty_lines": [
                "Your enthusiasm and community spirit are really attractive.",
                "Something about your energy tells me you are looking for someone who gets the hype.",
                "You carry yourself with this infectious passion that is genuinely captivating.",
            ],
            "cheesy_lines": [
                "Are you a BookTok girl? Because I want our story to go viral.",
                "Your profile tells me you are worth talking about and sharing.",
                "I promise to be the kind of love story that deserves a BookTok recommendation.",
            ],
            "prefill_text": "She is a BookTok girl. Write an opener that celebrates her book passion and community.",
            "upload_hint": "Upload a screenshot of her profile so the enthusiasm is shared.",
            "her_info_prefill": "She is a BookTok girl. Shares reads, passionate, community-oriented, enthusiastic.",
        },
    ],
}

