DATA = {
    "category_slug": "dating-apps",
    "category_name": "Dating Apps",
    "sort_order": 17,
    "topics": [
        {
            "slug": "hinge-openers",
            "keyword": "Hinge Openers",
            "h1": "The Best Hinge Openers (For When You Need the Perfect First Comment).",
            "title": "Best Hinge Openers | TryAgainText",
            "meta_description": "Use niche Hinge opener lines that feel personalized, thoughtful, and designed for Hinge's comment-based matching. Then generate a custom opener from her exact profile.",
            "seo_intro": "If you are messaging on Hinge, you need an opener that references her profile and shows you actually read it. Generic comments get ignored. These openers reference something real about her profile to start a genuine conversation.",
            "witty_lines": [
                "Your [detail from profile] tells me you are someone who actually has taste in [topic], and I appreciate that.",
                "I am probably not the first person to comment on [her detail], but I want to tell you why it matters.",
                "Your profile tells me you would appreciate someone who [specific trait], and that is exactly the energy I want to bring.",
            ],
            "flirty_lines": [
                "I want to be someone who gets the same kind of attention you clearly deserve.",
                "Something about your [profile detail] tells me you are genuinely worth the effort and I am here for it.",
                "You deserve someone who actually looks at your profile and wants to know more.",
            ],
            "cheesy_lines": [
                "Are you on Hinge? Because I think I just found what I am looking for.",
                "Your profile tells me you are actually interesting and I am here for that.",
                "I promise to comment better than everyone else on Hinge.",
            ],
            "prefill_text": "She is on Hinge. Write an opener that references something specific from her profile or photos.",
            "upload_hint": "Upload a screenshot of her Hinge profile so the comment feels genuinely personalized.",
            "her_info_prefill": "She is on Hinge. Wants genuine conversation starters, appreciates comments that reference her actual profile.",
        },
        {
            "slug": "bumble-first-message",
            "keyword": "Bumble First Message",
            "h1": "The Best Bumble First Messages (For When She Made the First Move).",
            "title": "Best Bumble First Messages | TryAgainText",
            "meta_description": "Use niche Bumble opening messages that feel confident, responsive, and genuinely interested. Then generate a custom message from her exact opening vibe.",
            "seo_intro": "On Bumble, she messaged first so she is already interested. Your job is to match her energy and show you are actually interested back. These messages respond to her opening without being generic.",
            "witty_lines": [
                "Your opener tells me you are the type who makes the first move and I respect that confidence.",
                "I could have swiped past but I am glad you sent the first message instead.",
                "You seem like someone who knows what she wants and is not afraid to say it.",
            ],
            "flirty_lines": [
                "I want to be the kind of person worth making the first move for.",
                "Something about your energy tells me you expect someone who actually matches your confidence.",
                "You deserve someone who appreciates that you had the courage to message first.",
            ],
            "cheesy_lines": [
                "Thank you for being brave enough to message first, I would have regretted if you didn't.",
                "Your message tells me you are worth the risk of saying yes.",
                "I promise to make your first move worth it.",
            ],
            "prefill_text": "She messaged first on Bumble. Write a message that matches her energy and shows genuine interest.",
            "upload_hint": "Upload a screenshot of her opening message so your response actually connects to what she said.",
            "her_info_prefill": "She messaged first on Bumble. Confident, took the initiative, wants someone matching her energy.",
        },
        {
            "slug": "tinder-opener",
            "keyword": "Tinder Opener",
            "h1": "The Best Tinder Openers (For When You Just Matched).",
            "title": "Best Tinder Openers | TryAgainText",
            "meta_description": "Use niche Tinder opening lines that feel unique, clever, and actually get responses. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "On Tinder, your first message needs to stand out from 50 other generic 'hey' messages. You need something that makes her actually want to respond. These openers avoid being boring without being creepy.",
            "witty_lines": [
                "Your profile tells me you probably get a lot of boring openers, so I am just going to say something real.",
                "I could say 'hey' like everyone else, but you clearly deserve more interesting.",
                "You seem like someone who appreciates genuine conversation over generic opening lines.",
            ],
            "flirty_lines": [
                "I want to be the Tinder message you are actually excited to respond to.",
                "Something about your profile tells me you expect someone who puts thought into their first message.",
                "You deserve someone who actually tries instead of just saying hi.",
            ],
            "cheesy_lines": [
                "Are you a match? Because I think I just won the Tinder lottery.",
                "Your profile is so interesting I had to say more than just hey.",
                "I promise to be the best conversation you have had on Tinder.",
            ],
            "prefill_text": "She matched with you on Tinder. Write an opener that stands out and actually gets a response.",
            "upload_hint": "Upload a screenshot of her Tinder profile so the opener feels connected to who she actually is.",
            "her_info_prefill": "She is on Tinder. Tired of generic openers, wants genuine conversation starters.",
        },
        {
            "slug": "coffee-meets-bagel",
            "keyword": "Coffee Meets Bagel",
            "h1": "The Best Coffee Meets Bagel Openers (For When the App Matters).",
            "title": "Best Coffee Meets Bagel Openers | TryAgainText",
            "meta_description": "Use niche Coffee Meets Bagel opening lines that feel intentional, thoughtful, and designed for serious dating. Then generate a custom opener from her exact profile.",
            "seo_intro": "Coffee Meets Bagel users are looking for something real. Your opener needs to feel intentional and show you are actually looking for a genuine connection, not just a quick match.",
            "witty_lines": [
                "Your profile tells me you are the type looking for something real, and that is exactly what I want too.",
                "I appreciate that CMB actually makes you match with people who are serious.",
                "You seem like someone who values actual compatibility over just swiping.",
            ],
            "flirty_lines": [
                "I want to be someone you actually see a future with.",
                "Something about your profile tells me you are ready for something real.",
                "You deserve someone who is actually serious about finding connection.",
            ],
            "cheesy_lines": [
                "Coffee Meets Bagel paired us for a reason and I think that reason is obvious.",
                "Your profile tells me you are the kind of person worth actually trying for.",
                "I promise this will not be just another CMB match that fizzles.",
            ],
            "prefill_text": "She matched with you on Coffee Meets Bagel. Write an opener showing you want something real.",
            "upload_hint": "Upload a screenshot of her profile so the opener feels genuinely matched.",
            "her_info_prefill": "She is on Coffee Meets Bagel. Serious about dating, values intention, wants genuine connection.",
        },
        {
            "slug": "hinge-prompt-answers",
            "keyword": "Hinge Prompt Answers",
            "h1": "The Best Hinge Prompt Answers (For When You Need to Actually Respond).",
            "title": "Best Hinge Prompt Answers | TryAgainText",
            "meta_description": "Use niche Hinge prompt response lines that feel genuine, thoughtful, and designed to keep the conversation going. Then generate a custom response from her exact question.",
            "seo_intro": "When a girl asks you a Hinge prompt question, your answer needs to feel genuine and move toward actual conversation. Generic or deflecting answers kill momentum. These responses actually address her question.",
            "witty_lines": [
                "Your question tells me you actually want to know the answer, not just match with someone random.",
                "I appreciate that Hinge makes you ask real questions instead of just judging on photos.",
                "You seem like someone who values the actual getting-to-know-you part.",
            ],
            "flirty_lines": [
                "I want to give you an answer that makes you actually want to keep talking.",
                "Something about your question tells me you are worth being genuine with.",
                "You deserve an actual answer, not just a deflection.",
            ],
            "cheesy_lines": [
                "Your prompt question is so good I actually want to answer it honestly.",
                "I promise my answer will be real and probably more interesting than you expected.",
                "That is actually a great question and I have a good answer.",
            ],
            "prefill_text": "She asked you a Hinge prompt question. Write an answer that is genuine and keeps conversation flowing.",
            "upload_hint": "Upload a screenshot of her prompt question so your answer actually connects.",
            "her_info_prefill": "She is on Hinge asking prompt questions. Wants genuine answers, values real conversation.",
        },
        {
            "slug": "bumble-prompt-response",
            "keyword": "Bumble Prompt Response",
            "h1": "The Best Bumble Prompt Responses (For When She Asked a Question).",
            "title": "Best Bumble Prompt Responses | TryAgainText",
            "meta_description": "Use niche Bumble response lines that feel thoughtful, engaging, and genuinely interested. Then generate a custom response from her exact prompt vibe.",
            "seo_intro": "On Bumble, if a girl sends you a prompt question in her opening message, your response needs to show you actually read it and care enough to answer real. These responses match her question energy.",
            "witty_lines": [
                "Your question tells me you are looking for an actual conversation, not small talk.",
                "I could give you a boring answer but you clearly deserve better.",
                "You seem like someone who values genuine responses to real questions.",
            ],
            "flirty_lines": [
                "I want to give you an answer that makes you excited to keep this going.",
                "Something about your question tells me you expect someone thoughtful.",
                "You deserve an actual conversation starter response.",
            ],
            "cheesy_lines": [
                "That is such a good prompt question I actually want to answer it well.",
                "Your question is so thoughtful I promise to give you a real answer.",
                "I appreciate that you asked something worth actually thinking about.",
            ],
            "prefill_text": "She sent you a prompt question on Bumble. Write a response that is genuine and engaging.",
            "upload_hint": "Upload a screenshot of her opening prompt so your response actually connects.",
            "her_info_prefill": "She sent a prompt question on Bumble. Wants genuine responses, values thoughtful conversation.",
        },
        {
            "slug": "dating-app-bio-girl",
            "keyword": "Dating App Bio Girl",
            "h1": "The Best Dating App Bio Girl Pickup Lines (For Any App).",
            "title": "Best Dating App Bio Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche dating app bio girl pickup lines that reference her actual bio and show you read her profile. Then generate a custom opener from her exact bio vibe.",
            "seo_intro": "The girl who puts real effort into her dating app bio is usually worth the effort too. These openers reference her actual bio and show you did more than just look at photos.",
            "witty_lines": [
                "Your bio tells me exactly what you are looking for and I think that is me.",
                "I could ignore your bio and send a generic opener but you clearly deserve more.",
                "You seem like someone who wrote a real bio expecting someone to actually read it.",
            ],
            "flirty_lines": [
                "I want to be the person your bio was describing.",
                "Something about your bio tells me you are serious about finding someone real.",
                "You deserve someone who actually reads what you write.",
            ],
            "cheesy_lines": [
                "Your bio is so good I had to message instead of just swiping.",
                "I promise I actually read your bio and did not just look at pictures.",
                "Your bio tells me you are interesting and I want to know more.",
            ],
            "prefill_text": "She has a thoughtful dating app bio. Write an opener that references what she actually wrote.",
            "upload_hint": "Upload a screenshot of her profile bio so the opener actually connects to her.",
            "her_info_prefill": "She puts effort into her dating app bio. Wants openers that show you read it, values genuine interest.",
        },
        {
            "slug": "instagram-dm-opener",
            "keyword": "Instagram DM Opener",
            "h1": "The Best Instagram DM Openers (For When You Slide Into DMs).",
            "title": "Best Instagram DM Openers | TryAgainText",
            "meta_description": "Use niche Instagram DM opening lines that feel genuine, not creepy, and actually get responses. Then generate a custom DM from her exact Instagram vibe.",
            "seo_intro": "If you are sliding into DMs on Instagram, you need an opener that feels genuine and not like a mass message. These openers reference something real from her Instagram to stand out.",
            "witty_lines": [
                "Your Instagram tells me you are interesting and I wanted to say hi.",
                "I could send a generic DM but your feed tells me you deserve more thought.",
                "You seem like someone who appreciates when people actually engage with your content.",
            ],
            "flirty_lines": [
                "I want to be the DM that actually makes you want to respond.",
                "Something about your Instagram tells me you are worth the slide into DMs.",
                "You deserve a message that feels genuine, not random.",
            ],
            "cheesy_lines": [
                "Your Instagram is so good I had to slide into DMs to say hi.",
                "I promise this is not a copy-paste DM, I actually think you are cool.",
                "Your vibe matches mine and I wanted you to know.",
            ],
            "prefill_text": "You are sliding into her Instagram DMs. Write an opener that feels genuine and gets a response.",
            "upload_hint": "Upload a screenshot of her Instagram profile so the DM feels actually personalized.",
            "her_info_prefill": "You found her on Instagram. Wants genuine DMs, not generic mass messages or creepy compliments.",
        },
    ],
}
