DATA = {
    "category_slug": "dog-breeds",
    "category_name": "Dog Breeds",
    "sort_order": 6,
    "topics": [
        {
            "slug": "golden-retriever",
            "keyword": "Golden Retriever",
            "h1": "The Best Golden Retriever Pickup Lines (For When She Has That Loyal, Sunshine Energy).",
            "title": "Best Golden Retriever Pickup Lines | TryAgainText",
            "meta_description": "Use niche Golden Retriever pickup lines that feel warm, playful, and loyal. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If her profile screams golden retriever energy — warm smile, outdoorsy photos, radiates kindness — these lines match that vibe without being corny. Use one as-is or generate something custom from her actual profile.",
            "witty_lines": [
                "Your profile has golden retriever energy and I mean that as the highest compliment a human can receive.",
                "I can tell you are the kind of person who makes strangers smile in the grocery store. That is weirdly attractive.",
                "You give off the vibe of someone who would absolutely stop a car to pet a dog. I need that energy in my life.",
            ],
            "flirty_lines": [
                "Your smile is the kind that makes people forget what they were about to say. It just happened to me.",
                "Something about your photos tells me you are warm, loyal, and probably give incredible hugs. I would like to test that last one.",
                "You seem like the kind of person who makes everywhere she goes feel a little more like home.",
            ],
            "cheesy_lines": [
                "Are you a golden retriever? Because I instantly trust you and want to spend all my time with you.",
                "They say golden retrievers are the most lovable breed. Your profile is giving that exact energy.",
                "I think I just found my favorite person on this app and yes I am talking about the golden retriever girl.",
            ],
            "prefill_text": "Her profile has warm, golden retriever energy — outdoorsy, smiling, and approachable. Write a playful opener that matches her sunshine vibe.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual personality, not just the dog breed comparison.",
            "her_info_prefill": "She has golden retriever energy. Warm smile, outdoorsy photos, looks like she radiates kindness.",
        },
        {
            "slug": "husky",
            "keyword": "Husky",
            "h1": "The Best Husky Pickup Lines (For When She Is Beautiful, Independent, and Slightly Dramatic).",
            "title": "Best Husky Pickup Lines | TryAgainText",
            "meta_description": "Use niche Husky pickup lines that feel bold, playful, and a little wild. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Husky energy means she is gorgeous, independent, and probably a little dramatic in the best way. She does not follow — she leads. These lines match that untamed confidence.",
            "witty_lines": [
                "Your profile has husky energy — stunning, slightly dramatic, and definitely not listening to anyone's rules.",
                "I can tell you are the type who has a strong opinion about everything and somehow makes that charming.",
                "Your photos have this wild, independent energy that makes me think you would rather run free than settle for boring.",
            ],
            "flirty_lines": [
                "You are giving gorgeous and untameable and I am here for every bit of it.",
                "Something about your vibe says you are fiercely loyal but only to people who actually earn it. Challenge accepted.",
                "Your energy is striking and I do not think you hear that enough from people who actually mean it.",
            ],
            "cheesy_lines": [
                "Are you a husky? Because you are beautiful, dramatic, and I am already obsessed.",
                "They say huskies are impossible to train. I am not trying to train you, just trying to keep up.",
                "Your profile hit me like a husky zoomie — fast, chaotic, and impossible to look away from.",
            ],
            "prefill_text": "Her profile has husky energy — beautiful, independent, and a little dramatic. Write a bold opener that respects her wild side.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her real personality, not just the husky comparison.",
            "her_info_prefill": "She has husky energy. Striking photos, independent vibe, looks like she does things her own way.",
        },
        {
            "slug": "french-bulldog",
            "keyword": "French Bulldog",
            "h1": "The Best French Bulldog Pickup Lines (For When She Is Cute, Funny, and Low-Key Bougie).",
            "title": "Best French Bulldog Pickup Lines | TryAgainText",
            "meta_description": "Use niche French Bulldog pickup lines that feel playful, cute, and a little bougie. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "French bulldog energy is adorable, a little sassy, and unapologetically bougie. If her profile has that cute-but-knows-it vibe, these lines land perfectly.",
            "witty_lines": [
                "Your profile has Frenchie energy — compact, adorable, and radiating main character vibes on a couch somewhere.",
                "I can tell you appreciate the finer things but also spend entire Sundays doing absolutely nothing. My kind of person.",
                "You give off the energy of someone whose apartment is nicer than mine and who definitely has a skincare routine.",
            ],
            "flirty_lines": [
                "You are cute, clearly have taste, and probably know the best brunch spots. I am already invested.",
                "Something about your photos says you are equal parts cozy and classy. That combination is dangerously attractive.",
                "Your vibe is effortlessly charming and I think you know exactly what you are doing with that.",
            ],
            "cheesy_lines": [
                "Are you a French Bulldog? Because you are impossibly cute and I want to take you everywhere.",
                "They say Frenchies snore a lot. I will take that over boring conversation any day.",
                "Your profile is giving premium Frenchie energy — small but commanding the entire room.",
            ],
            "prefill_text": "Her profile has French Bulldog energy — cute, sassy, and a little bougie. Write a charming opener that matches her vibe.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual style, not just the breed comparison.",
            "her_info_prefill": "She has French Bulldog energy. Cute photos, stylish, looks like she appreciates good food and cozy vibes.",
        },
        {
            "slug": "german-shepherd",
            "keyword": "German Shepherd",
            "h1": "The Best German Shepherd Pickup Lines (For When She Is Loyal, Smart, and Does Not Mess Around).",
            "title": "Best German Shepherd Pickup Lines | TryAgainText",
            "meta_description": "Use niche German Shepherd pickup lines that feel confident, loyal, and sharp. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "German shepherd energy means she is smart, protective of her circle, and does not waste time on people who are not serious. These lines show you can match her intensity.",
            "witty_lines": [
                "Your profile has German Shepherd energy — smart, loyal, and definitely running a background check on me right now.",
                "I can tell you are the kind of person people go to for advice because you are always the most put-together one in the room.",
                "Your photos give off strong protector energy. I bet your friends feel genuinely safe around you.",
            ],
            "flirty_lines": [
                "You seem like someone who does not settle for less than she deserves. That confidence is incredibly attractive.",
                "Your energy says you are loyal to the right people and I would love to earn a spot on that list.",
                "I get the feeling you are sharp, direct, and do not play games. That is exactly my type.",
            ],
            "cheesy_lines": [
                "Are you a German Shepherd? Because you are smart, beautiful, and I feel like I need to impress you.",
                "They say German Shepherds are fiercely loyal. I am looking for exactly that and your profile just flagged you.",
                "Your profile just passed my vibe check with flying colors and that never happens.",
            ],
            "prefill_text": "Her profile has German Shepherd energy — smart, loyal, and no-nonsense. Write a direct, confident opener that shows you are serious.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual personality, not just the breed comparison.",
            "her_info_prefill": "She has German Shepherd energy. Sharp, put-together photos. Looks intelligent, loyal, and does not waste time.",
        },
        {
            "slug": "labrador",
            "keyword": "Labrador",
            "h1": "The Best Labrador Pickup Lines (For When She Is Friendly, Fun, and Everyone Loves Her).",
            "title": "Best Labrador Pickup Lines | TryAgainText",
            "meta_description": "Use niche Labrador pickup lines that feel friendly, energetic, and lovable. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Labrador energy is pure joy — she is friendly, enthusiastic, and the kind of person everyone gravitates toward. These lines match that infectious, lovable vibe.",
            "witty_lines": [
                "Your profile has lab energy — friendly to literally everyone and somehow making that look effortlessly cool.",
                "I can tell you are the person at the party who makes everyone feel included. That is a superpower, not just a personality trait.",
                "You give off the energy of someone who has never met a stranger and honestly that is incredibly refreshing.",
            ],
            "flirty_lines": [
                "Your smile in these photos is the kind that makes an entire room feel warmer. I noticed it immediately.",
                "You seem like the kind of person who brings out the best version of everyone around her. I am curious what that looks like up close.",
                "There is something magnetic about how genuinely happy you look in your photos. I want to know what that energy is like in person.",
            ],
            "cheesy_lines": [
                "Are you a Labrador? Because you are adorable, everyone loves you, and I want to take you to the park.",
                "They say labs are the most popular breed. Looking at your profile, I completely understand why.",
                "Your energy just wagged its way into my heart and I am not even mad about it.",
            ],
            "prefill_text": "Her profile has Labrador energy — friendly, fun, and everyone loves her. Write a warm, upbeat opener that matches her joy.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual personality, not just the breed comparison.",
            "her_info_prefill": "She has Labrador energy. Big smile, active photos, looks like the friendliest person in any room.",
        },
        {
            "slug": "corgi",
            "keyword": "Corgi",
            "h1": "The Best Corgi Pickup Lines (For When She Is Short, Sweet, and Full of Personality).",
            "title": "Best Corgi Pickup Lines | TryAgainText",
            "meta_description": "Use niche Corgi pickup lines that feel cute, quirky, and full of character. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Corgi energy is compact, confident, and impossibly charming. If her profile radiates that fun-sized-but-big-personality vibe, these lines are tailored for her.",
            "witty_lines": [
                "Your profile has corgi energy — small but absolutely commanding the entire room and I am not complaining.",
                "I can tell you are the kind of person who does not need to be the loudest to be the most memorable. That is a rare quality.",
                "You give off the energy of someone who is simultaneously adorable and in charge. That duality is very attractive.",
            ],
            "flirty_lines": [
                "Your personality comes through your photos so clearly and it is genuinely one of the most charming things I have seen on this app.",
                "Something about your vibe tells me you are funnier than most people expect. I would love to find out firsthand.",
                "You seem like the kind of person who makes everything more entertaining just by being there. I want that energy around.",
            ],
            "cheesy_lines": [
                "Are you a corgi? Because you are unreasonably cute and I cannot look away.",
                "They say good things come in small packages. Your profile just proved that scientifically.",
                "Your energy just waddled into my heart at full speed and I have no complaints.",
            ],
            "prefill_text": "Her profile has corgi energy — cute, quirky, and full of personality. Write a charming opener that matches her fun vibe.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual personality, not just the breed comparison.",
            "her_info_prefill": "She has Corgi energy. Cute, fun-sized, big personality that fills the room.",
        },
        {
            "slug": "poodle",
            "keyword": "Poodle",
            "h1": "The Best Poodle Pickup Lines (For When She Is Elegant, Smart, and Knows Her Worth).",
            "title": "Best Poodle Pickup Lines | TryAgainText",
            "meta_description": "Use niche Poodle pickup lines that feel elegant, intelligent, and refined. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Poodle energy is elegant, intelligent, and unapologetically high-maintenance in the best way. If she carries herself with that polished, smart confidence, these lines match her perfectly.",
            "witty_lines": [
                "Your profile has poodle energy — elegant, clearly intelligent, and making everyone else look underdressed by comparison.",
                "I can tell you are the kind of person who has her life together in a way that is both impressive and slightly intimidating. I am into it.",
                "Your photos have this polished, intentional quality that tells me you put thought into everything you do. That is rare.",
            ],
            "flirty_lines": [
                "Your elegance is effortless and that is the hardest thing to pull off. I noticed it immediately.",
                "Something about your profile tells me you appreciate quality over quantity in every part of your life. I would love to meet that standard.",
                "You carry yourself with this quiet confidence that is infinitely more attractive than anything loud or obvious.",
            ],
            "cheesy_lines": [
                "Are you a poodle? Because you are elegant, intelligent, and clearly the most refined one here.",
                "They say poodles are one of the smartest breeds. Your profile just proved beauty and brains coexist perfectly.",
                "Your profile just set the bar so high that everyone else on this app should probably go home.",
            ],
            "prefill_text": "Her profile has poodle energy — elegant, smart, and polished. Write a refined opener that matches her sophistication.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just the breed comparison.",
            "her_info_prefill": "She has Poodle energy. Elegant, intelligent, polished photos. Carries herself with quiet confidence.",
        },
        {
            "slug": "pitbull",
            "keyword": "Pitbull",
            "h1": "The Best Pitbull Pickup Lines (For When She Is Tough on the Outside, Soft on the Inside).",
            "title": "Best Pitbull Pickup Lines | TryAgainText",
            "meta_description": "Use niche Pitbull pickup lines that feel strong, genuine, and surprisingly soft. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Pitbull energy means she looks tough but is secretly the most loyal, affectionate person once you earn her trust. These lines respect that duality.",
            "witty_lines": [
                "Your profile has pitbull energy — intimidating at first glance but I can tell you are secretly the most loyal person in the room.",
                "I get the feeling people underestimate how soft you actually are and you let them because it is funnier that way.",
                "You have this strong, grounded presence in your photos that says 'I do not need your approval but I will accept your attention.'",
            ],
            "flirty_lines": [
                "Your confidence is magnetic but it is the warmth underneath it that actually caught my attention.",
                "Something tells me your loyalty is earned, not given. I would love the chance to prove I am worth it.",
                "You seem like the kind of person who is fiercely protective of the people she loves. That is incredibly attractive.",
            ],
            "cheesy_lines": [
                "Are you a pitbull? Because you look tough but I bet you are the biggest sweetheart once I get to know you.",
                "They say pitbulls are misunderstood. Your profile tells me you have layers most people never get to see.",
                "Your energy is strong and soft at the same time and that combination is unbeatable.",
            ],
            "prefill_text": "Her profile has pitbull energy — strong exterior, loyal heart. Write a genuine opener that sees past the surface.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual personality, not just the tough-outside-soft-inside trope.",
            "her_info_prefill": "She has Pitbull energy. Strong, confident exterior. Secretly very loyal and warm with the right people.",
        },
        {
            "slug": "beagle",
            "keyword": "Beagle",
            "h1": "The Best Beagle Pickup Lines (For When She Is Curious, Adventurous, and Impossible to Ignore).",
            "title": "Best Beagle Pickup Lines | TryAgainText",
            "meta_description": "Use niche Beagle pickup lines that feel curious, adventurous, and endlessly charming. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Beagle energy is curious, adventurous, and always following her nose toward the next interesting thing. If she seems like the type who is always exploring, these lines match.",
            "witty_lines": [
                "Your profile has beagle energy — curious about everything, always on an adventure, and impossible to not find adorable.",
                "I can tell you are the kind of person who says yes to things before knowing all the details. That spontaneity is magnetic.",
                "Your photos tell me you have probably gotten lost in a city on purpose just to see what you would find. I respect that deeply.",
            ],
            "flirty_lines": [
                "Your sense of adventure comes through in every photo and it makes me want to plan something spontaneous with you.",
                "Something about your curious energy tells me a date with you would never be boring. Not even for a second.",
                "You seem like the kind of person who turns a wrong turn into the best part of the trip. I want that energy.",
            ],
            "cheesy_lines": [
                "Are you a beagle? Because you just followed my heart's scent and found it immediately.",
                "They say beagles are impossible to keep still. Your adventurous energy just proved why that is a feature, not a flaw.",
                "Your profile is like a treasure trail and I am happily following every clue.",
            ],
            "prefill_text": "Her profile has beagle energy — curious, adventurous, always exploring. Write a fun opener that matches her spontaneous vibe.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual adventures, not just the breed comparison.",
            "her_info_prefill": "She has Beagle energy. Adventure photos, curious vibe, looks like she is always exploring something new.",
        },
        {
            "slug": "shiba-inu",
            "keyword": "Shiba Inu",
            "h1": "The Best Shiba Inu Pickup Lines (For When She Is Independent, Sassy, and Selectively Social).",
            "title": "Best Shiba Inu Pickup Lines | TryAgainText",
            "meta_description": "Use niche Shiba Inu pickup lines that feel witty, independent, and selectively charming. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Shiba Inu energy means she is gorgeous, independent, and only gives her attention to people who actually interest her. She is selective and that is the point. These lines respect that.",
            "witty_lines": [
                "Your profile has shiba energy — gorgeous, clearly independent, and giving attention to exactly zero people who have not earned it.",
                "I can tell you are the kind of person who has a small circle by choice, not circumstance. I would like to apply for consideration.",
                "Your vibe says you do not chase people, people chase you. And here I am, proving your point.",
            ],
            "flirty_lines": [
                "Your selective energy is the most attractive thing on this app. It tells me your attention actually means something.",
                "Something about your independence makes me want to earn your time rather than just ask for it.",
                "You carry yourself like someone who genuinely does not need anyone but would choose the right person. That is powerful.",
            ],
            "cheesy_lines": [
                "Are you a Shiba Inu? Because you are beautiful, independent, and I already know earning your trust will be worth it.",
                "They say Shibas only bond with their chosen person. I am formally submitting my application.",
                "Your profile has that rare 'I am fine on my own but I will accept impressive' energy and I am here to try.",
            ],
            "prefill_text": "Her profile has Shiba Inu energy — independent, selective, gorgeous. Write an opener that earns her attention, not demands it.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual personality, not just the breed comparison.",
            "her_info_prefill": "She has Shiba Inu energy. Independent, selective, gorgeous. Only gives her time to people who genuinely interest her.",
        },
        {
            "slug": "dalmatian",
            "keyword": "Dalmatian",
            "h1": "The Best Dalmatian Pickup Lines (For When She Stands Out and Knows It).",
            "title": "Best Dalmatian Pickup Lines | TryAgainText",
            "meta_description": "Use niche Dalmatian pickup lines that feel bold, unique, and impossible to miss. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Dalmatian energy means she is striking, unique, and impossible to blend into a crowd. She does not look like anyone else and that is entirely the point. These lines celebrate that.",
            "witty_lines": [
                "Your profile has dalmatian energy — distinctive, impossible to ignore, and making everyone else on this app look generic.",
                "I can tell you are the kind of person who has never blended into a crowd, not because you try, but because you genuinely cannot help it.",
                "Your look is so distinct that I actually stopped scrolling. That has not happened in a genuinely long time.",
            ],
            "flirty_lines": [
                "You stand out in a way that is effortless and that makes it even more magnetic.",
                "Something about your unique energy tells me a conversation with you would be anything but predictable. I am very interested.",
                "You have this striking quality that goes beyond looks. It is in the way you carry yourself in every photo.",
            ],
            "cheesy_lines": [
                "Are you a Dalmatian? Because you are one of a kind and I spotted you immediately.",
                "They say no two Dalmatians have the same spots. Your profile proves no two people have the same kind of beautiful.",
                "I must have 101 reasons to message you but I only need one — your profile is genuinely captivating.",
            ],
            "prefill_text": "Her profile has Dalmatian energy — unique, striking, impossible to miss. Write a bold opener that celebrates how she stands out.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches what specifically makes her unique, not just generic compliments.",
            "her_info_prefill": "She has Dalmatian energy. Striking, unique look. Stands out effortlessly in every photo.",
        },
        {
            "slug": "border-collie",
            "keyword": "Border Collie",
            "h1": "The Best Border Collie Pickup Lines (For When She Is the Smartest Person in Every Room).",
            "title": "Best Border Collie Pickup Lines | TryAgainText",
            "meta_description": "Use niche Border Collie pickup lines that feel sharp, driven, and intellectually engaging. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Border collie energy means she is wickedly smart, always working on something, and needs someone who can keep up mentally. Lazy openers get ignored. These lines match her intensity.",
            "witty_lines": [
                "Your profile has border collie energy — the smartest one in the room and probably working on three things simultaneously.",
                "I can tell you are the kind of person who gets bored easily. Consider this my attempt to be interesting enough to hold your attention.",
                "Your photos give off the vibe of someone who has a planner, a side project, and a five-year plan. I find ambition incredibly attractive.",
            ],
            "flirty_lines": [
                "Your intelligence comes through your profile and it is genuinely the most attractive thing I have seen today.",
                "Something tells me you need mental stimulation more than compliments. So here is a question instead: what are you obsessed with right now?",
                "You seem like the kind of person who makes everyone around her smarter just by being in the conversation. I want that experience.",
            ],
            "cheesy_lines": [
                "Are you a Border Collie? Because you are clearly the smartest one here and I am already trying to impress you.",
                "They say Border Collies need constant mental stimulation. I promise this conversation will not bore you.",
                "Your profile just herded all my attention into one place and I am not fighting it.",
            ],
            "prefill_text": "Her profile has Border Collie energy — brilliant, driven, always working on something. Write an intellectually engaging opener.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific interests or ambitions, not just generic 'you seem smart' lines.",
            "her_info_prefill": "She has Border Collie energy. Sharp, ambitious, always busy. Needs someone who can match her mental energy.",
        },
        {
            "slug": "dachshund",
            "keyword": "Dachshund",
            "h1": "The Best Dachshund Pickup Lines (For When She Is Fearless, Funny, and Underestimated).",
            "title": "Best Dachshund Pickup Lines | TryAgainText",
            "meta_description": "Use niche Dachshund pickup lines that feel bold, funny, and surprisingly fearless. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Dachshund energy is small but mighty — she is braver than she looks, funnier than people expect, and absolutely will not back down from anything. These lines match that fearless humor.",
            "witty_lines": [
                "Your profile has dachshund energy — compact, fearless, and clearly not intimidated by anything or anyone.",
                "I can tell you are the kind of person who picks fights with people twice her size and wins. That energy is unmatched.",
                "Your photos give off this vibe of someone who is way tougher than she looks and finds that hilarious.",
            ],
            "flirty_lines": [
                "Your confidence-to-size ratio is genuinely impressive and I mean that as the highest compliment.",
                "Something about your fearless energy tells me you would be the most fun person at any table. I want a seat.",
                "You have this bold, take-no-nonsense vibe that makes me think you are exactly as fun as your profile suggests.",
            ],
            "cheesy_lines": [
                "Are you a Dachshund? Because you are small, mighty, and you just burrowed your way into my heart.",
                "They say Dachshunds were bred to fight badgers. Your energy says you would absolutely win that fight.",
                "Your profile has big dog energy in a fun-sized package and I am completely here for it.",
            ],
            "prefill_text": "Her profile has Dachshund energy — bold, funny, and underestimated. Write a playful opener that matches her fearless vibe.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual personality, not just the small-but-mighty trope.",
            "her_info_prefill": "She has Dachshund energy. Fearless, funny, way braver than she looks. Probably the boldest person in any room.",
        },
        {
            "slug": "great-dane",
            "keyword": "Great Dane",
            "h1": "The Best Great Dane Pickup Lines (For When She Has a Commanding Presence but a Gentle Heart).",
            "title": "Best Great Dane Pickup Lines | TryAgainText",
            "meta_description": "Use niche Great Dane pickup lines that feel grand, gentle, and genuinely impressive. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Great Dane energy means she has a commanding presence but is secretly a gentle giant. She takes up space effortlessly and has a warmth that surprises people. These lines honor that duality.",
            "witty_lines": [
                "Your profile has Great Dane energy — impossible to miss, effortlessly commanding, and probably secretly the gentlest person in the room.",
                "I can tell you are the kind of person who walks into a room and the energy shifts without you even trying.",
                "Your presence in these photos is striking. You have this natural magnetism that most people spend their whole lives trying to manufacture.",
            ],
            "flirty_lines": [
                "You have this powerful, elegant energy that drew me in immediately. And I get the sense there is real warmth underneath it.",
                "Something about your profile tells me you are way more gentle than your presence suggests. That combination is incredibly attractive.",
                "You carry yourself like someone who does not need to prove anything to anyone. That quiet power is magnetic.",
            ],
            "cheesy_lines": [
                "Are you a Great Dane? Because you are majestic, gentle, and I think you could fit on a couch with me.",
                "They say Great Danes think they are lap dogs. Your energy says you are powerful but secretly want to be cozy.",
                "Your profile just towered over everyone else on this app and I am not even a little surprised.",
            ],
            "prefill_text": "Her profile has Great Dane energy — commanding presence, gentle heart. Write an opener that sees both sides.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just the tall-and-impressive trope.",
            "her_info_prefill": "She has Great Dane energy. Commanding presence, turns heads. Secretly gentle and warm once you get close.",
        },
        {
            "slug": "australian-shepherd",
            "keyword": "Australian Shepherd",
            "h1": "The Best Australian Shepherd Pickup Lines (For When She Is Active, Smart, and Always Moving).",
            "title": "Best Australian Shepherd Pickup Lines | TryAgainText",
            "meta_description": "Use niche Australian Shepherd pickup lines that feel energetic, smart, and adventure-ready. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Australian Shepherd energy means she is athletic, brilliant, and always has something going on. She needs someone who can keep up with her pace and match her energy. These lines show you can.",
            "witty_lines": [
                "Your profile has Aussie Shepherd energy — athletic, smart, and clearly not the type to sit still for longer than five minutes.",
                "I can tell you are the kind of person who has a full calendar and still manages to fit in a hike before 8 AM. That discipline is attractive.",
                "Your photos give off this active, always-moving energy that makes me tired and impressed simultaneously.",
            ],
            "flirty_lines": [
                "Your energy is vibrant and your adventures look incredible. I would love to join one sometime.",
                "Something about your active lifestyle tells me you value experiences over things. I share that philosophy completely.",
                "You seem like the kind of person who makes lazy people want to get off the couch. That is a genuine superpower.",
            ],
            "cheesy_lines": [
                "Are you an Australian Shepherd? Because you are beautiful, energetic, and I am already trying to keep up with you.",
                "They say Aussie Shepherds need a job to be happy. Your profile says your job is making everything look effortlessly fun.",
                "Your adventure photos just herded my attention and I am happily following wherever this goes.",
            ],
            "prefill_text": "Her profile has Australian Shepherd energy — active, smart, always on the go. Write an energetic opener that keeps up with her pace.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific activities, not just generic active-lifestyle lines.",
            "her_info_prefill": "She has Australian Shepherd energy. Athletic, smart, always moving. Hiking and adventure photos everywhere.",
        },
        {
            "slug": "rottweiler",
            "keyword": "Rottweiler",
            "h1": "The Best Rottweiler Pickup Lines (For When She Is Protective, Strong, and Deeply Loyal).",
            "title": "Best Rottweiler Pickup Lines | TryAgainText",
            "meta_description": "Use niche Rottweiler pickup lines that feel strong, protective, and deeply genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Rottweiler energy means she is strong, protective of her people, and deeply loyal once you are in her circle. She does not let just anyone in — and that is what makes her trust so valuable.",
            "witty_lines": [
                "Your profile has Rottweiler energy — strong, protective, and clearly not letting anyone into her circle who has not earned it.",
                "I can tell you are the kind of person whose friends feel completely safe around. That protector energy is real and it is attractive.",
                "Your vibe says you do not suffer fools and honestly the bar needed someone to raise it. Thank you.",
            ],
            "flirty_lines": [
                "Your strength is obvious but I am more interested in the loyalty underneath it. That is the real treasure.",
                "Something about your energy tells me once someone earns your trust, they have it completely. I would love to be worth that.",
                "You carry yourself with this powerful, grounded confidence that makes me want to show up as my best self.",
            ],
            "cheesy_lines": [
                "Are you a Rottweiler? Because you look tough, but I bet your loyalty is the most beautiful thing about you.",
                "They say Rottweilers are the most loyal breed. Your profile says your heart is worth earning.",
                "Your energy just guarded my heart and honestly I feel safer already.",
            ],
            "prefill_text": "Her profile has Rottweiler energy — strong, protective, deeply loyal. Write a genuine opener that respects her strength.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual personality, not just the strong-and-loyal trope.",
            "her_info_prefill": "She has Rottweiler energy. Strong, protective, deeply loyal. Does not let just anyone in.",
        },
        {
            "slug": "samoyed",
            "keyword": "Samoyed",
            "h1": "The Best Samoyed Pickup Lines (For When She Is Fluffy, Happy, and Radiates Warmth).",
            "title": "Best Samoyed Pickup Lines | TryAgainText",
            "meta_description": "Use niche Samoyed pickup lines that feel warm, joyful, and irresistibly friendly. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Samoyed energy is pure, warm happiness. She smiles constantly, makes everyone feel welcome, and has this soft, approachable glow. These lines match that cozy, joyful vibe.",
            "witty_lines": [
                "Your profile has Samoyed energy — warm, smiling, and making everyone around you happier just by existing.",
                "I can tell you are the kind of person who walks into a room and the mood immediately improves. That is a genuine gift.",
                "Your photos radiate this effortless warmth that makes me think you have never met someone you could not make smile.",
            ],
            "flirty_lines": [
                "Your smile is the kind that makes strangers on the internet stop scrolling. You should know that.",
                "Something about your warm energy tells me spending time with you feels like the coziest, most comfortable thing in the world.",
                "You radiate this gentle, welcoming vibe that is incredibly rare on dating apps. I could not pass it by.",
            ],
            "cheesy_lines": [
                "Are you a Samoyed? Because you are fluffy, happy, and I want to be near you at all times.",
                "They say Samoyeds have a permanent smile. Your photos have the exact same energy and it is contagious.",
                "Your warmth just melted through my screen and I am not even trying to resist it.",
            ],
            "prefill_text": "Her profile has Samoyed energy — warm, joyful, radiating happiness. Write a cozy opener that matches her glow.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual warmth, not just generic happy-person lines.",
            "her_info_prefill": "She has Samoyed energy. Always smiling, radiates warmth and joy. Makes everyone around her happier.",
        },
        {
            "slug": "doberman",
            "keyword": "Doberman",
            "h1": "The Best Doberman Pickup Lines (For When She Is Sleek, Sharp, and Intimidatingly Beautiful).",
            "title": "Best Doberman Pickup Lines | TryAgainText",
            "meta_description": "Use niche Doberman pickup lines that feel sharp, elegant, and confidently direct. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Doberman energy is sleek, sharp, and intimidatingly beautiful. She carries herself with a precision that makes people look twice. These lines match that razor-sharp elegance.",
            "witty_lines": [
                "Your profile has Doberman energy — sleek, sharp, and making everyone else on this app look sloppy by comparison.",
                "I can tell you are the kind of person who has her aesthetic dialed in to the point where it feels like a personal brand. I respect it deeply.",
                "Your photos have this clean, intentional energy that tells me nothing about you is accidental.",
            ],
            "flirty_lines": [
                "Your elegance has an edge to it and that combination is one of the most attractive things I have encountered on here.",
                "Something about your sharp, polished energy tells me you appreciate someone who comes correct. So here I am, putting in the effort.",
                "You carry yourself with this cool precision that is both intimidating and magnetic. I decided to be brave about it.",
            ],
            "cheesy_lines": [
                "Are you a Doberman? Because you are sleek, sharp, and I am a little intimidated but definitely interested.",
                "They say Dobermans are one of the most elegant breeds. Your profile just confirmed that energy exists in human form.",
                "Your profile has security-detail energy — guarding its own excellence and letting no one unworthy through.",
            ],
            "prefill_text": "Her profile has Doberman energy — sleek, sharp, intimidatingly beautiful. Write a polished opener that matches her precision.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her specific aesthetic, not just generic elegance compliments.",
            "her_info_prefill": "She has Doberman energy. Sleek, sharp, polished. Intimidatingly beautiful with an intentional aesthetic.",
        },
        {
            "slug": "cavalier-king-charles",
            "keyword": "Cavalier King Charles",
            "h1": "The Best Cavalier King Charles Pickup Lines (For When She Is Sweet, Gentle, and Quietly Regal).",
            "title": "Best Cavalier King Charles Pickup Lines | TryAgainText",
            "meta_description": "Use niche Cavalier King Charles pickup lines that feel gentle, sweet, and quietly elegant. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Cavalier King Charles energy is gentle, affectionate, and quietly regal. She has this soft, kind presence that makes people feel instantly comfortable. These lines match that tender elegance.",
            "witty_lines": [
                "Your profile has Cavalier energy — gentle, elegant, and making everyone in the room feel immediately at ease.",
                "I can tell you are the kind of person who remembers small details about people. That thoughtfulness is genuinely rare.",
                "Your photos have this quiet, regal quality that tells me you do not need to be loud to leave an impression.",
            ],
            "flirty_lines": [
                "Your gentle energy is the most calming thing on this entire app. I noticed it immediately and I could not move on.",
                "Something about your quiet confidence tells me you are the kind of person who makes everyone around her feel valued. That is incredibly attractive.",
                "You have this tender, genuine warmth that makes me think a conversation with you would feel like the easiest thing in the world.",
            ],
            "cheesy_lines": [
                "Are you a Cavalier King Charles? Because you are sweet, regal, and I want you to sit in my lap immediately.",
                "They say Cavaliers were bred to be companions. Your profile says you were meant to make someone's life better.",
                "Your gentle elegance just waltzed into my heart like royalty and I am not complaining.",
            ],
            "prefill_text": "Her profile has Cavalier King Charles energy — sweet, gentle, quietly regal. Write a tender opener that matches her soft elegance.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual warmth, not just generic sweet-person lines.",
            "her_info_prefill": "She has Cavalier King Charles energy. Sweet, gentle, quietly elegant. Makes everyone feel comfortable and valued.",
        },
        {
            "slug": "bernese-mountain-dog",
            "keyword": "Bernese Mountain Dog",
            "h1": "The Best Bernese Mountain Dog Pickup Lines (For When She Is Big-Hearted, Outdoorsy, and Endlessly Cuddly).",
            "title": "Best Bernese Mountain Dog Pickup Lines | TryAgainText",
            "meta_description": "Use niche Bernese Mountain Dog pickup lines that feel warm, adventurous, and big-hearted. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Bernese Mountain Dog energy is warm, adventurous, and the kind of person everyone wants to hug. She loves the outdoors, has a huge heart, and makes everyone feel welcome. These lines match that cozy, adventurous spirit.",
            "witty_lines": [
                "Your profile has Bernese energy — big-hearted, outdoorsy, and the kind of person everyone wants to be around at a campfire.",
                "I can tell you are the kind of person who plans the group hike and also brings the best snacks. Both are equally important.",
                "Your photos give off this warm, mountain-lodge energy that makes me want to cancel plans and go on an adventure instead.",
            ],
            "flirty_lines": [
                "Your adventurous spirit comes through in every photo and it is one of the most attractive things I have seen on this app.",
                "Something about your big-hearted energy tells me you are the kind of person who makes everyone feel included. I want to experience that firsthand.",
                "You seem like the kind of person who gives the best hugs and honestly that might be the most underrated quality on a dating app.",
            ],
            "cheesy_lines": [
                "Are you a Bernese Mountain Dog? Because you are beautiful, cuddly, and I want to take you on every adventure.",
                "They say Berners are gentle giants. Your profile has that same rare combination of strong and soft.",
                "Your energy is like a warm cabin in the mountains — inviting, cozy, and exactly where I want to be.",
            ],
            "prefill_text": "Her profile has Bernese Mountain Dog energy — outdoorsy, warm, big-hearted. Write a cozy, adventurous opener that matches her spirit.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific outdoor interests, not just generic adventure lines.",
            "her_info_prefill": "She has Bernese Mountain Dog energy. Outdoorsy, big-hearted, cuddly. Nature photos and a warm, welcoming vibe.",
        },
    ],
}
