DATA = {
    "category_slug": "enneagram",
    "category_name": "Enneagram Types",
    "sort_order": 3,
    "topics": [
        {
            "slug": "type-1",
            "keyword": "Enneagram Type 1",
            "h1": "The Best Enneagram Type 1 Pickup Lines (For the Reformer).",
            "title": "Best Enneagram Type 1 Pickup Lines | TryAgainText",
            "meta_description": "Use niche Enneagram Type 1 pickup lines that feel principled, witty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Type 1s value integrity, quality, and doing things right. They notice effort and care deeply about standards. These lines show you brought your best.",
            "witty_lines": [
                "Your profile has the energy of someone who has strong opinions about how things should be done. I find that incredibly attractive.",
                "I can tell you are a Type 1 because your bio is polished, intentional, and has zero typos. Respect.",
                "You seem like someone who holds herself to a high standard. This is me trying to meet it.",
            ],
            "flirty_lines": [
                "Something about your profile tells me you care about getting things right. So do I \u2014 which is why I rewrote this message.",
                "Your energy is principled and warm at the same time. That combination is rare and very attractive.",
                "I like that your profile feels curated with care. It makes me want to put the same care into this conversation.",
            ],
            "cheesy_lines": [
                "Are you a Type 1? Because you just raised the standard for every profile on this app.",
                "They say Ones strive for perfection. Your profile just achieved it.",
                "I was going to send a lazy opener, but your profile made me want to do better. That is the Type 1 effect.",
            ],
            "prefill_text": "Her bio mentions Enneagram Type 1 or reformer energy. Write a polished, genuine opener that shows effort.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an Enneagram Type 1. Her profile is clean and purposeful. She seems principled, sharp, and detail-oriented.",
        },
        {
            "slug": "type-2",
            "keyword": "Enneagram Type 2",
            "h1": "The Best Enneagram Type 2 Pickup Lines (For the Helper).",
            "title": "Best Enneagram Type 2 Pickup Lines | TryAgainText",
            "meta_description": "Use niche Enneagram Type 2 pickup lines that feel warm, appreciative, and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Type 2s are generous, warm, and deeply caring. They often put others first and appreciate when someone notices them. These lines make her feel seen.",
            "witty_lines": [
                "Your profile has the energy of someone who takes care of everyone else. I am here to take care of this conversation for you.",
                "I can tell you are a Type 2 because your warmth comes through the screen and that is not easy to do.",
                "You seem like someone who makes everyone feel welcome. Consider me feeling very welcome right now.",
            ],
            "flirty_lines": [
                "Something about your warmth makes me want to show up for you the way you clearly show up for others.",
                "Your profile has this generous, caring energy that is genuinely magnetic. I wanted you to know that.",
                "I like that your profile feels like a warm hug. I would love to get to know the person behind it.",
            ],
            "cheesy_lines": [
                "Are you a Type 2? Because you just helped me believe in dating apps again.",
                "They say Twos give love freely. I am ready to receive and return it.",
                "Your profile is the most heartwarming thing on this app and I am not exaggerating.",
            ],
            "prefill_text": "Her bio mentions Enneagram Type 2 or helper energy. Write a warm, appreciative opener that makes her feel seen.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an Enneagram Type 2. Her profile feels nurturing and warm. She seems generous, empathetic, and people-oriented.",
        },
        {
            "slug": "type-3",
            "keyword": "Enneagram Type 3",
            "h1": "The Best Enneagram Type 3 Pickup Lines (For the Achiever).",
            "title": "Best Enneagram Type 3 Pickup Lines | TryAgainText",
            "meta_description": "Use niche Enneagram Type 3 pickup lines that feel impressive, confident, and goal-aware. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Type 3s are driven, image-conscious, and goal-oriented. They appreciate people who match their ambition and bring substance. These lines show you are on her level.",
            "witty_lines": [
                "Your profile looks like a personal brand launch and I mean that as a genuine compliment. It works.",
                "I can tell you are a Type 3 because everything about your profile feels strategic, polished, and effective.",
                "You seem like someone who sets goals and then exceeds them. I hope 'reply to a great opener' is on the list.",
            ],
            "flirty_lines": [
                "Your ambition is showing and honestly it is one of the most attractive things about your profile.",
                "I like that you clearly go after what you want. That confidence is magnetic.",
                "Something about your profile tells me you are the kind of person who makes things happen. I am impressed.",
            ],
            "cheesy_lines": [
                "Are you a Type 3? Because you just achieved the impossible \u2014 making me actually want to write a thoughtful first message.",
                "They say Threes are overachievers. Your profile is overachieving right now.",
                "You just set a new personal best on this app: most impressive profile I have ever seen.",
            ],
            "prefill_text": "Her bio mentions Enneagram Type 3 or achiever energy. Write a confident, impressive opener that matches her drive.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an Enneagram Type 3. Her profile is polished and ambitious. She seems driven, confident, and image-conscious.",
        },
        {
            "slug": "type-4",
            "keyword": "Enneagram Type 4",
            "h1": "The Best Enneagram Type 4 Pickup Lines (For the Individualist).",
            "title": "Best Enneagram Type 4 Pickup Lines | TryAgainText",
            "meta_description": "Use niche Enneagram Type 4 pickup lines that feel unique, emotional, and deeply personal. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Type 4s crave authenticity, depth, and emotional honesty. They can spot a generic message from a mile away. These lines are original, heartfelt, and uniquely hers.",
            "witty_lines": [
                "Your profile has an aesthetic that feels completely your own. In a sea of sameness, that stands out immediately.",
                "I can tell you are a Type 4 because your bio makes me feel something, which is rare for a dating app.",
                "You seem like someone who would rather be misunderstood than boring. I find that deeply compelling.",
            ],
            "flirty_lines": [
                "There is something hauntingly beautiful about your profile that made me stop scrolling and actually think.",
                "Your depth is showing and I am not going to pretend that is not extremely attractive.",
                "I like that your profile does not try to be like everyone else's. That kind of authenticity is magnetic.",
            ],
            "cheesy_lines": [
                "Are you a Type 4? Because your profile just made me feel feelings I did not know I had.",
                "They say Fours are one of a kind. Your profile is the proof.",
                "You just turned my mundane swiping session into an emotional experience. Very Type 4 of you.",
            ],
            "prefill_text": "Her bio mentions Enneagram Type 4 or individualist energy. Write an original, emotionally honest opener.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an Enneagram Type 4. Her profile has a unique aesthetic. She seems creative, emotionally deep, and fiercely individual.",
        },
        {
            "slug": "type-5",
            "keyword": "Enneagram Type 5",
            "h1": "The Best Enneagram Type 5 Pickup Lines (For the Investigator).",
            "title": "Best Enneagram Type 5 Pickup Lines | TryAgainText",
            "meta_description": "Use niche Enneagram Type 5 pickup lines that feel intelligent, curious, and respectful of boundaries. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Type 5s are observant, analytical, and value their space. They want someone who is interesting without being invasive. These lines engage her mind while respecting her boundaries.",
            "witty_lines": [
                "Your profile has the energy of someone with a private library and opinions about everything in it. I am intrigued.",
                "I can tell you are a Type 5 because your bio says just enough to be interesting and not a word more.",
                "You seem like someone who values quality over quantity in conversations. This is my attempt at quality.",
            ],
            "flirty_lines": [
                "Something about your quiet intelligence is genuinely magnetic. I wanted to reach out before I overthought it.",
                "Your profile has this cerebral appeal that makes me want to earn a real conversation with you.",
                "I like that your energy is reserved. It makes me think what you choose to share is actually worth hearing.",
            ],
            "cheesy_lines": [
                "Are you a Type 5? Because I have been analyzing your profile and the data says we should talk.",
                "They say Fives need to understand everything. I would love to be the next subject of your curiosity.",
                "Your profile has more depth per square inch than anything else on this app.",
            ],
            "prefill_text": "Her bio mentions Enneagram Type 5 or investigator energy. Write a smart, respectful opener that is curious without being pushy.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an Enneagram Type 5. Her profile is minimal but interesting. She seems analytical, curious, and private.",
        },
        {
            "slug": "type-6",
            "keyword": "Enneagram Type 6",
            "h1": "The Best Enneagram Type 6 Pickup Lines (For the Loyalist).",
            "title": "Best Enneagram Type 6 Pickup Lines | TryAgainText",
            "meta_description": "Use niche Enneagram Type 6 pickup lines that feel trustworthy, steady, and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Type 6s value trust, loyalty, and security. They are cautious but deeply committed once they feel safe. These lines build trust from the first message.",
            "witty_lines": [
                "Your profile has the energy of someone who thinks before she acts and still somehow looks spontaneous in every photo.",
                "I can tell you are a Type 6 because your bio feels considered, honest, and like it comes from someone you can trust.",
                "You seem like someone who values reliability. So here is a reliable fact: I genuinely liked your profile.",
            ],
            "flirty_lines": [
                "Something about your steady, grounded energy makes me want to show up as my most honest self.",
                "I like that your profile feels real. No filters, no performance. That is the most attractive thing I have seen today.",
                "Your warmth and genuineness come through clearly. I would love the chance to get to know that person.",
            ],
            "cheesy_lines": [
                "Are you a Type 6? Because I already feel like I can trust your taste in dating app matches.",
                "They say Sixes are the most loyal type. I am here to earn that loyalty one great conversation at a time.",
                "Your profile feels like a safe harbor in a sea of questionable profiles. I am docking my ship.",
            ],
            "prefill_text": "Her bio mentions Enneagram Type 6 or loyalist energy. Write a trustworthy, warm opener that feels safe and genuine.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an Enneagram Type 6. Her profile feels grounded and honest. She seems loyal, cautious, and warm once comfortable.",
        },
        {
            "slug": "type-7",
            "keyword": "Enneagram Type 7",
            "h1": "The Best Enneagram Type 7 Pickup Lines (For the Enthusiast).",
            "title": "Best Enneagram Type 7 Pickup Lines | TryAgainText",
            "meta_description": "Use niche Enneagram Type 7 pickup lines that feel adventurous, fun, and high-energy. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Type 7s live for excitement, variety, and positive experiences. Boring openers are an instant skip. These lines match her high-octane energy and promise a good time.",
            "witty_lines": [
                "Your profile has the energy of someone who has plans every weekend and backup plans for those plans.",
                "I can tell you are a Type 7 because your photos look like a trailer for the most fun life ever.",
                "You seem like someone who says 'yes' first and figures out the details later. Honestly, same.",
            ],
            "flirty_lines": [
                "Your adventurous energy is contagious. I am already thinking about all the things we could do together.",
                "I like that your profile feels like pure fun. A conversation with you seems like it would make my whole week.",
                "Something about your energy tells me you turn ordinary moments into extraordinary ones. I want in.",
            ],
            "cheesy_lines": [
                "Are you a Type 7? Because my FOMO just kicked in and it is all about missing a chance to talk to you.",
                "They say Sevens are always chasing the next adventure. I volunteer as your next great experience.",
                "Your profile is the most exciting thing on this app and it is not even close.",
            ],
            "prefill_text": "Her bio mentions Enneagram Type 7 or enthusiast energy. Write a fun, energetic opener that promises a good time.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an Enneagram Type 7. Her photos are full of adventures and fun. She seems spontaneous, optimistic, and endlessly energetic.",
        },
        {
            "slug": "type-8",
            "keyword": "Enneagram Type 8",
            "h1": "The Best Enneagram Type 8 Pickup Lines (For the Challenger).",
            "title": "Best Enneagram Type 8 Pickup Lines | TryAgainText",
            "meta_description": "Use niche Enneagram Type 8 pickup lines that feel bold, direct, and confident. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Type 8s are strong, protective, and respect directness above all. They see through flattery and want someone who can stand their ground. These lines bring that energy.",
            "witty_lines": [
                "Your profile has big energy and I am not going to pretend I am not a little intimidated. But here I am anyway.",
                "I can tell you are a Type 8 because your bio has the confidence of someone who does not need this app but chose to be here.",
                "You seem like someone who respects honesty over charm. So honestly: your profile is impressive and I want to talk.",
            ],
            "flirty_lines": [
                "Your strength and directness are genuinely attractive. I am not going to sugarcoat that.",
                "I like that your energy says you can handle anything. Including, hopefully, my best attempt at an opener.",
                "Something about your confidence makes me want to bring mine. This is me showing up fully.",
            ],
            "cheesy_lines": [
                "Are you a Type 8? Because you just challenged every weak opener I have ever considered sending.",
                "They say Eights are the toughest type. You just made swiping right the bravest thing I have done all week.",
                "Your profile has more authority than my entire LinkedIn. I am not intimidated. Okay, slightly.",
            ],
            "prefill_text": "Her bio mentions Enneagram Type 8 or challenger energy. Write a bold, direct opener that does not back down.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an Enneagram Type 8. Her profile is bold and assertive. She seems strong, protective, and direct.",
        },
        {
            "slug": "type-9",
            "keyword": "Enneagram Type 9",
            "h1": "The Best Enneagram Type 9 Pickup Lines (For the Peacemaker).",
            "title": "Best Enneagram Type 9 Pickup Lines | TryAgainText",
            "meta_description": "Use niche Enneagram Type 9 pickup lines that feel calm, genuine, and easygoing. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Type 9s value peace, harmony, and genuine connection. They do not want pressure or intensity from a first message. These lines are warm, relaxed, and feel like an easy yes.",
            "witty_lines": [
                "Your profile has the most calming energy on this entire app. I feel more relaxed just from reading your bio.",
                "I can tell you are a Type 9 because everything about your profile feels balanced, warm, and effortless.",
                "You seem like someone who makes even awkward first dates feel natural. That is a genuine superpower.",
            ],
            "flirty_lines": [
                "Something about your easygoing energy makes me think a conversation with you would feel like catching up with an old friend.",
                "Your warmth is understated but very real. I would love to experience that in person.",
                "I like that your profile feels calm and genuine. It makes me want to be the same way with you.",
            ],
            "cheesy_lines": [
                "Are you a Type 9? Because you just brought peace to my chaotic swiping experience.",
                "They say Nines create harmony wherever they go. You just harmonized my entire evening.",
                "Your profile is like a Sunday morning \u2014 calm, beautiful, and I never want it to end.",
            ],
            "prefill_text": "Her bio mentions Enneagram Type 9 or peacemaker energy. Write a calm, warm opener that feels low-pressure.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an Enneagram Type 9. Her profile has a calm, balanced feel. She seems easygoing, warm, and gentle.",
        },
    ],
}
