DATA = {
    "category_slug": "fandoms",
    "category_name": "TV & Movie Fandoms",
    "sort_order": 7,
    "topics": [
        {
            "slug": "the-office",
            "keyword": "The Office",
            "h1": "The Best The Office Pickup Lines (For When She Quotes Michael Scott in Her Bio).",
            "title": "Best The Office Pickup Lines | TryAgainText",
            "meta_description": "Use niche The Office pickup lines that feel witty, warm, and Dunder Mifflin-approved. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she quotes The Office in her bio, she values humor, warmth, and someone who gets the references. These lines hit that sweet spot between Jim-level charm and Michael-level confidence.",
            "witty_lines": [
                "Your profile is the Jim Halpert of this app — effortlessly charming while everyone else is trying way too hard.",
                "I was going to lead with a Michael Scott quote but honestly your profile deserves something original. So here I am, panicking.",
                "You seem like the kind of person who has a strong opinion about whether the show gets worse after Michael leaves. I need to hear it.",
            ],
            "flirty_lines": [
                "Your bio says you love The Office and that alone tells me you have good taste. Your photos confirm it.",
                "I am looking for someone who wants a love story like Jim and Pam but with better communication. Your profile makes me think you get that.",
                "You have this warm, funny energy that reminds me of the best parts of the show — effortless and genuine.",
            ],
            "cheesy_lines": [
                "Are you a Dunder Mifflin employee? Because I feel a workplace romance brewing and HR has not been notified.",
                "I would explain how much I like your profile but I am afraid I would turn into Michael Scott at the Dundies.",
                "If your love language is Office quotes, mine is matching that energy. That is what she said.",
            ],
            "prefill_text": "Her bio mentions The Office or quotes Michael Scott. Write a witty opener that shows you actually watch the show, not just quote it.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her actual bio, not just generic Office quotes.",
            "her_info_prefill": "She loves The Office. Her bio probably quotes it. She values humor and warmth in conversation.",
        },
        {
            "slug": "harry-potter",
            "keyword": "Harry Potter",
            "h1": "The Best Harry Potter Pickup Lines (For When She Still Checks Her Hogwarts House).",
            "title": "Best Harry Potter Pickup Lines | TryAgainText",
            "meta_description": "Use niche Harry Potter pickup lines that feel magical, clever, and house-specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she mentions Hogwarts, her house, or anything wizarding world, she wants someone who gets it — not someone who just says 'I am a Gryffindor too.' These lines show actual range.",
            "witty_lines": [
                "Your profile has the energy of someone who knows her Hogwarts house, her patronus, and exactly which professor she would befriend. I respect that depth.",
                "I was going to use a Harry Potter pickup line but your profile is too interesting for something that lazy. So instead: what is your most controversial HP take?",
                "You seem like the kind of person who has reread the series multiple times and notices new things every time. That attention to detail is attractive.",
            ],
            "flirty_lines": [
                "I do not need Amortentia to know I am interested. Your profile did that all on its own.",
                "Your energy is giving head girl vibes — smart, put together, and slightly intimidating in the best way.",
                "Something about your profile feels like finding a really good book. I do not want to put it down.",
            ],
            "cheesy_lines": [
                "Are you a Snitch? Because you are exactly what I have been looking for and you are worth 150 points.",
                "I must have used Felix Felicis today because finding your profile feels like pure liquid luck.",
                "Is your name Accio? Because you just pulled me in from across the entire app.",
            ],
            "prefill_text": "Her bio mentions Harry Potter, Hogwarts, or her house. Write a clever opener that goes beyond basic HP references.",
            "upload_hint": "Upload a screenshot of her profile so the opener ties into her specific house or HP references, not just generic magic jokes.",
            "her_info_prefill": "She loves Harry Potter. Probably knows her house and patronus. Values cleverness and depth in conversation.",
        },
        {
            "slug": "marvel",
            "keyword": "Marvel",
            "h1": "The Best Marvel Pickup Lines (For When She Actually Knows the MCU Timeline).",
            "title": "Best Marvel Pickup Lines | TryAgainText",
            "meta_description": "Use niche Marvel pickup lines that feel confident, witty, and MCU-literate. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she mentions Marvel in her bio, she is not looking for 'I am basically Tony Stark.' She wants someone who actually gets the universe and can be clever about it. These lines deliver.",
            "witty_lines": [
                "Your profile has the energy of someone who has a top five MCU ranking and will defend it aggressively. I am here for that debate.",
                "I can tell you actually watch the post-credits scenes. That patience and commitment? Very attractive qualities.",
                "You seem like the kind of person who has a strong opinion about which phase was the best and I need to hear it immediately.",
            ],
            "flirty_lines": [
                "I do not need a multiverse to know you are one of a kind. Your profile makes that pretty obvious.",
                "Your energy is giving main Avenger vibes — confident, interesting, and clearly the one everyone wants on their team.",
                "Something about your profile tells me you are the kind of person who makes everything more fun. I want to test that theory.",
            ],
            "cheesy_lines": [
                "Are you the Infinity Gauntlet? Because with one look at your profile, you snapped away my ability to think straight.",
                "I must be in the quantum realm because time stopped the second I saw your photos.",
                "Forget the multiverse of madness. Your profile is the multiverse of attractiveness.",
            ],
            "prefill_text": "Her bio mentions Marvel or the MCU. Write a confident opener that shows you actually know the universe, not just the memes.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific Marvel interests, not just generic superhero jokes.",
            "her_info_prefill": "She is into Marvel. Probably has opinions about the MCU timeline. Values wit and pop culture fluency.",
        },
        {
            "slug": "anime",
            "keyword": "Anime",
            "h1": "The Best Anime Pickup Lines (For When She Lists Her MAL in Her Bio).",
            "title": "Best Anime Pickup Lines | TryAgainText",
            "meta_description": "Use niche anime pickup lines that feel genuine, otaku-literate, and not cringe. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she mentions anime in her profile, she wants someone who actually watches it — not someone who only knows Naruto. These lines show range and genuine appreciation for the culture.",
            "witty_lines": [
                "Your profile has the energy of someone with a carefully curated anime list and strong opinions about sub vs dub. I need to know which side you are on.",
                "I can tell you are not a casual anime watcher. Your vibe says you have cried over at least three fictional characters and I respect that deeply.",
                "You seem like the kind of person who can explain an entire anime plot in sixty seconds and somehow make it sound like a TED talk.",
            ],
            "flirty_lines": [
                "Your profile has main character energy and not the oblivious shounen kind. More like the cool, confident type everyone roots for.",
                "I do not need a red string of fate to feel drawn to your profile. It happened on its own.",
                "Your energy is giving protagonist vibes — interesting, layered, and clearly the center of your own story.",
            ],
            "cheesy_lines": [
                "Are you an anime opening? Because I could watch you on repeat and never hit skip.",
                "I must have activated my Sharingan because I cannot stop analyzing every detail of your profile.",
                "If liking your profile was a jutsu, I would have no chakra left.",
            ],
            "prefill_text": "Her bio mentions anime or specific shows. Write a genuine opener that shows you appreciate the culture, not just the surface-level memes.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific anime taste, not just generic weeb humor.",
            "her_info_prefill": "She is into anime. Has taste beyond mainstream shows. Values genuine otaku energy over casual references.",
        },
        {
            "slug": "taylor-swift",
            "keyword": "Taylor Swift",
            "h1": "The Best Taylor Swift Pickup Lines (For When She Has an Era for Every Mood).",
            "title": "Best Taylor Swift Pickup Lines | TryAgainText",
            "meta_description": "Use niche Taylor Swift pickup lines that feel clever, era-specific, and genuinely Swiftie-approved. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Swiftie, she does not want lazy 'Shake It Off' references. She wants someone who understands eras, deep cuts, and the emotional range of the discography. These lines show that.",
            "witty_lines": [
                "Your profile has the emotional range of the entire Taylor Swift discography and I mean that as a serious compliment.",
                "I can tell by your photos which era you are currently in and honestly? It suits you perfectly.",
                "You seem like the kind of Swiftie who has a specific song for every life event. I want to know your funeral song pick.",
            ],
            "flirty_lines": [
                "Your profile is giving Lover era energy — warm, romantic, and making me want to be stupidly optimistic about dating apps.",
                "Something about your vibe tells me you appreciate a good love story. I would like to write one with you.",
                "You have this effortless, golden-hour energy in your photos and I could not scroll past it.",
            ],
            "cheesy_lines": [
                "Are you a Taylor Swift album? Because I keep coming back to your profile and discovering something new every time.",
                "I must be in my lover era because I just saw your profile and my heart did the thing.",
                "If you were a Taylor Swift song, you would be a bonus track — the kind people search for because you are worth the effort.",
            ],
            "prefill_text": "Her bio mentions Taylor Swift, a specific era, or Swiftie culture. Write a clever opener that shows real discography knowledge.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific era or Taylor Swift taste, not just surface-level hits.",
            "her_info_prefill": "She is a Swiftie. Probably identifies with a specific era. Values emotional depth and lyrical cleverness.",
        },
        {
            "slug": "star-wars",
            "keyword": "Star Wars",
            "h1": "The Best Star Wars Pickup Lines (For When She Knows the Difference Between Canon and Legends).",
            "title": "Best Star Wars Pickup Lines | TryAgainText",
            "meta_description": "Use niche Star Wars pickup lines that feel clever, galaxy-brained, and Force-sensitive. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she mentions Star Wars in her profile, she wants someone who gets it — not someone who just says 'May the Force be with you.' These lines show genuine fandom knowledge and charm.",
            "witty_lines": [
                "Your profile has the energy of someone who has strong opinions about the prequels and I desperately need to hear them.",
                "I can tell you are the kind of Star Wars fan who actually reads the expanded lore. That depth of commitment is genuinely attractive.",
                "Your photos give off main character energy — and in this galaxy, that means something.",
            ],
            "flirty_lines": [
                "I do not need the Force to sense there is something special about you. Your profile made that obvious.",
                "Your energy is giving rebel alliance — bold, principled, and fighting for something worth believing in.",
                "Something about your profile tells me you are the kind of person who makes even a galaxy far far away feel like home.",
            ],
            "cheesy_lines": [
                "Are you the Force? Because I feel a strong, undeniable pull toward you and I am not resisting it.",
                "I must be a Jedi because I sensed your profile from across the entire app.",
                "If love was a lightsaber, your profile just activated mine. I am aware of how that sounds.",
            ],
            "prefill_text": "Her bio mentions Star Wars, a specific character, or faction. Write a clever opener that shows real fandom depth.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific Star Wars interests, not just generic Force jokes.",
            "her_info_prefill": "She is a Star Wars fan. Probably has opinions about the prequels and sequels. Values fandom depth over surface-level quotes.",
        },
        {
            "slug": "lord-of-the-rings",
            "keyword": "Lord of the Rings",
            "h1": "The Best Lord of the Rings Pickup Lines (For When She Would Follow Aragorn Into Battle).",
            "title": "Best Lord of the Rings Pickup Lines | TryAgainText",
            "meta_description": "Use niche Lord of the Rings pickup lines that feel epic, genuine, and fellowship-worthy. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she mentions LOTR, she values depth, loyalty, and epic storytelling. She is not interested in surface-level small talk. These lines have the emotional weight of a Tolkien scene.",
            "witty_lines": [
                "Your profile has the energy of someone who has read the Silmarillion and can explain it without making people's eyes glaze over. Marry me.",
                "I can tell you are the kind of person who cried during the 'my friends, you bow to no one' scene. I respect that emotional range.",
                "Your vibe says you have strong opinions about extended editions vs theatrical cuts and I already know you are right.",
            ],
            "flirty_lines": [
                "Your profile feels like finding Rivendell after a long journey — beautiful, welcoming, and exactly what I needed.",
                "Something about your energy tells me you value loyalty above everything else. I would ride into battle with that quality.",
                "You carry yourself with this quiet, Aragorn-level confidence that is incredibly rare and incredibly attractive.",
            ],
            "cheesy_lines": [
                "Are you the One Ring? Because I have been searching the entire app for you and now I never want to let go.",
                "I must be Samwise because I am following you on this journey no matter where it goes.",
                "Your profile is my precious and I am not even ashamed to say it.",
            ],
            "prefill_text": "Her bio mentions Lord of the Rings, Tolkien, or Middle-earth. Write an epic opener with genuine emotional depth.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific LOTR interests, not just generic fellowship jokes.",
            "her_info_prefill": "She loves Lord of the Rings. Values depth, loyalty, and epic storytelling. Probably has a favorite character she will defend fiercely.",
        },
        {
            "slug": "studio-ghibli",
            "keyword": "Studio Ghibli",
            "h1": "The Best Studio Ghibli Pickup Lines (For When She Has a Totoro Phone Case and a Gentle Soul).",
            "title": "Best Studio Ghibli Pickup Lines | TryAgainText",
            "meta_description": "Use niche Studio Ghibli pickup lines that feel gentle, whimsical, and deeply genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she loves Ghibli films, she values gentleness, beauty in small moments, and emotional depth without cynicism. These lines have that warm, whimsical quality that matches her soul.",
            "witty_lines": [
                "Your profile has Ghibli energy — beautiful, gentle, and making me believe the world is actually a magical place.",
                "I can tell you are the kind of person who notices the small, beautiful things most people walk right past. That awareness is rare.",
                "Your photos have this warm, lived-in quality that feels like a Miyazaki background painting come to life.",
            ],
            "flirty_lines": [
                "Your energy is like a quiet Ghibli scene — no dialogue needed, just pure, beautiful feeling. I am completely drawn in.",
                "Something about your profile tells me you believe in kindness as a strength, not a weakness. That is genuinely attractive.",
                "You have this whimsical, gentle quality that makes me want to slow down and pay more attention to beautiful things. Starting with you.",
            ],
            "cheesy_lines": [
                "Are you a Ghibli film? Because you are beautiful, comforting, and I want to experience you again and again.",
                "I must be Totoro because I was just standing here and then the most magical person on this app appeared.",
                "If your profile was a Ghibli soundtrack, it would be the kind that makes people cry on public transport.",
            ],
            "prefill_text": "Her bio mentions Studio Ghibli, Miyazaki, or specific films. Write a gentle, whimsical opener that matches her soul.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific Ghibli favorites, not just generic anime compliments.",
            "her_info_prefill": "She loves Studio Ghibli. Has a gentle, whimsical soul. Values beauty in small moments and emotional depth.",
        },
        {
            "slug": "stranger-things",
            "keyword": "Stranger Things",
            "h1": "The Best Stranger Things Pickup Lines (For When She Would Survive the Upside Down).",
            "title": "Best Stranger Things Pickup Lines | TryAgainText",
            "meta_description": "Use niche Stranger Things pickup lines that feel nostalgic, brave, and party-worthy. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into Stranger Things, she values loyalty, bravery, and that nostalgic 80s energy. She wants someone who would face the Demogorgon, not run from it. These lines match.",
            "witty_lines": [
                "Your profile has the energy of someone who would absolutely survive the Upside Down and still have time for a witty comeback.",
                "I can tell you are the kind of person who would be in the party, not the townsperson who ignores all the weird stuff happening.",
                "Your vibe says you appreciate nostalgia but you are not stuck in it. That balance is genuinely attractive.",
            ],
            "flirty_lines": [
                "Your energy is giving Eleven vibes — powerful, layered, and way more interesting than anyone expects at first glance.",
                "Something about your profile tells me you value real friendships and bravery over surface-level connections. I am here for that depth.",
                "You have this magnetic, courageous energy that makes me want to be on your team for whatever comes next.",
            ],
            "cheesy_lines": [
                "Are you the Upside Down? Because everything flipped the moment I saw your profile.",
                "I must have rolled a natural 20 because finding your profile feels like a critical hit.",
                "Your profile just opened a gate to another dimension and I am walking straight through it.",
            ],
            "prefill_text": "Her bio mentions Stranger Things or 80s nostalgia. Write a brave, nostalgic opener that shows you actually watch the show.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific Stranger Things interests, not just generic 80s lines.",
            "her_info_prefill": "She loves Stranger Things. Values loyalty, bravery, and nostalgia. Probably has a favorite character and season.",
        },
        {
            "slug": "game-of-thrones",
            "keyword": "Game of Thrones",
            "h1": "The Best Game of Thrones Pickup Lines (For When She Still Has Strong Feelings About Season 8).",
            "title": "Best Game of Thrones Pickup Lines | TryAgainText",
            "meta_description": "Use niche Game of Thrones pickup lines that feel clever, bold, and Westeros-literate. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she mentions Game of Thrones, she values complex storytelling, power dynamics, and probably still has very strong feelings about the ending. These lines match that passionate, opinionated energy.",
            "witty_lines": [
                "Your profile has the energy of someone who could sit on the Iron Throne and actually do a decent job of ruling. That is rare.",
                "I can tell you have opinions about the final season and I am prepared to agree with all of them to win your favor.",
                "Your vibe says you are strategic, observant, and would absolutely survive King's Landing. I need that energy in my life.",
            ],
            "flirty_lines": [
                "Your profile has the intrigue of a Westeros plotline — layered, compelling, and I cannot stop paying attention.",
                "Something about your energy tells me you appreciate boldness. So here I am, making my move before the Red Wedding of my confidence kicks in.",
                "You carry yourself like someone who knows the game and plays it well. That strategic confidence is very attractive.",
            ],
            "cheesy_lines": [
                "Are you the Iron Throne? Because I would cross seven kingdoms just for a chance to sit beside you.",
                "I must know nothing because I cannot figure out how someone this impressive is still on this app.",
                "Winter is coming but your profile just made everything feel a lot warmer.",
            ],
            "prefill_text": "Her bio mentions Game of Thrones, a specific house, or character. Write a clever opener that shows real Westeros knowledge.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific GoT interests, not just generic throne jokes.",
            "her_info_prefill": "She loves Game of Thrones. Has strong opinions about characters and the ending. Values clever, bold conversation.",
        },
        {
            "slug": "breaking-bad",
            "keyword": "Breaking Bad",
            "h1": "The Best Breaking Bad Pickup Lines (For When She Appreciates Moral Complexity and Great Writing).",
            "title": "Best Breaking Bad Pickup Lines | TryAgainText",
            "meta_description": "Use niche Breaking Bad pickup lines that feel sharp, witty, and chemistry-approved. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she mentions Breaking Bad, she appreciates great writing, moral complexity, and people who are smarter than they look. These lines match that sharp, no-filler energy.",
            "witty_lines": [
                "Your profile has the writing quality of a Breaking Bad episode — tight, no filler, and making me want to know what happens next.",
                "I can tell you are the kind of person who appreciates good storytelling over cheap thrills. Your profile proves it.",
                "Your vibe says you have strong opinions about Walter White's arc and I need to hear every single one of them.",
            ],
            "flirty_lines": [
                "The chemistry between your profile and my interest is undeniable. And yes I am aware of that pun.",
                "Something about your sharp, no-nonsense energy tells me you appreciate people who are direct. So here I am.",
                "You carry yourself with this intelligent confidence that tells me our conversation would actually go somewhere interesting.",
            ],
            "cheesy_lines": [
                "Are you a Breaking Bad episode? Because once I started looking at your profile, I could not stop.",
                "I am the one who swipes right. And your profile is the reason.",
                "Your profile is 99.1 percent pure and I am saying that with full Heisenberg respect.",
            ],
            "prefill_text": "Her bio mentions Breaking Bad or Better Call Saul. Write a sharp, clever opener that matches her taste for quality storytelling.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific tastes, not just generic BB quotes.",
            "her_info_prefill": "She loves Breaking Bad. Appreciates moral complexity, great writing, and sharp humor. Probably watched Better Call Saul too.",
        },
        {
            "slug": "friends",
            "keyword": "Friends",
            "h1": "The Best Friends Pickup Lines (For When She Is Still on Her Third Rewatch).",
            "title": "Best Friends Pickup Lines | TryAgainText",
            "meta_description": "Use niche Friends pickup lines that feel cozy, funny, and Central Perk-approved. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she loves Friends, she values humor, comfort, and the idea that your people are everything. She wants someone who gets the references but also brings genuine warmth. These lines deliver.",
            "witty_lines": [
                "Your profile has the rewatchability of Friends — every time I look at it I notice something new and charming.",
                "I can tell you have a strong opinion about whether Ross and Rachel were on a break and I already know yours is correct.",
                "Your vibe says you are the friend everyone goes to for advice and also the funniest one in the group. Dual threat.",
            ],
            "flirty_lines": [
                "Your energy is warm, funny, and comforting in the best way. Like the show but with better hair. Sorry Rachel.",
                "Something about your profile tells me spending time with you would feel easy, natural, and full of laughter. I want that.",
                "You have this genuine, approachable energy that makes me think a first date with you would feel like we have known each other for years.",
            ],
            "cheesy_lines": [
                "Are you an episode of Friends? Because I could replay this moment and never get tired of it.",
                "I must be at Central Perk because I just saw someone I want to share a couch with for a very long time.",
                "Your profile is the lobster. You know exactly what I mean.",
            ],
            "prefill_text": "Her bio mentions Friends or quotes the show. Write a warm, funny opener that matches her cozy, humorous vibe.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific Friends preferences, not just generic quotes.",
            "her_info_prefill": "She loves Friends. Values humor, warmth, and close friendships. Probably on her third rewatch and has a favorite character.",
        },
        {
            "slug": "disney",
            "keyword": "Disney",
            "h1": "The Best Disney Pickup Lines (For When She Still Believes in Magic and Is Not Sorry About It).",
            "title": "Best Disney Pickup Lines | TryAgainText",
            "meta_description": "Use niche Disney pickup lines that feel magical, warm, and genuinely charming. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she loves Disney, she values magic, optimism, and unapologetic joy. She is not naive — she just chooses to believe in good things. These lines match that enchanted energy.",
            "witty_lines": [
                "Your profile has Disney main character energy — optimistic, charming, and clearly destined for a great story.",
                "I can tell you are the kind of person who tears up during the opening of Up and is not embarrassed about it. That emotional honesty is beautiful.",
                "Your photos give off this warm, magical vibe that makes me think you still believe the world is a wonderful place. I find that incredibly refreshing.",
            ],
            "flirty_lines": [
                "Your smile has the kind of magic that Disney tries to animate but can never quite capture. It is better in person, I am sure.",
                "Something about your joyful energy tells me you would make even a regular Tuesday feel like an adventure. I want that.",
                "You have this enchanting quality that is rare and genuine and I could not scroll past it without saying something.",
            ],
            "cheesy_lines": [
                "Are you a Disney movie? Because my heart just started singing and there is nothing I can do about it.",
                "I must be under a spell because I have looked at your profile twelve times and I still cannot stop.",
                "Your profile is the happily ever after I did not know I was looking for.",
            ],
            "prefill_text": "Her bio mentions Disney, specific films, or theme parks. Write a magical, warm opener that matches her joyful energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific Disney favorites, not just generic princess jokes.",
            "her_info_prefill": "She loves Disney. Values magic, optimism, and joy. Probably has a favorite film she defends passionately.",
        },
        {
            "slug": "true-crime",
            "keyword": "True Crime",
            "h1": "The Best True Crime Pickup Lines (For When She Has a Podcast Queue Full of Murder Mysteries).",
            "title": "Best True Crime Pickup Lines | TryAgainText",
            "meta_description": "Use niche true crime pickup lines that feel witty, dark-humored, and investigation-worthy. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into true crime, she is observant, curious, and probably already running a background check on you. These lines lean into that investigative energy with the right amount of dark humor.",
            "witty_lines": [
                "Your profile has true crime energy — you have probably already Googled me and honestly I respect the due diligence.",
                "I can tell you are the kind of person who notices details most people miss. That observational skill is genuinely intimidating and attractive.",
                "Your vibe says you listen to true crime podcasts to fall asleep and somehow that makes you more interesting, not less.",
            ],
            "flirty_lines": [
                "Your curiosity is magnetic. I can tell you are someone who asks the questions other people are afraid to ask.",
                "Something about your sharp, investigative energy tells me you would see through any generic opener immediately. So here is my honest attempt.",
                "You seem like the kind of person who reads people incredibly well. I would love to know what you read from my profile.",
            ],
            "cheesy_lines": [
                "Are you a true crime podcast? Because I started looking at your profile and now I am completely hooked.",
                "I must be a cold case because you just cracked me wide open with one look.",
                "Your profile is the mystery I actually want to solve and I am fully committed to the investigation.",
            ],
            "prefill_text": "Her bio mentions true crime, podcasts, or documentaries. Write a witty opener with just the right amount of dark humor.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific true crime interests, not just generic murder jokes.",
            "her_info_prefill": "She is into true crime. Sharp, observant, curious. Probably has a favorite podcast and has already researched you.",
        },
        {
            "slug": "k-drama",
            "keyword": "K-Drama",
            "h1": "The Best K-Drama Pickup Lines (For When She Has a Watchlist Longer Than Most People's Attention Span).",
            "title": "Best K-Drama Pickup Lines | TryAgainText",
            "meta_description": "Use niche K-Drama pickup lines that feel romantic, dramatic, and second-lead-syndrome approved. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she watches K-Dramas, she values romance, emotional depth, and the kind of grand gestures that make real life feel underwhelming. These lines bring that drama-level charm to your opener.",
            "witty_lines": [
                "Your profile has K-Drama energy — emotionally rich, beautifully composed, and making me feel things I was not prepared for.",
                "I can tell you have experienced second lead syndrome and carried that emotional scar with grace. I respect your journey.",
                "Your vibe says you have a watchlist longer than your to-do list and honestly, priorities.",
            ],
            "flirty_lines": [
                "Your energy is giving main lead vibes — the kind of person the entire story revolves around and everyone roots for.",
                "Something about your profile tells me you appreciate a good slow burn. I am willing to earn every episode.",
                "You have this romantic, deeply genuine quality that feels like the best K-Drama love interest brought to life.",
            ],
            "cheesy_lines": [
                "Are you a K-Drama? Because I just started looking at your profile and I already know I am going to binge all sixteen episodes.",
                "I must have accidentally walked into a K-Drama because the moment I saw you, the OST started playing.",
                "Your profile is the plot twist I did not see coming and now I cannot focus on anything else.",
            ],
            "prefill_text": "Her bio mentions K-Dramas or specific shows. Write a romantic, drama-worthy opener that matches her taste for emotional depth.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific K-Drama taste, not just generic romance lines.",
            "her_info_prefill": "She loves K-Dramas. Values romance, emotional depth, and grand gestures. Has a watchlist and probably strong opinions about second leads.",
        },
        {
            "slug": "the-witcher",
            "keyword": "The Witcher",
            "h1": "The Best The Witcher Pickup Lines (For When She Tosses a Coin to Her Favorite Monster Hunter).",
            "title": "Best The Witcher Pickup Lines | TryAgainText",
            "meta_description": "Use niche Witcher pickup lines that feel rugged, clever, and Continent-worthy. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into The Witcher, she appreciates dark fantasy, moral gray areas, and someone who is tougher than they look. These lines have that rugged, monster-hunting charm.",
            "witty_lines": [
                "Your profile has Witcher energy — dark, layered, and clearly hiding something interesting beneath the surface.",
                "I can tell you are the kind of person who roots for the morally complex anti-hero. That taste in characters says a lot about your depth.",
                "Your vibe says you have read the books, watched the show, and played the games. That level of commitment deserves recognition.",
            ],
            "flirty_lines": [
                "Something about your energy tells me you appreciate people who are rough around the edges but genuine underneath. I am applying.",
                "Your profile has this dark, magnetic quality that I could not scroll past. Consider me interested.",
                "You seem like the kind of person who values loyalty over charm. I can offer both, but loyalty first.",
            ],
            "cheesy_lines": [
                "Are you a djinn wish? Because meeting you feels like destiny and I am not questioning it.",
                "Toss a coin to your Witcher because I am about to go on a quest to win your attention.",
                "Your profile just cast Axii on me because I am completely under your spell.",
            ],
            "prefill_text": "Her bio mentions The Witcher, Geralt, or dark fantasy. Write a rugged, clever opener with genuine depth.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific Witcher interests, not just generic fantasy lines.",
            "her_info_prefill": "She loves The Witcher. Appreciates dark fantasy, moral complexity, and rugged charm. Probably has opinions about the adaptation.",
        },
        {
            "slug": "succession",
            "keyword": "Succession",
            "h1": "The Best Succession Pickup Lines (For When She Understands Power Dynamics and Excellent Writing).",
            "title": "Best Succession Pickup Lines | TryAgainText",
            "meta_description": "Use niche Succession pickup lines that feel sharp, satirical, and prestige-TV literate. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she watches Succession, she values sharp writing, dark humor, and understanding power dynamics. She is not interested in basic openers — she wants someone who matches her taste for intelligent TV.",
            "witty_lines": [
                "Your profile has Succession energy — sharp, layered, and making me feel like I need to bring my A-game or get eaten alive.",
                "I can tell you appreciate dark humor and excellent writing. Your bio reads like a prestige TV pilot and I am already subscribed.",
                "Your vibe says you understand power dynamics better than most people understand basic conversation. That is intimidating and attractive.",
            ],
            "flirty_lines": [
                "Your intelligence comes through your profile like a Succession monologue — precise, devastating, and impossible to look away from.",
                "Something about your sharp energy tells me you do not tolerate mediocrity. I am here to prove I am above the bar.",
                "You carry yourself with this confident, strategic energy that tells me you know exactly what you want. Very attractive quality.",
            ],
            "cheesy_lines": [
                "Are you a Succession episode? Because I started looking at your profile and now I need to see every season.",
                "I must be a Roy sibling because I am desperately trying to win your approval and it is not going well.",
                "Your profile has CEO energy and I am here for the hostile takeover of my attention.",
            ],
            "prefill_text": "Her bio mentions Succession or prestige TV. Write a sharp, witty opener that matches her taste for intelligent entertainment.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific TV taste, not just generic rich-people jokes.",
            "her_info_prefill": "She loves Succession. Values sharp writing, dark humor, and power dynamics. Probably the smartest person in most rooms.",
        },
        {
            "slug": "bridgerton",
            "keyword": "Bridgerton",
            "h1": "The Best Bridgerton Pickup Lines (For When She Wants Regency Romance With Modern Energy).",
            "title": "Best Bridgerton Pickup Lines | TryAgainText",
            "meta_description": "Use niche Bridgerton pickup lines that feel romantic, witty, and Lady Whistledown-approved. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into Bridgerton, she values romance, wit, and the idea that love should be dramatic and intentional. She wants someone who courts, not just texts. These lines deliver that energy.",
            "witty_lines": [
                "Your profile has the intrigue of a Bridgerton season premiere — everyone is talking about it and for good reason.",
                "I can tell you are the kind of person who believes romance should be intentional, not accidental. I agree completely.",
                "Your vibe says Lady Whistledown would write about you favorably and that is the highest compliment I can offer.",
            ],
            "flirty_lines": [
                "Your profile has this romantic, elegant energy that makes me want to actually court you properly, not just send a lazy text.",
                "Something about your energy tells me you deserve the grand gesture, not the low-effort opener. So I am putting in the work.",
                "You carry yourself with this graceful confidence that feels timeless. I noticed it immediately.",
            ],
            "cheesy_lines": [
                "Are you a Bridgerton ball? Because the moment I saw your profile, the entire room disappeared.",
                "I must be the diamond of the season because you just made me the center of attention in my own heart.",
                "Your profile just burned brighter than a Lady Whistledown scandal and I am completely here for it.",
            ],
            "prefill_text": "Her bio mentions Bridgerton or Regency romance. Write a charming, intentional opener that feels like proper courting.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific romantic energy, not just generic period-drama lines.",
            "her_info_prefill": "She loves Bridgerton. Values romance, wit, and intentional courtship. Wants someone who puts in real effort.",
        },
        {
            "slug": "rick-and-morty",
            "keyword": "Rick and Morty",
            "h1": "The Best Rick and Morty Pickup Lines (For When She Has a High IQ and Dark Humor).",
            "title": "Best Rick and Morty Pickup Lines | TryAgainText",
            "meta_description": "Use niche Rick and Morty pickup lines that feel smart, absurd, and multiverse-aware. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she watches Rick and Morty, she values intelligence, dark humor, and existential absurdity. She does not want a basic opener — she wants something that matches her weird, brilliant energy.",
            "witty_lines": [
                "Your profile has the energy of someone who laughs at existential dread and somehow makes that a personality trait. I am very into it.",
                "I can tell you are the kind of person who appreciates when humor gets dark and weird. Consider this my application to match that frequency.",
                "Your vibe says you have thought about the multiverse theory at 2 AM and found it both terrifying and hilarious. Same.",
            ],
            "flirty_lines": [
                "In infinite timelines, I would swipe right on you in every single one. The math checks out.",
                "Something about your smart, absurd energy tells me our conversation would be the best kind of chaotic. I want in.",
                "You have this brilliant, unapologetically weird quality that most people try to hide. You wear it perfectly.",
            ],
            "cheesy_lines": [
                "Are you a portal gun? Because you just transported me to a dimension where I am actually smooth.",
                "Wubba lubba dub dub but actually the opposite because finding your profile made me genuinely happy.",
                "I have searched the multiverse and your profile is the one constant that is impressive in every timeline.",
            ],
            "prefill_text": "Her bio mentions Rick and Morty or shows she has dark, absurd humor. Write a smart, weird opener that matches her energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific humor, not just generic multiverse jokes.",
            "her_info_prefill": "She watches Rick and Morty. Values intelligence, dark humor, and absurdity. Probably overthinks everything in the best way.",
        },
        {
            "slug": "batman",
            "keyword": "Batman",
            "h1": "The Best Batman Pickup Lines (For When She Appreciates the Dark Knight Over Every Other Hero).",
            "title": "Best Batman Pickup Lines | TryAgainText",
            "meta_description": "Use niche Batman pickup lines that feel dark, confident, and Gotham-worthy. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she prefers Batman over every other superhero, she values depth, complexity, and the idea that you do not need superpowers to be extraordinary. These lines match that dark, sophisticated energy.",
            "witty_lines": [
                "Your profile has Batman energy — mysterious, layered, and clearly the most interesting person in Gotham. I mean this app.",
                "I can tell you are the kind of person who prefers a complex anti-hero over a perfect protagonist. That taste says everything.",
                "Your vibe says you appreciate darkness with depth, not darkness for show. That distinction matters and you clearly get it.",
            ],
            "flirty_lines": [
                "Your profile has this dark, magnetic quality that drew me in. Like Gotham at night — dangerous but beautiful.",
                "Something about your confident, mysterious energy tells me there is way more to discover. I am genuinely intrigued.",
                "You carry yourself with this quiet intensity that most people cannot pull off. On you, it is effortless.",
            ],
            "cheesy_lines": [
                "Are you Gotham City? Because you are dark, beautiful, and I want to protect you at all costs.",
                "I am not the hero this app deserves, but I am the one your profile needs right now.",
                "Your profile just activated the Bat-Signal in my heart and I am responding immediately.",
            ],
            "prefill_text": "Her bio mentions Batman, DC Comics, or dark heroes. Write a confident, layered opener that matches her taste for depth.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific Batman interests, not just generic superhero lines.",
            "her_info_prefill": "She loves Batman. Values complexity, depth, and sophistication. Prefers dark heroes over perfect ones.",
        },
        {
            "slug": "one-piece",
            "keyword": "One Piece",
            "h1": "The Best One Piece Pickup Lines (For When She Has Sailed the Grand Line and Has No Regrets).",
            "title": "Best One Piece Pickup Lines | TryAgainText",
            "meta_description": "Use niche One Piece pickup lines that feel adventurous, loyal, and nakama-approved. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into One Piece, she values loyalty, adventure, and the kind of bonds that survive anything. She wants someone who understands that nakama is everything. These lines match.",
            "witty_lines": [
                "Your profile has Straw Hat energy — adventurous, fiercely loyal, and clearly on a journey to become the best version of yourself.",
                "I can tell you are the kind of person who has watched over a thousand episodes of something and considers that an achievement, not a problem. Respect.",
                "Your vibe says you value loyalty above everything else and would go to war for your friends. That energy is unmatched.",
            ],
            "flirty_lines": [
                "Your adventurous spirit comes through every photo and it makes me want to join your crew immediately.",
                "Something about your profile tells me you are the kind of person who chases dreams without apology. That fearlessness is magnetic.",
                "You have this warm, ride-or-die energy that tells me you are worth every second of getting to know.",
            ],
            "cheesy_lines": [
                "Are you the One Piece? Because I have been on a long journey and I think I just found the treasure.",
                "I must have Observation Haki because I sensed your incredible energy from across the entire app.",
                "Your profile just gave me the will of D — the D stands for definitely interested.",
            ],
            "prefill_text": "Her bio mentions One Piece, specific characters, or nakama values. Write an adventurous opener that shows genuine fandom knowledge.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific One Piece interests, not just generic anime lines.",
            "her_info_prefill": "She loves One Piece. Values loyalty, adventure, and deep bonds. Probably has a favorite Straw Hat and will defend them.",
        },
        {
            "slug": "the-sims",
            "keyword": "The Sims",
            "h1": "The Best The Sims Pickup Lines (For When She Has Built Better Lives in a Simulation Than Most People Have in Reality).",
            "title": "Best The Sims Pickup Lines | TryAgainText",
            "meta_description": "Use niche The Sims pickup lines that feel creative, funny, and surprisingly deep. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she plays The Sims, she is creative, has a dark sense of humor, and has probably committed more virtual crimes than she will admit. These lines match that chaotic, creative energy.",
            "witty_lines": [
                "Your profile has Sims player energy — creative, slightly chaotic, and definitely hiding some dark secrets about pool ladders.",
                "I can tell you are the kind of person who spends four hours building a house and ten minutes actually playing the game. That dedication to aesthetics is beautiful.",
                "Your vibe says you have given your Sims better lives than most real people and honestly that is a compliment to your design skills.",
            ],
            "flirty_lines": [
                "Your creative energy comes through your profile and it tells me your imagination is one of the most interesting things about you.",
                "Something about your playful, chaotic energy makes me think spending time with you would be the most entertaining thing possible.",
                "You seem like the kind of person who builds entire worlds for fun. That creative mind is incredibly attractive.",
            ],
            "cheesy_lines": [
                "Are you a Sims character? Because I just saw a green diamond above your profile and I am clicking.",
                "I must have high relationship points because I feel an immediate connection with your profile.",
                "Your profile just gave me the Dazed moodlet because I genuinely cannot think straight after seeing it.",
            ],
            "prefill_text": "Her bio mentions The Sims or she gives off creative, chaotic energy. Write a funny, playful opener that matches.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her actual interests, not just generic gaming lines.",
            "her_info_prefill": "She plays The Sims. Creative, funny, probably has a dark sense of humor about virtual life. Values imagination.",
        },
        {
            "slug": "pokemon",
            "keyword": "Pokemon",
            "h1": "The Best Pokemon Pickup Lines (For When She Still Knows Her Starter and Is Proud of It).",
            "title": "Best Pokemon Pickup Lines | TryAgainText",
            "meta_description": "Use niche Pokemon pickup lines that feel nostalgic, clever, and trainer-certified. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into Pokemon, she has nostalgia for the classics but probably still keeps up with new generations. She wants someone who gets the references without being cringe about it. These lines deliver.",
            "witty_lines": [
                "Your profile has Champion energy — confident, well-rounded, and clearly the one everyone is trying to beat.",
                "I can tell you still remember your first starter and would defend that choice to the death. I need to know which one.",
                "Your vibe says you have opinions about which generation was the best and they are probably correct.",
            ],
            "flirty_lines": [
                "Your profile is the rarest encounter on this app and I am not letting it run away.",
                "Something about your nostalgic, playful energy tells me you know how to have fun without taking yourself too seriously. Very attractive.",
                "You have this warm, adventure-ready quality that makes me think exploring the world with you would be the best journey.",
            ],
            "cheesy_lines": [
                "Are you a legendary Pokemon? Because you are one of a kind and I just used my Master Ball.",
                "I must have used Sweet Scent because the best person on this app just appeared.",
                "Your profile is super effective against my ability to keep scrolling.",
            ],
            "prefill_text": "Her bio mentions Pokemon, a specific starter, or generation. Write a nostalgic, clever opener that shows real trainer knowledge.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific Pokemon taste, not just generic Pikachu jokes.",
            "her_info_prefill": "She loves Pokemon. Nostalgic but still engaged. Probably knows her starter, type, and favorite generation.",
        },
        {
            "slug": "twilight",
            "keyword": "Twilight",
            "h1": "The Best Twilight Pickup Lines (For When She Is Team Edward, Team Jacob, or Secretly Team Carlisle).",
            "title": "Best Twilight Pickup Lines | TryAgainText",
            "meta_description": "Use niche Twilight pickup lines that feel dramatic, romantic, and unapologetically nostalgic. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she still references Twilight, she is unashamed of her romantic side and values intensity in love. She is not looking for lukewarm — she wants someone who matches her passionate energy.",
            "witty_lines": [
                "Your profile has the emotional intensity of a Twilight novel and I mean that as the highest compliment available.",
                "I can tell you have a team and you will defend it until your last breath. That loyalty is genuinely attractive.",
                "Your vibe says you are unapologetically romantic and have zero patience for people who make fun of that. Good. Neither do I.",
            ],
            "flirty_lines": [
                "Your profile has this dramatic, magnetic quality that makes me want to stare at you for the entire lunch period and then pretend I was not.",
                "Something about your romantic energy tells me you believe love should be intense, not casual. I completely agree.",
                "You carry yourself with this passionate confidence that tells me you feel things deeply and that is one of the most attractive qualities a person can have.",
            ],
            "cheesy_lines": [
                "Are you Bella Swan? Because you just walked into this app and every head turned, including mine.",
                "I have been alive for over a hundred years and your profile is the first thing that has made me feel alive. Wait, I am not actually a vampire.",
                "And so the lion fell in love with the lamb. The lamb being your incredibly compelling profile.",
            ],
            "prefill_text": "Her bio mentions Twilight, her team, or vampire romance. Write a dramatic, romantic opener that matches her passionate energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific Twilight interests, not just generic vampire lines.",
            "her_info_prefill": "She loves Twilight. Unapologetically romantic. Has a team and strong feelings about the saga. Values intensity in love.",
        },
        {
            "slug": "doctor-who",
            "keyword": "Doctor Who",
            "h1": "The Best Doctor Who Pickup Lines (For When She Has Traveled Through Time and Still Chose This App).",
            "title": "Best Doctor Who Pickup Lines | TryAgainText",
            "meta_description": "Use niche Doctor Who pickup lines that feel clever, timeless, and companion-worthy. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Whovian, she values intelligence, adventure, and the idea that the best people are a little bit odd. She wants someone who is curious about everything and afraid of nothing. These lines match.",
            "witty_lines": [
                "Your profile has the energy of someone who has a favorite Doctor and will explain why they are objectively correct for forty-five minutes. I want to hear it.",
                "I can tell you are the kind of person who values curiosity and kindness above everything else. Very companion-worthy qualities.",
                "Your vibe says you are bigger on the inside — way more depth and personality than anyone expects from a first look.",
            ],
            "flirty_lines": [
                "Your profile is like the TARDIS — every time I look, I discover there is more to explore. And it is all fascinating.",
                "Something about your curious, adventurous energy tells me you see the universe as full of wonder. I want to see it through your eyes.",
                "You carry yourself with this brilliant, slightly eccentric confidence that is incredibly rare and completely magnetic.",
            ],
            "cheesy_lines": [
                "Are you a Time Lord? Because you just made my heart beat in double time.",
                "I must have a sonic screwdriver because your profile just unlocked something in me.",
                "Your profile is timeless. And I do not say that to every dimension-traveling stranger I meet.",
            ],
            "prefill_text": "Her bio mentions Doctor Who, a specific Doctor, or Whovian culture. Write a clever, adventurous opener with genuine fandom knowledge.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific Doctor Who interests, not just generic time travel jokes.",
            "her_info_prefill": "She is a Whovian. Values curiosity, adventure, and kindness. Has a favorite Doctor and strong opinions about the show.",
        },
    ],
}
