DATA = {
    "category_slug": "hobbies",
    "category_name": "Hobbies & Interests",
    "sort_order": 4,
    "topics": [
        {
            "slug": "rock-climbing",
            "keyword": "Rock Climbing",
            "h1": "The Best Rock Climbing Pickup Lines (For Adventurous Souls).",
            "title": "Best Rock Climbing Pickup Lines | TryAgainText",
            "meta_description": "Use niche rock climbing pickup lines that feel bold and adventurous. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Rock climbers thrive on challenge, trust, and pushing limits. They respect someone who shows up with grit and a sense of adventure.",
            "witty_lines": [
                "Your profile has the energy of someone who trusts the process, even when the next hold looks impossible. I respect that.",
                "I can tell you are a climber because your bio is minimal, intentional, and makes me want to reach higher.",
                "You seem like someone who is not afraid of a challenge. Consider this my attempt to send a route I have never tried before.",
            ],
            "flirty_lines": [
                "Something about the way you carry yourself tells me you know how to commit to a wall and a conversation. I find that really attractive.",
                "Your adventurous energy is magnetic. I would love to be your next belay partner in life.",
                "I like that your profile feels fearless. It makes me want to take a risk and say something real.",
            ],
            "cheesy_lines": [
                "Are you a rock climber? Because you just raised the bar on every profile I have seen.",
                "They say climbing is about trust. I trust that swiping right on you was the best move I have made all week.",
                "Your profile is the summit I have been working toward this entire time on this app.",
            ],
            "prefill_text": "Her bio mentions rock climbing or bouldering. Write a bold, adventurous opener that matches her energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She is into rock climbing. Her profile feels adventurous and fearless. She seems athletic, determined, and loves a challenge.",
        },
        {
            "slug": "yoga",
            "keyword": "Yoga",
            "h1": "The Best Yoga Pickup Lines (For the Mindful and Centered).",
            "title": "Best Yoga Pickup Lines | TryAgainText",
            "meta_description": "Use niche yoga pickup lines that feel grounded and mindful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Yoga lovers value presence, balance, and intentional living. They appreciate someone who brings calm energy and genuine curiosity.",
            "witty_lines": [
                "Your profile has the energy of someone who actually breathes before reacting. That is rare and genuinely attractive.",
                "I can tell you practice yoga because your bio feels balanced, grounded, and effortlessly put together.",
                "You seem like someone who is flexible in all the right ways \u2014 including how she sees the world.",
            ],
            "flirty_lines": [
                "Something about your calm, centered energy makes me want to slow down and actually be present with you.",
                "Your profile radiates this peaceful strength that I find incredibly magnetic.",
                "I like that your energy feels intentional. It makes me want to bring that same presence to this conversation.",
            ],
            "cheesy_lines": [
                "Are you a yogi? Because you just aligned my chakras with a single profile photo.",
                "They say yoga is about finding balance. You just balanced out my entire feed.",
                "Your profile has me in savasana because I am completely at peace after reading it.",
            ],
            "prefill_text": "Her bio mentions yoga or mindfulness. Write a grounded, present opener that matches her centered energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She practices yoga. Her profile feels calm and intentional. She seems mindful, flexible, and spiritually grounded.",
        },
        {
            "slug": "pottery",
            "keyword": "Pottery",
            "h1": "The Best Pottery Pickup Lines (For the Creatively Hands-On).",
            "title": "Best Pottery Pickup Lines | TryAgainText",
            "meta_description": "Use niche pottery pickup lines that feel creative and hands-on. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Pottery lovers are patient, tactile, and creative. They appreciate someone who values the process as much as the finished product.",
            "witty_lines": [
                "Your profile has the energy of someone who makes beautiful things with her hands and does not rush the process.",
                "I can tell you are into pottery because your bio feels carefully shaped, like something you took your time with.",
                "You seem like someone who knows that the best things take patience. This message is me being patient and intentional.",
            ],
            "flirty_lines": [
                "Something about your creative energy makes me think a conversation with you would be like working with clay \u2014 it just gets better the more you invest.",
                "Your profile has this earthy, grounded warmth that I find genuinely attractive.",
                "I like that you create things with your hands. There is something deeply appealing about that kind of presence.",
            ],
            "cheesy_lines": [
                "Are you a potter? Because you just threw me for a loop and I am still spinning.",
                "They say pottery is about centering. You just centered my entire evening.",
                "Your profile is a work of art and I am not even being cheesy. Okay, maybe a little.",
            ],
            "prefill_text": "Her bio mentions pottery or ceramics. Write a creative, patient opener that values the process.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She is into pottery. Her profile feels creative and grounded. She seems patient, artistic, and hands-on.",
        },
        {
            "slug": "photography",
            "keyword": "Photography",
            "h1": "The Best Photography Pickup Lines (For Those Who See the World Differently).",
            "title": "Best Photography Pickup Lines | TryAgainText",
            "meta_description": "Use niche photography pickup lines that feel observant and artistic. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Photographers notice what others miss. They value perspective, light, and capturing honest moments. They appreciate someone who sees them clearly.",
            "witty_lines": [
                "Your profile has the energy of someone who sees beauty in things other people walk right past. I notice that about you.",
                "I can tell you are a photographer because your photos tell a story most people would need a thousand words for.",
                "You seem like someone who knows the difference between looking and seeing. I am trying to do the latter with your profile.",
            ],
            "flirty_lines": [
                "Something about the way you frame your world makes me want to be part of the composition.",
                "Your eye for detail is showing and I find it incredibly attractive.",
                "I like that your profile feels curated but not staged. That balance is hard to achieve and you nailed it.",
            ],
            "cheesy_lines": [
                "Are you a photographer? Because every time I look at your profile, I see something new worth appreciating.",
                "They say photographers capture moments. You just captured my full attention.",
                "Your profile has perfect exposure, great composition, and I am fully in focus on you right now.",
            ],
            "prefill_text": "Her bio mentions photography. Write an observant, detail-oriented opener that shows you really looked.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She is into photography. Her profile has a strong visual sense. She seems creative, observant, and detail-oriented.",
        },
        {
            "slug": "hiking",
            "keyword": "Hiking",
            "h1": "The Best Hiking Pickup Lines (For the Trail-Ready and Adventurous).",
            "title": "Best Hiking Pickup Lines | TryAgainText",
            "meta_description": "Use niche hiking pickup lines that feel outdoorsy and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Hikers love the outdoors, value endurance, and appreciate someone willing to go the distance. A good opener should feel like the start of a great trail.",
            "witty_lines": [
                "Your profile has the energy of someone who wakes up early on weekends by choice and somehow makes that look appealing.",
                "I can tell you are a hiker because your photos have better scenery than most people's entire camera rolls.",
                "You seem like someone who measures a good day by elevation gained, not likes received.",
            ],
            "flirty_lines": [
                "Something about your love for the outdoors makes me want to explore more than just your profile.",
                "Your adventurous energy is the kind that makes a simple walk feel like a real journey. I want in.",
                "I like that your profile feels grounded and real. No filters needed when the backdrop is already that beautiful.",
            ],
            "cheesy_lines": [
                "Are you a hiker? Because I have been on a long trail of bad profiles and yours is the summit view.",
                "They say hiking is about the journey. I would love to start this one with you.",
                "Your profile just gave me that same feeling you get when you finally reach the overlook. Breathtaking.",
            ],
            "prefill_text": "Her bio mentions hiking or trail adventures. Write an outdoorsy, genuine opener that feels like fresh air.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She is into hiking. Her profile is full of trail photos and outdoor adventures. She seems active, grounded, and nature-loving.",
        },
        {
            "slug": "surfing",
            "keyword": "Surfing",
            "h1": "The Best Surfing Pickup Lines (For Wave Chasers).",
            "title": "Best Surfing Pickup Lines | TryAgainText",
            "meta_description": "Use niche surfing pickup lines that feel laid-back and adventurous. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Surfers live for the moment, respect the ocean, and value people who can go with the flow. A good opener should feel effortless, not forced.",
            "witty_lines": [
                "Your profile has the energy of someone who checks the surf report before checking her phone. I respect those priorities.",
                "I can tell you surf because your vibe is equal parts chill and fearless, which is a hard combination to pull off.",
                "You seem like someone who knows that the best things in life require patience and good timing. This is my best timing.",
            ],
            "flirty_lines": [
                "Something about your easygoing energy makes me feel like a conversation with you would just flow naturally.",
                "Your sun-kissed, carefree vibe is incredibly attractive. I had to say something.",
                "I like that your profile feels like a perfect wave \u2014 effortless but clearly something special.",
            ],
            "cheesy_lines": [
                "Are you a surfer? Because I have been waiting for the right wave and I think you are it.",
                "They say surfing is all about catching the right moment. This is me not letting this one pass.",
                "Your profile just wiped out every other one I have seen today. In the best way possible.",
            ],
            "prefill_text": "Her bio mentions surfing or ocean life. Write a laid-back, easy-flowing opener that matches her vibe.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She surfs. Her profile has beach and ocean energy. She seems free-spirited, patient, and adventurous.",
        },
        {
            "slug": "skateboarding",
            "keyword": "Skateboarding",
            "h1": "The Best Skateboarding Pickup Lines (For the Fearlessly Creative).",
            "title": "Best Skateboarding Pickup Lines | TryAgainText",
            "meta_description": "Use niche skateboarding pickup lines that feel cool and creative. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Skateboarders are creative, resilient, and do not care about fitting in. They respect authenticity and someone who is not afraid to eat pavement trying.",
            "witty_lines": [
                "Your profile has the energy of someone who learned every trick by falling a hundred times first. That kind of grit is attractive.",
                "I can tell you skate because your whole vibe says 'I do not need your approval but I will accept your compliment.'",
                "You seem like someone who sees the world as one giant skatepark. I like that perspective.",
            ],
            "flirty_lines": [
                "Something about your fearless, creative energy makes me want to try something I have never tried before \u2014 like writing a genuinely good opener.",
                "Your style is effortlessly cool and I am not going to pretend I did not notice.",
                "I like that your profile does not try to impress anyone. That lack of effort is somehow the most impressive thing here.",
            ],
            "cheesy_lines": [
                "Are you a skater? Because you just kickflipped my expectations for this app.",
                "They say skateboarding is about commitment. I am fully committed to this conversation.",
                "Your profile just sent me on a half-pipe of emotions and I am here for the ride.",
            ],
            "prefill_text": "Her bio mentions skateboarding. Write a cool, authentic opener that does not try too hard.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She skateboards. Her profile has an effortlessly cool vibe. She seems creative, resilient, and independent.",
        },
        {
            "slug": "gardening",
            "keyword": "Gardening",
            "h1": "The Best Gardening Pickup Lines (For Green Thumbs and Patient Souls).",
            "title": "Best Gardening Pickup Lines | TryAgainText",
            "meta_description": "Use niche gardening pickup lines that feel nurturing and grounded. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Gardeners are patient, nurturing, and find joy in watching things grow. They value someone who appreciates the slow beauty of tending to something with care.",
            "witty_lines": [
                "Your profile has the energy of someone who talks to her plants and they actually listen. I want that kind of attention.",
                "I can tell you are a gardener because your bio feels carefully cultivated, like something you tended to over time.",
                "You seem like someone who knows that the best things need sunlight, water, and patience. I am willing to be that patient.",
            ],
            "flirty_lines": [
                "Something about your nurturing energy makes me think you could make anything flourish \u2014 including a conversation with a stranger.",
                "Your profile has this warm, grounded quality that feels like stepping into a garden in full bloom.",
                "I like that you grow things. There is something deeply attractive about someone who creates life with her hands.",
            ],
            "cheesy_lines": [
                "Are you a gardener? Because something just bloomed in my chest and I think it is your fault.",
                "They say gardeners have the best patience. I hope that extends to giving me a chance.",
                "Your profile is the only thing on this app that is actually growing on me. In the best way.",
            ],
            "prefill_text": "Her bio mentions gardening or plants. Write a warm, nurturing opener that feels organic.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She loves gardening. Her profile has a warm, earthy feel. She seems patient, nurturing, and grounded.",
        },
        {
            "slug": "cooking",
            "keyword": "Cooking",
            "h1": "The Best Cooking Pickup Lines (For Those Who Bring the Heat).",
            "title": "Best Cooking Pickup Lines | TryAgainText",
            "meta_description": "Use niche cooking pickup lines that feel warm and flavorful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Home cooks are creative, generous, and express love through food. They appreciate someone who values effort, flavor, and showing up hungry.",
            "witty_lines": [
                "Your profile has the energy of someone who seasons by instinct, not measurement. That confidence is attractive.",
                "I can tell you love cooking because your bio has layers, depth, and leaves me wanting more.",
                "You seem like someone who turns simple ingredients into something extraordinary. This is me being a simple ingredient.",
            ],
            "flirty_lines": [
                "Something about your love for cooking tells me you put care into everything you do. I find that really appealing.",
                "Your warmth and creativity are showing through your profile and I am genuinely drawn in.",
                "I like that you cook. There is something about someone who creates with their hands that I find irresistible.",
            ],
            "cheesy_lines": [
                "Are you a cook? Because you just added spice to my entire evening.",
                "They say the way to someone's heart is through their stomach. Your profile just took a shortcut straight there.",
                "Your profile is like a perfect recipe \u2014 balanced, flavorful, and I want seconds.",
            ],
            "prefill_text": "Her bio mentions cooking or foodie energy. Write a warm, flavorful opener that matches her creative side.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She loves cooking. Her profile has a warm, creative energy. She seems generous, passionate, and detail-oriented about flavor.",
        },
        {
            "slug": "baking",
            "keyword": "Baking",
            "h1": "The Best Baking Pickup Lines (For the Sweet and Precise).",
            "title": "Best Baking Pickup Lines | TryAgainText",
            "meta_description": "Use niche baking pickup lines that feel sweet and thoughtful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Bakers are precise, patient, and find joy in creating something sweet from scratch. They appreciate someone who values effort and the little details.",
            "witty_lines": [
                "Your profile has the energy of someone who measures ingredients exactly and still somehow makes it look effortless.",
                "I can tell you bake because your bio is layered, sweet, and clearly took some effort to put together.",
                "You seem like someone who knows that good things take time and the right temperature. I am willing to wait.",
            ],
            "flirty_lines": [
                "Something about your precise, caring energy tells me everything you make turns out wonderful. Including first impressions.",
                "Your profile has this sweet, warm quality that makes me want to pull up a chair and stay a while.",
                "I like that you bake. There is something about the patience and care it takes that I find really attractive.",
            ],
            "cheesy_lines": [
                "Are you a baker? Because you just made my heart rise faster than sourdough on a warm day.",
                "They say baking is a science. The chemistry between your profile and me is undeniable.",
                "Your profile is like a fresh pastry \u2014 warm, inviting, and impossible to pass by.",
            ],
            "prefill_text": "Her bio mentions baking or pastry. Write a sweet, thoughtful opener that values precision and care.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She loves baking. Her profile has a sweet, precise feel. She seems patient, detail-oriented, and creative.",
        },
        {
            "slug": "gaming",
            "keyword": "Gaming",
            "h1": "The Best Gaming Pickup Lines (For the Player Two You Have Been Looking For).",
            "title": "Best Gaming Pickup Lines | TryAgainText",
            "meta_description": "Use niche gaming pickup lines that feel clever and reference-worthy. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Gamers value skill, humor, and shared experiences. They want someone who gets the references and can hold their own in a lobby or a conversation.",
            "witty_lines": [
                "Your profile has the energy of someone who has strong opinions about which controller is best. I am already invested in hearing them.",
                "I can tell you are a gamer because your bio has the pacing of a well-written side quest \u2014 intriguing and worth following.",
                "You seem like someone who does not skip cutscenes. That tells me you appreciate a good story. Here is mine.",
            ],
            "flirty_lines": [
                "Something about your profile tells me a co-op session with you would be the best kind of grind.",
                "Your competitive energy is attractive. I would love to see if we have the same taste in games and conversation.",
                "I like that you game. There is something about someone who commits to mastering something she loves that pulls me in.",
            ],
            "cheesy_lines": [
                "Are you a gamer? Because I just found the rare drop I have been looking for this entire session.",
                "They say gaming is about timing. Matching with you feels like a perfectly timed combo.",
                "Your profile is the main quest I did not know I was supposed to be on.",
            ],
            "prefill_text": "Her bio mentions gaming. Write a clever opener that uses gaming references without overdoing it.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She is a gamer. Her profile has a fun, competitive edge. She seems witty, passionate, and community-oriented.",
        },
        {
            "slug": "anime",
            "keyword": "Anime",
            "h1": "The Best Anime Pickup Lines (For Cultured Weebs and Casual Fans Alike).",
            "title": "Best Anime Pickup Lines | TryAgainText",
            "meta_description": "Use niche anime pickup lines that feel clever and authentic. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Anime fans appreciate storytelling, emotional depth, and shared fandoms. They want someone who gets it without trying too hard to prove they do.",
            "witty_lines": [
                "Your profile has the energy of a protagonist who does not realize she is the main character yet. I am here for the arc.",
                "I can tell you watch anime because your aesthetic has layers that most people would need a whole season to unpack.",
                "You seem like someone who has a top-five anime list ready at all times and will defend it passionately. I respect that.",
            ],
            "flirty_lines": [
                "Something about your profile gives me the same feeling as the opening scene of a show I already know I am going to binge.",
                "Your energy is the perfect blend of soft and intense, like the best character arcs. I am drawn in.",
                "I like that you are into anime. It tells me you value depth, emotion, and stories that actually mean something.",
            ],
            "cheesy_lines": [
                "Are you into anime? Because this feels like the start of a filler arc I actually want to watch.",
                "They say anime fans are emotionally invested. I am already emotionally invested in getting a reply from you.",
                "Your profile just triggered my final form: actually writing a thoughtful first message.",
            ],
            "prefill_text": "Her bio mentions anime. Write a clever opener that references anime culture naturally without being cringe.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She watches anime. Her profile has a creative, expressive vibe. She seems passionate about storytelling and has strong taste.",
        },
        {
            "slug": "vinyl-collecting",
            "keyword": "Vinyl Collecting",
            "h1": "The Best Vinyl Collecting Pickup Lines (For Audiophiles With Taste).",
            "title": "Best Vinyl Collecting Pickup Lines | TryAgainText",
            "meta_description": "Use niche vinyl collecting pickup lines that feel authentic and taste-driven. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Vinyl collectors value intentionality, sound quality, and the ritual of listening. They appreciate someone who cares about taste, not just trends.",
            "witty_lines": [
                "Your profile has the energy of someone whose record collection says more about her than any bio ever could.",
                "I can tell you collect vinyl because your aesthetic is warm, analog, and just a little bit nostalgic.",
                "You seem like someone who judges people by their record taste. I am ready to be judged.",
            ],
            "flirty_lines": [
                "Something about your profile makes me feel like we would have one of those conversations that only happens when a great album is playing in the background.",
                "Your taste is showing and I find it incredibly attractive. I would love to compare collections sometime.",
                "I like that you are into vinyl. It tells me you slow down and actually listen, which is rare and appealing.",
            ],
            "cheesy_lines": [
                "Are you a vinyl collector? Because I have been flipping through profiles and yours is the A-side I have been looking for.",
                "They say vinyl sounds warmer. Your profile has that same warm, analog quality.",
                "Your profile just scratched an itch I did not know I had. Pun very much intended.",
            ],
            "prefill_text": "Her bio mentions vinyl or records. Write a taste-driven opener that shows you appreciate the ritual of listening.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She collects vinyl records. Her profile has a warm, curated aesthetic. She seems intentional, taste-driven, and nostalgic in a cool way.",
        },
        {
            "slug": "bird-watching",
            "keyword": "Bird Watching",
            "h1": "The Best Bird Watching Pickup Lines (For the Patient and Observant).",
            "title": "Best Bird Watching Pickup Lines | TryAgainText",
            "meta_description": "Use niche bird watching pickup lines that feel observant and charming. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Birders are patient, observant, and find wonder in the everyday. They appreciate someone who notices the details and does not rush past the good stuff.",
            "witty_lines": [
                "Your profile has the energy of someone who can sit still for hours waiting for the right moment. That patience is genuinely attractive.",
                "I can tell you are a birder because you seem like someone who notices things other people miss entirely.",
                "You seem like someone whose idea of a perfect morning involves binoculars and silence. I find that deeply appealing.",
            ],
            "flirty_lines": [
                "Something about your quiet, observant energy makes me feel like being around you would make me notice more beauty in the world.",
                "Your patience and attention to detail are showing and I am drawn to both.",
                "I like that you bird watch. It tells me you appreciate stillness and find magic in small moments.",
            ],
            "cheesy_lines": [
                "Are you a birder? Because I have been scanning this app and you are the rarest sighting I have made.",
                "They say birding is about patience. I would happily wait as long as it takes for a reply from you.",
                "Your profile just made my heart do that thing it does when you spot a bird you have never seen before.",
            ],
            "prefill_text": "Her bio mentions bird watching or birding. Write a patient, observant opener that values the small things.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She bird watches. Her profile has a calm, observant quality. She seems patient, detail-oriented, and deeply connected to nature.",
        },
        {
            "slug": "tarot",
            "keyword": "Tarot",
            "h1": "The Best Tarot Pickup Lines (For the Intuitively Gifted).",
            "title": "Best Tarot Pickup Lines | TryAgainText",
            "meta_description": "Use niche tarot pickup lines that feel intuitive and mystical. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Tarot readers value intuition, symbolism, and deeper meaning. They appreciate someone who is open-minded and comfortable with the unseen.",
            "witty_lines": [
                "Your profile has the energy of someone who pulled The Star card and decided to just embody it permanently.",
                "I can tell you read tarot because your bio has layers of meaning that reward a closer look.",
                "You seem like someone who trusts her intuition. Mine is telling me I should absolutely send this message.",
            ],
            "flirty_lines": [
                "Something about your mystical energy makes me feel like the universe put your profile in my path for a reason.",
                "Your intuitive, soulful vibe is magnetic. I would love to know what the cards say about us.",
                "I like that you are into tarot. It tells me you look for meaning beyond the surface, and that is exactly what I want to do with you.",
            ],
            "cheesy_lines": [
                "Are you into tarot? Because I did not need a reading to know you are The Empress of this app.",
                "They say the cards never lie. Every card in my spread is pointing me toward your profile.",
                "Your profile just gave me major Tower energy \u2014 completely unexpected and about to change everything.",
            ],
            "prefill_text": "Her bio mentions tarot or spirituality. Write an intuitive, open-minded opener that respects her practice.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She reads tarot. Her profile has a mystical, intuitive quality. She seems spiritually open, reflective, and in tune with symbolism.",
        },
        {
            "slug": "thrifting",
            "keyword": "Thrifting",
            "h1": "The Best Thrifting Pickup Lines (For Treasure Hunters With Style).",
            "title": "Best Thrifting Pickup Lines | TryAgainText",
            "meta_description": "Use niche thrifting pickup lines that feel stylish and treasure-hunt-worthy. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Thrifters have a sharp eye for hidden gems and value uniqueness over trends. They appreciate someone who recognizes quality when they see it.",
            "witty_lines": [
                "Your profile has the energy of someone who walks into a thrift store and finds the one perfect piece everyone else missed.",
                "I can tell you thrift because your style is unique, curated, and clearly not from a fast fashion algorithm.",
                "You seem like someone who knows that the best finds are never on the surface. I am hoping that applies to dating apps too.",
            ],
            "flirty_lines": [
                "Something about your eye for hidden gems tells me you see value where others overlook it. I find that really attractive.",
                "Your one-of-a-kind style is magnetic. I would love to hear the story behind every piece.",
                "I like that you thrift. It tells me you appreciate things with character and history, not just a price tag.",
            ],
            "cheesy_lines": [
                "Are you a thrifter? Because I have been digging through profiles and you are the vintage find I have been searching for.",
                "They say the best thrift finds are priceless. So is matching with you.",
                "Your profile is the kind of rare find that makes the entire search worth it.",
            ],
            "prefill_text": "Her bio mentions thrifting or vintage style. Write a stylish, treasure-hunt-themed opener that values uniqueness.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She loves thrifting. Her profile has a unique, curated style. She seems resourceful, fashion-forward, and appreciates character over trends.",
        },
        {
            "slug": "journaling",
            "keyword": "Journaling",
            "h1": "The Best Journaling Pickup Lines (For the Deeply Reflective).",
            "title": "Best Journaling Pickup Lines | TryAgainText",
            "meta_description": "Use niche journaling pickup lines that feel thoughtful and introspective. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Journalers value reflection, self-awareness, and the power of words. They appreciate someone who thinks before they speak and means what they say.",
            "witty_lines": [
                "Your profile has the energy of someone who processes the world through writing and somehow makes sense of it all.",
                "I can tell you journal because your bio reads like it was drafted, revised, and perfected. I appreciate that effort.",
                "You seem like someone who has a notebook full of thoughts most people would be too afraid to write down.",
            ],
            "flirty_lines": [
                "Something about your reflective energy makes me want to be thoughtful with every word I say to you.",
                "Your self-awareness is genuinely attractive. I like that you take the time to understand yourself.",
                "I like that you journal. It tells me you value inner depth, and I would love to explore what is beneath the surface.",
            ],
            "cheesy_lines": [
                "Are you a journaler? Because I want to be the entry that made you smile today.",
                "They say journaling is self-care. Reading your profile was the most caring thing I have done for myself all week.",
                "Your profile reads like a beautifully written page I never want to turn.",
            ],
            "prefill_text": "Her bio mentions journaling or reflective writing. Write a thoughtful, introspective opener that values words.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She journals. Her profile has a reflective, thoughtful quality. She seems introspective, articulate, and emotionally intelligent.",
        },
        {
            "slug": "dnd",
            "keyword": "Dungeons & Dragons",
            "h1": "The Best D&D Pickup Lines (For the Dice-Rolling Romantics).",
            "title": "Best D&D Pickup Lines | TryAgainText",
            "meta_description": "Use niche D&D pickup lines that feel creative and campaign-worthy. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "D&D players are creative, collaborative, and love storytelling. They want someone who brings imagination to the table and can commit to a long campaign.",
            "witty_lines": [
                "Your profile has the energy of someone who has a detailed backstory ready for every character she rolls. I am fascinated.",
                "I can tell you play D&D because your bio has the world-building quality of a well-crafted campaign setting.",
                "You seem like someone who takes roleplay seriously and I mean that in the most respectful, dice-rolling way possible.",
            ],
            "flirty_lines": [
                "Something about your creative energy makes me think adventuring with you would be the campaign of a lifetime.",
                "Your imagination and depth are showing and I find both incredibly attractive.",
                "I like that you play D&D. It tells me you value collaboration, creativity, and stories that go somewhere meaningful.",
            ],
            "cheesy_lines": [
                "Are you a D&D player? Because I just rolled a natural 20 on my perception check and noticed you immediately.",
                "They say the best campaigns are the ones you never want to end. Matching with you feels like session one of exactly that.",
                "Your profile just gave me inspiration. Literally, I am using it on this charisma check.",
            ],
            "prefill_text": "Her bio mentions D&D or tabletop games. Write a creative, campaign-flavored opener that is charming without being corny.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She plays D&D. Her profile has a creative, imaginative energy. She seems collaborative, nerdy in the best way, and loves storytelling.",
        },
        {
            "slug": "chess",
            "keyword": "Chess",
            "h1": "The Best Chess Pickup Lines (For Strategic Minds).",
            "title": "Best Chess Pickup Lines | TryAgainText",
            "meta_description": "Use niche chess pickup lines that feel strategic and clever. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Chess players think ahead, value strategy, and respect a worthy opponent. They want someone who can match their intellect and keep them guessing.",
            "witty_lines": [
                "Your profile has the energy of someone who is always three moves ahead. I am doing my best to keep up.",
                "I can tell you play chess because your bio is calculated, precise, and leaves nothing to chance.",
                "You seem like someone who appreciates a strong opening. Consider this my Sicilian Defense \u2014 bold and committed.",
            ],
            "flirty_lines": [
                "Something about your strategic mind is incredibly attractive. I would love to see if you are as sharp in conversation.",
                "Your intelligence is the most magnetic thing about your profile and there is a lot of competition.",
                "I like that you play chess. It tells me you think deeply and do not waste moves. Neither am I.",
            ],
            "cheesy_lines": [
                "Are you a chess player? Because you just put my heart in check and I do not see a way out.",
                "They say chess is the game of kings. Matching with you feels like a royal victory.",
                "Your profile is checkmate. I did not even see it coming.",
            ],
            "prefill_text": "Her bio mentions chess. Write a strategic, clever opener that shows you can think on her level.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She plays chess. Her profile feels sharp and deliberate. She seems analytical, competitive, and intellectually curious.",
        },
        {
            "slug": "crossfit",
            "keyword": "CrossFit",
            "h1": "The Best CrossFit Pickup Lines (For the Relentlessly Driven).",
            "title": "Best CrossFit Pickup Lines | TryAgainText",
            "meta_description": "Use niche CrossFit pickup lines that feel intense and driven. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "CrossFitters are disciplined, community-driven, and push past limits daily. They want someone who respects the grind and can match their intensity.",
            "witty_lines": [
                "Your profile has the energy of someone who finishes the WOD and then asks if there is a bonus round.",
                "I can tell you do CrossFit because your entire vibe screams discipline, community, and never skipping a day.",
                "You seem like someone who treats every challenge like a PR opportunity. This message is mine.",
            ],
            "flirty_lines": [
                "Something about your drive and discipline is genuinely magnetic. I wanted to match that energy with my opener.",
                "Your commitment to showing up every day is incredibly attractive. I would love to bring that same consistency.",
                "I like that you do CrossFit. It tells me you do not settle for easy and that is exactly the kind of person I want to talk to.",
            ],
            "cheesy_lines": [
                "Are you into CrossFit? Because my heart rate just spiked and I have not even left the couch.",
                "They say CrossFit builds community. I am here to join yours.",
                "Your profile is the toughest WOD I have faced today \u2014 because I cannot stop coming back to it.",
            ],
            "prefill_text": "Her bio mentions CrossFit. Write an intense, driven opener that respects her discipline.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She does CrossFit. Her profile radiates discipline and grit. She seems competitive, community-oriented, and relentlessly driven.",
        },
        {
            "slug": "running",
            "keyword": "Running",
            "h1": "The Best Running Pickup Lines (For Those Who Go the Distance).",
            "title": "Best Running Pickup Lines | TryAgainText",
            "meta_description": "Use niche running pickup lines that feel enduring and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Runners value endurance, mental toughness, and the meditative clarity of a long run. They appreciate someone who understands commitment to the process.",
            "witty_lines": [
                "Your profile has the energy of someone who runs before the sun comes up and somehow makes that lifestyle look appealing.",
                "I can tell you are a runner because your bio has the pacing of a perfect negative split \u2014 it only gets better.",
                "You seem like someone who knows that the hardest part is starting. So here I am, starting this conversation.",
            ],
            "flirty_lines": [
                "Something about your endurance and discipline makes me think you bring that same commitment to everything you care about.",
                "Your drive is genuinely attractive. I would love to keep pace with someone like you.",
                "I like that you run. It tells me you show up for yourself daily, and that kind of self-respect is magnetic.",
            ],
            "cheesy_lines": [
                "Are you a runner? Because you have been running through my mind since I saw your profile.",
                "They say running is a metaphor for life. I would love to go the distance with you.",
                "Your profile just lapped every other one on this app. And it was not even close.",
            ],
            "prefill_text": "Her bio mentions running or marathons. Write an enduring, genuine opener that goes the distance.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She is a runner. Her profile shows discipline and endurance. She seems mentally tough, goal-driven, and committed to the process.",
        },
        {
            "slug": "cycling",
            "keyword": "Cycling",
            "h1": "The Best Cycling Pickup Lines (For Two-Wheeled Adventurers).",
            "title": "Best Cycling Pickup Lines | TryAgainText",
            "meta_description": "Use niche cycling pickup lines that feel adventurous and free. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Cyclists love freedom, endurance, and exploring the world at their own pace. They appreciate someone who values the journey as much as the destination.",
            "witty_lines": [
                "Your profile has the energy of someone who has strong opinions about gear ratios and I find that oddly attractive.",
                "I can tell you cycle because your vibe is equal parts endurance and freedom, which is a rare combination.",
                "You seem like someone who measures distance in stories, not just miles. I would love to hear a few.",
            ],
            "flirty_lines": [
                "Something about your love for the open road makes me think a conversation with you would feel like a perfect downhill stretch.",
                "Your adventurous, free-spirited energy is showing and I am very drawn to it.",
                "I like that you cycle. It tells me you enjoy the ride, not just the finish line.",
            ],
            "cheesy_lines": [
                "Are you a cyclist? Because my heart just shifted into a higher gear looking at your profile.",
                "They say cycling is about momentum. This conversation already has it.",
                "Your profile is the scenic route I did not know I needed today.",
            ],
            "prefill_text": "Her bio mentions cycling or biking. Write a free-spirited, adventurous opener that values the journey.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She cycles. Her profile has an adventurous, free-spirited feel. She seems endurance-driven, independent, and loves exploring.",
        },
        {
            "slug": "painting",
            "keyword": "Painting",
            "h1": "The Best Painting Pickup Lines (For the Visually Expressive).",
            "title": "Best Painting Pickup Lines | TryAgainText",
            "meta_description": "Use niche painting pickup lines that feel artistic and expressive. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Painters see the world in color, texture, and emotion. They value expression and appreciate someone who notices the beauty in their perspective.",
            "witty_lines": [
                "Your profile has the energy of someone who sees colors other people do not even know exist.",
                "I can tell you paint because your aesthetic is vivid, intentional, and impossible to scroll past.",
                "You seem like someone whose world is more colorful than most. I would love to see it through your eyes.",
            ],
            "flirty_lines": [
                "Something about your artistic eye makes everything around you feel more beautiful. Including this moment.",
                "Your creative expression is magnetic. I would love to know what inspires you.",
                "I like that you paint. There is something deeply attractive about someone who creates beauty from nothing.",
            ],
            "cheesy_lines": [
                "Are you a painter? Because your profile is a masterpiece and I am standing in the gallery staring.",
                "They say every painting tells a story. Your profile just told me mine was about to get a lot more interesting.",
                "Your profile is the kind of art that makes you stop and feel something real.",
            ],
            "prefill_text": "Her bio mentions painting or art. Write an expressive, visually rich opener that appreciates her creativity.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She paints. Her profile has a vivid, artistic quality. She seems expressive, emotionally rich, and visually creative.",
        },
        {
            "slug": "tattoos",
            "keyword": "Tattoos",
            "h1": "The Best Tattoo Pickup Lines (For the Inked and Intentional).",
            "title": "Best Tattoo Pickup Lines | TryAgainText",
            "meta_description": "Use niche tattoo pickup lines that feel bold and story-driven. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Tattoo lovers value self-expression, permanence, and stories worth telling. They appreciate someone who asks about the meaning, not just the art.",
            "witty_lines": [
                "Your profile has the energy of someone whose tattoos all have stories and none of them are boring.",
                "I can tell you are into tattoos because your aesthetic is bold, intentional, and unapologetically you.",
                "You seem like someone who commits to things that matter. Every piece of ink says that louder than any bio could.",
            ],
            "flirty_lines": [
                "Something about the way you wear your art makes me want to know every story behind it.",
                "Your self-expression is magnetic. I would love to hear which piece means the most to you.",
                "I like that your tattoos tell a story. It tells me you value meaning over aesthetics, even though you have both.",
            ],
            "cheesy_lines": [
                "Are you into tattoos? Because your profile just left a permanent impression on me.",
                "They say tattoos are forever. So is the memory of seeing your profile for the first time.",
                "Your ink game is as strong as your profile game and that is saying something.",
            ],
            "prefill_text": "Her bio or photos show tattoos. Write a bold, story-curious opener that asks about the meaning, not just the look.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She has tattoos. Her profile feels bold and intentional. She seems expressive, committed to her choices, and loves storytelling through art.",
        },
        {
            "slug": "coffee",
            "keyword": "Coffee",
            "h1": "The Best Coffee Pickup Lines (For the Caffeinated and Curious).",
            "title": "Best Coffee Pickup Lines | TryAgainText",
            "meta_description": "Use niche coffee pickup lines that feel warm and flavorful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Coffee lovers appreciate ritual, quality, and the art of slowing down with a great cup. They want someone who understands that coffee is more than caffeine.",
            "witty_lines": [
                "Your profile has the energy of someone who has strong opinions about pour-over technique and I want to hear every one of them.",
                "I can tell you are a coffee person because your vibe is warm, rich, and just the right amount of intense.",
                "You seem like someone who judges a city by its coffee shops. I respect those priorities deeply.",
            ],
            "flirty_lines": [
                "Something about your warm, grounded energy makes me think a coffee date with you would be the highlight of my week.",
                "Your taste is refined and showing. I would love to compare favorite roasters over an actual cup sometime.",
                "I like that you take coffee seriously. It tells me you appreciate the ritual and the details, and I am into both.",
            ],
            "cheesy_lines": [
                "Are you a coffee lover? Because you just gave me a bigger jolt than my morning espresso.",
                "They say coffee wakes you up. Your profile just woke up my entire dating life.",
                "Your profile is like a perfect latte \u2014 warm, balanced, and I want one every morning.",
            ],
            "prefill_text": "Her bio mentions coffee or cafe culture. Write a warm, flavorful opener that appreciates the ritual.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She loves coffee. Her profile has a warm, cozy energy. She seems taste-driven, ritualistic, and appreciates quality over convenience.",
        },
        {
            "slug": "camping",
            "keyword": "Camping",
            "h1": "The Best Camping Pickup Lines (For the Outdoorsy and Unplugged).",
            "title": "Best Camping Pickup Lines | TryAgainText",
            "meta_description": "Use niche camping pickup lines that feel rugged and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Campers love simplicity, nature, and unplugging from the noise. They appreciate someone who can be present without needing a plan for every moment.",
            "witty_lines": [
                "Your profile has the energy of someone who can start a campfire and a great conversation with equal ease.",
                "I can tell you camp because your vibe is rugged, real, and refreshingly unplugged.",
                "You seem like someone who is happiest when the cell signal disappears. I find that incredibly attractive.",
            ],
            "flirty_lines": [
                "Something about your love for the outdoors tells me you value real connection over digital noise. So do I.",
                "Your grounded, nature-loving energy is magnetic. I would love to share a campfire conversation with you.",
                "I like that you camp. It tells me you are comfortable with simplicity and silence, and that is rare.",
            ],
            "cheesy_lines": [
                "Are you a camper? Because you just pitched a tent in my thoughts and I do not want you to leave.",
                "They say camping is about getting back to basics. Matching with you feels like the most basic and best thing I have done.",
                "Your profile is like a perfect campsite \u2014 warm, inviting, and somewhere I want to stay.",
            ],
            "prefill_text": "Her bio mentions camping or the outdoors. Write a rugged, genuine opener that values presence and simplicity.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She loves camping. Her profile feels outdoorsy and grounded. She seems adventurous, low-maintenance, and happiest in nature.",
        },
        {
            "slug": "fishing",
            "keyword": "Fishing",
            "h1": "The Best Fishing Pickup Lines (For the Patient and Persistent).",
            "title": "Best Fishing Pickup Lines | TryAgainText",
            "meta_description": "Use niche fishing pickup lines that feel patient and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Fishers value patience, solitude, and the thrill of the catch. They appreciate someone who understands that good things come to those who wait.",
            "witty_lines": [
                "Your profile has the energy of someone who can sit in silence for hours and still call it a perfect day.",
                "I can tell you fish because your patience and calm are visible even through a screen.",
                "You seem like someone who knows that the best catches require the right bait and perfect timing. This is my best cast.",
            ],
            "flirty_lines": [
                "Something about your patient, outdoorsy energy makes me feel like you would make even a quiet morning on the water unforgettable.",
                "Your calm confidence is genuinely attractive. I would love to spend time with someone who appreciates stillness.",
                "I like that you fish. It tells me you find peace in patience, and that is a quality I really admire.",
            ],
            "cheesy_lines": [
                "Are you into fishing? Because I have been casting lines all day and yours is the only profile I want to reel in.",
                "They say fishing is about patience. I would wait as long as it takes for a reply from you.",
                "Your profile is the big catch I have been telling my friends about.",
            ],
            "prefill_text": "Her bio mentions fishing. Write a patient, genuine opener that values calm and persistence.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She fishes. Her profile has a calm, outdoorsy quality. She seems patient, persistent, and at peace in nature.",
        },
        {
            "slug": "woodworking",
            "keyword": "Woodworking",
            "h1": "The Best Woodworking Pickup Lines (For the Hands-On and Crafted).",
            "title": "Best Woodworking Pickup Lines | TryAgainText",
            "meta_description": "Use niche woodworking pickup lines that feel crafted and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Woodworkers are patient, skilled, and take pride in building things that last. They appreciate someone who values craftsmanship and attention to detail.",
            "witty_lines": [
                "Your profile has the energy of someone who builds things with her hands and takes pride in every joint and finish.",
                "I can tell you do woodworking because your bio feels carefully constructed, like something made to last.",
                "You seem like someone who knows the difference between quick and quality. This message is my attempt at quality.",
            ],
            "flirty_lines": [
                "Something about your craftsmanship energy makes me think everything you touch turns out better than expected.",
                "Your hands-on, creative approach to life is genuinely attractive. I would love to see what you have built.",
                "I like that you work with wood. There is something timeless about someone who creates lasting things in a disposable world.",
            ],
            "cheesy_lines": [
                "Are you into woodworking? Because you just constructed the most impressive profile I have ever seen.",
                "They say measure twice, cut once. I have read your profile twice and I am ready to make my move.",
                "Your profile is built like fine furniture \u2014 solid, beautiful, and clearly made with care.",
            ],
            "prefill_text": "Her bio mentions woodworking or carpentry. Write a crafted, detail-oriented opener that values building things well.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She does woodworking. Her profile feels hands-on and grounded. She seems patient, skilled, and proud of her craft.",
        },
        {
            "slug": "knitting",
            "keyword": "Knitting",
            "h1": "The Best Knitting Pickup Lines (For the Cozy and Creative).",
            "title": "Best Knitting Pickup Lines | TryAgainText",
            "meta_description": "Use niche knitting pickup lines that feel cozy and heartfelt. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Knitters are patient, creative, and find meditation in repetition. They appreciate someone who values handmade over store-bought and coziness over flash.",
            "witty_lines": [
                "Your profile has the energy of someone who can turn a ball of yarn into something beautiful while watching a show. That multitasking is impressive.",
                "I can tell you knit because your bio feels carefully crafted, stitch by stitch, into something warm.",
                "You seem like someone who values making things by hand in a world that buys everything pre-made. I find that really appealing.",
            ],
            "flirty_lines": [
                "Something about your cozy, creative energy makes me want to curl up and have the longest conversation of my life with you.",
                "Your warmth is tangible even through a screen. I would love to experience it in person.",
                "I like that you knit. It tells me you are patient, creative, and put care into the things you make. Including, I bet, your relationships.",
            ],
            "cheesy_lines": [
                "Are you a knitter? Because you just wove your way into my thoughts and I am not mad about it.",
                "They say knitting is meditative. Your profile has that same calming, grounding effect on me.",
                "Your profile is like a hand-knit sweater \u2014 warm, unique, and made with love.",
            ],
            "prefill_text": "Her bio mentions knitting or fiber arts. Write a cozy, heartfelt opener that values patience and creativity.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She knits. Her profile has a cozy, creative warmth. She seems patient, artistic, and values handmade over mass-produced.",
        },
        {
            "slug": "reading",
            "keyword": "Reading",
            "h1": "The Best Reading Pickup Lines (For the Endlessly Curious).",
            "title": "Best Reading Pickup Lines | TryAgainText",
            "meta_description": "Use niche reading pickup lines that feel bookish and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Readers are curious, imaginative, and value depth over small talk. They want someone who can recommend a great book and hold an even better conversation.",
            "witty_lines": [
                "Your profile has the energy of someone who judges a bookshelf harder than a dating profile. I respect those priorities.",
                "I can tell you are a reader because your bio has the depth of a novel I would actually finish.",
                "You seem like someone who always has a book recommendation ready. I am here for it and for the conversation that comes with it.",
            ],
            "flirty_lines": [
                "Something about your bookish energy makes me think a conversation with you would have more layers than most novels.",
                "Your curiosity and depth are showing and I find both incredibly attractive.",
                "I like that you read. It tells me you are comfortable spending time in your own head, and that kind of inner world is magnetic.",
            ],
            "cheesy_lines": [
                "Are you a reader? Because your profile is the most compelling thing I have read all week and I want the next chapter.",
                "They say a good book changes you. Your profile just changed my expectations for this entire app.",
                "Your profile reads like a bestseller \u2014 impossible to put down once you start.",
            ],
            "prefill_text": "Her bio mentions reading or books. Write a bookish, curious opener that values depth and good taste.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She loves reading. Her profile has a thoughtful, curious quality. She seems imaginative, well-read, and values intellectual depth.",
        },
        {
            "slug": "bouldering",
            "keyword": "Bouldering",
            "h1": "The Best Bouldering Pickup Lines (For the Problem-Solvers).",
            "title": "Best Bouldering Pickup Lines | TryAgainText",
            "meta_description": "Use niche bouldering pickup lines that feel gritty and cerebral. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Boulderers are problem-solvers who combine physical strength with mental strategy. They respect persistence and someone who is not afraid to fail and try again.",
            "witty_lines": [
                "Your profile has the energy of someone who stares at a problem wall for twenty minutes and then sends it clean. That focus is impressive.",
                "I can tell you boulder because your vibe is equal parts strength and strategy, which is a hard beta to read.",
                "You seem like someone who does not mind falling as long as the problem is worth solving. I am hoping I am worth a shot.",
            ],
            "flirty_lines": [
                "Something about your problem-solving energy makes me think you approach everything with the same grit and grace. I find that really attractive.",
                "Your strength and intelligence are both on display and I am drawn to the combination.",
                "I like that you boulder. It tells me you are not afraid of a challenge and you trust your own ability. Both are magnetic.",
            ],
            "cheesy_lines": [
                "Are you a boulderer? Because I have been trying to figure out the right approach to your profile and I think I just found the crux.",
                "They say bouldering is chess with your body. Matching with you is the smartest move I have made.",
                "Your profile is the V10 I have been training for all season.",
            ],
            "prefill_text": "Her bio mentions bouldering. Write a gritty, cerebral opener that respects her problem-solving side.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She boulders. Her profile shows strength and strategy. She seems persistent, analytical, and physically capable.",
        },
        {
            "slug": "pilates",
            "keyword": "Pilates",
            "h1": "The Best Pilates Pickup Lines (For the Strong and Controlled).",
            "title": "Best Pilates Pickup Lines | TryAgainText",
            "meta_description": "Use niche pilates pickup lines that feel poised and intentional. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Pilates practitioners value control, alignment, and inner strength. They appreciate someone who is intentional with their body and their words.",
            "witty_lines": [
                "Your profile has the energy of someone who makes the hardest exercises look effortless. That control is genuinely impressive.",
                "I can tell you do pilates because your entire presence feels aligned, strong, and deliberately put together.",
                "You seem like someone who values form over speed in everything she does. This message is me focusing on form.",
            ],
            "flirty_lines": [
                "Something about your poised, controlled energy is incredibly attractive. I would love to match that intentionality.",
                "Your inner strength is showing and it is the most magnetic thing about your profile.",
                "I like that you do pilates. It tells me you care about how you carry yourself, and that kind of awareness is rare.",
            ],
            "cheesy_lines": [
                "Are you into pilates? Because your profile just engaged my core emotions.",
                "They say pilates is about alignment. Everything about your profile aligns with what I have been looking for.",
                "Your profile has perfect form, great balance, and I am fully engaged.",
            ],
            "prefill_text": "Her bio mentions pilates. Write a poised, intentional opener that values control and strength.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She does pilates. Her profile feels poised and strong. She seems disciplined, intentional, and deeply in control.",
        },
        {
            "slug": "martial-arts",
            "keyword": "Martial Arts",
            "h1": "The Best Martial Arts Pickup Lines (For the Disciplined and Fearless).",
            "title": "Best Martial Arts Pickup Lines | TryAgainText",
            "meta_description": "Use niche martial arts pickup lines that feel respectful and bold. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Martial artists value discipline, respect, and continuous growth. They appreciate someone who shows up with humility and genuine confidence.",
            "witty_lines": [
                "Your profile has the energy of someone who could take me down and still be polite about it. That balance is impressive.",
                "I can tell you train because your discipline and focus come through even in a dating profile.",
                "You seem like someone who bows before she fights and means both equally. I respect that deeply.",
            ],
            "flirty_lines": [
                "Something about your disciplined energy makes me want to show up with the same respect and intention you clearly bring to everything.",
                "Your quiet confidence is the most attractive thing on this app right now.",
                "I like that you train martial arts. It tells me you value growth, respect, and never settle for where you are. All incredibly attractive.",
            ],
            "cheesy_lines": [
                "Are you a martial artist? Because you just knocked out every other profile without even trying.",
                "They say martial arts is about discipline. You just disciplined me into writing my best opener ever.",
                "Your profile has black belt energy and I am not even close to your level but I am showing up anyway.",
            ],
            "prefill_text": "Her bio mentions martial arts. Write a respectful, bold opener that values discipline and growth.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She trains martial arts. Her profile feels disciplined and confident. She seems focused, respectful, and constantly growing.",
        },
        {
            "slug": "salsa-dancing",
            "keyword": "Salsa Dancing",
            "h1": "The Best Salsa Dancing Pickup Lines (For the Rhythmically Gifted).",
            "title": "Best Salsa Dancing Pickup Lines | TryAgainText",
            "meta_description": "Use niche salsa dancing pickup lines that feel rhythmic and passionate. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Salsa dancers value connection, rhythm, and the chemistry of a great partner. They appreciate someone who can follow the music and lead with confidence.",
            "witty_lines": [
                "Your profile has the energy of someone who can feel the rhythm in any room and makes everyone else want to move too.",
                "I can tell you dance salsa because your vibe is equal parts passion and precision, which is exactly how the best leads work.",
                "You seem like someone who tests a partner in the first eight counts and decides from there. This opener is my first count.",
            ],
            "flirty_lines": [
                "Something about your passionate, rhythmic energy makes me think being around you would feel like the best song you have ever heard.",
                "Your confidence on and off the dance floor is magnetic. I would love to experience both.",
                "I like that you dance salsa. It tells me you value connection, chemistry, and showing up fully present.",
            ],
            "cheesy_lines": [
                "Are you a salsa dancer? Because my heart is already doing a cross-body lead toward you.",
                "They say salsa is about connection. I already feel one and we have not even talked yet.",
                "Your profile has more rhythm than anything else on this app and I am ready to follow your lead.",
            ],
            "prefill_text": "Her bio mentions salsa dancing. Write a rhythmic, passionate opener that values connection and chemistry.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She dances salsa. Her profile has a passionate, rhythmic energy. She seems confident, expressive, and values partner chemistry.",
        },
        {
            "slug": "stand-up-comedy",
            "keyword": "Stand-Up Comedy",
            "h1": "The Best Stand-Up Comedy Pickup Lines (For the Fearlessly Funny).",
            "title": "Best Stand-Up Comedy Pickup Lines | TryAgainText",
            "meta_description": "Use niche stand-up comedy pickup lines that feel sharp and confident. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Stand-up comedians are observant, brave, and turn vulnerability into laughter. They want someone who can take a joke, land one, and appreciate the craft.",
            "witty_lines": [
                "Your profile has the energy of someone who has been workshopping a bit about dating apps and honestly I would listen to the full set.",
                "I can tell you do stand-up because your bio has timing, delivery, and a punchline that actually landed.",
                "You seem like someone who turns awkward moments into material. This message is either a great opener or your next bit.",
            ],
            "flirty_lines": [
                "Something about your fearless, observant energy makes me think a date with you would be the most fun I have had in months.",
                "Your humor is the most attractive thing about your profile, and the bar was already high.",
                "I like that you do comedy. It tells me you are brave enough to be vulnerable in front of strangers, and that takes real confidence.",
            ],
            "cheesy_lines": [
                "Are you a comedian? Because your profile just got a genuine laugh out of me and that never happens on this app.",
                "They say comedy is tragedy plus time. Matching with you is the happiest ending to my tragic swiping session.",
                "Your profile has better material than most open mics I have been to. And I mean that sincerely.",
            ],
            "prefill_text": "Her bio mentions stand-up comedy. Write a sharp, funny opener that shows you appreciate the craft.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her hobby.",
            "her_info_prefill": "She does stand-up comedy. Her profile is sharp and funny. She seems observant, brave, and turns vulnerability into humor.",
        },
    ],
}
