DATA = {
    "category_slug": "literature",
    "category_name": "Literature",
    "sort_order": 0,
    "topics": [
        {
            "slug": "dostoevsky",
            "keyword": "Dostoevsky",
            "h1": "The Best Dostoevsky Pickup Lines (To Impress a Bookworm).",
            "title": "Best Dostoevsky Pickup Lines | TryAgainText",
            "meta_description": "Use niche Dostoevsky pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Dostoevsky can make generic openers feel weak. These lines give you a stronger starting point by referencing Crime and Punishment without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "You mentioned Raskolnikov like it was casual, so I already know this conversation will have layers.",
                "Most people open with 'hey.' Your Crime and Punishment reference just raised the bar by about 500 pages.",
                "If your personality has even half the tension of a Dostoevsky novel, I am already hooked.",
            ],
            "flirty_lines": [
                "Something about a person who reads Dostoevsky and still smiles in every photo is very attractive.",
                "I would love to hear your take on Sonya over coffee \u2014 and yes, that is my version of a smooth ask.",
                "Your profile has that rare mix of depth and warmth that makes me want to skip small talk entirely.",
            ],
            "cheesy_lines": [
                "Are you Crime and Punishment? Because I cannot stop thinking about you and I have not even finished the first chapter.",
                "I must be Raskolnikov, because matching with you just changed my whole moral calculus.",
                "You had me at Dostoevsky. Everything after that was just epilogue.",
            ],
            "prefill_text": "Her bio: Crime and Punishment changed my life. Write a playful opener that sounds smart, not try-hard.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She has a quote from Crime and Punishment in her bio and a coffee shop photo. She seems witty and intellectual, but not overly serious.",
        },
        {
            "slug": "william-shakespeare",
            "keyword": "William Shakespeare",
            "h1": "The Best William Shakespeare Pickup Lines (To Impress a Bookworm).",
            "title": "Best William Shakespeare Pickup Lines | TryAgainText",
            "meta_description": "Use niche William Shakespeare pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves William Shakespeare can make generic openers feel weak. These lines give you a stronger starting point by referencing Hamlet without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "To message or not to message was never really a question once I saw your profile.",
                "You like Shakespeare, so you already know the best love stories start with good wordplay.",
                "Your profile reads like a sonnet \u2014 14 seconds in and I am already trying to figure out the volta.",
            ],
            "flirty_lines": [
                "If Shakespeare wrote a meet-cute, it would probably start with a match this good.",
                "I am not going to quote Romeo at you, but I will say your profile stopped my scroll completely.",
                "You seem like someone who appreciates a well-timed entrance \u2014 so here I am.",
            ],
            "cheesy_lines": [
                "Are you a Shakespeare play? Because I am already invested in Act One and I need to know how this ends.",
                "Shall I compare thee to a summer's day? No, that has been done. But this match does feel kind of perfect.",
                "I think we just matched in iambic pentameter, because the rhythm already feels right.",
            ],
            "prefill_text": "Her bio: Shakespeare in the park and annotated sonnets. Write a witty opener that feels confident and playful.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes theater nights, old books, and sharp humor. She seems social and very articulate.",
        },
        {
            "slug": "jane-austen",
            "keyword": "Jane Austen",
            "h1": "The Best Jane Austen Pickup Lines (To Impress a Bookworm).",
            "title": "Best Jane Austen Pickup Lines | TryAgainText",
            "meta_description": "Use niche Jane Austen pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Jane Austen can make generic openers feel weak. These lines give you a stronger starting point by referencing Pride and Prejudice without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "You like Austen, so I know you can spot bad dialogue from a mile away \u2014 consider this my audition.",
                "Your profile has strong Elizabeth Bennet energy, which means I need to bring more than just a large estate.",
                "I was going to open with something generic, but your Pride and Prejudice reference demands better.",
            ],
            "flirty_lines": [
                "I am not Mr. Darcy, but I did re-read my opener three times before sending it to you.",
                "Something about someone who loves Austen and still keeps things effortlessly modern is really attractive.",
                "Your profile made me want to write something worth replying to \u2014 which is rare and you should know that.",
            ],
            "cheesy_lines": [
                "It is a truth universally acknowledged that a guy who matches with you must be in want of a great opener.",
                "Are you Pride and Prejudice? Because my first impression of your profile just keeps getting better.",
                "I think you just Darcyed me \u2014 I was not planning to catch feelings this early in the conversation.",
            ],
            "prefill_text": "Her bio: Pride and Prejudice forever, tea dates, and witty banter. Write a flirty opener that feels polished, not cheesy.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She loves period dramas and dry humor. She seems confident, smart, and selective.",
        },
        {
            "slug": "leo-tolstoy",
            "keyword": "Leo Tolstoy",
            "h1": "The Best Leo Tolstoy Pickup Lines (To Impress a Bookworm).",
            "title": "Best Leo Tolstoy Pickup Lines | TryAgainText",
            "meta_description": "Use niche Leo Tolstoy pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Leo Tolstoy can make generic openers feel weak. These lines give you a stronger starting point by referencing War and Peace without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "You read War and Peace for fun, so I know you have the patience for a conversation with actual depth.",
                "Tolstoy wrote that all happy families are alike \u2014 but your profile is genuinely one of a kind.",
                "If you can finish War and Peace, you can definitely handle my longest anecdote. Fair warning, it is a good one.",
            ],
            "flirty_lines": [
                "Someone who reads Tolstoy and still looks this relaxed in photos has a vibe I want to know more about.",
                "I would love to hear what pulled you into Russian lit \u2014 preferably somewhere with good coffee and no time limit.",
                "Your profile feels like the kind of person who makes a two-hour conversation feel like twenty minutes.",
            ],
            "cheesy_lines": [
                "Are you War and Peace? Because I started your profile thinking I would skim, and now I am fully committed.",
                "I came here for casual swiping and you just turned this into an epic love story. Very Tolstoy of you.",
                "Matching with you feels like the first chapter of something I will not want to put down.",
            ],
            "prefill_text": "Her bio: Tolstoy, museums, and long walks. Write a message that feels smart, warm, and low-pressure.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She reads Russian classics and likes philosophical chats. She also has travel photos and a calm vibe.",
        },
        {
            "slug": "franz-kafka",
            "keyword": "Franz Kafka",
            "h1": "The Best Franz Kafka Pickup Lines (To Impress a Bookworm).",
            "title": "Best Franz Kafka Pickup Lines | TryAgainText",
            "meta_description": "Use niche Franz Kafka pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Franz Kafka can make generic openers feel weak. These lines give you a stronger starting point by referencing The Trial without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "You like Kafka, so you already know that sometimes the most absurd situations lead somewhere interesting.",
                "Dating apps feel very Kafkaesque until you match with someone who actually has taste. So thanks for that.",
                "Your profile has The Trial energy \u2014 I do not fully understand what is happening, but I am compelled to keep going.",
            ],
            "flirty_lines": [
                "Someone who reads Kafka and still radiates warmth in photos is a combination I did not expect but really like.",
                "I would love to talk about existential dread with you over coffee. That sounded smoother in my head, but I stand by it.",
                "Your profile is the opposite of absurd \u2014 it is specific, interesting, and made me want to actually write something real.",
            ],
            "cheesy_lines": [
                "Are you The Metamorphosis? Because one look at your profile and I am a changed man.",
                "I woke up this morning as a regular guy on a dating app. Then I saw your profile. Very Kafka plot twist.",
                "Gregor Samsa turned into a bug. I just turned into someone who sends thoughtful first messages. You did that.",
            ],
            "prefill_text": "Her bio: Kafka, black coffee, and rainy city walks. Write a witty opener with subtle flirt energy.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes absurd humor and thoughtful books. She looks artsy and understated, not flashy.",
        },
        {
            "slug": "albert-camus",
            "keyword": "Albert Camus",
            "h1": "The Best Albert Camus Pickup Lines (To Impress a Bookworm).",
            "title": "Best Albert Camus Pickup Lines | TryAgainText",
            "meta_description": "Use niche Albert Camus pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Albert Camus can make generic openers feel weak. These lines give you a stronger starting point by referencing The Stranger without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "Camus said the only serious question is whether life is worth living. I say the only serious question is whether you will reply.",
                "You like The Stranger, so you probably appreciate someone who skips the performative small talk. Consider it skipped.",
                "Your profile has that Camus energy \u2014 effortlessly cool while clearly thinking about everything.",
            ],
            "flirty_lines": [
                "One must imagine Sisyphus happy, and I must imagine you saying yes to coffee with me.",
                "You read Camus and watch indie films, and somehow your profile still feels warmer than most. That is a rare thing.",
                "Something about how you put your profile together tells me a real conversation with you would be worth showing up for.",
            ],
            "cheesy_lines": [
                "Are you The Stranger? Because I cannot explain why I am so drawn to you, but I am not going to fight it.",
                "Camus said to live to the point of tears. Your profile just got me to the point of sending my best opener.",
                "I used to think life was absurd. Then I matched with you and suddenly it all makes sense.",
            ],
            "prefill_text": "Her bio: Camus, indie films, and ocean sunsets. Write an opener that is thoughtful but still flirty.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She seems introspective and stylish, with a calm personality. She likes meaningful conversation but hates forced intensity.",
        },
        {
            "slug": "gabriel-garcia-marquez",
            "keyword": "Gabriel Garcia Marquez",
            "h1": "The Best Gabriel Garcia Marquez Pickup Lines (To Impress a Bookworm).",
            "title": "Best Gabriel Garcia Marquez Pickup Lines | TryAgainText",
            "meta_description": "Use niche Gabriel Garcia Marquez pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Gabriel Garcia Marquez can make generic openers feel weak. These lines give you a stronger starting point by referencing One Hundred Years of Solitude without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "You like Marquez, so you understand that the best stories blur the line between real and magic. This match might qualify.",
                "One Hundred Years of Solitude is a lot of patience for one book. I just need you to have enough for one coffee date.",
                "Your profile has magical realism energy \u2014 everything looks normal on the surface, but something about it feels extraordinary.",
            ],
            "flirty_lines": [
                "Marquez wrote about love that spans generations. I would settle for love that spans a really good first date with you.",
                "Someone who reads Marquez and writes like that in their bio is the kind of person I actually want to get to know.",
                "Your profile reminds me why Marquez said the heart has more rooms than a hotel. You just opened a new one.",
            ],
            "cheesy_lines": [
                "Are you One Hundred Years of Solitude? Because I have been waiting a very long time for a match this good.",
                "Marquez made butterflies a symbol of love. You just made my stomach full of them.",
                "I think you just proved magical realism is real, because matching with you feels like something out of a Marquez novel.",
            ],
            "prefill_text": "Her bio: Marquez, flowers, and handwritten notes. Write a poetic opener that still feels modern and easy to reply to.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes magical realism and travel photography. She seems warm, artistic, and thoughtful.",
        },
        {
            "slug": "virginia-woolf",
            "keyword": "Virginia Woolf",
            "h1": "The Best Virginia Woolf Pickup Lines (To Impress a Bookworm).",
            "title": "Best Virginia Woolf Pickup Lines | TryAgainText",
            "meta_description": "Use niche Virginia Woolf pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Virginia Woolf can make generic openers feel weak. These lines give you a stronger starting point by referencing To the Lighthouse without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "You like Virginia Woolf, so I know you notice the details most people scroll right past. No pressure on me at all.",
                "Woolf could turn a single afternoon into a masterpiece. Your profile did something similar in about six photos.",
                "A room of one's own is great, but I think a table for two with you might be even better.",
            ],
            "flirty_lines": [
                "Someone who reads Woolf and takes photos like that has a way of seeing the world I would really like to hear about.",
                "Your profile has this calm, observant warmth \u2014 like the best parts of To the Lighthouse without the existential crisis.",
                "I get the feeling a real conversation with you would be the kind where time disappears. I am into that.",
            ],
            "cheesy_lines": [
                "Are you To the Lighthouse? Because I keep coming back to your profile and noticing something new every time.",
                "Virginia Woolf wrote in streams of consciousness. You just gave me a stream of interest.",
                "I was going to play it cool, but your Woolf reference made me want to be honest \u2014 your profile is beautiful.",
            ],
            "prefill_text": "Her bio: Virginia Woolf, sea air, and long bookstore afternoons. Write an opener that is elegant, warm, and low pressure.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes modernist literature and calm settings. She seems reflective, creative, and emotionally intelligent.",
        },
        {
            "slug": "oscar-wilde",
            "keyword": "Oscar Wilde",
            "h1": "The Best Oscar Wilde Pickup Lines (To Impress a Bookworm).",
            "title": "Best Oscar Wilde Pickup Lines | TryAgainText",
            "meta_description": "Use niche Oscar Wilde pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Oscar Wilde can make generic openers feel weak. These lines give you a stronger starting point by referencing The Picture of Dorian Gray without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "Wilde said he could resist everything except temptation. Your profile just proved his point.",
                "You quote Oscar Wilde, which means your standards for wit are dangerously high. Challenge accepted.",
                "If Dorian Gray had a dating profile, it would not be half as interesting as yours. And his was literally magic.",
            ],
            "flirty_lines": [
                "Someone who loves Wilde and has that much style clearly knows what they want. I like that a lot.",
                "Your profile has this sharp, playful confidence that makes me want to bring my A-game to every message.",
                "Oscar Wilde made being charming look effortless. You are doing the same thing right now.",
            ],
            "cheesy_lines": [
                "Are you The Picture of Dorian Gray? Because your profile just gets better the longer I look at it.",
                "Wilde said to be yourself because everyone else is taken. Well, I would really like the taken version to be taken by me.",
                "I can resist everything except temptation \u2014 and your profile is extremely tempting.",
            ],
            "prefill_text": "Her bio: Oscar Wilde quotes, galleries, and late-night espresso. Write a witty opener with stylish flirt energy.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes sharp humor and fashion-forward photos. She seems bold, social, and playful.",
        },
        {
            "slug": "ernest-hemingway",
            "keyword": "Ernest Hemingway",
            "h1": "The Best Ernest Hemingway Pickup Lines (To Impress a Bookworm).",
            "title": "Best Ernest Hemingway Pickup Lines | TryAgainText",
            "meta_description": "Use niche Ernest Hemingway pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Ernest Hemingway can make generic openers feel weak. These lines give you a stronger starting point by referencing The Sun Also Rises without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "Hemingway kept it short. So will I: your profile is great and I want to buy you a drink.",
                "You like Hemingway, so you know the best things are said with the fewest words. Here is mine \u2014 let's meet.",
                "The Sun Also Rises, and so did my expectations when I read your profile.",
            ],
            "flirty_lines": [
                "Hemingway wrote about people who lived fully and loved recklessly. Your profile gives me that same energy.",
                "Someone who reads Hemingway and takes road trips clearly knows how to make life interesting. I am intrigued.",
                "Your profile is direct, confident, and a little adventurous \u2014 basically everything Hemingway would approve of.",
            ],
            "cheesy_lines": [
                "Are you The Old Man and the Sea? Because I am willing to put in serious effort for this catch.",
                "Hemingway said the world breaks everyone, but matching with you just put me back together.",
                "I came here for casual swiping and your profile turned this into A Moveable Feast.",
            ],
            "prefill_text": "Her bio: Hemingway, road trips, and black coffee. Write a direct opener that feels confident and grounded.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes minimalist writing and outdoor photos. Tone should be concise, calm, and masculine without being stiff.",
        },
        {
            "slug": "f-scott-fitzgerald",
            "keyword": "F. Scott Fitzgerald",
            "h1": "The Best F. Scott Fitzgerald Pickup Lines (To Impress a Bookworm).",
            "title": "Best F. Scott Fitzgerald Pickup Lines | TryAgainText",
            "meta_description": "Use niche F. Scott Fitzgerald pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves F. Scott Fitzgerald can make generic openers feel weak. These lines give you a stronger starting point by referencing The Great Gatsby without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "Gatsby threw entire parties hoping the right person would show up. I just swiped right. Much more efficient.",
                "You like Fitzgerald, so you know the difference between style and substance. Your profile has both.",
                "That green light at the end of the dock has nothing on the green dot that says you are online right now.",
            ],
            "flirty_lines": [
                "Fitzgerald wrote about people who light up a room. Your profile just did that to my entire phone screen.",
                "Jazz bars, city nights, and Gatsby in your bio \u2014 you clearly know how to make an evening memorable.",
                "Your profile has this effortless, golden-hour energy that makes me want to know the person behind it.",
            ],
            "cheesy_lines": [
                "Are you The Great Gatsby? Because I have been staring at your profile from across the app like a man with a dream.",
                "Fitzgerald said the test of a first-rate intelligence is holding two opposed ideas at once. Mine are 'play it cool' and 'message her immediately.'",
                "Old sport, I believe this match is the start of something extraordinary.",
            ],
            "prefill_text": "Her bio: Gatsby, jazz bars, and city nights. Write a stylish opener that feels romantic but not overdone.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She loves vintage style and literature references. She seems social, classy, and playful.",
        },
        {
            "slug": "george-orwell",
            "keyword": "George Orwell",
            "h1": "The Best George Orwell Pickup Lines (To Impress a Bookworm).",
            "title": "Best George Orwell Pickup Lines | TryAgainText",
            "meta_description": "Use niche George Orwell pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves George Orwell can make generic openers feel weak. These lines give you a stronger starting point by referencing Nineteen Eighty-Four without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "Big Brother is watching, but honestly, I have only been watching your profile. Slightly less dystopian.",
                "You like Orwell, so you already know that most of what people say is doublespeak. I will skip that part.",
                "In a world of thoughtcrime, your profile is the most dangerous thing on this app \u2014 genuinely interesting.",
            ],
            "flirty_lines": [
                "Someone who reads Orwell and still has a sense of humor about the world is exactly who I want to talk to.",
                "Your profile feels honest in a way that most profiles are not. That is very attractive and very Orwell-approved.",
                "I get the feeling you are the kind of person who makes sharp observations and then laughs about them. I want in.",
            ],
            "cheesy_lines": [
                "Are you Nineteen Eighty-Four? Because you have been living in my head rent-free since I saw your profile.",
                "Orwell warned us about surveillance, but I cannot stop checking if you have messaged me back.",
                "This is not a thoughtcrime \u2014 I genuinely think we would have an amazing first date.",
            ],
            "prefill_text": "Her bio: Orwell, politics podcasts, and dry humor. Write a smart opener that is flirty and concise.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes thoughtful conversation and current affairs. She seems witty, analytical, and confident.",
        },
        {
            "slug": "charles-dickens",
            "keyword": "Charles Dickens",
            "h1": "The Best Charles Dickens Pickup Lines (To Impress a Bookworm).",
            "title": "Best Charles Dickens Pickup Lines | TryAgainText",
            "meta_description": "Use niche Charles Dickens pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Charles Dickens can make generic openers feel weak. These lines give you a stronger starting point by referencing Great Expectations without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "It was the best of swipes, it was the worst of swipes \u2014 until yours. Yours was clearly the best.",
                "You like Dickens, so you appreciate a good character introduction. Here is mine: I come with great expectations.",
                "Your profile has more depth than a Dickens novel and it took me way less time to get invested.",
            ],
            "flirty_lines": [
                "Someone who reads Dickens and spends rainy days in cafes is exactly the kind of person I want to be across the table from.",
                "Your profile is warm, detailed, and makes me want to know the full story. Very Dickensian in the best way.",
                "I get the feeling you are the kind of person who makes a cold afternoon feel like the best day of the week.",
            ],
            "cheesy_lines": [
                "Are you Great Expectations? Because I opened your profile expecting nothing and now I am completely hooked.",
                "Please, sir, can I have some more \u2014 of your time, specifically?",
                "Dickens wrote serial novels that kept people coming back every week. Your profile just did the same thing to me.",
            ],
            "prefill_text": "Her bio: Dickens, rainy-day cafes, and museums. Write an opener that feels witty, warm, and timeless.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes classic novels and cozy city walks. She seems warm, articulate, and thoughtful.",
        },
        {
            "slug": "mark-twain",
            "keyword": "Mark Twain",
            "h1": "The Best Mark Twain Pickup Lines (To Impress a Bookworm).",
            "title": "Best Mark Twain Pickup Lines | TryAgainText",
            "meta_description": "Use niche Mark Twain pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Mark Twain can make generic openers feel weak. These lines give you a stronger starting point by referencing Adventures of Huckleberry Finn without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "Twain said the secret of getting ahead is getting started. So here I am, starting with my best material.",
                "You like Mark Twain, so you know that the funniest people are also the smartest. Your profile confirms that theory.",
                "Reports of interesting people on dating apps have been greatly exaggerated \u2014 until your profile showed up.",
            ],
            "flirty_lines": [
                "Someone who loves Twain and stand-up clearly has excellent taste in humor. I would love to make you laugh in person.",
                "Your profile has this easygoing confidence that makes me think a first date with you would be genuinely fun.",
                "Twain made adventure look effortless. Your weekend travel photos are doing the same thing right now.",
            ],
            "cheesy_lines": [
                "Are you Huckleberry Finn? Because I want to go on an adventure with you and see where the river takes us.",
                "Twain said truth is stranger than fiction. Matching with someone this interesting on a dating app proves it.",
                "I just rafted through a hundred profiles and yours is the only one worth stopping for. Very Huck Finn of me.",
            ],
            "prefill_text": "Her bio: Mark Twain, stand-up clips, and weekend travel. Write a witty opener that feels playful and easygoing.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes satire and lighthearted banter. She seems outgoing and fun, not overly formal.",
        },
        {
            "slug": "emily-bronte",
            "keyword": "Emily Bronte",
            "h1": "The Best Emily Bronte Pickup Lines (To Impress a Bookworm).",
            "title": "Best Emily Bronte Pickup Lines | TryAgainText",
            "meta_description": "Use niche Emily Bronte pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Emily Bronte can make generic openers feel weak. These lines give you a stronger starting point by referencing Wuthering Heights without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "You like Wuthering Heights, so you know that real chemistry usually comes with a little dramatic tension.",
                "Your profile has moor-at-midnight energy \u2014 dark, atmospheric, and impossible to look away from.",
                "Heathcliff had to wander the moors for years. I just had to swipe through this app. Slightly less dramatic, same energy.",
            ],
            "flirty_lines": [
                "Someone who loves Emily Bronte and rain playlists is exactly the kind of person I want to share a quiet evening with.",
                "Your profile has this moody warmth that makes me think a real conversation with you would feel like a good novel.",
                "I do not need Wuthering Heights drama \u2014 but I would not mind getting lost in a long conversation with you.",
            ],
            "cheesy_lines": [
                "Are you Wuthering Heights? Because I am haunted by your profile and I am not even mad about it.",
                "Heathcliff said 'I cannot live without my soul.' I am saying I cannot scroll past without messaging you.",
                "You just turned my casual swiping session into a gothic romance. I did not see that coming.",
            ],
            "prefill_text": "Her bio: Emily Bronte, rain playlists, and black tea. Write an opener that feels romantic and poetic but still modern.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes gothic romance and atmospheric photography. She seems introspective and emotionally expressive.",
        },
        {
            "slug": "victor-hugo",
            "keyword": "Victor Hugo",
            "h1": "The Best Victor Hugo Pickup Lines (To Impress a Bookworm).",
            "title": "Best Victor Hugo Pickup Lines | TryAgainText",
            "meta_description": "Use niche Victor Hugo pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Victor Hugo can make generic openers feel weak. These lines give you a stronger starting point by referencing Les Miserables without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "You like Les Mis, so you know the best stories are about people who refuse to give up. Consider this my opening act.",
                "Victor Hugo wrote 1,400 pages when he had something to say. I will keep it shorter, but the enthusiasm is the same.",
                "Your profile has the emotional range of a Hugo novel \u2014 warm, dramatic, and completely compelling.",
            ],
            "flirty_lines": [
                "Someone who loves Hugo and goes to the theater is the kind of person who actually feels things deeply. That is attractive.",
                "Your profile made me want to write something real instead of copy-pasting the same line I send everyone. You deserve that.",
                "Do you hear the people sing? No, but I hear myself rehearsing what to say on a first date with you.",
            ],
            "cheesy_lines": [
                "Are you Les Miserables? Because I am emotionally invested and we have not even had our first conversation yet.",
                "Victor Hugo made Paris romantic. You just made this dating app romantic. Equally impressive.",
                "One more day \u2014 that is all I need to think of the perfect second message. But the first one is: hi, you are amazing.",
            ],
            "prefill_text": "Her bio: Victor Hugo, architecture walks, and theater nights. Write a warm opener with strong romantic subtext.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes French classics and dramatic storytelling. She seems empathetic, artistic, and confident.",
        },
        {
            "slug": "marcel-proust",
            "keyword": "Marcel Proust",
            "h1": "The Best Marcel Proust Pickup Lines (To Impress a Bookworm).",
            "title": "Best Marcel Proust Pickup Lines | TryAgainText",
            "meta_description": "Use niche Marcel Proust pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Marcel Proust can make generic openers feel weak. These lines give you a stronger starting point by referencing In Search of Lost Time without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "You like Proust, so you understand that the smallest details can mean everything. I noticed yours.",
                "Proust wrote seven volumes about memory and time. I am writing one message about you, and it already feels significant.",
                "In Search of Lost Time \u2014 or in my case, in search of someone who actually reads Proust. Found you.",
            ],
            "flirty_lines": [
                "Someone who reads Proust and loves slow Sundays clearly knows that the best things are not rushed. I appreciate that.",
                "Your profile has this quiet elegance that made me pause and actually think about what to say. That never happens.",
                "Proust found meaning in a madeleine. I found something interesting in your profile. Both feel like a good sign.",
            ],
            "cheesy_lines": [
                "Are you In Search of Lost Time? Because I just lost twenty minutes reading your profile and I do not want them back.",
                "Proust dipped a cookie in tea and remembered everything. I saw your profile and forgot everyone else.",
                "They say you can not get lost time back, but matching with you makes up for every bad date I have ever had.",
            ],
            "prefill_text": "Her bio: Proust, pastries, and slow Sundays. Write a thoughtful opener that feels intimate but light.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes literary cafes and reflective writing. She seems subtle, elegant, and emotionally intelligent.",
        },
        {
            "slug": "james-joyce",
            "keyword": "James Joyce",
            "h1": "The Best James Joyce Pickup Lines (To Impress a Bookworm).",
            "title": "Best James Joyce Pickup Lines | TryAgainText",
            "meta_description": "Use niche James Joyce pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves James Joyce can make generic openers feel weak. These lines give you a stronger starting point by referencing Ulysses without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "You like Joyce, so you already know that the most interesting journeys happen in a single day. Let's start ours.",
                "Ulysses is one long day in Dublin. This is one great match on my phone. Both deserve serious attention.",
                "Your profile has stream-of-consciousness energy \u2014 every detail flows into the next and all of it is interesting.",
            ],
            "flirty_lines": [
                "Someone who reads Joyce and walks cities for fun clearly pays attention to the world. I find that really attractive.",
                "Your profile has this smart, artistic warmth that makes me want to skip the small talk and go straight to something real.",
                "Joyce said yes I said yes I will Yes \u2014 and honestly, that is how I felt when I saw we matched.",
            ],
            "cheesy_lines": [
                "Are you Ulysses? Because everyone says you are incredible and I am ready to commit the time to prove it.",
                "Joyce spent seventeen years writing Ulysses. I spent seventeen seconds on your profile and I am already a fan.",
                "Bloomsday is once a year. Matching with you feels like a holiday I want to celebrate immediately.",
            ],
            "prefill_text": "Her bio: James Joyce, city walks, and independent cinemas. Write a clever opener that feels modern and playful.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes modernist literature and urban culture. She seems witty, artistic, and socially confident.",
        },
        {
            "slug": "homer",
            "keyword": "Homer",
            "h1": "The Best Homer Pickup Lines (To Impress a Bookworm).",
            "title": "Best Homer Pickup Lines | TryAgainText",
            "meta_description": "Use niche Homer pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Homer can make generic openers feel weak. These lines give you a stronger starting point by referencing The Odyssey without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "Odysseus took ten years to get home. I took ten seconds to message you. I think my quest is going better.",
                "You like Homer, so you know that every great journey starts with leaving your comfort zone. This is me doing that.",
                "Your profile has Odyssey energy \u2014 adventurous, full of surprises, and worth every twist along the way.",
            ],
            "flirty_lines": [
                "Someone who loves Greek myths and hiking clearly lives for adventure. I would love to hear your best travel story.",
                "The Sirens tried to lure Odysseus off course. Your profile just did the same to my evening plans.",
                "Your profile has this fearless, curious energy that makes me want to plan something spontaneous with you.",
            ],
            "cheesy_lines": [
                "Are you The Odyssey? Because I have been on a long journey through this app and you feel like the destination.",
                "Odysseus had Penelope waiting at the end. I have your profile open and a message worth sending. Same energy.",
                "Homer wrote about heroes. Matching with you might be my origin story.",
            ],
            "prefill_text": "Her bio: Greek myths, museums, and hiking trips. Write an adventurous opener that feels fun and grounded.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes mythology and active weekends. She seems confident, curious, and energetic.",
        },
        {
            "slug": "dante-alighieri",
            "keyword": "Dante Alighieri",
            "h1": "The Best Dante Alighieri Pickup Lines (To Impress a Bookworm).",
            "title": "Best Dante Alighieri Pickup Lines | TryAgainText",
            "meta_description": "Use niche Dante Alighieri pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Dante Alighieri can make generic openers feel weak. These lines give you a stronger starting point by referencing The Divine Comedy without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "Dante walked through nine circles of hell. I walked through this entire dating app. Your profile is my Paradiso.",
                "You like Dante, so you understand that the best journeys have layers. This conversation is about to have a few.",
                "Abandon all hope, ye who enter here \u2014 unless you matched with someone who reads Dante. Then it gets interesting.",
            ],
            "flirty_lines": [
                "Dante had Beatrice as his guide to paradise. I just need you to guide me to a good first date.",
                "Someone who reads The Divine Comedy and likes candlelit dinners clearly has impeccable taste. I am impressed.",
                "Your profile has this quiet intensity that makes me want to say something real instead of something safe.",
            ],
            "cheesy_lines": [
                "Are you The Divine Comedy? Because reading your profile took me through every emotion and ended in paradise.",
                "Dante saw Beatrice and wrote an entire epic about her. I saw your profile and I am writing this message. Same inspiration.",
                "They say the path to paradise begins with a dark wood. Mine just started with a right swipe.",
            ],
            "prefill_text": "Her bio: Dante, art history, and candlelit dinners. Write an opener that feels cultured, playful, and romantic.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes classical literature and thoughtful conversation. She seems romantic, sophisticated, and witty.",
        },
        {
            "slug": "miguel-de-cervantes",
            "keyword": "Miguel de Cervantes",
            "h1": "The Best Miguel de Cervantes Pickup Lines (To Impress a Bookworm).",
            "title": "Best Miguel de Cervantes Pickup Lines | TryAgainText",
            "meta_description": "Use niche Miguel de Cervantes pickup lines that feel witty, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Matching with someone who loves Miguel de Cervantes can make generic openers feel weak. These lines give you a stronger starting point by referencing Don Quixote without sounding forced. Use one as a base, then personalize with details from her profile.",
            "witty_lines": [
                "Don Quixote charged at windmills thinking they were giants. I am charging into your DMs thinking this could be great.",
                "You like Cervantes, so you appreciate someone who commits fully to a bit. Watch me commit to this opener.",
                "Your profile has that rare mix of idealism and sarcasm \u2014 like Don Quixote with better self-awareness.",
            ],
            "flirty_lines": [
                "Someone who reads Don Quixote and keeps travel journals is clearly living a life worth hearing about.",
                "Cervantes wrote about chasing impossible dreams. Messaging someone this interesting on a dating app might qualify.",
                "Your profile makes me want to be more adventurous \u2014 starting with actually sending a message that is worth your time.",
            ],
            "cheesy_lines": [
                "Are you Don Quixote? Because I am about to go on a wildly ambitious quest to get a reply from you.",
                "Every Don Quixote needs a Sancho Panza. I am applying for the position of your adventure sidekick.",
                "Cervantes proved that the best stories come from people who dream big. Matching with you feels like the start of one.",
            ],
            "prefill_text": "Her bio: Don Quixote, travel journals, and playful sarcasm. Write a witty opener that feels adventurous and sincere.",
            "upload_hint": "Upload a screenshot of her full profile so the opener matches her actual vibe, not just one keyword.",
            "her_info_prefill": "She likes satire and travel-themed stories. She seems lively, curious, and easy to joke with.",
        },
    ],
}
