DATA = {
    "category_slug": "love-languages",
    "category_name": "Love Languages",
    "sort_order": 10,
    "topics": [
        {
            "slug": "words-of-affirmation",
            "keyword": "Words of Affirmation",
            "h1": "The Best Words of Affirmation Pickup Lines (For When She Needs to Hear It).",
            "title": "Best Words of Affirmation Pickup Lines | TryAgainText",
            "meta_description": "Use niche words of affirmation pickup lines that feel genuine, verbal, and genuinely complimentary. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If her love language is words of affirmation, she needs to hear that she is valued and noticed. Empty compliments do not work. These lines are specific and genuine.",
            "witty_lines": [
                "Your profile tells me exactly how you see yourself and I want to tell you what I see.",
                "I could scroll past but I actually want you to know that you stand out.",
                "You seem like someone who appreciates being told the truth and I think you are exceptional.",
            ],
            "flirty_lines": [
                "I want to tell you directly — you are genuinely one of the most interesting profiles I have seen.",
                "Something about your energy tells me you need to hear good things and I will say them.",
                "You deserve to know how exceptional you are and I am going to make sure you do.",
            ],
            "cheesy_lines": [
                "Are you words of affirmation? Because I have so many beautiful things to tell you.",
                "Your profile makes me want to say all the kind things you probably need to hear.",
                "I promise to tell you every good thing I think about you.",
            ],
            "prefill_text": "Her love language is words of affirmation. Write an opener that is genuinely complimentary and specific.",
            "upload_hint": "Upload a screenshot of her profile so the compliments are actually personalized, not generic.",
            "her_info_prefill": "Her love language is words of affirmation. Needs to hear genuine compliments and affection.",
        },
        {
            "slug": "acts-of-service",
            "keyword": "Acts of Service",
            "h1": "The Best Acts of Service Pickup Lines (For When She Appreciates You Showing Up).",
            "title": "Best Acts of Service Pickup Lines | TryAgainText",
            "meta_description": "Use niche acts of service pickup lines that feel practical, reliable, and genuinely helpful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If her love language is acts of service, she does not need pretty words. She needs someone who shows up and helps. These lines promise action.",
            "witty_lines": [
                "Your profile tells me you are someone who appreciates actions over words and I respect that.",
                "I can tell you are the type who notices when someone actually shows up and does things.",
                "You seem like someone who would rather have reliable help than empty promises.",
            ],
            "flirty_lines": [
                "I want to be the kind of person who does things for you without being asked.",
                "Something about your energy tells me you need someone present and practical. I can be that.",
                "You deserve someone who shows up, helps out, and makes your life easier.",
            ],
            "cheesy_lines": [
                "Are you acts of service? Because I am ready to help with literally anything.",
                "Your profile tells me you are looking for someone reliable and I promise to be that.",
                "Let me handle things for you — that is how I show I care.",
            ],
            "prefill_text": "Her love language is acts of service. Write an opener that promises genuine help and reliability.",
            "upload_hint": "Upload a screenshot of her profile so the offer to help is actually relevant.",
            "her_info_prefill": "Her love language is acts of service. Appreciates reliable help and people who show up.",
        },
        {
            "slug": "gift-giving",
            "keyword": "Gift Giving",
            "h1": "The Best Gift Giving Pickup Lines (For When She Notices the Thoughtful Touches).",
            "title": "Best Gift Giving Pickup Lines | TryAgainText",
            "meta_description": "Use niche gift giving pickup lines that feel thoughtful, personal, and intentional. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If her love language is gift giving, she notices thoughtfulness and cherishes meaning. A gift that shows you paid attention is worth more than generic words.",
            "witty_lines": [
                "Your profile tells me you notice when people put thought into things.",
                "I can tell you are the type who appreciates intentionality and I want to give you that.",
                "You seem like someone who values gifts that actually mean something.",
            ],
            "flirty_lines": [
                "I want to be the person who gives you gifts that actually make you smile.",
                "Something about your energy tells me thoughtful gestures matter and I am ready to make them.",
                "You deserve to feel remembered and I want to be someone who shows that.",
            ],
            "cheesy_lines": [
                "Are you gift giving? Because I already know the first gift will be flowers and conversation.",
                "Your profile tells me you deserve someone who remembers the small things.",
                "Let me spoil you with gifts that actually mean something.",
            ],
            "prefill_text": "Her love language is gift giving. Write an opener that shows you think about thoughtful gestures.",
            "upload_hint": "Upload a screenshot of her profile so the gift sentiment is actually personalized.",
            "her_info_prefill": "Her love language is gift giving. Notices thoughtfulness and cherishes meaningful gestures.",
        },
        {
            "slug": "quality-time",
            "keyword": "Quality Time",
            "h1": "The Best Quality Time Pickup Lines (For When She Needs Your Full Attention).",
            "title": "Best Quality Time Pickup Lines | TryAgainText",
            "meta_description": "Use niche quality time pickup lines that feel present, focused, and genuinely engaged. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If her love language is quality time, she wants your undivided attention and genuine presence. Scrolling while together will not cut it. These lines promise real connection.",
            "witty_lines": [
                "Your profile tells me you are someone who wants real time together, not just parallel existence.",
                "I can tell you are the type who needs actual presence and I am genuinely interested.",
                "You seem like someone who values being fully seen and understood.",
            ],
            "flirty_lines": [
                "I want to be someone who actually looks at you when you talk, not just waits for my turn.",
                "Something about your energy tells me you need someone fully present. I can do that.",
                "You deserve all my attention and I promise to give it to you.",
            ],
            "cheesy_lines": [
                "Are you quality time? Because I could look at your profile forever.",
                "Your profile tells me you are worth my undivided attention.",
                "I promise to put my phone down and actually be with you.",
            ],
            "prefill_text": "Her love language is quality time. Write an opener that promises genuine presence and engagement.",
            "upload_hint": "Upload a screenshot of her profile so the promise to spend time together feels real.",
            "her_info_prefill": "Her love language is quality time. Needs undivided attention and genuine presence.",
        },
        {
            "slug": "physical-touch",
            "keyword": "Physical Touch",
            "h1": "The Best Physical Touch Pickup Lines (For When She Needs the Physical Connection).",
            "title": "Best Physical Touch Pickup Lines | TryAgainText",
            "meta_description": "Use niche physical touch pickup lines that feel warm, sensual, and tactile. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If her love language is physical touch, she expresses and receives love through contact. Warmth, hugs, and intimacy are her dialects. These lines match that sensuality.",
            "witty_lines": [
                "Your profile tells me you are someone who feels through touch and I am very into that.",
                "I can tell you are the type who needs physical affection and connection.",
                "You seem like someone who expresses love through touch and I appreciate that deeply.",
            ],
            "flirty_lines": [
                "I want to be the kind of person who knows exactly how you like to be held.",
                "Something about your energy tells me you crave the physical closeness and I am ready for it.",
                "You deserve someone who touches you like you matter, because you do.",
            ],
            "cheesy_lines": [
                "Are you physical touch? Because I cannot wait to hold your hand.",
                "Your profile tells me we would have incredible chemistry in person.",
                "I promise to touch you like you are someone I cannot let go of.",
            ],
            "prefill_text": "Her love language is physical touch. Write an opener that feels warm, sensual, and tactile.",
            "upload_hint": "Upload a screenshot of her profile so the physical intimacy promise feels genuine.",
            "her_info_prefill": "Her love language is physical touch. Needs physical affection and tactile connection.",
        },
    ],
}
