DATA = {
    "category_slug": "mbti",
    "category_name": "MBTI Personality Types",
    "sort_order": 2,
    "topics": [
        {
            "slug": "intj",
            "keyword": "INTJ",
            "h1": "The Best INTJ Pickup Lines (For the Mastermind Type).",
            "title": "Best INTJ Pickup Lines | TryAgainText",
            "meta_description": "Use niche INTJ pickup lines that feel strategic, witty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "INTJs value competence, depth, and efficiency. They see through generic flattery instantly. These lines show you can think on her level without being try-hard about it.",
            "witty_lines": [
                "Your profile is so well-optimized it feels like you A/B tested it. I respect the strategy.",
                "I can tell you are an INTJ because your bio says more in two sentences than most people say in ten.",
                "You seem like someone who already has a mental framework for evaluating first messages. I hope this one scores well.",
            ],
            "flirty_lines": [
                "Something about someone who is clearly brilliant and still chooses to be on a dating app is very appealing to me.",
                "Your profile has this quiet intensity that makes me want to earn a real conversation with you.",
                "I like that you do not waste words. It makes me think every word you do say actually matters.",
            ],
            "cheesy_lines": [
                "Are you an INTJ? Because you just strategically captured my full attention.",
                "They say INTJs plan everything. Please tell me you planned for this match.",
                "I must be a well-structured argument, because you seem like the type who would actually appreciate one.",
            ],
            "prefill_text": "Her bio mentions INTJ or Mastermind energy. Write a sharp, efficient opener that respects her intelligence.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an INTJ. Her profile is concise and intentional. She seems analytical, independent, and confident.",
        },
        {
            "slug": "intp",
            "keyword": "INTP",
            "h1": "The Best INTP Pickup Lines (For the Thinker Type).",
            "title": "Best INTP Pickup Lines | TryAgainText",
            "meta_description": "Use niche INTP pickup lines that feel curious, clever, and intellectually playful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "INTPs love ideas, systems, and genuine curiosity. They would rather debate a fascinating question than receive a compliment. These lines engage her mind first.",
            "witty_lines": [
                "Your profile raises more interesting questions than it answers, and I mean that as the highest compliment.",
                "I can tell you are an INTP because your bio feels like the opening paragraph of something I want to keep reading.",
                "You seem like someone who has a take on everything and is waiting for someone smart enough to ask.",
            ],
            "flirty_lines": [
                "There is something genuinely attractive about someone who thinks deeply and still keeps things light. Your profile does that.",
                "Your curiosity is showing and honestly it is one of the most appealing things about your profile.",
                "I get the feeling a real conversation with you would make me smarter. That is a rare quality.",
            ],
            "cheesy_lines": [
                "Are you an INTP? Because my brain just generated a hundred theories about you and I need data.",
                "They say INTPs live in their heads. Can I get a visitor pass?",
                "You just turned my casual swiping into a full research project. I am not complaining.",
            ],
            "prefill_text": "Her bio mentions INTP or analytical/curious energy. Write a curious, intellectually engaging opener.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an INTP. Her profile has quirky, intellectual references. She seems curious, independent, and quietly funny.",
        },
        {
            "slug": "entj",
            "keyword": "ENTJ",
            "h1": "The Best ENTJ Pickup Lines (For the Commander Type).",
            "title": "Best ENTJ Pickup Lines | TryAgainText",
            "meta_description": "Use niche ENTJ pickup lines that feel confident, direct, and impressive. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "ENTJs respect ambition, directness, and people who can hold their own. Timid openers get ignored. These lines match her commanding energy with genuine confidence.",
            "witty_lines": [
                "Your profile has CEO energy and I am here to pitch myself as worth your time.",
                "I can tell you are an ENTJ because your bio reads like a mission statement and I am ready to align.",
                "You seem like someone who runs meetings, conversations, and dating apps with equal authority.",
            ],
            "flirty_lines": [
                "I respect someone who knows what she wants. Your profile makes that very clear and it is attractive.",
                "Your confidence is not subtle and I like that. It makes me want to bring my best.",
                "Something tells me a first date with you would feel like the best interview I have ever had.",
            ],
            "cheesy_lines": [
                "Are you an ENTJ? Because you just took command of my entire attention span.",
                "They say ENTJs are natural leaders. Lead me to coffee and I will follow.",
                "Your profile just reorganized my priorities. You are now at the top.",
            ],
            "prefill_text": "Her bio mentions ENTJ or boss/leader energy. Write a confident, direct opener that does not waste her time.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an ENTJ. Her profile is bold and ambitious. She seems driven, confident, and direct.",
        },
        {
            "slug": "entp",
            "keyword": "ENTP",
            "h1": "The Best ENTP Pickup Lines (For the Debater Type).",
            "title": "Best ENTP Pickup Lines | TryAgainText",
            "meta_description": "Use niche ENTP pickup lines that feel sharp, playful, and intellectually stimulating. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "ENTPs thrive on wit, debate, and mental sparring. They get bored by predictable messages. These lines start the verbal chess match she actually wants.",
            "witty_lines": [
                "Your profile has strong 'I will play devil's advocate for fun' energy and I am absolutely here for it.",
                "I can tell you are an ENTP because your bio is simultaneously charming and slightly provocative.",
                "You seem like someone who turns every conversation into the most interesting one in the room.",
            ],
            "flirty_lines": [
                "Your energy is playful and sharp and honestly that combination is dangerously attractive.",
                "I like that your profile keeps me on my toes. Predictable is boring and you are clearly not that.",
                "Something tells me flirting with you is a sport. I am ready to compete.",
            ],
            "cheesy_lines": [
                "Are you an ENTP? Because you just started a debate in my head about whether to play it cool or message you immediately.",
                "They say ENTPs argue for fun. I would love to argue over dinner about who pays.",
                "Your profile just challenged every assumption I had about dating apps. Well played.",
            ],
            "prefill_text": "Her bio mentions ENTP or debater energy. Write a sharp, playful opener that invites banter.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an ENTP. Her profile is witty and provocative. She seems quick, playful, and intellectually competitive.",
        },
        {
            "slug": "infj",
            "keyword": "INFJ",
            "h1": "The Best INFJ Pickup Lines (For the Rarest Type).",
            "title": "Best INFJ Pickup Lines | TryAgainText",
            "meta_description": "Use niche INFJ pickup lines that feel deep, genuine, and emotionally intelligent. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "INFJs are rare, intuitive, and deeply values-driven. They can sense inauthenticity immediately. These lines are sincere, specific, and emotionally tuned in.",
            "witty_lines": [
                "Your profile has this quiet depth that makes me think you understand people better than they understand themselves.",
                "I can tell you are an INFJ because your bio feels carefully chosen, like every word was placed with intention.",
                "You seem like someone who is selective about who gets her time. I hope this message earns some of it.",
            ],
            "flirty_lines": [
                "There is something magnetic about someone who is clearly perceptive and still warm. Your profile has both.",
                "I like that your profile feels real. It makes me want to skip the surface-level stuff entirely.",
                "Your energy is the kind that makes people feel understood. That is a genuinely rare and attractive quality.",
            ],
            "cheesy_lines": [
                "Are you an INFJ? Because you just read my soul through a dating app and I was not prepared.",
                "They say INFJs are the rarest type. Matching with you just proved that theory.",
                "Your profile has more emotional intelligence than most novels I have read. I am genuinely impressed.",
            ],
            "prefill_text": "Her bio mentions INFJ or mentions being rare/intuitive. Write a sincere, emotionally intelligent opener.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an INFJ. Her profile is thoughtful and values-driven. She seems intuitive, warm, and deeply selective.",
        },
        {
            "slug": "infp",
            "keyword": "INFP",
            "h1": "The Best INFP Pickup Lines (For the Dreamer Type).",
            "title": "Best INFP Pickup Lines | TryAgainText",
            "meta_description": "Use niche INFP pickup lines that feel creative, heartfelt, and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "INFPs are idealistic, creative, and deeply feeling. They want authenticity over polish. These lines come from the heart without being overwhelming.",
            "witty_lines": [
                "Your profile feels like it was written by someone who journals and I mean that as the best possible compliment.",
                "I can tell you are an INFP because your bio has more soul than most people's entire online presence.",
                "You seem like someone who finds meaning in small moments. Here is a small moment: I really liked your profile.",
            ],
            "flirty_lines": [
                "There is something beautiful about someone who is clearly creative and still grounded. Your profile radiates that.",
                "Your profile made me pause and think about what to say. That almost never happens and it says a lot about you.",
                "I like that your energy is gentle and still interesting. That combination is incredibly attractive.",
            ],
            "cheesy_lines": [
                "Are you an INFP? Because you just made me feel things from a dating app profile and I was not ready.",
                "They say INFPs are dreamers. You just showed up in mine.",
                "Your profile reads like my favorite song \u2014 I want to experience it again from the beginning.",
            ],
            "prefill_text": "Her bio mentions INFP or dreamer/creative energy. Write a heartfelt, genuine opener that feels personal.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an INFP. Her profile is creative and expressive. She seems idealistic, warm, and emotionally authentic.",
        },
        {
            "slug": "enfj",
            "keyword": "ENFJ",
            "h1": "The Best ENFJ Pickup Lines (For the Protagonist Type).",
            "title": "Best ENFJ Pickup Lines | TryAgainText",
            "meta_description": "Use niche ENFJ pickup lines that feel warm, engaging, and socially aware. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "ENFJs are natural connectors who light up every room they enter. They appreciate sincerity and people who show up fully. These lines match her warm, outgoing energy.",
            "witty_lines": [
                "Your profile radiates the energy of someone who makes everyone around her feel important. That is a real gift.",
                "I can tell you are an ENFJ because your bio somehow made me feel welcomed before we even matched.",
                "You seem like the person everyone goes to for advice and that makes me want your take on whether I should send this message. Too late.",
            ],
            "flirty_lines": [
                "Your warmth comes through even in photos. I would love to experience that in a real conversation.",
                "I like that your energy is both confident and caring. That combination is rare and very attractive.",
                "Something about your profile makes me think you are the kind of person who turns strangers into friends in minutes.",
            ],
            "cheesy_lines": [
                "Are you an ENFJ? Because you just inspired me to write the best opener I have ever sent.",
                "They say ENFJs are natural protagonists. You just became the main character of my match list.",
                "Your profile has so much positive energy it should come with a warning label.",
            ],
            "prefill_text": "Her bio mentions ENFJ or warm leader energy. Write an engaging, sincere opener that matches her social warmth.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an ENFJ. Her photos show her surrounded by friends. She seems warm, charismatic, and socially confident.",
        },
        {
            "slug": "enfp",
            "keyword": "ENFP",
            "h1": "The Best ENFP Pickup Lines (For the Campaigner Type).",
            "title": "Best ENFP Pickup Lines | TryAgainText",
            "meta_description": "Use niche ENFP pickup lines that feel enthusiastic, creative, and spontaneous. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "ENFPs are enthusiastic, imaginative, and endlessly curious. They want someone who can match their energy and keep things interesting. Boring openers need not apply.",
            "witty_lines": [
                "Your profile has the energy of someone who started three creative projects this week and finished one beautifully.",
                "I can tell you are an ENFP because your bio made me smile, think, and want to message you all in about five seconds.",
                "You seem like someone who could make a trip to the grocery store feel like an adventure.",
            ],
            "flirty_lines": [
                "Your enthusiasm is infectious and I mean that literally \u2014 I am now enthusiastic about messaging you.",
                "I like that your profile feels spontaneous and real. That kind of energy is genuinely magnetic.",
                "Something about your vibe makes me think a conversation with you could go anywhere and I would enjoy every second.",
            ],
            "cheesy_lines": [
                "Are you an ENFP? Because you just sparked about seventeen different conversation ideas in my head.",
                "They say ENFPs see potential in everything. I see potential in this match and I think you do too.",
                "Your profile is a whole mood and that mood is 'best first date ever.'",
            ],
            "prefill_text": "Her bio mentions ENFP or creative/spontaneous energy. Write an enthusiastic, fun opener that matches her vibe.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an ENFP. Her profile is colorful and enthusiastic. She seems creative, curious, and full of energy.",
        },
        {
            "slug": "istj",
            "keyword": "ISTJ",
            "h1": "The Best ISTJ Pickup Lines (For the Inspector Type).",
            "title": "Best ISTJ Pickup Lines | TryAgainText",
            "meta_description": "Use niche ISTJ pickup lines that feel reliable, genuine, and grounded. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "ISTJs value reliability, honesty, and follow-through. Flashy or vague openers will not impress her. These lines are direct, genuine, and demonstrate real effort.",
            "witty_lines": [
                "Your profile is straightforward, well-organized, and tells me exactly what I need to know. I appreciate that more than you think.",
                "I can tell you are an ISTJ because your bio feels like it was proofread twice and that is honestly attractive.",
                "You seem like someone who values actions over words. So consider this message step one of many.",
            ],
            "flirty_lines": [
                "I like that your profile is honest and grounded. It makes me want to match that energy with something real.",
                "You give off the vibe of someone who follows through on plans. Dinner, Saturday, you pick the place?",
                "Something about your profile tells me you are dependable in the best way. That is genuinely attractive.",
            ],
            "cheesy_lines": [
                "Are you an ISTJ? Because you just organized my chaotic dating life into something that makes sense.",
                "They say ISTJs are the backbone of everything. You just became the backbone of my interest.",
                "Your profile is the most reliable thing I have found on this app and I am not letting it go.",
            ],
            "prefill_text": "Her bio mentions ISTJ or responsible/reliable energy. Write a grounded, straightforward opener.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an ISTJ. Her profile is clear and no-nonsense. She seems dependable, honest, and grounded.",
        },
        {
            "slug": "isfj",
            "keyword": "ISFJ",
            "h1": "The Best ISFJ Pickup Lines (For the Defender Type).",
            "title": "Best ISFJ Pickup Lines | TryAgainText",
            "meta_description": "Use niche ISFJ pickup lines that feel warm, considerate, and sincere. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "ISFJs are caring, loyal, and thoughtful. They appreciate when someone notices the effort they put into things. These lines show genuine warmth and attention to detail.",
            "witty_lines": [
                "Your profile has the energy of someone who remembers birthdays, checks on friends, and still somehow looks this good. Impressive.",
                "I can tell you are an ISFJ because your profile feels carefully curated in a way that is warm, not calculated.",
                "You seem like someone who puts thought into everything she does. This message is me trying to do the same.",
            ],
            "flirty_lines": [
                "Your warmth comes through in every photo and it makes me want to be the kind of person who deserves a reply.",
                "I like that your profile feels genuine. It makes me think you are the kind of person who makes everyone feel at home.",
                "Something about your energy tells me a date with you would feel comfortable and exciting at the same time.",
            ],
            "cheesy_lines": [
                "Are you an ISFJ? Because you just made this entire app feel warmer.",
                "They say ISFJs take care of everyone. Who takes care of you? I am volunteering.",
                "Your profile is a safe space and I am moving in emotionally.",
            ],
            "prefill_text": "Her bio mentions ISFJ or caring/thoughtful energy. Write a warm, considerate opener that shows attention to detail.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an ISFJ. Her photos feel warm and genuine. She seems nurturing, loyal, and quietly confident.",
        },
        {
            "slug": "estj",
            "keyword": "ESTJ",
            "h1": "The Best ESTJ Pickup Lines (For the Executive Type).",
            "title": "Best ESTJ Pickup Lines | TryAgainText",
            "meta_description": "Use niche ESTJ pickup lines that feel direct, competent, and no-nonsense. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "ESTJs are organized, direct, and results-oriented. They do not have time for games or vague conversation starters. These lines get to the point with confidence.",
            "witty_lines": [
                "Your profile has the efficiency of someone who runs her life like a well-managed company. I am applying.",
                "I can tell you are an ESTJ because your bio is clear, direct, and somehow still charming.",
                "You seem like someone who appreciates when people get to the point. So here it is: I think we should talk.",
            ],
            "flirty_lines": [
                "I respect that your profile does not waste anyone's time. That kind of directness is really attractive.",
                "Your energy says you know exactly what you bring to the table. I would love a seat.",
                "I like that you are clearly competent and confident. It makes me want to step up my game.",
            ],
            "cheesy_lines": [
                "Are you an ESTJ? Because you just managed to capture my attention with executive-level precision.",
                "They say ESTJs are born leaders. Lead me to a first date and I will bring my best.",
                "Your profile runs smoother than most organizations I have worked for.",
            ],
            "prefill_text": "Her bio mentions ESTJ or executive/leader energy. Write a direct, confident opener that respects her time.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an ESTJ. Her profile is organized and assertive. She seems competent, direct, and socially confident.",
        },
        {
            "slug": "esfj",
            "keyword": "ESFJ",
            "h1": "The Best ESFJ Pickup Lines (For the Consul Type).",
            "title": "Best ESFJ Pickup Lines | TryAgainText",
            "meta_description": "Use niche ESFJ pickup lines that feel friendly, warm, and socially engaging. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "ESFJs are warm, sociable, and genuinely caring. They value harmony and authentic connection. These lines match her friendly energy with genuine warmth.",
            "witty_lines": [
                "Your profile has the energy of someone who knows everyone at the party and somehow makes each person feel special.",
                "I can tell you are an ESFJ because your photos radiate the kind of warmth that makes people want to be around you.",
                "You seem like the friend everyone relies on and the person I want to get to know for myself.",
            ],
            "flirty_lines": [
                "Your social energy is magnetic. I would love to be the person you choose to share some of it with.",
                "I like that your profile feels genuinely friendly. It makes the idea of a first date with you feel easy.",
                "Something about your warmth makes me want to be honest: I think your profile is lovely and I want to know more.",
            ],
            "cheesy_lines": [
                "Are you an ESFJ? Because you just made everyone else on this app disappear.",
                "They say ESFJs bring people together. You just brought me and this send button together.",
                "Your profile is the social event of my evening and I am RSVPing yes.",
            ],
            "prefill_text": "Her bio mentions ESFJ or social/warm energy. Write a friendly, engaging opener that feels genuine.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an ESFJ. Her photos show her with friends and family. She seems warm, sociable, and caring.",
        },
        {
            "slug": "istp",
            "keyword": "ISTP",
            "h1": "The Best ISTP Pickup Lines (For the Virtuoso Type).",
            "title": "Best ISTP Pickup Lines | TryAgainText",
            "meta_description": "Use niche ISTP pickup lines that feel cool, practical, and low-key impressive. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "ISTPs are independent, hands-on, and effortlessly cool. They do not respond to over-the-top flattery. These lines are understated, practical, and genuinely interesting.",
            "witty_lines": [
                "Your profile has this calm, capable energy that makes me think you could fix a car and then explain quantum physics over dinner.",
                "I can tell you are an ISTP because your vibe is low-key cool in a way that most people try too hard to achieve.",
                "You seem like someone who would rather show than tell. I respect that. Here is me showing interest.",
            ],
            "flirty_lines": [
                "There is something really attractive about someone who is clearly independent and still down to connect.",
                "Your profile has this understated confidence that makes me want to learn more about what you are into.",
                "I like that your energy is chill without being distant. That balance is hard to find.",
            ],
            "cheesy_lines": [
                "Are you an ISTP? Because you just deconstructed my usual opener and now I have to build a better one.",
                "They say ISTPs are hands-on learners. I would love to learn what makes you tick.",
                "Your profile is like a well-built machine \u2014 efficient, impressive, and I want to know how it works.",
            ],
            "prefill_text": "Her bio mentions ISTP or hands-on/independent energy. Write a cool, understated opener that is not over the top.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an ISTP. Her profile has action shots or practical hobbies. She seems independent, calm, and capable.",
        },
        {
            "slug": "isfp",
            "keyword": "ISFP",
            "h1": "The Best ISFP Pickup Lines (For the Adventurer Type).",
            "title": "Best ISFP Pickup Lines | TryAgainText",
            "meta_description": "Use niche ISFP pickup lines that feel artistic, gentle, and authentic. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "ISFPs are gentle, artistic, and deeply in tune with beauty. They value authenticity over performance. These lines are sincere, creative, and match her quiet aesthetic.",
            "witty_lines": [
                "Your profile feels like a curated gallery exhibit \u2014 every photo tells a story and I want to hear all of them.",
                "I can tell you are an ISFP because your aesthetic sense is effortless and everything just flows.",
                "You seem like someone who experiences the world through all five senses. I find that really compelling.",
            ],
            "flirty_lines": [
                "There is something quietly beautiful about your profile that makes me want to slow down and pay attention.",
                "Your creative energy is magnetic. I would love to see the world through your eyes for an afternoon.",
                "I like that your profile is artistic without trying to be. That kind of authenticity is very attractive.",
            ],
            "cheesy_lines": [
                "Are you an ISFP? Because your profile is a work of art and I am standing here admiring it.",
                "They say ISFPs live in the moment. This moment \u2014 matching with you \u2014 is a good one.",
                "Your profile just turned my phone screen into an art gallery. I am not leaving.",
            ],
            "prefill_text": "Her bio mentions ISFP or artistic/adventurer energy. Write a gentle, creative opener that feels authentic.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an ISFP. Her photos are aesthetic and nature-oriented. She seems artistic, gentle, and free-spirited.",
        },
        {
            "slug": "estp",
            "keyword": "ESTP",
            "h1": "The Best ESTP Pickup Lines (For the Entrepreneur Type).",
            "title": "Best ESTP Pickup Lines | TryAgainText",
            "meta_description": "Use niche ESTP pickup lines that feel bold, fun, and action-oriented. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "ESTPs are energetic, bold, and action-oriented. They get bored by long, hesitant openers. These lines are direct, fun, and ready to go.",
            "witty_lines": [
                "Your profile has the energy of someone who makes decisions fast and regrets nothing. I am here for it.",
                "I can tell you are an ESTP because your photos look like a highlight reel of someone who actually lives.",
                "You seem like someone who does not overthink things. In that spirit: hi, you are interesting, let's talk.",
            ],
            "flirty_lines": [
                "Your energy is bold and spontaneous and I would love to see where a conversation with you goes.",
                "I like that your profile feels alive. It makes me think spending time with you would never be boring.",
                "Something about your vibe says you are the type to say yes to plans and figure out the details later. Same.",
            ],
            "cheesy_lines": [
                "Are you an ESTP? Because you just took the most direct route to my attention.",
                "They say ESTPs live for the thrill. Matching with you is the most exciting thing that has happened today.",
                "Your profile has more action than most movies I have watched this year.",
            ],
            "prefill_text": "Her bio mentions ESTP or bold/action energy. Write a direct, fun opener that does not overthink it.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an ESTP. Her photos are active and social. She seems bold, fun, and lives in the moment.",
        },
        {
            "slug": "esfp",
            "keyword": "ESFP",
            "h1": "The Best ESFP Pickup Lines (For the Entertainer Type).",
            "title": "Best ESFP Pickup Lines | TryAgainText",
            "meta_description": "Use niche ESFP pickup lines that feel fun, vibrant, and energetic. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "ESFPs are the life of the party \u2014 fun, expressive, and magnetic. They want someone who can match their energy and keep things exciting. These lines bring the fun.",
            "witty_lines": [
                "Your profile has main character energy and everyone else is just a background extra. Including me, apparently.",
                "I can tell you are an ESFP because your photos look like you are having more fun than anyone else on this app.",
                "You seem like someone who turns every room into a party. I want an invite.",
            ],
            "flirty_lines": [
                "Your energy is vibrant and honestly contagious. I am smiling just from looking at your profile.",
                "I like that your profile feels like pure joy. Spending time with you seems like it would be unforgettable.",
                "Something about your vibe tells me you know how to have fun without trying. That is incredibly attractive.",
            ],
            "cheesy_lines": [
                "Are you an ESFP? Because you just entertained me more in six photos than most people do in six dates.",
                "They say ESFPs are born performers. Your profile is the best show I have seen all week.",
                "Your energy is a party and I am showing up with my best outfit and no intention of leaving early.",
            ],
            "prefill_text": "Her bio mentions ESFP or entertainer/party energy. Write a fun, vibrant opener that matches her energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her type.",
            "her_info_prefill": "She is an ESFP. Her photos are vibrant and social. She seems fun, expressive, and loves being around people.",
        },
    ],
}
