DATA = {
    "category_slug": "music-genres",
    "category_name": "Music Genres",
    "sort_order": 8,
    "topics": [
        {
            "slug": "indie-rock",
            "keyword": "Indie Rock",
            "h1": "The Best Indie Rock Pickup Lines (For When Her Spotify Is Suspiciously Good).",
            "title": "Best Indie Rock Pickup Lines | TryAgainText",
            "meta_description": "Use niche indie rock pickup lines that feel authentic, understated, and music-literate. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she has indie rock taste, she values authenticity over mainstream appeal. Generic compliments feel like top 40 radio to her. These lines match her curated, effortlessly cool energy.",
            "witty_lines": [
                "Your profile has the energy of a perfectly curated indie playlist — every detail intentional but nothing feels like it is trying too hard.",
                "I can tell you are the kind of person who has strong opinions about which album was a band's real peak. I need to hear yours.",
                "Your photos have this lo-fi, authentic quality that tells me your Spotify Wrapped is genuinely interesting.",
            ],
            "flirty_lines": [
                "Your vibe is like a great B-side — understated, surprising, and way better than what most people are paying attention to.",
                "Something about your profile tells me you appreciate things that are real over things that are popular. I am trying to be both right now.",
                "You have this effortlessly cool energy that I would normally only associate with someone who has seen at least fifty live shows.",
            ],
            "cheesy_lines": [
                "Are you an indie band? Because I discovered you by accident and now I cannot stop telling everyone about you.",
                "I must be at a house show because your profile just made a small room feel electric.",
                "If you were a vinyl record, you would be the limited press that everyone is trying to find.",
            ],
            "prefill_text": "Her bio mentions indie rock, specific bands, or vinyl. Write an authentic opener that matches her curated taste.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific music taste, not just generic indie vibes.",
            "her_info_prefill": "She is into indie rock. Probably has a carefully curated music taste. Values authenticity over mainstream appeal.",
        },
        {
            "slug": "hip-hop",
            "keyword": "Hip-Hop",
            "h1": "The Best Hip-Hop Pickup Lines (For When She Knows the Difference Between Bars and Vibes).",
            "title": "Best Hip-Hop Pickup Lines | TryAgainText",
            "meta_description": "Use niche hip-hop pickup lines that feel confident, clever, and culture-aware. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into hip-hop, she appreciates confidence, wordplay, and cultural awareness. A weak opener is the equivalent of mumble rap when she wanted lyrical. These lines bring bars.",
            "witty_lines": [
                "Your profile has the energy of a classic album — every photo is a track and there are no skips.",
                "I can tell you actually listen to lyrics, not just beats. That level of attention to detail is rare and attractive.",
                "Your vibe says you have a top five rappers list and it is probably better than mine. I still want to argue about it.",
            ],
            "flirty_lines": [
                "Your confidence in these photos is magnetic. It is the kind of energy that makes the whole room pay attention.",
                "Something about your profile tells me you appreciate someone who comes correct. So here I am, no filler, just bars.",
                "You have the energy of someone who knows her worth and does not settle. That is the most attractive thing on this app.",
            ],
            "cheesy_lines": [
                "Are you a hip-hop beat? Because my heart just started matching your rhythm and I cannot stop it.",
                "I must be a verse because I have been waiting for the right beat and your profile just dropped it.",
                "If your profile was a track, it would be platinum. No features needed.",
            ],
            "prefill_text": "Her bio mentions hip-hop, rap, or specific artists. Write a confident opener with wordplay that matches her energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific hip-hop taste, not just generic rap culture.",
            "her_info_prefill": "She is into hip-hop. Appreciates confidence, wordplay, and culture. Probably has strong opinions about who is the GOAT.",
        },
        {
            "slug": "country-music",
            "keyword": "Country Music",
            "h1": "The Best Country Music Pickup Lines (For When She Has Boots and a Spotify Full of Nashville).",
            "title": "Best Country Music Pickup Lines | TryAgainText",
            "meta_description": "Use niche country music pickup lines that feel genuine, warm, and small-town charming. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she loves country music, she values storytelling, sincerity, and someone who is not afraid to be a little sentimental. These lines have that front-porch, slow-dance energy.",
            "witty_lines": [
                "Your profile tells a better story than most country songs and it does not even need a truck or a dirt road.",
                "I can tell you are the kind of person who knows every word to a song after hearing it twice. That memory is impressive.",
                "Your photos have this warm, golden-hour energy that feels like driving down a back road with the windows down.",
            ],
            "flirty_lines": [
                "You look like the kind of woman country songs are written about — the one they never got over.",
                "Something about your smile reminds me of the good kind of country love song. The kind that sticks with you.",
                "Your energy is warm, genuine, and a little bit magnetic. I could not keep scrolling without saying something.",
            ],
            "cheesy_lines": [
                "Are you a country song? Because you have my heart doing that slow two-step thing and I am not fighting it.",
                "I must be at a honky-tonk because your profile just made me want to dance with a stranger.",
                "If love is a highway, your profile is the scenic route and I am in no rush.",
            ],
            "prefill_text": "Her bio mentions country music, Nashville, or specific country artists. Write a genuine, warm opener with storytelling charm.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific country taste, not just generic Nashville cliches.",
            "her_info_prefill": "She loves country music. Values sincerity, storytelling, and warm energy. Probably loves a good love song.",
        },
        {
            "slug": "edm",
            "keyword": "EDM",
            "h1": "The Best EDM Pickup Lines (For When She Lives for the Drop).",
            "title": "Best EDM Pickup Lines | TryAgainText",
            "meta_description": "Use niche EDM pickup lines that feel energetic, fun, and festival-ready. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into EDM, she values energy, experiences, and people who are not afraid to have fun. A boring opener is the equivalent of a buildup with no drop. These lines deliver.",
            "witty_lines": [
                "Your profile has the energy of a festival set — high energy, good vibes, and zero chance I am walking away early.",
                "I can tell you are the kind of person who plans trips around lineups and honestly that level of commitment is attractive.",
                "Your photos have this electric, alive energy that tells me you know how to have the best time in any room.",
            ],
            "flirty_lines": [
                "Your energy is like a perfect buildup — I can feel this conversation is about to go somewhere really good.",
                "Something about your profile makes me think you are the kind of person who turns a random Tuesday into an adventure. I want in.",
                "You have this vibrant, magnetic energy that makes everything around you feel more exciting. I noticed it immediately.",
            ],
            "cheesy_lines": [
                "Are you a bass drop? Because my heart just did that thing where it stops for a second and then hits harder.",
                "I must be at a festival because your profile just gave me the best set of the night.",
                "If your energy was a BPM, it would be 128 — the perfect tempo for falling for someone.",
            ],
            "prefill_text": "Her bio mentions EDM, festivals, or specific DJs. Write an energetic, fun opener that matches her festival-ready vibe.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific EDM taste or festival photos, not just generic rave culture.",
            "her_info_prefill": "She is into EDM. Festival photos, high energy vibe. Values fun, experiences, and people who bring good energy.",
        },
        {
            "slug": "r-and-b",
            "keyword": "R&B",
            "h1": "The Best R&B Pickup Lines (For When She Has Impeccable Taste in Slow Jams).",
            "title": "Best R&B Pickup Lines | TryAgainText",
            "meta_description": "Use niche R&B pickup lines that feel smooth, genuine, and emotionally aware. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into R&B, she values emotional intelligence, smooth energy, and someone who is not afraid of feelings. These lines bring that late-night, honest conversation energy.",
            "witty_lines": [
                "Your profile has the energy of a late-night R&B playlist — smooth, intentional, and making me feel things I was not expecting.",
                "I can tell you are the kind of person who actually listens to lyrics, not just vibes. That emotional awareness is rare.",
                "Your photos have this warm, effortless quality that reminds me of the best kind of slow jam — understated but unforgettable.",
            ],
            "flirty_lines": [
                "Your energy is the human equivalent of a perfectly placed key change — unexpected and genuinely moving.",
                "Something about your profile tells me you appreciate depth over surface-level small talk. I am here for that.",
                "You have this quiet confidence that is way more attractive than people who try to be loud about it.",
            ],
            "cheesy_lines": [
                "Are you an R&B song? Because you just set the mood and I did not even know I needed it.",
                "I must be listening to a slow jam because time just slowed down the second I saw your profile.",
                "If your vibe was a genre, it would be R&B — smooth, deep, and impossible to skip.",
            ],
            "prefill_text": "Her bio mentions R&B, soul music, or specific artists. Write a smooth, emotionally aware opener that matches her energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific R&B taste, not just generic smooth-talk.",
            "her_info_prefill": "She is into R&B. Values emotional intelligence, smooth energy, and depth. Probably has a go-to slow jam playlist.",
        },
        {
            "slug": "jazz",
            "keyword": "Jazz",
            "h1": "The Best Jazz Pickup Lines (For When She Appreciates Improvisation and Staying Up Late).",
            "title": "Best Jazz Pickup Lines | TryAgainText",
            "meta_description": "Use niche jazz pickup lines that feel smooth, sophisticated, and spontaneous. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into jazz, she values sophistication, spontaneity, and the beauty of improvisation. She appreciates people who can think on their feet and find beauty in the unexpected. These lines swing.",
            "witty_lines": [
                "Your profile has jazz energy — complex, improvisational, and way too sophisticated for anyone who is not paying close attention.",
                "I can tell you are the kind of person who appreciates a good live performance over anything manufactured. That authenticity is rare.",
                "Your vibe says you have stayed up past midnight listening to something beautiful and considered it time well spent. I relate deeply.",
            ],
            "flirty_lines": [
                "Your energy is like a great jazz solo — unexpected, captivating, and making me feel things I did not plan on feeling tonight.",
                "Something about your sophisticated, spontaneous energy tells me a conversation with you would never hit a boring note.",
                "You carry yourself with this effortless cool that reminds me of the best kind of late-night set — intimate and unforgettable.",
            ],
            "cheesy_lines": [
                "Are you a jazz standard? Because you are timeless and I want to hear you on repeat.",
                "I must be at a jazz club because your profile just set the mood for the entire evening.",
                "Your energy has more range than a Coltrane solo and I am completely mesmerized.",
            ],
            "prefill_text": "Her bio mentions jazz, live music, or specific artists. Write a smooth, sophisticated opener that matches her improvisational energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific jazz taste, not just generic smooth-talk.",
            "her_info_prefill": "She is into jazz. Values sophistication, spontaneity, and live music. Appreciates people who think on their feet.",
        },
        {
            "slug": "punk-rock",
            "keyword": "Punk Rock",
            "h1": "The Best Punk Rock Pickup Lines (For When She Does Not Care What You Think and That Is the Point).",
            "title": "Best Punk Rock Pickup Lines | TryAgainText",
            "meta_description": "Use niche punk rock pickup lines that feel raw, authentic, and unapologetically direct. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into punk, she values authenticity over polish, substance over style, and does not need your approval. A tryhard opener will crash and burn. These lines are raw and real.",
            "witty_lines": [
                "Your profile has punk energy — raw, authentic, and clearly not designed to impress anyone. That is exactly why it works.",
                "I can tell you are the kind of person who values substance over style and calls out performative nonsense immediately. I respect that deeply.",
                "Your vibe says you formed your own opinions before the internet told you what to think. That independence is genuinely attractive.",
            ],
            "flirty_lines": [
                "Your unapologetic energy is the most refreshing thing on this entire app. No filter, no performance, just real.",
                "Something about your raw, honest vibe tells me you do not waste time on people who are not genuine. So here is my genuine attempt.",
                "You carry yourself like someone who does not need anyone's validation and that confidence is magnetic.",
            ],
            "cheesy_lines": [
                "Are you a punk show? Because you are loud, chaotic, and the most fun I could possibly have.",
                "I must be in the mosh pit because your profile just hit me and I liked it.",
                "Your energy has more power than a three-chord song and that is saying everything.",
            ],
            "prefill_text": "Her bio mentions punk, specific bands, or she has raw, authentic energy. Write a direct, no-BS opener that respects her independence.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just generic rebel cliches.",
            "her_info_prefill": "She is into punk rock. Values authenticity, independence, and directness. Does not care about polish or performance.",
        },
        {
            "slug": "classical-music",
            "keyword": "Classical Music",
            "h1": "The Best Classical Music Pickup Lines (For When She Knows the Difference Between Baroque and Romantic).",
            "title": "Best Classical Music Pickup Lines | TryAgainText",
            "meta_description": "Use niche classical music pickup lines that feel refined, intelligent, and deeply appreciative. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she loves classical music, she values depth, patience, and beauty that reveals itself over time. She is not interested in instant gratification — she appreciates the slow build. These lines honor that.",
            "witty_lines": [
                "Your profile has the structure of a great symphony — a compelling opening, beautiful development, and I am not ready for it to end.",
                "I can tell you are the kind of person who actually listens to an entire piece instead of skipping to the famous part. That patience is rare.",
                "Your vibe says you have strong opinions about conductors and can explain why tempo matters more than most people realize. I am listening.",
            ],
            "flirty_lines": [
                "Your elegance has this timeless quality that reminds me of the best compositions — enduring, layered, and more beautiful with every encounter.",
                "Something about your refined energy tells me you appreciate things that take time to truly understand. I would love to be one of them.",
                "You carry yourself with this graceful, composed confidence that is deeply attractive to anyone paying close enough attention.",
            ],
            "cheesy_lines": [
                "Are you a classical piece? Because you are beautiful, complex, and I could listen to you for hours.",
                "I must be in a concert hall because your profile just gave me a standing ovation feeling.",
                "Your profile has more movements than a Beethoven symphony and each one is better than the last.",
            ],
            "prefill_text": "Her bio mentions classical music, specific composers, or she plays an instrument. Write a refined opener that matches her depth.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific classical interests, not just generic music compliments.",
            "her_info_prefill": "She loves classical music. Values depth, patience, and timeless beauty. Probably plays an instrument or attends performances.",
        },
        {
            "slug": "reggaeton",
            "keyword": "Reggaeton",
            "h1": "The Best Reggaeton Pickup Lines (For When She Lives for the Perreo and Good Vibes).",
            "title": "Best Reggaeton Pickup Lines | TryAgainText",
            "meta_description": "Use niche reggaeton pickup lines that feel confident, fun, and full of Latin energy. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into reggaeton, she values confidence, fun, and someone who can match her energy on and off the dance floor. Boring openers get left on read. These lines bring the heat.",
            "witty_lines": [
                "Your profile has reggaeton energy — confident, fun, and making everyone in the room want to move.",
                "I can tell you are the kind of person who owns the dance floor and does not apologize for it. That confidence is everything.",
                "Your photos have this vibrant, high-energy quality that tells me you know how to have a good time better than most people on this app.",
            ],
            "flirty_lines": [
                "Your confidence radiates through every photo and it is the kind of energy that makes people stop what they are doing and pay attention.",
                "Something about your vibrant energy tells me spending time with you would be the most fun I have had in a while.",
                "You carry yourself with this bold, unapologetic energy that is incredibly attractive. I had to say something.",
            ],
            "cheesy_lines": [
                "Are you a reggaeton beat? Because my heart just started moving and it is not stopping anytime soon.",
                "I must be at the club because your profile just dropped the hardest beat of the night.",
                "Your energy has more dembow than a Bad Bunny track and I am living for it.",
            ],
            "prefill_text": "Her bio mentions reggaeton, Latin music, or specific artists. Write a confident, fun opener that matches her high-energy vibe.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific music taste, not just generic Latin culture lines.",
            "her_info_prefill": "She is into reggaeton. Confident, fun, high-energy. Probably owns the dance floor and values someone who can keep up.",
        },
        {
            "slug": "lo-fi",
            "keyword": "Lo-Fi",
            "h1": "The Best Lo-Fi Pickup Lines (For When She Studies to Chill Beats and Thrives in Quiet Moments).",
            "title": "Best Lo-Fi Pickup Lines | TryAgainText",
            "meta_description": "Use niche lo-fi pickup lines that feel calm, genuine, and beautifully understated. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into lo-fi, she values calm, authenticity, and finding beauty in the quiet moments. She does not need loud to be interesting. These lines match that gentle, reflective energy.",
            "witty_lines": [
                "Your profile has lo-fi energy — calm, intentional, and making the chaos of this app feel suddenly peaceful.",
                "I can tell you are the kind of person who finds beauty in quiet moments and rainy afternoons. That sensitivity is genuinely rare.",
                "Your photos have this warm, analog quality that tells me you appreciate imperfection as an art form. I find that beautiful.",
            ],
            "flirty_lines": [
                "Your calm, genuine energy is the most attractive thing on this app. It feels like a deep breath in a noisy room.",
                "Something about your understated vibe tells me a conversation with you would feel easy, warm, and completely natural.",
                "You have this quiet magnetism that most people miss because they are looking for something louder. I am glad I noticed.",
            ],
            "cheesy_lines": [
                "Are you a lo-fi beat? Because you are calm, beautiful, and I could listen to you on repeat forever.",
                "I must be studying because your profile just helped me focus on the only thing that matters right now.",
                "Your energy is the human equivalent of rain on a window with a warm coffee in hand.",
            ],
            "prefill_text": "Her bio mentions lo-fi, chill beats, or she gives off calm, reflective energy. Write a gentle, understated opener that matches.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual calm vibe, not just generic chill-beats lines.",
            "her_info_prefill": "She is into lo-fi. Calm, reflective, values quiet moments. Finds beauty in simplicity and imperfection.",
        },
        {
            "slug": "metal",
            "keyword": "Metal",
            "h1": "The Best Metal Pickup Lines (For When She Headbangs and Has a Heart of Gold).",
            "title": "Best Metal Pickup Lines | TryAgainText",
            "meta_description": "Use niche metal pickup lines that feel intense, genuine, and mosh-pit approved. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into metal, she values intensity, authenticity, and people who are not afraid to be loud about what they love. Surface-level openers get crushed. These lines bring the heavy.",
            "witty_lines": [
                "Your profile has metal energy — intense, unapologetic, and making everything else on this app sound like elevator music.",
                "I can tell you are the kind of person who judges people by their music taste and I am both nervous and excited about that.",
                "Your vibe says you have been to shows where you lost your voice and considered it a perfect night. Absolute respect.",
            ],
            "flirty_lines": [
                "Your intense, passionate energy is the most real thing on this app. I could not scroll past it.",
                "Something about your fearless vibe tells me you do not hold back in anything — music, opinions, or feelings. That honesty is magnetic.",
                "You carry yourself with this powerful confidence that comes from knowing exactly who you are. That self-assurance is incredibly attractive.",
            ],
            "cheesy_lines": [
                "Are you a metal riff? Because you are heavy, powerful, and now stuck in my head permanently.",
                "I must be at a concert because your profile just hit me harder than a wall of sound.",
                "Your energy has more power than a double bass pedal and I am headbanging in appreciation.",
            ],
            "prefill_text": "Her bio mentions metal, specific bands, or concerts. Write an intense, genuine opener that matches her energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific metal taste, not just generic headbanger cliches.",
            "her_info_prefill": "She is into metal. Intense, authentic, passionate. Values realness and is not afraid to be loud about what she loves.",
        },
        {
            "slug": "pop",
            "keyword": "Pop Music",
            "h1": "The Best Pop Music Pickup Lines (For When She Knows Every Word to Every Hit and Is Not Sorry).",
            "title": "Best Pop Music Pickup Lines | TryAgainText",
            "meta_description": "Use niche pop music pickup lines that feel fun, catchy, and unapologetically joyful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she loves pop, she values fun, energy, and the shared experience of a song everyone knows. She is not a music snob — she just loves what sounds good. These lines match that joyful, inclusive energy.",
            "witty_lines": [
                "Your profile has pop energy — catchy, fun, and making everyone around you feel better just for experiencing it.",
                "I can tell you are the kind of person who sings in the car at full volume and makes the passengers join in. That energy is contagious.",
                "Your vibe says you have an opinion about every pop song of the last decade and could win a music trivia night single-handedly.",
            ],
            "flirty_lines": [
                "Your joyful energy is infectious and I mean that in the best possible way. I felt it through my screen.",
                "Something about your fun, upbeat vibe tells me you are the kind of person who makes any situation more entertaining. I want in.",
                "You have this bright, magnetic quality that makes me think you are the person everyone gravitates toward at a party. I get why.",
            ],
            "cheesy_lines": [
                "Are you a pop song? Because you are catchy, stuck in my head, and I am pressing repeat.",
                "I must be at a concert because your profile just gave me the best performance of the night.",
                "Your energy just went number one on my charts and it is not coming down.",
            ],
            "prefill_text": "Her bio mentions pop music or she has fun, upbeat energy. Write a catchy, joyful opener that matches her vibe.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific music taste, not just generic pop lines.",
            "her_info_prefill": "She loves pop music. Fun, joyful, unapologetic. Sings in the car and makes everyone join in.",
        },
        {
            "slug": "folk",
            "keyword": "Folk Music",
            "h1": "The Best Folk Music Pickup Lines (For When She Owns a Flannel and Has a Spotify Full of Storytellers).",
            "title": "Best Folk Music Pickup Lines | TryAgainText",
            "meta_description": "Use niche folk music pickup lines that feel genuine, warm, and story-driven. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she loves folk music, she values storytelling, sincerity, and the kind of quiet beauty that sneaks up on you. She wants someone real, not someone performing. These lines are authentic.",
            "witty_lines": [
                "Your profile has folk energy — genuine, story-driven, and making me feel things I was not expecting from a dating app.",
                "I can tell you are the kind of person who appreciates a good story more than a good beat. That depth of listening is beautiful.",
                "Your photos have this warm, campfire quality that tells me you value real moments over manufactured ones.",
            ],
            "flirty_lines": [
                "Your genuine, earthy energy is the most grounding thing on this app. I noticed it immediately.",
                "Something about your honest vibe tells me you are the kind of person who says what she means and means what she says. That is rare and attractive.",
                "You have this quiet, sincere quality that reminds me of the best folk song — understated but deeply moving.",
            ],
            "cheesy_lines": [
                "Are you a folk song? Because you are honest, beautiful, and telling a story I want to hear all of.",
                "I must be at a bonfire because your profile just made everything feel warm and close.",
                "Your energy has more soul than an entire folk festival and I am completely captivated.",
            ],
            "prefill_text": "Her bio mentions folk music, storytelling, or acoustic vibes. Write a genuine, warm opener with sincerity.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her specific earthy vibe, not just generic flannel-and-campfire lines.",
            "her_info_prefill": "She loves folk music. Genuine, story-driven, values sincerity. Probably appreciates campfires, nature, and honest conversation.",
        },
        {
            "slug": "afrobeats",
            "keyword": "Afrobeats",
            "h1": "The Best Afrobeats Pickup Lines (For When She Moves to the Rhythm and Brings the Vibes).",
            "title": "Best Afrobeats Pickup Lines | TryAgainText",
            "meta_description": "Use niche Afrobeats pickup lines that feel vibrant, joyful, and rhythm-rich. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into Afrobeats, she values joy, rhythm, and cultural energy. She brings the vibes wherever she goes and wants someone who can match. These lines have that infectious, feel-good energy.",
            "witty_lines": [
                "Your profile has Afrobeats energy — vibrant, joyful, and making everything around you move to a better rhythm.",
                "I can tell you are the kind of person who brings the energy to every gathering and never has to try. It is just natural.",
                "Your photos have this alive, celebratory quality that tells me you know how to enjoy life better than most people on this app.",
            ],
            "flirty_lines": [
                "Your vibrant energy is the most magnetic thing I have encountered on here. It radiates from every photo.",
                "Something about your joyful, rhythmic vibe tells me spending time with you would feel like the best night out. I am very interested.",
                "You carry yourself with this natural, effortless grace that is both beautiful and impossible to ignore.",
            ],
            "cheesy_lines": [
                "Are you an Afrobeats track? Because my heart just found a new rhythm and it is all because of you.",
                "I must be at the best party ever because your profile just set the vibe for the whole night.",
                "Your energy has more groove than a Burna Boy chorus and I am moving to your rhythm.",
            ],
            "prefill_text": "Her bio mentions Afrobeats or specific artists. Write a vibrant, joyful opener that matches her rhythm.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific music and cultural energy, not just generic dance lines.",
            "her_info_prefill": "She is into Afrobeats. Vibrant, joyful, brings the energy everywhere. Values rhythm, culture, and good vibes.",
        },
        {
            "slug": "techno",
            "keyword": "Techno",
            "h1": "The Best Techno Pickup Lines (For When She Dances Until Sunrise and Means It).",
            "title": "Best Techno Pickup Lines | TryAgainText",
            "meta_description": "Use niche techno pickup lines that feel dark, hypnotic, and warehouse-ready. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into techno, she values depth, endurance, and the kind of experience that most people cannot handle. She does not need mainstream approval. These lines match that underground, hypnotic energy.",
            "witty_lines": [
                "Your profile has techno energy — dark, hypnotic, and the kind of experience you cannot fully appreciate unless you commit to it.",
                "I can tell you are the kind of person who has strong opinions about BPM and considers that a personality trait. It is.",
                "Your vibe says you have danced in a warehouse until sunrise and considered it spiritual. I want to understand that energy.",
            ],
            "flirty_lines": [
                "Your dark, magnetic energy is the most interesting thing on this app. It pulled me in immediately.",
                "Something about your underground vibe tells me you operate on a different frequency than most people. I want to tune in.",
                "You carry yourself with this intense, focused energy that tells me you take experiences seriously. That depth is attractive.",
            ],
            "cheesy_lines": [
                "Are you a techno set? Because I started listening and now I never want it to end.",
                "I must be in Berghain because your profile just gave me the best experience of the night and I barely made it through the door.",
                "Your energy has more depth than a four-hour DJ set and I am locked in for every minute.",
            ],
            "prefill_text": "Her bio mentions techno, raves, or underground music. Write a dark, hypnotic opener that matches her intensity.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific techno taste, not just generic rave culture.",
            "her_info_prefill": "She is into techno. Dark, intense, underground energy. Values depth and endurance over mainstream appeal.",
        },
        {
            "slug": "k-pop",
            "keyword": "K-Pop",
            "h1": "The Best K-Pop Pickup Lines (For When She Stans Hard and Has Fancams Ready).",
            "title": "Best K-Pop Pickup Lines | TryAgainText",
            "meta_description": "Use niche K-Pop pickup lines that feel fun, devoted, and stan-culture literate. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into K-Pop, she is passionate, dedicated, and does not apologize for stanning. She wants someone who respects the culture, not someone who dismisses it. These lines show you get it.",
            "witty_lines": [
                "Your profile has K-Pop stan energy — devoted, organized, and clearly capable of running a fan account as a full-time job.",
                "I can tell you are the kind of person who has streaming schedules and considers that a reasonable life choice. That dedication is actually impressive.",
                "Your vibe says you could name every member of your bias group faster than most people can name their coworkers. Absolute respect.",
            ],
            "flirty_lines": [
                "Your passionate energy is contagious and I mean that genuinely. The way you care about things you love is beautiful.",
                "Something about your devoted, joyful vibe tells me you bring that same intensity to everything in your life. I find that incredibly attractive.",
                "You have this vibrant, all-in energy that most people are afraid to show. You wear it proudly and it suits you.",
            ],
            "cheesy_lines": [
                "Are you a K-Pop comeback? Because you just dropped into my feed and I have been streaming your profile on repeat.",
                "I must be your bias wrecker because I was not in the plan but here I am trying to win your heart.",
                "Your profile just debuted at number one on my personal chart and it is not moving.",
            ],
            "prefill_text": "Her bio mentions K-Pop, a specific group, or stan culture. Write a fun opener that shows you respect the culture.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific group or bias, not just generic K-Pop cliches.",
            "her_info_prefill": "She is into K-Pop. Passionate, dedicated, proud of her fandom. Values devotion and does not apologize for stanning.",
        },
        {
            "slug": "blues",
            "keyword": "Blues",
            "h1": "The Best Blues Pickup Lines (For When She Feels Everything Deeply and Owns It).",
            "title": "Best Blues Pickup Lines | TryAgainText",
            "meta_description": "Use niche blues pickup lines that feel soulful, genuine, and emotionally rich. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into blues, she values emotional honesty, depth, and people who are not afraid to feel things fully. She does not want surface-level anything. These lines come from a real place.",
            "witty_lines": [
                "Your profile has blues energy — deep, honest, and telling a story that most people do not have the emotional range to appreciate.",
                "I can tell you are the kind of person who finds beauty in sadness and strength in vulnerability. That emotional intelligence is rare.",
                "Your vibe says you have lived some life and turned it into wisdom rather than bitterness. That is the most attractive thing a person can do.",
            ],
            "flirty_lines": [
                "Your depth comes through every photo and it tells me you are someone worth knowing beyond the surface.",
                "Something about your soulful energy makes me think a conversation with you would feel like the most honest thing I have experienced in a long time.",
                "You carry yourself with this quiet, emotional strength that is deeply attractive to anyone paying real attention.",
            ],
            "cheesy_lines": [
                "Are you a blues song? Because you are deeply moving, a little bit sad, and I cannot stop listening.",
                "I must have the blues because I saw your profile and now nothing else compares.",
                "Your energy has more soul than a twelve-bar progression and I am feeling every note.",
            ],
            "prefill_text": "Her bio mentions blues, soul, or she has deep, emotionally honest energy. Write a soulful opener that matches her depth.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual emotional energy, not just generic blues cliches.",
            "her_info_prefill": "She is into blues. Emotionally deep, honest, values vulnerability. Feels things fully and is not afraid to show it.",
        },
        {
            "slug": "disco",
            "keyword": "Disco",
            "h1": "The Best Disco Pickup Lines (For When She Lives for the Groove and Good Times).",
            "title": "Best Disco Pickup Lines | TryAgainText",
            "meta_description": "Use niche disco pickup lines that feel groovy, fun, and floor-filling. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she loves disco, she values fun, self-expression, and the kind of uninhibited joy that makes everyone around her feel free. These lines have that sparkle and groove.",
            "witty_lines": [
                "Your profile has disco energy — sparkling, joyful, and making everyone around you want to dance even if they cannot.",
                "I can tell you are the kind of person who makes any room feel like a dance floor just by showing up. That is a rare gift.",
                "Your photos have this shimmering, alive quality that tells me you take fun seriously and refuse to be boring.",
            ],
            "flirty_lines": [
                "Your joyful, uninhibited energy is the most attractive thing on this app. You genuinely glow.",
                "Something about your sparkly vibe tells me you are the kind of person who turns ordinary moments into celebrations. I want that energy.",
                "You carry yourself with this radiant, free-spirited confidence that makes everyone else look like they are trying too hard.",
            ],
            "cheesy_lines": [
                "Are you a disco ball? Because you are shining, spinning, and reflecting light into every corner of this app.",
                "I must be on the dance floor because your profile just made me want to move.",
                "Your energy has more groove than a Donna Summer track and the night is just getting started.",
            ],
            "prefill_text": "Her bio mentions disco, dancing, or she has sparkly, fun energy. Write a groovy opener that matches her joyful vibe.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her actual personality, not just generic disco cliches.",
            "her_info_prefill": "She loves disco. Sparkly, fun, free-spirited. Values self-expression and turning every moment into a celebration.",
        },
        {
            "slug": "latin-pop",
            "keyword": "Latin Pop",
            "h1": "The Best Latin Pop Pickup Lines (For When She Sings Shakira in the Shower and Knows Every Word).",
            "title": "Best Latin Pop Pickup Lines | TryAgainText",
            "meta_description": "Use niche Latin pop pickup lines that feel passionate, fun, and culturally vibrant. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into Latin pop, she values passion, rhythm, and someone who can bring real energy to a conversation. She wants chemistry, not formality. These lines have that Latin fire.",
            "witty_lines": [
                "Your profile has Latin pop energy — passionate, rhythmic, and impossible to ignore once it starts playing.",
                "I can tell you are the kind of person who sings along at full volume and makes everyone else want to join in. That energy is infectious.",
                "Your photos have this warm, vibrant quality that tells me you bring color and life to everything you touch.",
            ],
            "flirty_lines": [
                "Your passionate energy is magnetic and I can tell it is genuine, not performative. That authenticity is incredibly attractive.",
                "Something about your vibrant vibe tells me a date with you would feel like the most alive I have been in months.",
                "You carry yourself with this natural warmth and confidence that makes cold small talk feel impossible. I prefer it that way.",
            ],
            "cheesy_lines": [
                "Are you a Latin pop hit? Because you are passionate, catchy, and I am singing your praises to everyone.",
                "I must be at a concert because your profile just made my heart beat to a completely new rhythm.",
                "Your energy has more fire than a Shakira chorus and my hips are not lying about how I feel.",
            ],
            "prefill_text": "Her bio mentions Latin pop or specific artists. Write a passionate, warm opener that matches her vibrant energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener references her specific music taste, not just generic Latin cliches.",
            "her_info_prefill": "She is into Latin pop. Passionate, warm, vibrant. Brings energy and rhythm to everything she does.",
        },
        {
            "slug": "grunge",
            "keyword": "Grunge",
            "h1": "The Best Grunge Pickup Lines (For When She Wears Flannel Unironically and Has a Soul).",
            "title": "Best Grunge Pickup Lines | TryAgainText",
            "meta_description": "Use niche grunge pickup lines that feel raw, real, and 90s-authentic. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into grunge, she values rawness, emotional honesty, and the kind of music that does not care about being pretty. She wants someone genuine, not polished. These lines are unfiltered.",
            "witty_lines": [
                "Your profile has grunge energy — raw, authentic, and not trying to impress anyone who does not get it.",
                "I can tell you are the kind of person who values realness over aesthetics and considers that a feature, not a flaw. Same.",
                "Your vibe says you have listened to Nevermind front to back more times than you can count and that is basically a personality test I trust.",
            ],
            "flirty_lines": [
                "Your raw, honest energy is the most genuine thing on this app. I could not ignore it.",
                "Something about your unfiltered vibe tells me you are tired of people who perform instead of exist. I am here to just exist.",
                "You carry yourself with this real, unpolished confidence that is infinitely more attractive than anything manufactured.",
            ],
            "cheesy_lines": [
                "Are you a grunge song? Because you are raw, beautiful, and making me feel things I had forgotten about.",
                "I must be in Seattle in 1991 because your profile just changed everything I thought I knew about this app.",
                "Your energy smells like teen spirit and I mean that as the highest compliment available.",
            ],
            "prefill_text": "Her bio mentions grunge, 90s music, or specific bands. Write a raw, genuine opener that does not try too hard.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual unfiltered vibe, not just generic 90s nostalgia.",
            "her_info_prefill": "She is into grunge. Raw, authentic, values emotional honesty over polish. Probably wears flannel unironically.",
        },
    ],
}
