DATA = {
    "category_slug": "professions",
    "category_name": "Professions",
    "sort_order": 5,
    "topics": [
        {
            "slug": "nurse",
            "keyword": "Nurse",
            "h1": "The Best Nurse Pickup Lines (For Healthcare Heroes).",
            "title": "Best Nurse Pickup Lines | TryAgainText",
            "meta_description": "Use niche nurse pickup lines that feel genuine and caring. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Nurses are compassionate, resilient, and give more of themselves than most people realize. They appreciate someone who sees the person behind the scrubs.",
            "witty_lines": [
                "Your profile has the energy of someone who keeps her cool when everything around her is chaos. That composure is incredibly attractive.",
                "I can tell you are a nurse because your warmth and patience come through even in a dating profile.",
                "You seem like someone who has seen it all and still shows up with empathy. That is rare and I notice it.",
            ],
            "flirty_lines": [
                "Something about your caring energy makes me want to show up for you the way you clearly show up for everyone else.",
                "Your strength and compassion are both on full display and I find the combination magnetic.",
                "I like that you are a nurse. It tells me you have more patience and heart than most people I will ever meet.",
            ],
            "cheesy_lines": [
                "Are you a nurse? Because my heart rate just spiked and I think you are the only one qualified to check it.",
                "They say nurses are healers. You just healed my faith in dating apps.",
                "Your profile is the best medicine I have found on this app and I did not even know I needed it.",
            ],
            "prefill_text": "Her bio mentions she is a nurse. Write a genuine, appreciative opener that sees the person behind the profession.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a nurse. Her profile feels warm and resilient. She seems compassionate, strong, and deeply caring.",
        },
        {
            "slug": "doctor",
            "keyword": "Doctor",
            "h1": "The Best Doctor Pickup Lines (For the Brilliant and Driven).",
            "title": "Best Doctor Pickup Lines | TryAgainText",
            "meta_description": "Use niche doctor pickup lines that feel respectful and smart. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Doctors are intelligent, driven, and have sacrificed years to master their craft. They appreciate someone who respects their time and matches their depth.",
            "witty_lines": [
                "Your profile has the energy of someone who spent a decade becoming exceptional and still somehow has a great personality. Impressive.",
                "I can tell you are a doctor because your bio is precise, confident, and wastes zero words. I respect the efficiency.",
                "You seem like someone who is used to being the smartest person in the room. I am not competing, just appreciating.",
            ],
            "flirty_lines": [
                "Something about your intelligence and drive makes me want to bring my absolute best to this conversation.",
                "Your dedication is showing and I find it genuinely magnetic. I would love to know the person behind the credentials.",
                "I like that you are a doctor. It tells me you commit fully to what matters, and I find that incredibly attractive.",
            ],
            "cheesy_lines": [
                "Are you a doctor? Because you just diagnosed the problem with my dating life \u2014 I had not found your profile yet.",
                "They say doctors save lives. You just saved my evening.",
                "Your profile has the kind of precision and warmth that makes me think your bedside manner is unmatched.",
            ],
            "prefill_text": "Her bio mentions she is a doctor. Write a respectful, intelligent opener that values her time and depth.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a doctor. Her profile feels sharp and accomplished. She seems intelligent, driven, and values her time.",
        },
        {
            "slug": "teacher",
            "keyword": "Teacher",
            "h1": "The Best Teacher Pickup Lines (For the Patient and Passionate).",
            "title": "Best Teacher Pickup Lines | TryAgainText",
            "meta_description": "Use niche teacher pickup lines that feel warm and thoughtful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Teachers are patient, passionate, and shape the future every day. They appreciate someone who values what they do and brings curiosity to the conversation.",
            "witty_lines": [
                "Your profile has the energy of someone who makes complicated things simple and makes everyone feel like they belong. That is a gift.",
                "I can tell you are a teacher because your bio is clear, engaging, and somehow makes me want to learn more.",
                "You seem like someone who has the patience of a saint and the humor to survive anything. Both are very attractive.",
            ],
            "flirty_lines": [
                "Something about your warm, encouraging energy makes me think a conversation with you would bring out the best in me.",
                "Your passion for what you do is magnetic. I would love to know what else lights you up like that.",
                "I like that you are a teacher. It tells me you care about people growing, and I find that deeply attractive.",
            ],
            "cheesy_lines": [
                "Are you a teacher? Because I just learned something new about what I am looking for, and it is you.",
                "They say teachers change lives. You just changed my entire swiping experience.",
                "Your profile gets an A-plus and I am not even grading on a curve.",
            ],
            "prefill_text": "Her bio mentions she is a teacher. Write a warm, curious opener that values her patience and passion.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a teacher. Her profile feels warm and engaging. She seems patient, passionate, and deeply invested in others.",
        },
        {
            "slug": "engineer",
            "keyword": "Engineer",
            "h1": "The Best Engineer Pickup Lines (For the Problem-Solvers).",
            "title": "Best Engineer Pickup Lines | TryAgainText",
            "meta_description": "Use niche engineer pickup lines that feel smart and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Engineers are analytical, creative problem-solvers who build things that work. They appreciate someone who values logic but can also surprise them.",
            "witty_lines": [
                "Your profile has the energy of someone who solves problems for a living and still has the creativity to write an interesting bio. Rare combination.",
                "I can tell you are an engineer because your profile is optimized, efficient, and still somehow charming.",
                "You seem like someone who appreciates elegant solutions. This is my attempt at one for the problem of a good first message.",
            ],
            "flirty_lines": [
                "Something about your analytical mind combined with your warmth is a combination I did not expect and cannot stop thinking about.",
                "Your intelligence is the most attractive thing about your profile, and the competition was steep.",
                "I like that you are an engineer. It tells me you build things that last, and I would love to see if that applies to conversations too.",
            ],
            "cheesy_lines": [
                "Are you an engineer? Because you just solved the equation I have been stuck on \u2014 what does the perfect profile look like.",
                "They say engineers make things work. You just made this app work for me.",
                "Your profile is structurally sound, aesthetically pleasing, and built to impress. You clearly engineered it well.",
            ],
            "prefill_text": "Her bio mentions she is an engineer. Write a smart, genuine opener that values problem-solving and creativity.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is an engineer. Her profile feels sharp and efficient. She seems analytical, creative, and values things that work well.",
        },
        {
            "slug": "lawyer",
            "keyword": "Lawyer",
            "h1": "The Best Lawyer Pickup Lines (For the Sharp and Persuasive).",
            "title": "Best Lawyer Pickup Lines | TryAgainText",
            "meta_description": "Use niche lawyer pickup lines that feel sharp and confident. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Lawyers are articulate, sharp, and can argue both sides of anything. They appreciate someone who brings substance and can hold their own in a debate.",
            "witty_lines": [
                "Your profile has the energy of someone who could win an argument I did not even know I was in. I find that thrilling.",
                "I can tell you are a lawyer because your bio is persuasive, airtight, and leaves no room for objection.",
                "You seem like someone who values a strong opening statement. Consider this mine.",
            ],
            "flirty_lines": [
                "Something about your sharp, confident energy makes me want to present my best case for why you should reply.",
                "Your intelligence and poise are genuinely magnetic. I would love to see if our chemistry holds up under cross-examination.",
                "I like that you are a lawyer. It tells me you fight for what matters and I find that incredibly attractive.",
            ],
            "cheesy_lines": [
                "Are you a lawyer? Because you just made a compelling case for being the most interesting person on this app.",
                "They say lawyers never rest. Neither has my mind since I saw your profile.",
                "Your profile is exhibit A in the case of why I should keep using this app.",
            ],
            "prefill_text": "Her bio mentions she is a lawyer. Write a sharp, confident opener that brings substance and holds its own.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a lawyer. Her profile feels sharp and polished. She seems articulate, driven, and values substance over fluff.",
        },
        {
            "slug": "bartender",
            "keyword": "Bartender",
            "h1": "The Best Bartender Pickup Lines (For the Social and Quick-Witted).",
            "title": "Best Bartender Pickup Lines | TryAgainText",
            "meta_description": "Use niche bartender pickup lines that feel fun and socially sharp. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Bartenders are social, quick-witted, and read people for a living. They have heard every bad line, so yours needs to stand out with genuine charm.",
            "witty_lines": [
                "Your profile has the energy of someone who has heard every pickup line in existence and is immune to all of them. Challenge accepted.",
                "I can tell you bartend because your vibe says you can hold a conversation with anyone and still be the most interesting person at the bar.",
                "You seem like someone who can read a person in thirty seconds flat. I hope I am making a good first impression.",
            ],
            "flirty_lines": [
                "Something about your social, confident energy tells me you know what real chemistry looks like. I would love to test ours.",
                "Your quick wit and warmth are both showing and I am drawn to the combination.",
                "I like that you bartend. It tells me you are great with people, can handle pressure, and never run out of stories.",
            ],
            "cheesy_lines": [
                "Are you a bartender? Because you just mixed up my emotions and I am ordering another round.",
                "They say bartenders are great listeners. I have a lot I would love to tell you over a drink you made.",
                "Your profile is top shelf and I am not even close to done reading it.",
            ],
            "prefill_text": "Her bio mentions she bartends. Write a fun, socially sharp opener that stands out from the lines she hears nightly.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a bartender. Her profile feels social and confident. She seems quick-witted, charismatic, and hard to impress.",
        },
        {
            "slug": "firefighter",
            "keyword": "Firefighter",
            "h1": "The Best Firefighter Pickup Lines (For the Brave and Selfless).",
            "title": "Best Firefighter Pickup Lines | TryAgainText",
            "meta_description": "Use niche firefighter pickup lines that feel bold and respectful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Firefighters are brave, selfless, and thrive under pressure. They appreciate someone who respects what they do without making it their entire identity.",
            "witty_lines": [
                "Your profile has the energy of someone who runs toward danger while everyone else runs away. That courage is genuinely attractive.",
                "I can tell you are a firefighter because your confidence is steady, not showy, like someone who has proven herself when it mattered.",
                "You seem like someone who stays calm when everything heats up. I could use that energy in my life.",
            ],
            "flirty_lines": [
                "Something about your brave, grounded energy makes me want to show up with the same kind of courage in this message.",
                "Your strength and selflessness are magnetic. I would love to know the person behind the bravery.",
                "I like that you are a firefighter. It tells me you protect what matters and that kind of heart is rare.",
            ],
            "cheesy_lines": [
                "Are you a firefighter? Because you just set my heart on fire and only you can put it out.",
                "They say firefighters are heroes. You just rescued my evening from another boring swipe session.",
                "Your profile is five alarms and I am responding immediately.",
            ],
            "prefill_text": "Her bio mentions she is a firefighter. Write a bold, respectful opener that honors her courage without overdoing it.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a firefighter. Her profile feels brave and grounded. She seems courageous, selfless, and calm under pressure.",
        },
        {
            "slug": "pilot",
            "keyword": "Pilot",
            "h1": "The Best Pilot Pickup Lines (For the High-Flying and Adventurous).",
            "title": "Best Pilot Pickup Lines | TryAgainText",
            "meta_description": "Use niche pilot pickup lines that feel adventurous and confident. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Pilots are confident, precise, and see the world from a perspective most people never will. They appreciate someone who can keep up with their lifestyle.",
            "witty_lines": [
                "Your profile has the energy of someone who has seen sunrise from 35,000 feet and still thinks a good conversation is the best view.",
                "I can tell you are a pilot because your confidence has that calm, steady quality of someone who is literally in control of the sky.",
                "You seem like someone whose life moves fast but who still values the moments when everything slows down.",
            ],
            "flirty_lines": [
                "Something about your adventurous, confident energy makes me want to be wherever your next destination is.",
                "Your poise and sense of adventure are both incredibly attractive. I would love to explore both.",
                "I like that you are a pilot. It tells me you are precise, fearless, and always heading somewhere interesting.",
            ],
            "cheesy_lines": [
                "Are you a pilot? Because my heart just took off and I think you are in the cockpit.",
                "They say pilots have the best views. Mine just improved dramatically.",
                "Your profile has me on cloud nine and I have not even left the ground yet.",
            ],
            "prefill_text": "Her bio mentions she is a pilot. Write an adventurous, confident opener that matches her high-flying energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a pilot. Her profile feels adventurous and composed. She seems confident, well-traveled, and precise.",
        },
        {
            "slug": "chef",
            "keyword": "Chef",
            "h1": "The Best Chef Pickup Lines (For the Creative and Passionate).",
            "title": "Best Chef Pickup Lines | TryAgainText",
            "meta_description": "Use niche chef pickup lines that feel passionate and flavorful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Chefs are creative, intense, and pour their soul into their craft. They appreciate someone who respects the art and brings their own flavor to the table.",
            "witty_lines": [
                "Your profile has the energy of someone who tastes everything twice and sends nothing out until it is perfect. I respect that standard.",
                "I can tell you are a chef because your bio has layers, depth, and a finish that lingers.",
                "You seem like someone who knows that the best dishes come from passion, not a recipe. I am bringing that same energy here.",
            ],
            "flirty_lines": [
                "Something about your creative intensity is magnetic. I would love to experience the world through your palate.",
                "Your passion is on full display and I find it incredibly attractive. I want to know what drives it.",
                "I like that you are a chef. It tells me you create with instinct and care, and that is the most appealing combination.",
            ],
            "cheesy_lines": [
                "Are you a chef? Because your profile is the most well-crafted thing I have tasted \u2014 I mean, seen \u2014 all day.",
                "They say the way to someone's heart is through their stomach. Your profile just took a shortcut.",
                "Your profile is a five-star experience and I would like to make a reservation for a conversation.",
            ],
            "prefill_text": "Her bio mentions she is a chef. Write a passionate, flavorful opener that respects her craft.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a chef. Her profile feels passionate and intense. She seems creative, detail-driven, and pours herself into her work.",
        },
        {
            "slug": "therapist",
            "keyword": "Therapist",
            "h1": "The Best Therapist Pickup Lines (For the Emotionally Intelligent).",
            "title": "Best Therapist Pickup Lines | TryAgainText",
            "meta_description": "Use niche therapist pickup lines that feel genuine and emotionally aware. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Therapists are deeply empathetic, emotionally intelligent, and value authentic connection. They can spot inauthenticity instantly, so be real or do not bother.",
            "witty_lines": [
                "Your profile has the energy of someone who listens to understand, not just to respond. That is a superpower most people do not have.",
                "I can tell you are a therapist because your bio makes me feel seen and I have only read three sentences.",
                "You seem like someone who values emotional honesty above everything. So honestly: your profile is remarkable.",
            ],
            "flirty_lines": [
                "Something about your empathetic, grounded energy makes me want to be completely genuine with you from the first message.",
                "Your emotional intelligence is the most attractive thing about your profile. And I mean that without a trace of irony.",
                "I like that you are a therapist. It tells me you understand people at a depth most never reach, and I find that magnetic.",
            ],
            "cheesy_lines": [
                "Are you a therapist? Because I just had a breakthrough \u2014 I finally found the profile I have been looking for.",
                "They say therapists create safe spaces. Your profile is the safest place on this entire app.",
                "Your profile just gave me the kind of validation I did not know I needed today.",
            ],
            "prefill_text": "Her bio mentions she is a therapist. Write a genuine, emotionally honest opener that respects her depth.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a therapist. Her profile feels warm and insightful. She seems empathetic, emotionally intelligent, and values authenticity.",
        },
        {
            "slug": "architect",
            "keyword": "Architect",
            "h1": "The Best Architect Pickup Lines (For the Visionary Builders).",
            "title": "Best Architect Pickup Lines | TryAgainText",
            "meta_description": "Use niche architect pickup lines that feel creative and thoughtful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Architects blend creativity with precision, designing spaces that shape how people live. They appreciate someone who notices structure, beauty, and intention.",
            "witty_lines": [
                "Your profile has the energy of someone who sees potential in empty spaces and turns them into something people never want to leave.",
                "I can tell you are an architect because your bio is structurally sound, aesthetically considered, and designed with purpose.",
                "You seem like someone who cares about how things are built, not just how they look. This message is my foundation.",
            ],
            "flirty_lines": [
                "Something about your creative vision combined with your precision is a combination I find incredibly attractive.",
                "Your eye for design is showing in everything about your profile. I would love to see the world through that lens.",
                "I like that you are an architect. It tells me you think about how things fit together, and I am curious if we do.",
            ],
            "cheesy_lines": [
                "Are you an architect? Because you just designed the blueprint for the perfect profile.",
                "They say architects shape the world. You just reshaped my expectations for this app.",
                "Your profile has better structure than most buildings I have been in. And way more character.",
            ],
            "prefill_text": "Her bio mentions she is an architect. Write a creative, design-aware opener that values vision and structure.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is an architect. Her profile feels creative and precise. She seems visionary, detail-oriented, and values intentional design.",
        },
        {
            "slug": "pharmacist",
            "keyword": "Pharmacist",
            "h1": "The Best Pharmacist Pickup Lines (For the Precise and Caring).",
            "title": "Best Pharmacist Pickup Lines | TryAgainText",
            "meta_description": "Use niche pharmacist pickup lines that feel smart and caring. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Pharmacists are meticulous, knowledgeable, and trusted by their communities. They appreciate someone who values precision and cares about getting things right.",
            "witty_lines": [
                "Your profile has the energy of someone who reads the fine print and still manages to be the most interesting person in the room.",
                "I can tell you are a pharmacist because your bio is precise, trustworthy, and clearly knows what it is doing.",
                "You seem like someone who gets the details right every time. I am hoping this message meets your standards.",
            ],
            "flirty_lines": [
                "Something about your careful, knowledgeable energy makes me want to be equally thoughtful with every word I say to you.",
                "Your intelligence and warmth are a powerful combination. I would love to experience both firsthand.",
                "I like that you are a pharmacist. It tells me people trust you with the important things, and I can see why.",
            ],
            "cheesy_lines": [
                "Are you a pharmacist? Because you just prescribed exactly what I needed \u2014 a reason to keep swiping.",
                "They say pharmacists know all the right combinations. I think we might be one.",
                "Your profile is the perfect dose of smart, warm, and interesting.",
            ],
            "prefill_text": "Her bio mentions she is a pharmacist. Write a smart, precise opener that values her expertise and care.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a pharmacist. Her profile feels precise and warm. She seems knowledgeable, detail-oriented, and trusted by those around her.",
        },
        {
            "slug": "veterinarian",
            "keyword": "Veterinarian",
            "h1": "The Best Veterinarian Pickup Lines (For Animal Lovers With Heart).",
            "title": "Best Veterinarian Pickup Lines | TryAgainText",
            "meta_description": "Use niche veterinarian pickup lines that feel compassionate and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Veterinarians are compassionate, smart, and chose a career because they genuinely care. They appreciate someone who sees the heart behind the science.",
            "witty_lines": [
                "Your profile has the energy of someone whose patients love her unconditionally, which is the highest endorsement anyone can get.",
                "I can tell you are a vet because your warmth and intelligence come through in equal measure, and that is a rare balance.",
                "You seem like someone who chose the hardest version of caring for a living. I find that dedication incredibly attractive.",
            ],
            "flirty_lines": [
                "Something about your compassionate, brilliant energy makes me think you bring that same care to every part of your life.",
                "Your gentleness and intelligence are both magnetic. I would love to get to know the person behind the white coat.",
                "I like that you are a vet. It tells me your heart is as big as your brain, and that is the best combination I can think of.",
            ],
            "cheesy_lines": [
                "Are you a veterinarian? Because you just adopted a permanent spot in my thoughts.",
                "They say animals are the best judges of character. If they trust you, I trust you.",
                "Your profile has the kind of warmth that makes me want to bring you my heart for a checkup.",
            ],
            "prefill_text": "Her bio mentions she is a veterinarian. Write a compassionate, genuine opener that values her heart and dedication.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a veterinarian. Her profile feels compassionate and smart. She seems gentle, dedicated, and deeply caring about animals.",
        },
        {
            "slug": "paramedic",
            "keyword": "Paramedic",
            "h1": "The Best Paramedic Pickup Lines (For the Fearless First Responders).",
            "title": "Best Paramedic Pickup Lines | TryAgainText",
            "meta_description": "Use niche paramedic pickup lines that feel brave and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Paramedics are calm under pressure, selfless, and make split-second decisions that save lives. They appreciate someone who shows up with real energy, not rehearsed lines.",
            "witty_lines": [
                "Your profile has the energy of someone who stays calm when the world is falling apart. That composure is deeply attractive.",
                "I can tell you are a paramedic because your presence feels steady, reliable, and like someone who has earned every bit of her confidence.",
                "You seem like someone who does not have time for small talk. So here is something real: your profile stood out immediately.",
            ],
            "flirty_lines": [
                "Something about your courage and calm is a combination I was not expecting to find on a dating app. I am glad I did.",
                "Your selfless energy is magnetic. I would love to show up for you the way you show up for everyone else.",
                "I like that you are a paramedic. It tells me you act when it matters and I find that kind of decisiveness incredibly attractive.",
            ],
            "cheesy_lines": [
                "Are you a paramedic? Because my heart just stopped and I think you are the only one who can revive it.",
                "They say paramedics are first on the scene. You were first on my mind tonight.",
                "Your profile just gave me a pulse I did not know I was missing.",
            ],
            "prefill_text": "Her bio mentions she is a paramedic. Write a brave, genuine opener that respects her courage and calm.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a paramedic. Her profile feels brave and steady. She seems calm under pressure, selfless, and decisive.",
        },
        {
            "slug": "dentist",
            "keyword": "Dentist",
            "h1": "The Best Dentist Pickup Lines (For the Detail-Oriented and Precise).",
            "title": "Best Dentist Pickup Lines | TryAgainText",
            "meta_description": "Use niche dentist pickup lines that feel smart and charming. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Dentists are precise, detail-oriented, and care about things most people overlook. They appreciate someone who notices the little things and brings a great smile.",
            "witty_lines": [
                "Your profile has the energy of someone who notices details that everyone else misses. I can appreciate that level of attention.",
                "I can tell you are a dentist because your profile is polished, precise, and clearly well taken care of.",
                "You seem like someone who values maintenance and consistency. This is me consistently showing up with my best effort.",
            ],
            "flirty_lines": [
                "Something about your precise, caring energy tells me you bring that same attention to everything that matters to you.",
                "Your profile made me smile, which I am told is the highest compliment I can give a dentist.",
                "I like that you are a dentist. It tells me you care about the details that make a real difference, and I find that really appealing.",
            ],
            "cheesy_lines": [
                "Are you a dentist? Because your profile just gave me the best smile I have had all day.",
                "They say dentists see people at their most vulnerable. I am ready to be vulnerable with this opener.",
                "Your profile is so good it should come with a cleaning \u2014 because it is spotless.",
            ],
            "prefill_text": "Her bio mentions she is a dentist. Write a smart, detail-oriented opener that brings a smile.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a dentist. Her profile feels polished and precise. She seems detail-oriented, caring, and takes pride in her work.",
        },
        {
            "slug": "software-developer",
            "keyword": "Software Developer",
            "h1": "The Best Software Developer Pickup Lines (For the Logic-Minded Creatives).",
            "title": "Best Software Developer Pickup Lines | TryAgainText",
            "meta_description": "Use niche software developer pickup lines that feel nerdy and charming. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Software developers are logical, creative, and build things from nothing. They appreciate someone who can think clearly and does not need everything spelled out.",
            "witty_lines": [
                "Your profile has the energy of someone who debugs problems in her head while pretending to listen in meetings. I find that relatable and attractive.",
                "I can tell you are a developer because your bio is clean, efficient, and has zero unnecessary fluff.",
                "You seem like someone who values elegant solutions. I am hoping this opener compiles on the first try.",
            ],
            "flirty_lines": [
                "Something about your logical yet creative mind is a combination that keeps pulling me back to your profile.",
                "Your intelligence is the most magnetic thing about you, and your profile had plenty of competition.",
                "I like that you write code. It tells me you build things from scratch and solve problems most people cannot even define.",
            ],
            "cheesy_lines": [
                "Are you a developer? Because you just resolved every merge conflict in my love life.",
                "They say developers automate everything. You just automated my decision to send a thoughtful first message.",
                "Your profile is production-ready and I am deploying this conversation immediately.",
            ],
            "prefill_text": "Her bio mentions she is a software developer. Write a clever, nerdy opener that values logic and creativity.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a software developer. Her profile feels sharp and efficient. She seems logical, creative, and builds things that work.",
        },
        {
            "slug": "accountant",
            "keyword": "Accountant",
            "h1": "The Best Accountant Pickup Lines (For the Precise and Reliable).",
            "title": "Best Accountant Pickup Lines | TryAgainText",
            "meta_description": "Use niche accountant pickup lines that feel smart and dependable. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Accountants are detail-oriented, reliable, and keep everything balanced. They appreciate someone who is honest, organized, and values stability.",
            "witty_lines": [
                "Your profile has the energy of someone who balances everything in her life with the same precision she brings to a spreadsheet.",
                "I can tell you are an accountant because your bio adds up perfectly \u2014 nothing exaggerated, nothing missing.",
                "You seem like someone who notices when things do not balance. I am hoping this conversation is a perfect equation.",
            ],
            "flirty_lines": [
                "Something about your organized, reliable energy makes me feel like you would bring that same stability to everything you care about.",
                "Your quiet confidence and precision are genuinely attractive. I would love to get behind those numbers.",
                "I like that you are an accountant. It tells me you are someone people can count on, and I find that very appealing.",
            ],
            "cheesy_lines": [
                "Are you an accountant? Because I have been running the numbers and we add up perfectly.",
                "They say accountants find value everywhere. I just found it in your profile.",
                "Your profile is a net positive in my day and I am not even auditing.",
            ],
            "prefill_text": "Her bio mentions she is an accountant. Write a smart, dependable opener that values precision and reliability.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is an accountant. Her profile feels organized and dependable. She seems precise, reliable, and quietly confident.",
        },
        {
            "slug": "real-estate-agent",
            "keyword": "Real Estate Agent",
            "h1": "The Best Real Estate Agent Pickup Lines (For the Hustle and Heart).",
            "title": "Best Real Estate Agent Pickup Lines | TryAgainText",
            "meta_description": "Use niche real estate agent pickup lines that feel ambitious and personable. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Real estate agents are ambitious, personable, and know how to close. They appreciate someone who brings their own energy and does not waste time.",
            "witty_lines": [
                "Your profile has the energy of someone who could sell me a house I did not know I needed. And I would thank her for it.",
                "I can tell you are in real estate because your profile has incredible curb appeal and I am already interested in the details.",
                "You seem like someone who reads people as fast as she reads listings. I hope I am giving good first-impression energy.",
            ],
            "flirty_lines": [
                "Something about your ambitious, personable energy makes me think you bring that same passion to everything, not just closings.",
                "Your hustle and charm are both on display and I find the combination irresistible.",
                "I like that you are in real estate. It tells me you are driven, social, and know what people really want.",
            ],
            "cheesy_lines": [
                "Are you a real estate agent? Because I was not in the market, but your profile just changed that.",
                "They say location is everything. I think I just found the best spot on this entire app.",
                "Your profile has me ready to sign on the dotted line. Where do I commit?",
            ],
            "prefill_text": "Her bio mentions she is a real estate agent. Write an ambitious, personable opener that matches her hustle.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a real estate agent. Her profile feels ambitious and warm. She seems driven, social, and knows how to connect with people.",
        },
        {
            "slug": "personal-trainer",
            "keyword": "Personal Trainer",
            "h1": "The Best Personal Trainer Pickup Lines (For the Motivated and Strong).",
            "title": "Best Personal Trainer Pickup Lines | TryAgainText",
            "meta_description": "Use niche personal trainer pickup lines that feel energetic and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Personal trainers are disciplined, motivating, and invest in other people's growth. They appreciate someone who shows up ready to put in the work.",
            "witty_lines": [
                "Your profile has the energy of someone who motivates other people for a living and still has plenty left for herself.",
                "I can tell you are a trainer because your vibe says discipline, energy, and 'no excuses' in the best possible way.",
                "You seem like someone who pushes people past their comfort zones. Consider this me stepping outside mine.",
            ],
            "flirty_lines": [
                "Something about your motivating energy makes me want to show up as the best version of myself for this conversation.",
                "Your discipline and warmth are a powerful combination. I am genuinely drawn to both.",
                "I like that you are a personal trainer. It tells me you believe in people's potential and invest in making it real.",
            ],
            "cheesy_lines": [
                "Are you a personal trainer? Because my heart rate just went up and I have not moved from the couch.",
                "They say trainers push you to your limits. Your profile just pushed this app to its peak performance.",
                "Your profile is the hardest workout my thumbs have ever done \u2014 because I keep scrolling back to read it again.",
            ],
            "prefill_text": "Her bio mentions she is a personal trainer. Write an energetic, genuine opener that matches her motivating energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a personal trainer. Her profile feels energetic and strong. She seems disciplined, motivating, and invested in growth.",
        },
        {
            "slug": "photographer-pro",
            "keyword": "Photographer",
            "h1": "The Best Photographer Pickup Lines (For the Visual Storytellers).",
            "title": "Best Photographer Pickup Lines | TryAgainText",
            "meta_description": "Use niche photographer pickup lines that feel artistic and observant. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Professional photographers see the world through a unique lens. They value perspective, timing, and someone who appreciates the art behind the image.",
            "witty_lines": [
                "Your profile has the energy of someone who captures moments other people forget to notice. That awareness is rare.",
                "I can tell you are a photographer because your aesthetic tells a story without a single word of explanation.",
                "You seem like someone who waits for the right light before pressing the shutter. I am hoping this is the right moment to say something.",
            ],
            "flirty_lines": [
                "Something about the way you see the world makes me want to be part of the frame.",
                "Your artistic eye and creative vision are incredibly attractive. I would love to see what inspires you.",
                "I like that you are a photographer. It tells me you value beauty, patience, and the stories behind the surface.",
            ],
            "cheesy_lines": [
                "Are you a photographer? Because your profile just developed into the highlight of my evening.",
                "They say a picture is worth a thousand words. Your profile left me speechless, so that math checks out.",
                "Your profile has perfect composition, beautiful depth of field, and I am fully in focus on you.",
            ],
            "prefill_text": "Her bio mentions she is a professional photographer. Write an artistic, observant opener that values her creative eye.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a professional photographer. Her profile has a strong visual identity. She seems artistic, observant, and tells stories through images.",
        },
        {
            "slug": "graphic-designer",
            "keyword": "Graphic Designer",
            "h1": "The Best Graphic Designer Pickup Lines (For the Visually Brilliant).",
            "title": "Best Graphic Designer Pickup Lines | TryAgainText",
            "meta_description": "Use niche graphic designer pickup lines that feel creative and sharp. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Graphic designers think visually, solve problems creatively, and care deeply about aesthetics. They appreciate someone who notices good design and does not settle for generic.",
            "witty_lines": [
                "Your profile has the energy of someone who cringes at bad kerning and I have never found that more attractive.",
                "I can tell you are a graphic designer because your profile has better visual hierarchy than most websites I visit.",
                "You seem like someone who would redesign this entire app if given the chance. Honestly, please do.",
            ],
            "flirty_lines": [
                "Something about your creative eye makes everything around you feel more intentional. Including this moment.",
                "Your aesthetic sensibility is magnetic. I would love to see the world through your design lens.",
                "I like that you are a designer. It tells me you care about how things feel, not just how they function.",
            ],
            "cheesy_lines": [
                "Are you a graphic designer? Because your profile has perfect alignment and I am feeling very centered right now.",
                "They say good design is invisible. But yours is impossible to miss.",
                "Your profile just kerned its way into my heart and I have no complaints about the spacing.",
            ],
            "prefill_text": "Her bio mentions she is a graphic designer. Write a visually aware, creative opener that appreciates good design.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a graphic designer. Her profile has a strong visual sense. She seems creative, detail-oriented, and cares about aesthetics.",
        },
        {
            "slug": "musician",
            "keyword": "Musician",
            "h1": "The Best Musician Pickup Lines (For the Soulful and Expressive).",
            "title": "Best Musician Pickup Lines | TryAgainText",
            "meta_description": "Use niche musician pickup lines that feel soulful and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Musicians are expressive, emotionally deep, and pour themselves into their art. They appreciate someone who listens with intention and feels the music.",
            "witty_lines": [
                "Your profile has the energy of someone who hears melodies in everyday noise and turns them into something beautiful.",
                "I can tell you are a musician because your bio has rhythm, dynamics, and a hook that made me come back for more.",
                "You seem like someone who expresses what she feels through sound rather than words. I want to hear both.",
            ],
            "flirty_lines": [
                "Something about your soulful, expressive energy makes me think being around you would feel like hearing your favorite song for the first time.",
                "Your passion for music is magnetic. I would love to know what you are creating right now.",
                "I like that you are a musician. It tells me you feel things deeply and are not afraid to share that with the world.",
            ],
            "cheesy_lines": [
                "Are you a musician? Because your profile just hit a note I did not know I could feel.",
                "They say music is the universal language. Your profile just spoke to me fluently.",
                "Your profile has more soul than an entire playlist and I am pressing repeat.",
            ],
            "prefill_text": "Her bio mentions she is a musician. Write a soulful, genuine opener that values her art and expression.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a musician. Her profile feels soulful and expressive. She seems passionate, emotionally deep, and lives through her art.",
        },
        {
            "slug": "barista",
            "keyword": "Barista",
            "h1": "The Best Barista Pickup Lines (For the Craft-Obsessed and Friendly).",
            "title": "Best Barista Pickup Lines | TryAgainText",
            "meta_description": "Use niche barista pickup lines that feel warm and craft-driven. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Baristas are friendly, detail-oriented, and turn a simple drink into an experience. They appreciate someone who values craft and good vibes over pretension.",
            "witty_lines": [
                "Your profile has the energy of someone who remembers every regular's order and somehow makes each one feel like the most important person.",
                "I can tell you are a barista because your vibe is warm, caffeinated, and impossible not to come back to.",
                "You seem like someone who has strong opinions about espresso and I would love to hear every single one.",
            ],
            "flirty_lines": [
                "Something about your warm, craft-driven energy makes me think even a simple coffee with you would become something memorable.",
                "Your friendliness and attention to detail are both showing and I find the combination genuinely attractive.",
                "I like that you are a barista. It tells me you care about the experience, not just the product, and that is rare.",
            ],
            "cheesy_lines": [
                "Are you a barista? Because you just steamed up my entire evening.",
                "They say a good barista makes your day. Your profile just made my week.",
                "Your profile is like the perfect latte \u2014 warm, beautifully crafted, and exactly what I needed.",
            ],
            "prefill_text": "Her bio mentions she is a barista. Write a warm, craft-appreciative opener with good vibes.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a barista. Her profile feels warm and craft-driven. She seems friendly, detail-oriented, and passionate about good coffee.",
        },
        {
            "slug": "librarian",
            "keyword": "Librarian",
            "h1": "The Best Librarian Pickup Lines (For the Quietly Brilliant).",
            "title": "Best Librarian Pickup Lines | TryAgainText",
            "meta_description": "Use niche librarian pickup lines that feel bookish and charming. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Librarians are knowledgeable, organized, and quietly passionate about connecting people with ideas. They appreciate someone who values curiosity and respects the quiet.",
            "witty_lines": [
                "Your profile has the energy of someone who can recommend the perfect book based on a two-sentence description of your mood.",
                "I can tell you are a librarian because your bio is organized, thoughtful, and makes me want to come back for more.",
                "You seem like someone who has read more books than most people will in a lifetime and somehow stays curious for more.",
            ],
            "flirty_lines": [
                "Something about your quietly brilliant energy makes me want to sit down with you and talk until the library closes.",
                "Your knowledge and warmth are a beautiful combination. I would love to explore both.",
                "I like that you are a librarian. It tells me you connect people with the right ideas at the right time, and that is a real gift.",
            ],
            "cheesy_lines": [
                "Are you a librarian? Because I have been browsing all day and you are the only thing I want to check out.",
                "They say librarians know everything. I would love to learn something new from you.",
                "Your profile is overdue for a conversation and I am here to start one.",
            ],
            "prefill_text": "Her bio mentions she is a librarian. Write a bookish, curious opener that respects her knowledge and quiet passion.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a librarian. Her profile feels thoughtful and organized. She seems knowledgeable, curious, and quietly passionate.",
        },
        {
            "slug": "flight-attendant",
            "keyword": "Flight Attendant",
            "h1": "The Best Flight Attendant Pickup Lines (For the Well-Traveled and Poised).",
            "title": "Best Flight Attendant Pickup Lines | TryAgainText",
            "meta_description": "Use niche flight attendant pickup lines that feel worldly and charming. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Flight attendants are poised, adaptable, and have seen the world. They appreciate someone who can keep up with their lifestyle and bring something new to the conversation.",
            "witty_lines": [
                "Your profile has the energy of someone who has been to more countries than most people have been to restaurants. I am impressed.",
                "I can tell you are a flight attendant because your poise and adaptability come through even in a dating profile.",
                "You seem like someone who can handle turbulence with a smile. I am hoping this conversation is smooth sailing.",
            ],
            "flirty_lines": [
                "Something about your worldly, poised energy makes me think every story you tell would be worth hearing twice.",
                "Your adaptability and charm are a combination I find incredibly attractive. Where in the world are you right now?",
                "I like that you are a flight attendant. It tells me you are graceful under pressure and always ready for the next adventure.",
            ],
            "cheesy_lines": [
                "Are you a flight attendant? Because my heart just took off and I do not want it to land.",
                "They say flight attendants see the world. I would love to see it through your eyes.",
                "Your profile just upgraded my entire evening to first class.",
            ],
            "prefill_text": "Her bio mentions she is a flight attendant. Write a worldly, charming opener that matches her well-traveled energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a flight attendant. Her profile feels poised and adventurous. She seems well-traveled, adaptable, and effortlessly charming.",
        },
        {
            "slug": "mechanic",
            "keyword": "Mechanic",
            "h1": "The Best Mechanic Pickup Lines (For the Hands-On Problem Solvers).",
            "title": "Best Mechanic Pickup Lines | TryAgainText",
            "meta_description": "Use niche mechanic pickup lines that feel hands-on and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Mechanics are resourceful, skilled, and fix things most people do not understand. They appreciate someone who respects hands-on work and does not underestimate them.",
            "witty_lines": [
                "Your profile has the energy of someone who can diagnose a problem by sound alone. That kind of skill is seriously impressive.",
                "I can tell you are a mechanic because your confidence has that earned quality of someone who fixes things for real.",
                "You seem like someone who does not just talk about getting things done \u2014 you actually do them. I find that very attractive.",
            ],
            "flirty_lines": [
                "Something about your hands-on, capable energy makes me think you approach everything with the same skill and care.",
                "Your confidence is the kind that comes from actually knowing what you are doing. I find that magnetic.",
                "I like that you are a mechanic. It tells me you are resourceful, patient, and never give up on a problem.",
            ],
            "cheesy_lines": [
                "Are you a mechanic? Because you just fixed something I did not even know was broken \u2014 my faith in this app.",
                "They say mechanics keep things running. You just got my heart started.",
                "Your profile runs smoother than anything I have seen on this app. Clearly well-maintained.",
            ],
            "prefill_text": "Her bio mentions she is a mechanic. Write a genuine, respectful opener that values her hands-on skill.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a mechanic. Her profile feels confident and capable. She seems resourceful, skilled, and takes pride in hands-on work.",
        },
        {
            "slug": "electrician",
            "keyword": "Electrician",
            "h1": "The Best Electrician Pickup Lines (For the Skilled and Grounded).",
            "title": "Best Electrician Pickup Lines | TryAgainText",
            "meta_description": "Use niche electrician pickup lines that feel sharp and grounded. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Electricians are skilled, safety-conscious, and keep the world running behind the scenes. They appreciate someone who respects the craft and does not take their work for granted.",
            "witty_lines": [
                "Your profile has the energy of someone who literally powers the world and still has time to look great doing it.",
                "I can tell you are an electrician because your presence is electric. Sorry, I had to. But I genuinely mean it.",
                "You seem like someone who stays grounded no matter how charged things get. I admire that balance.",
            ],
            "flirty_lines": [
                "Something about your skilled, grounded energy makes me think you bring that same steady hand to everything in your life.",
                "Your confidence and capability are a combination I find genuinely attractive. I wanted you to know that.",
                "I like that you are an electrician. It tells me you are skilled, precise, and not afraid of a challenge.",
            ],
            "cheesy_lines": [
                "Are you an electrician? Because there is definitely a spark between us and I am not going to ignore it.",
                "They say electricians make connections. I would love to make one with you.",
                "Your profile just lit up my entire evening. And I am not even going to apologize for that one.",
            ],
            "prefill_text": "Her bio mentions she is an electrician. Write a grounded, genuine opener that respects her skilled trade.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is an electrician. Her profile feels skilled and grounded. She seems capable, safety-conscious, and proud of her trade.",
        },
        {
            "slug": "farmer",
            "keyword": "Farmer",
            "h1": "The Best Farmer Pickup Lines (For the Hardworking and Rooted).",
            "title": "Best Farmer Pickup Lines | TryAgainText",
            "meta_description": "Use niche farmer pickup lines that feel earthy and sincere. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Farmers are hardworking, patient, and deeply connected to the land. They appreciate someone who values honest work and understands the rhythm of nature.",
            "witty_lines": [
                "Your profile has the energy of someone who wakes up before dawn and still somehow looks amazing at sunset. That work ethic is attractive.",
                "I can tell you farm because your vibe is rooted, real, and has zero pretension. I find that refreshing.",
                "You seem like someone who understands that good things take time, hard work, and the right conditions. I am willing to put in all three.",
            ],
            "flirty_lines": [
                "Something about your grounded, hardworking energy makes me think you bring that same devotion to everything you care about.",
                "Your connection to the land and your honesty are both showing. I find both deeply attractive.",
                "I like that you farm. It tells me you understand patience, seasons, and growing something real from the ground up.",
            ],
            "cheesy_lines": [
                "Are you a farmer? Because something just grew in my heart and I think you planted it.",
                "They say farmers reap what they sow. I am sowing this conversation with my best effort.",
                "Your profile is the most organic thing I have found on this app and I mean that in every way.",
            ],
            "prefill_text": "Her bio mentions she is a farmer. Write an earthy, sincere opener that values hard work and patience.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a farmer. Her profile feels grounded and honest. She seems hardworking, patient, and deeply connected to the land.",
        },
        {
            "slug": "social-worker",
            "keyword": "Social Worker",
            "h1": "The Best Social Worker Pickup Lines (For the Compassionate Changemakers).",
            "title": "Best Social Worker Pickup Lines | TryAgainText",
            "meta_description": "Use niche social worker pickup lines that feel compassionate and real. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Social workers are empathetic, resilient, and fight for people who cannot fight for themselves. They appreciate someone who sees the strength behind the compassion.",
            "witty_lines": [
                "Your profile has the energy of someone who carries the weight of other people's stories and still shows up with hope. That resilience is extraordinary.",
                "I can tell you are a social worker because your empathy is palpable even through a screen.",
                "You seem like someone who sees the best in people even when the world makes that hard. I find that kind of strength beautiful.",
            ],
            "flirty_lines": [
                "Something about your compassionate, fierce energy makes me want to be someone worth your time and attention.",
                "Your heart is as strong as your mind and that combination is the most attractive thing I have seen today.",
                "I like that you are a social worker. It tells me you care deeply and fight hard for what matters. Both are magnetic.",
            ],
            "cheesy_lines": [
                "Are you a social worker? Because you just advocated your way into my thoughts and I am not filing a complaint.",
                "They say social workers change lives. You just changed the trajectory of my evening.",
                "Your profile has more heart than anything else on this app and I want to know the person behind it.",
            ],
            "prefill_text": "Her bio mentions she is a social worker. Write a compassionate, genuine opener that sees her strength and heart.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a social worker. Her profile feels compassionate and strong. She seems empathetic, resilient, and deeply committed to justice.",
        },
        {
            "slug": "physical-therapist",
            "keyword": "Physical Therapist",
            "h1": "The Best Physical Therapist Pickup Lines (For the Healing and Motivating).",
            "title": "Best Physical Therapist Pickup Lines | TryAgainText",
            "meta_description": "Use niche physical therapist pickup lines that feel encouraging and genuine. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Physical therapists are patient, encouraging, and help people rebuild what is broken. They appreciate someone who values recovery, growth, and showing up consistently.",
            "witty_lines": [
                "Your profile has the energy of someone who motivates people through their hardest days and makes it look like kindness. That is a rare gift.",
                "I can tell you are a PT because your patience and encouragement come through even in a dating profile.",
                "You seem like someone who believes in incremental progress and celebrates small wins. I like that philosophy.",
            ],
            "flirty_lines": [
                "Something about your encouraging, healing energy makes me want to show up as my best self for this conversation.",
                "Your patience and strength are both magnetic. I would love to know the person who helps others find theirs.",
                "I like that you are a physical therapist. It tells me you invest in people's recovery and growth, and that kind of care is deeply attractive.",
            ],
            "cheesy_lines": [
                "Are you a physical therapist? Because you just rehabilitated my expectations for this entire app.",
                "They say PTs help people move forward. You just moved me to write my best first message.",
                "Your profile has the most therapeutic effect of anything I have encountered today.",
            ],
            "prefill_text": "Her bio mentions she is a physical therapist. Write an encouraging, genuine opener that values patience and recovery.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her profession.",
            "her_info_prefill": "She is a physical therapist. Her profile feels encouraging and warm. She seems patient, motivating, and invested in helping people heal.",
        },
    ],
}
