DATA = {
    "category_slug": "relationship-archetypes",
    "category_name": "Relationship Archetypes",
    "sort_order": 15,
    "topics": [
        {
            "slug": "golden-retriever-girlfriend",
            "keyword": "Golden Retriever Girlfriend",
            "h1": "The Best Golden Retriever Girlfriend Pickup Lines (For When She's Loyal and Energetic).",
            "title": "Best Golden Retriever Girlfriend Pickup Lines | TryAgainText",
            "meta_description": "Use niche golden retriever girlfriend pickup lines that feel warm, loyal, and genuinely excited. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she has golden retriever girlfriend energy, she is loyal, enthusiastic, and genuinely excited to see you. She loves unconditionally and shows up for the people she cares about. These lines match that warmth.",
            "witty_lines": [
                "Your profile tells me you are the type who gets genuinely excited about people you like.",
                "I can tell you are someone who loves hard and shows it, and I respect that energy.",
                "You seem like someone who is always happy to see someone they care about.",
            ],
            "flirty_lines": [
                "I want to be someone you get that genuinely excited about.",
                "Something about your energy tells me you love the people in your life completely and I want to be one of them.",
                "You deserve someone who matches your loyalty and enthusiasm.",
            ],
            "cheesy_lines": [
                "Are you a golden retriever girlfriend? Because I want to be the person you are always excited to see.",
                "Your profile tells me you bring that pure joy energy and I am here for it.",
                "I promise to be the one who gets the same excited energy you give to everyone.",
            ],
            "prefill_text": "She has golden retriever girlfriend energy. Write an opener that matches her warmth, loyalty, and genuine excitement.",
            "upload_hint": "Upload a screenshot of her profile so the excitement feels genuine and specific to who she is.",
            "her_info_prefill": "She has golden retriever girlfriend energy. Loyal, enthusiastic, genuinely excited about the people she cares about.",
        },
        {
            "slug": "black-cat-girlfriend",
            "keyword": "Black Cat Girlfriend",
            "h1": "The Best Black Cat Girlfriend Pickup Lines (For When She's Independent and Mysterious).",
            "title": "Best Black Cat Girlfriend Pickup Lines | TryAgainText",
            "meta_description": "Use niche black cat girlfriend pickup lines that feel intriguing, independent, and respectfully distant. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she has black cat girlfriend energy, she is independent, mysterious, and chooses who gets close to her. She does not need your attention but you have hers if you earn it. These lines respect that boundary.",
            "witty_lines": [
                "Your profile tells me you are someone who picks who gets to be in your circle.",
                "I can tell you are the type who is fine alone but selective with who you let in.",
                "You seem like someone with standards and I genuinely respect that.",
            ],
            "flirty_lines": [
                "I want to be someone you actually choose to spend time with, not someone who has to convince you.",
                "Something about your energy tells me you do not need anyone and that is incredibly attractive.",
                "You deserve someone who understands that your independence is non-negotiable.",
            ],
            "cheesy_lines": [
                "Are you a black cat girlfriend? Because I want to be the one you choose to come home to.",
                "Your profile tells me you are mysterious and I am intrigued by that.",
                "I promise to respect your independence while hoping you choose me.",
            ],
            "prefill_text": "She has black cat girlfriend energy. Write an opener that respects her independence while showing genuine interest.",
            "upload_hint": "Upload a screenshot of her profile so the interest feels earned, not assumed.",
            "her_info_prefill": "She has black cat girlfriend energy. Independent, mysterious, selective about who gets close to her.",
        },
        {
            "slug": "chaotic-good-girl",
            "keyword": "Chaotic Good Girl",
            "h1": "The Best Chaotic Good Girl Pickup Lines (For When She's Unpredictable and Principled).",
            "title": "Best Chaotic Good Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche chaotic good girl pickup lines that feel spontaneous, principled, and adventurous. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she has chaotic good girl energy, she does things on her own terms but always with good intentions. She is spontaneous, unpredictable, and refuses to live by conventional rules. These lines celebrate that.",
            "witty_lines": [
                "Your profile tells me you make your own rules and stick to your own moral code.",
                "I can tell you are the type who does what she thinks is right, not what is expected.",
                "You seem like someone who is willing to break the rules if it serves the greater good.",
            ],
            "flirty_lines": [
                "I want to be someone who appreciates how unpredictably wonderful you are.",
                "Something about your energy tells me you do not fit in a box and I love that.",
                "You deserve someone who celebrates your chaotic, good-hearted nature.",
            ],
            "cheesy_lines": [
                "Are you chaotic good? Because I want to be part of your adventure.",
                "Your profile tells me you live by your own rules and that is incredibly hot.",
                "I promise to keep up with your unpredictable, well-intentioned chaos.",
            ],
            "prefill_text": "She has chaotic good girl energy. Write an opener that celebrates her spontaneity and principled nature.",
            "upload_hint": "Upload a screenshot of her profile so the appeal feels connected to her actual values.",
            "her_info_prefill": "She has chaotic good girl energy. Unpredictable, spontaneous, principled, does things on her own terms.",
        },
        {
            "slug": "therapy-speak-girl",
            "keyword": "Therapy Speak Girl",
            "h1": "The Best Therapy Speak Girl Pickup Lines (For When She's Emotionally Aware).",
            "title": "Best Therapy Speak Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche therapy speak girl pickup lines that feel emotionally intelligent and psychologically aware. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a therapy speak girl, she is emotionally intelligent, communicates in boundaries, and references her own growth journey. She values introspection and wants a partner who does too. These lines speak that language.",
            "witty_lines": [
                "Your profile tells me you are the type who has done the inner work.",
                "I can tell you understand your own patterns and communicate about them clearly.",
                "You seem like someone who values emotional intelligence and self-awareness.",
            ],
            "flirty_lines": [
                "I want to be someone you can be emotionally present with.",
                "Something about your energy tells me you do the work on yourself and I respect that deeply.",
                "You deserve someone who speaks your language of growth and boundaries.",
            ],
            "cheesy_lines": [
                "Are you therapy speak? Because I want to work through things with you.",
                "Your profile tells me you are emotionally intelligent and I am attracted to that.",
                "I promise to respect your boundaries and do my own inner work.",
            ],
            "prefill_text": "She is a therapy speak girl. Write an opener that shows emotional intelligence and respect for her journey.",
            "upload_hint": "Upload a screenshot of her profile so the appeal feels grounded in actual emotional maturity.",
            "her_info_prefill": "She is a therapy speak girl. Emotionally intelligent, self-aware, communicates in boundaries and growth.",
        },
        {
            "slug": "main-character-energy",
            "keyword": "Main Character Energy",
            "h1": "The Best Main Character Energy Pickup Lines (For When She's Unapologetically Herself).",
            "title": "Best Main Character Energy Pickup Lines | TryAgainText",
            "meta_description": "Use niche main character energy pickup lines that feel cinematic, confident, and genuinely captivating. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she has main character energy, she moves through the world like the protagonist of her own story. Confident, intentional, and magnetic. She does not dim herself for anyone. These lines celebrate that.",
            "witty_lines": [
                "Your profile tells me you see yourself as the lead and not the supporting character.",
                "I can tell you move through life with genuine confidence and intention.",
                "You seem like someone who is unapologetically themselves.",
            ],
            "flirty_lines": [
                "I want to be someone who is worthy of being in your story.",
                "Something about your energy tells me you know your own worth and live accordingly.",
                "You deserve someone who sees how exceptional you are because you already know it.",
            ],
            "cheesy_lines": [
                "Are you main character energy? Because I want to be part of your narrative.",
                "Your profile tells me you are the lead in your own life and I am here for it.",
                "I promise to be a love interest worthy of your story.",
            ],
            "prefill_text": "She has main character energy. Write an opener that celebrates her confidence and cinematic presence.",
            "upload_hint": "Upload a screenshot of her profile so the compliment feels specific to how she carries herself.",
            "her_info_prefill": "She has main character energy. Confident, intentional, unapologetically herself, magnetic presence.",
        },
        {
            "slug": "red-flag-collector",
            "keyword": "Red Flag Collector",
            "h1": "The Best Red Flag Collector Pickup Lines (For When She Dates Unavailable People).",
            "title": "Best Red Flag Collector Pickup Lines | TryAgainText",
            "meta_description": "Use niche red flag collector pickup lines that feel self-aware and gently acknowledging her patterns. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a red flag collector, she has a type: emotionally unavailable, complicated, or broken. She loves the idea of fixing them. These lines acknowledge that pattern with gentle humor and authentic interest.",
            "witty_lines": [
                "Your profile tells me you have a thing for people who need fixing.",
                "I can tell you are attracted to potential rather than current reality.",
                "You seem like someone who sees the best in people even when they do not see it in themselves.",
            ],
            "flirty_lines": [
                "I want to be someone who does not make you work so hard.",
                "Something about your energy tells me you deserve someone who is actually available.",
                "You deserve someone who shows up without you having to convince them.",
            ],
            "cheesy_lines": [
                "Are you a red flag collector? Because I promise to be a green flag.",
                "Your profile tells me I might be the opposite of your usual type.",
                "I promise to show you what it feels like to date someone who is already together.",
            ],
            "prefill_text": "She is a red flag collector. Write an opener that acknowledges her pattern with humor and authentic interest.",
            "upload_hint": "Upload a screenshot of her profile so the appeal feels grounded in actual self-awareness.",
            "her_info_prefill": "She is a red flag collector. Attracted to unavailable people, loves potential, needs someone actually present.",
        },
        {
            "slug": "situationship-girl",
            "keyword": "Situationship Girl",
            "h1": "The Best Situationship Girl Pickup Lines (For When She's Stuck in Ambiguity).",
            "title": "Best Situationship Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche situationship girl pickup lines that feel direct, clear, and genuinely interested in defining things. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a situationship girl, she is stuck in undefined territory. Maybe she is waiting for someone to step up and ask for real commitment. These lines offer clarity instead of games.",
            "witty_lines": [
                "Your profile tells me you deserve someone who is clear about what he wants.",
                "I can tell you are probably tired of guessing where you stand with people.",
                "You seem like someone who is worth actually committing to.",
            ],
            "flirty_lines": [
                "I want to be someone who is certain about you instead of making you guess.",
                "Something about your energy tells me you deserve real definition, not ambiguity.",
                "You deserve someone who chooses you intentionally.",
            ],
            "cheesy_lines": [
                "Are you in a situationship? Because I want to make things official.",
                "Your profile tells me you deserve actual clarity and commitment.",
                "I promise to be direct about what I want instead of keeping you in limbo.",
            ],
            "prefill_text": "She is a situationship girl. Write an opener that offers clarity, directness, and genuine commitment interest.",
            "upload_hint": "Upload a screenshot of her profile so the intention feels real and specific.",
            "her_info_prefill": "She is a situationship girl. Stuck in undefined territory, deserves clarity and real commitment.",
        },
        {
            "slug": "slow-burn-girl",
            "keyword": "Slow Burn Girl",
            "h1": "The Best Slow Burn Girl Pickup Lines (For When She Needs Time to Fall).",
            "title": "Best Slow Burn Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche slow burn girl pickup lines that feel patient, intentional, and willing to invest time. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a slow burn girl, she does not fall quickly. She takes time to build trust and let feelings develop naturally. She values someone willing to invest in the slow build. These lines show patience.",
            "witty_lines": [
                "Your profile tells me you are not the type who falls immediately.",
                "I can tell you build feelings slowly and that makes them actually real.",
                "You seem like someone who values the slow building of something genuine.",
            ],
            "flirty_lines": [
                "I want to be someone you take time to fall for.",
                "Something about your energy tells me you take relationships seriously and build them right.",
                "You deserve someone patient enough to let real feelings develop.",
            ],
            "cheesy_lines": [
                "Are you a slow burn? Because I want to invest the time.",
                "Your profile tells me you are worth the wait and the building.",
                "I promise to be patient while real feelings actually develop.",
            ],
            "prefill_text": "She is a slow burn girl. Write an opener that shows patience and willingness to invest time.",
            "upload_hint": "Upload a screenshot of her profile so the timeline feels reasonable and genuine.",
            "her_info_prefill": "She is a slow burn girl. Does not fall quickly, needs time to build trust, values intentional connection.",
        },
        {
            "slug": "low-maintenance-girl",
            "keyword": "Low Maintenance Girl",
            "h1": "The Best Low Maintenance Girl Pickup Lines (For When She's Easygoing).",
            "title": "Best Low Maintenance Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche low maintenance girl pickup lines that feel genuine, easygoing, and relieved. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a low maintenance girl, she is easygoing, drama-free, and genuinely happy with simple things. She does not need constant validation or elaborate gestures. These lines celebrate that.",
            "witty_lines": [
                "Your profile tells me you are the type who is easy to be around.",
                "I can tell you do not need a lot to be happy and genuinely appreciate that.",
                "You seem like someone who is genuinely easygoing about life.",
            ],
            "flirty_lines": [
                "I want to be with someone who makes life simple and fun.",
                "Something about your energy tells me you do not create unnecessary drama.",
                "You deserve someone who appreciates how easygoing you are.",
            ],
            "cheesy_lines": [
                "Are you low maintenance? Because I am relieved and attracted to that.",
                "Your profile tells me you are genuinely easygoing and that is hot.",
                "I promise to keep life simple and genuinely fun with you.",
            ],
            "prefill_text": "She is a low maintenance girl. Write an opener that appreciates her easygoing nature.",
            "upload_hint": "Upload a screenshot of her profile so the appeal feels connected to her actual laid-back energy.",
            "her_info_prefill": "She is a low maintenance girl. Easygoing, drama-free, genuinely happy with simple things.",
        },
        {
            "slug": "high-maintenance-girl",
            "keyword": "High Maintenance Girl",
            "h1": "The Best High Maintenance Girl Pickup Lines (For When She Knows Her Worth).",
            "title": "Best High Maintenance Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche high maintenance girl pickup lines that feel respectful, certain, and genuinely matching her energy. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a high maintenance girl, she knows her worth and expects to be treated accordingly. She has standards and is not apologetic about them. She wants someone who can match her energy. These lines show you can.",
            "witty_lines": [
                "Your profile tells me you know exactly what you deserve and you do not settle.",
                "I can tell you have standards and I genuinely respect someone who knows their worth.",
                "You seem like someone who expects to be treated well and that is fair.",
            ],
            "flirty_lines": [
                "I want to be someone who actually meets your standards.",
                "Something about your energy tells me you expect the best and you get it.",
                "You deserve someone who matches your energy and shows up accordingly.",
            ],
            "cheesy_lines": [
                "Are you high maintenance? Because I am ready for the challenge.",
                "Your profile tells me you know your worth and I am here for it.",
                "I promise to treat you like the catch you actually are.",
            ],
            "prefill_text": "She is a high maintenance girl. Write an opener that respects her standards and matches her energy.",
            "upload_hint": "Upload a screenshot of her profile so the commitment feels real and capable.",
            "her_info_prefill": "She is a high maintenance girl. Knows her worth, has high standards, expects to be treated well.",
        },
    ],
}
