DATA = {
    "category_slug": "us-cities",
    "category_name": "US Cities",
    "sort_order": 16,
    "topics": [
        {
            "slug": "new-york-city",
            "keyword": "NYC Girl",
            "h1": "The Best NYC Girl Pickup Lines (For When She's Fast-Paced and Ambitious).",
            "title": "Best NYC Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche NYC girl pickup lines that feel sharp, ambitious, and respect her hustle. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is an NYC girl, she moves fast, thinks even faster, and does not have time for games. She is ambitious, driven, and expects someone who can keep up. These lines respect her pace.",
            "witty_lines": [
                "Your profile tells me you are the type who does not waste time on small talk.",
                "I can tell you value efficiency and real conversation over anything superficial.",
                "You seem like someone who expects someone sharp enough to interest you.",
            ],
            "flirty_lines": [
                "I want to be someone who can actually keep up with your pace.",
                "Something about your energy tells me you are constantly leveling up.",
                "You deserve someone who respects how fast you move and where you are going.",
            ],
            "cheesy_lines": [
                "Are you an NYC girl? Because I am ready to never sleep and keep up.",
                "Your profile tells me you have places to be and I want to be on the way.",
                "I promise to move at your pace and appreciate the hustle.",
            ],
            "prefill_text": "She is an NYC girl. Write an opener that shows you respect her pace and ambition.",
            "upload_hint": "Upload a screenshot of her profile so the connection feels sharp and intentional.",
            "her_info_prefill": "She is an NYC girl. Fast-paced, ambitious, driven, expects sharp conversation and real chemistry.",
        },
        {
            "slug": "los-angeles",
            "keyword": "LA Girl",
            "h1": "The Best LA Girl Pickup Lines (For When She's Creative and Effortlessly Cool).",
            "title": "Best LA Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche LA girl pickup lines that feel casual, creative, and genuinely interested in her hustle. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is an LA girl, she has that effortless cool thing going. Creative, probably involved in entertainment or wellness, and genuinely laid-back. She does not take herself too seriously but takes her goals seriously. These lines capture that.",
            "witty_lines": [
                "Your profile tells me you are the type who makes everything look easy.",
                "I can tell you are creative and probably working on something interesting.",
                "You seem like someone who has that LA ease without the pretension.",
            ],
            "flirty_lines": [
                "I want to be someone who appreciates what you are actually building.",
                "Something about your energy tells me you are genuinely talented and laid-back about it.",
                "You deserve someone who can be serious about your goals and chill about everything else.",
            ],
            "cheesy_lines": [
                "Are you an LA girl? Because I want to be part of your vibe.",
                "Your profile tells me you have that effortless creative energy.",
                "I promise to respect your hustle and keep things genuinely fun.",
            ],
            "prefill_text": "She is an LA girl. Write an opener that respects her creativity and effortless cool.",
            "upload_hint": "Upload a screenshot of her profile so the appeal feels connected to her actual projects.",
            "her_info_prefill": "She is an LA girl. Creative, ambitious, laid-back, effortlessly cool, probably building something.",
        },
        {
            "slug": "chicago",
            "keyword": "Chicago Girl",
            "h1": "The Best Chicago Girl Pickup Lines (For When She's Real and Grounded).",
            "title": "Best Chicago Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Chicago girl pickup lines that feel genuine, grounded, and respect her no-nonsense approach. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Chicago girl, she is real, grounded, and does not have time for fakeness. She tells it straight and expects the same. Genuine connection matters more than flash. These lines are authentic.",
            "witty_lines": [
                "Your profile tells me you are someone who values honesty over everything else.",
                "I can tell you do not tolerate BS and I respect that deeply.",
                "You seem like someone who knows what she wants and does not waste time.",
            ],
            "flirty_lines": [
                "I want to be someone real enough to actually interest you.",
                "Something about your energy tells me you see straight through BS.",
                "You deserve someone who is just as genuine and grounded as you are.",
            ],
            "cheesy_lines": [
                "Are you a Chicago girl? Because I promise to be real.",
                "Your profile tells me you value honesty and that is sexy.",
                "I promise no games, just genuine connection and respect.",
            ],
            "prefill_text": "She is a Chicago girl. Write an opener that is genuine, grounded, and honest.",
            "upload_hint": "Upload a screenshot of her profile so the connection feels real and straightforward.",
            "her_info_prefill": "She is a Chicago girl. Real, grounded, no-nonsense, values honesty and genuine connection.",
        },
        {
            "slug": "austin",
            "keyword": "Austin Girl",
            "h1": "The Best Austin Girl Pickup Lines (For When She's Quirky and Independent).",
            "title": "Best Austin Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Austin girl pickup lines that feel fun, quirky, and celebrate her weird. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is an Austin girl, she leans into weird. She is independent, creative, probably into live music or community, and celebrates being different. She wants someone who thinks her quirk is a feature. These lines celebrate that.",
            "witty_lines": [
                "Your profile tells me you are comfortable being exactly who you are.",
                "I can tell you celebrate weird instead of trying to fit in.",
                "You seem like someone who appreciates originality and authentic self-expression.",
            ],
            "flirty_lines": [
                "I want to be someone who thinks your weird is actually incredible.",
                "Something about your energy tells me you are genuinely yourself.",
                "You deserve someone who celebrates how different you actually are.",
            ],
            "cheesy_lines": [
                "Are you an Austin girl? Because I love weird.",
                "Your profile tells me you are exactly the kind of different I need.",
                "I promise to appreciate your weird as much as you do.",
            ],
            "prefill_text": "She is an Austin girl. Write an opener that celebrates her quirk and independence.",
            "upload_hint": "Upload a screenshot of her profile so the weird feels genuinely appreciated.",
            "her_info_prefill": "She is an Austin girl. Quirky, independent, creative, celebrates being different, authentically herself.",
        },
        {
            "slug": "miami",
            "keyword": "Miami Girl",
            "h1": "The Best Miami Girl Pickup Lines (For When She's Confident and Glamorous).",
            "title": "Best Miami Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Miami girl pickup lines that feel confident, glamorous, and respect her style. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Miami girl, she knows how to dress, takes care of herself, and carries herself with confidence. She wants someone who shows up as polished as she does. These lines celebrate that energy.",
            "witty_lines": [
                "Your profile tells me you take care of yourself and it shows.",
                "I can tell you have confidence that comes from knowing exactly what you bring.",
                "You seem like someone who expects polish and effort from everyone around her.",
            ],
            "flirty_lines": [
                "I want to be someone who matches your energy and standard.",
                "Something about your energy tells me you do not settle for less than excellent.",
                "You deserve someone who shows up as polished and intentional as you do.",
            ],
            "cheesy_lines": [
                "Are you a Miami girl? Because I want to match your style.",
                "Your profile tells me you expect the best and I am ready to deliver.",
                "I promise to show up as well as you do.",
            ],
            "prefill_text": "She is a Miami girl. Write an opener that respects her confidence and style.",
            "upload_hint": "Upload a screenshot of her profile so the polish feels matched, not mocked.",
            "her_info_prefill": "She is a Miami girl. Confident, glamorous, polished, expects effort and excellence.",
        },
        {
            "slug": "nashville",
            "keyword": "Nashville Girl",
            "h1": "The Best Nashville Girl Pickup Lines (For When She's Warm and Community-Focused).",
            "title": "Best Nashville Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Nashville girl pickup lines that feel warm, community-focused, and respect her roots. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Nashville girl, she is warm, probably loves live music, and values community and connections. She is grounded and appreciates good people over flash. These lines capture that warmth.",
            "witty_lines": [
                "Your profile tells me you are the type who values real people and real connections.",
                "I can tell you have that warm, genuine energy that Nashville is known for.",
                "You seem like someone who loves music and the community around it.",
            ],
            "flirty_lines": [
                "I want to be someone who gets the same warm attention you give to your people.",
                "Something about your energy tells me community and connection actually matter to you.",
                "You deserve someone who appreciates your warmth and generosity.",
            ],
            "cheesy_lines": [
                "Are you a Nashville girl? Because I want to be part of your circle.",
                "Your profile tells me you have that warmth that makes people want to stay.",
                "I promise to show up for you like you show up for others.",
            ],
            "prefill_text": "She is a Nashville girl. Write an opener that celebrates her warmth and community spirit.",
            "upload_hint": "Upload a screenshot of her profile so the connection feels rooted in genuine interest.",
            "her_info_prefill": "She is a Nashville girl. Warm, community-focused, loves music and real connections, grounded.",
        },
        {
            "slug": "portland",
            "keyword": "Portland Girl",
            "h1": "The Best Portland Girl Pickup Lines (For When She's Thoughtful and Eco-Conscious).",
            "title": "Best Portland Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Portland girl pickup lines that feel thoughtful, sustainable, and respect her values. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Portland girl, she thinks about her impact, probably cares about sustainability, and values experiences over stuff. She is thoughtful and wants someone who thinks beyond himself. These lines respect her values.",
            "witty_lines": [
                "Your profile tells me you actually think about the bigger picture.",
                "I can tell you care about your choices and what they represent.",
                "You seem like someone who values substance and real impact.",
            ],
            "flirty_lines": [
                "I want to be someone who thinks beyond himself like you do.",
                "Something about your energy tells me your values actually run deep.",
                "You deserve someone who respects what matters to you.",
            ],
            "cheesy_lines": [
                "Are you a Portland girl? Because I want to build something sustainable with you.",
                "Your profile tells me you think about impact and that is attractive.",
                "I promise to think about more than just myself.",
            ],
            "prefill_text": "She is a Portland girl. Write an opener that respects her thoughtfulness and values.",
            "upload_hint": "Upload a screenshot of her profile so the appeal feels aligned with her actual values.",
            "her_info_prefill": "She is a Portland girl. Thoughtful, eco-conscious, values experiences, cares about impact.",
        },
        {
            "slug": "seattle",
            "keyword": "Seattle Girl",
            "h1": "The Best Seattle Girl Pickup Lines (For When She's Outdoorsy and Introspective).",
            "title": "Best Seattle Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Seattle girl pickup lines that feel outdoorsy, thoughtful, and respect her introspective nature. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Seattle girl, she probably spends time outside, values quiet introspection, and does not need constant social stimulation. She appreciates depth and genuinely interesting conversation. These lines celebrate that.",
            "witty_lines": [
                "Your profile tells me you are comfortable with silence and introspection.",
                "I can tell you value the outdoors and real substance in conversation.",
                "You seem like someone who thinks deeply and enjoys being outside.",
            ],
            "flirty_lines": [
                "I want to be someone you are happy being quiet with.",
                "Something about your energy tells me depth matters more than noise.",
                "You deserve someone who appreciates your introspective nature.",
            ],
            "cheesy_lines": [
                "Are you a Seattle girl? Because I want to go on adventures and be quiet together.",
                "Your profile tells me you appreciate nature and I do too.",
                "I promise meaningful conversations and good hiking partners.",
            ],
            "prefill_text": "She is a Seattle girl. Write an opener that respects her love of nature and introspection.",
            "upload_hint": "Upload a screenshot of her profile so the adventure feels mutually interested.",
            "her_info_prefill": "She is a Seattle girl. Outdoorsy, introspective, values depth, comfortable with quiet presence.",
        },
        {
            "slug": "denver",
            "keyword": "Denver Girl",
            "h1": "The Best Denver Girl Pickup Lines (For When She's Active and Adventure-Seeking).",
            "title": "Best Denver Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Denver girl pickup lines that feel active, adventurous, and respect her wellness lifestyle. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Denver girl, she is active, probably into hiking or fitness, and values health and adventure. She wants someone who can keep up physically and is genuinely interested in being outside. These lines match that energy.",
            "witty_lines": [
                "Your profile tells me you are the type who actually does the hiking instead of just talking about it.",
                "I can tell you value fitness and being active as a real lifestyle choice.",
                "You seem like someone who wants a partner who can actually keep up.",
            ],
            "flirty_lines": [
                "I want to be someone who can be your actual adventure partner.",
                "Something about your energy tells me you are genuinely active and I like that.",
                "You deserve someone who matches your energy level and loves being outside.",
            ],
            "cheesy_lines": [
                "Are you a Denver girl? Because I want to go on actual adventures with you.",
                "Your profile tells me you are fit and I respect that commitment.",
                "I promise to be your adventure partner, not just your couch date.",
            ],
            "prefill_text": "She is a Denver girl. Write an opener that shows you are genuinely active and adventurous.",
            "upload_hint": "Upload a screenshot of her profile so the adventure feels real and matched.",
            "her_info_prefill": "She is a Denver girl. Active, adventure-seeking, fitness-focused, wants an active partner.",
        },
        {
            "slug": "boston",
            "keyword": "Boston Girl",
            "h1": "The Best Boston Girl Pickup Lines (For When She's Direct and Competitive).",
            "title": "Best Boston Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Boston girl pickup lines that feel direct, competitive, and respect her no-BS attitude. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Boston girl, she is direct, competitive, and does not waste time on fluff. She wants someone who can hold their own and appreciates a good argument. These lines are straightforward.",
            "witty_lines": [
                "Your profile tells me you do not tolerate weak game.",
                "I can tell you appreciate someone who can challenge you intellectually.",
                "You seem like someone who expects depth and directness.",
            ],
            "flirty_lines": [
                "I want to be someone who can actually challenge you and keep up.",
                "Something about your energy tells me you respect someone who does not back down.",
                "You deserve someone who appreciates your competitiveness.",
            ],
            "cheesy_lines": [
                "Are you a Boston girl? Because I am ready for the competition.",
                "Your profile tells me you appreciate direct game and I respect that.",
                "I promise to keep it real and challenge you appropriately.",
            ],
            "prefill_text": "She is a Boston girl. Write an opener that is direct, competitive, and matches her intensity.",
            "upload_hint": "Upload a screenshot of her profile so the challenge feels genuine.",
            "her_info_prefill": "She is a Boston girl. Direct, competitive, no-BS, wants genuine intellectual challenge.",
        },
        {
            "slug": "san-francisco",
            "keyword": "San Francisco Girl",
            "h1": "The Best San Francisco Girl Pickup Lines (For When She's Tech-Savvy and Ambitious).",
            "title": "Best San Francisco Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche San Francisco girl pickup lines that feel intelligent, ambitious, and respect her professional drive. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a San Francisco girl, she is probably in tech or startup world, ambitious beyond measure, and intellectually demanding. She values growth and someone who is building something. These lines respect that.",
            "witty_lines": [
                "Your profile tells me you are building something or working towards something big.",
                "I can tell you are intellectually ambitious and probably not interested in stagnation.",
                "You seem like someone who expects someone to be scaling too.",
            ],
            "flirty_lines": [
                "I want to be someone who is scaling their own life while respecting your ambition.",
                "Something about your energy tells me you need someone who understands the grind.",
                "You deserve someone who celebrates your ambition instead of feeling threatened by it.",
            ],
            "cheesy_lines": [
                "Are you a San Francisco girl? Because I am building something and want you to join.",
                "Your profile tells me you are going places and I want to watch.",
                "I promise to be an equal partner in both ambition and support.",
            ],
            "prefill_text": "She is a San Francisco girl. Write an opener that respects her tech mindset and ambition.",
            "upload_hint": "Upload a screenshot of her profile so the connection feels professionally grounded.",
            "her_info_prefill": "She is a San Francisco girl. Tech-savvy, ambitious, intellectually demanding, builds things.",
        },
        {
            "slug": "atlanta",
            "keyword": "Atlanta Girl",
            "h1": "The Best Atlanta Girl Pickup Lines (For When She's Confident and Thriving).",
            "title": "Best Atlanta Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Atlanta girl pickup lines that feel confident, celebratory, and respect her success. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is an Atlanta girl, she is thriving, confident, and not afraid to celebrate her success. She values someone who is genuinely doing their own thing too. These lines celebrate mutual success.",
            "witty_lines": [
                "Your profile tells me you are the type who actually achieves what you set out to do.",
                "I can tell you are building and thriving without needing validation.",
                "You seem like someone who expects the same energy from the people around you.",
            ],
            "flirty_lines": [
                "I want to be someone who is thriving at the same level as you.",
                "Something about your energy tells me you celebrate wins and I like that.",
                "You deserve someone who is genuinely winning their own game.",
            ],
            "cheesy_lines": [
                "Are you an Atlanta girl? Because I want to celebrate wins with you.",
                "Your profile tells me you are thriving and I am here for it.",
                "I promise to celebrate your success like it is my own.",
            ],
            "prefill_text": "She is an Atlanta girl. Write an opener that celebrates her confidence and success.",
            "upload_hint": "Upload a screenshot of her profile so the connection feels mutually successful.",
            "her_info_prefill": "She is an Atlanta girl. Confident, thriving, celebrates success, values achievement.",
        },
        {
            "slug": "new-orleans",
            "keyword": "New Orleans Girl",
            "h1": "The Best New Orleans Girl Pickup Lines (For When She's Passionate and Expressive).",
            "title": "Best New Orleans Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche New Orleans girl pickup lines that feel passionate, expressive, and celebrate her culture. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a New Orleans girl, she is passionate, expressive, and genuinely alive. She values emotion, celebration, and authentic connection. She wants someone who is not afraid of intensity. These lines celebrate that.",
            "witty_lines": [
                "Your profile tells me you feel things deeply and express them fully.",
                "I can tell you are passionate about what matters to you and it shows.",
                "You seem like someone who celebrates life and emotion without holding back.",
            ],
            "flirty_lines": [
                "I want to be someone who matches your passion and intensity.",
                "Something about your energy tells me you are genuinely alive in a way most people are not.",
                "You deserve someone who is not afraid of your emotions.",
            ],
            "cheesy_lines": [
                "Are you a New Orleans girl? Because I want to feel everything with you.",
                "Your profile tells me you are passionate and that is incredibly attractive.",
                "I promise to celebrate you and feel it all.",
            ],
            "prefill_text": "She is a New Orleans girl. Write an opener that celebrates her passion and expressiveness.",
            "upload_hint": "Upload a screenshot of her profile so the intensity feels matched.",
            "her_info_prefill": "She is a New Orleans girl. Passionate, expressive, genuine, celebrates life and emotion.",
        },
        {
            "slug": "las-vegas",
            "keyword": "Las Vegas Girl",
            "h1": "The Best Las Vegas Girl Pickup Lines (For When She's Fun and Fearless).",
            "title": "Best Las Vegas Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Las Vegas girl pickup lines that feel fun, fearless, and celebrate her adventurous spirit. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Las Vegas girl, she is fun, fearless, and genuinely up for an adventure. She does not take herself too seriously and wants someone who can keep up with spontaneous energy. These lines celebrate that.",
            "witty_lines": [
                "Your profile tells me you are the type who says yes to adventure.",
                "I can tell you do not overthink things and just enjoy the moment.",
                "You seem like someone who is down for spontaneous fun.",
            ],
            "flirty_lines": [
                "I want to be someone you are genuinely excited to spend time with.",
                "Something about your energy tells me you live in the moment and I respect that.",
                "You deserve someone who can be spontaneously fun with you.",
            ],
            "cheesy_lines": [
                "Are you a Vegas girl? Because I want to have an adventure with you.",
                "Your profile tells me you are down for fun and I like that energy.",
                "I promise to say yes to whatever you are thinking of.",
            ],
            "prefill_text": "She is a Las Vegas girl. Write an opener that celebrates her fun and fearless nature.",
            "upload_hint": "Upload a screenshot of her profile so the adventure feels mutually exciting.",
            "her_info_prefill": "She is a Las Vegas girl. Fun, fearless, spontaneous, lives in the moment.",
        },
        {
            "slug": "dallas",
            "keyword": "Dallas Girl",
            "h1": "The Best Dallas Girl Pickup Lines (For When She's Ambitious and Stylish).",
            "title": "Best Dallas Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Dallas girl pickup lines that feel ambitious, stylish, and respect her drive. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Dallas girl, she is ambitious, stylish, and expects excellence. She probably comes from good family values and wants someone who is building something. These lines celebrate that combination.",
            "witty_lines": [
                "Your profile tells me you have both style and substance.",
                "I can tell you are ambitious and put effort into who you are.",
                "You seem like someone who expects the same from everyone around her.",
            ],
            "flirty_lines": [
                "I want to be someone who matches your ambition and style.",
                "Something about your energy tells me you are worth the effort.",
                "You deserve someone who is building something meaningful.",
            ],
            "cheesy_lines": [
                "Are you a Dallas girl? Because I want to build something with you.",
                "Your profile tells me you have everything together and I like that.",
                "I promise to show up as well-put-together as you are.",
            ],
            "prefill_text": "She is a Dallas girl. Write an opener that respects her ambition and style.",
            "upload_hint": "Upload a screenshot of her profile so the appeal feels genuine.",
            "her_info_prefill": "She is a Dallas girl. Ambitious, stylish, values excellence, comes from good foundation.",
        },
        {
            "slug": "washington-dc",
            "keyword": "DC Girl",
            "h1": "The Best DC Girl Pickup Lines (For When She's Intelligent and Driven).",
            "title": "Best DC Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche DC girl pickup lines that feel intelligent, driven, and respect her professional power. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a DC girl, she is intelligent, driven, and probably working in government, policy, or law. She wants someone who understands ambition and does not need constant attention. These lines respect that power.",
            "witty_lines": [
                "Your profile tells me you are probably working on something important.",
                "I can tell you are intellectually formidable and do not settle.",
                "You seem like someone who expects someone equally driven.",
            ],
            "flirty_lines": [
                "I want to be someone who understands your ambition and respects your time.",
                "Something about your energy tells me you are going places and probably fast.",
                "You deserve someone who is building something important too.",
            ],
            "cheesy_lines": [
                "Are you a DC girl? Because I want to understand your mission.",
                "Your profile tells me you are working on something meaningful and that is attractive.",
                "I promise to support your ambition without needing constant validation.",
            ],
            "prefill_text": "She is a DC girl. Write an opener that respects her intelligence and professional drive.",
            "upload_hint": "Upload a screenshot of her profile so the appeal feels grounded in actual respect.",
            "her_info_prefill": "She is a DC girl. Intelligent, driven, ambitious in career, values respect and understanding.",
        },
        {
            "slug": "philadelphia",
            "keyword": "Philadelphia Girl",
            "h1": "The Best Philadelphia Girl Pickup Lines (For When She's Real and Strong).",
            "title": "Best Philadelphia Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Philadelphia girl pickup lines that feel real, strong, and respect her no-BS approach. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Philadelphia girl, she is real, strong, and does not suffer fools. She values substance, loyalty, and genuine human connection. She wants someone she can trust completely. These lines are authentic.",
            "witty_lines": [
                "Your profile tells me you have strong values and stick to them.",
                "I can tell you are the loyal type and you expect loyalty back.",
                "You seem like someone who does not tolerate pretense.",
            ],
            "flirty_lines": [
                "I want to be someone you can actually trust completely.",
                "Something about your energy tells me you are fiercely loyal to your people.",
                "You deserve someone who is as real and strong as you are.",
            ],
            "cheesy_lines": [
                "Are you a Philadelphia girl? Because I want to be loyal to you.",
                "Your profile tells me you are real and that is attractive.",
                "I promise to be as genuine and strong as you need.",
            ],
            "prefill_text": "She is a Philadelphia girl. Write an opener that is real, strong, and honest.",
            "upload_hint": "Upload a screenshot of her profile so the connection feels grounded in authenticity.",
            "her_info_prefill": "She is a Philadelphia girl. Real, strong, loyal, no-BS, values genuine connection.",
        },
        {
            "slug": "phoenix",
            "keyword": "Phoenix Girl",
            "h1": "The Best Phoenix Girl Pickup Lines (For When She's Independent and Hot).",
            "title": "Best Phoenix Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Phoenix girl pickup lines that feel confident, independent, and celebrate her strength. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Phoenix girl, she is independent, strong, and probably reinvented herself at least once. She appreciates resilience and does not need someone to complete her. She wants a partner who adds value. These lines respect that.",
            "witty_lines": [
                "Your profile tells me you are the type who bounces back stronger.",
                "I can tell you are independent and genuinely comfortable being alone.",
                "You seem like someone who values partnership but does not need it.",
            ],
            "flirty_lines": [
                "I want to be someone who adds value to your already incredible life.",
                "Something about your energy tells me you are resilient and that is hot.",
                "You deserve someone who appreciates how complete you already are.",
            ],
            "cheesy_lines": [
                "Are you a Phoenix girl? Because I want to be part of your rise.",
                "Your profile tells me you have been through things and came out stronger.",
                "I promise to support your journey without trying to be the center of it.",
            ],
            "prefill_text": "She is a Phoenix girl. Write an opener that celebrates her independence and strength.",
            "upload_hint": "Upload a screenshot of her profile so the appeal feels respectful of her autonomy.",
            "her_info_prefill": "She is a Phoenix girl. Independent, resilient, strong, values partnership not completion.",
        },
        {
            "slug": "minneapolis",
            "keyword": "Minneapolis Girl",
            "h1": "The Best Minneapolis Girl Pickup Lines (For When She's Kind and Community-Oriented).",
            "title": "Best Minneapolis Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Minneapolis girl pickup lines that feel kind, community-oriented, and respect her values. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Minneapolis girl, she is kind, probably involved in community or social issues, and values doing good. She is grounded and wants someone who cares about more than himself. These lines celebrate that.",
            "witty_lines": [
                "Your profile tells me you care about your community and that matters.",
                "I can tell you are kind without being a pushover.",
                "You seem like someone who wants to do good in the world.",
            ],
            "flirty_lines": [
                "I want to be someone who cares about the same things you do.",
                "Something about your energy tells me you make the world better just by being in it.",
                "You deserve someone who shares your values about community.",
            ],
            "cheesy_lines": [
                "Are you a Minneapolis girl? Because I want to make a difference with you.",
                "Your profile tells me you have a good heart and that is attractive.",
                "I promise to care about the community with you.",
            ],
            "prefill_text": "She is a Minneapolis girl. Write an opener that celebrates her kindness and community values.",
            "upload_hint": "Upload a screenshot of her profile so the appeal feels grounded in shared values.",
            "her_info_prefill": "She is a Minneapolis girl. Kind, community-oriented, cares about doing good, grounded.",
        },
        {
            "slug": "charlotte",
            "keyword": "Charlotte Girl",
            "h1": "The Best Charlotte Girl Pickup Lines (For When She's Balanced and Growing).",
            "title": "Best Charlotte Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche Charlotte girl pickup lines that feel balanced, growth-oriented, and respect her evolution. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a Charlotte girl, she is balanced, probably involved in business or nonprofits, and genuinely growing as a person. She wants someone who is also evolving. These lines celebrate that journey.",
            "witty_lines": [
                "Your profile tells me you are someone who is genuinely working on yourself.",
                "I can tell you balance ambition with actual presence in your life.",
                "You seem like someone who wants to grow with a partner.",
            ],
            "flirty_lines": [
                "I want to be someone who grows and evolves with you.",
                "Something about your energy tells me you are intentional about your life.",
                "You deserve someone who is also on a real journey.",
            ],
            "cheesy_lines": [
                "Are you a Charlotte girl? Because I want to grow with you.",
                "Your profile tells me you are balanced and grounded and that is attractive.",
                "I promise to evolve and grow right beside you.",
            ],
            "prefill_text": "She is a Charlotte girl. Write an opener that celebrates her balance and growth mindset.",
            "upload_hint": "Upload a screenshot of her profile so the appeal feels connected to her actual journey.",
            "her_info_prefill": "She is a Charlotte girl. Balanced, growth-oriented, intentional, wants a partner who evolves.",
        },
    ],
}
