DATA = {
    "category_slug": "wellness",
    "category_name": "Wellness & Self-Care",
    "sort_order": 14,
    "topics": [
        {
            "slug": "therapy-girl",
            "keyword": "Therapy Girl",
            "h1": "The Best Therapy Girl Pickup Lines (For When She Is Emotionally Intelligent).",
            "title": "Best Therapy Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche therapy girl pickup lines that feel emotionally aware, genuinely understanding, and psychologically literate. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a therapy girl, she is emotionally intelligent, talks about mental health, and values emotional growth. She wants someone who understands psychology. These lines honor that.",
            "witty_lines": [
                "Your profile has therapy girl energy — you understand emotional complexity.",
                "I can tell you speak the language of emotions and growth.",
                "You seem like someone who values mental health and self-awareness.",
            ],
            "flirty_lines": [
                "Your emotional intelligence is really attractive.",
                "Something about your energy tells me you are looking for someone psychologically aware.",
                "You carry yourself with this emotionally mature presence that is impressive.",
            ],
            "cheesy_lines": [
                "Are you a therapy girl? Because you just helped me understand myself better.",
                "Your profile tells me you are emotionally intelligent and deeply aware.",
                "I promise to work through things with you in the healthiest ways.",
            ],
            "prefill_text": "She is a therapy girl. Write an opener that celebrates her emotional intelligence.",
            "upload_hint": "Upload a screenshot of her profile so the psychological connection is real.",
            "her_info_prefill": "She is a therapy girl. Emotionally intelligent, values mental health, psychologically aware.",
        },
        {
            "slug": "manifestation-girl",
            "keyword": "Manifestation Girl",
            "h1": "The Best Manifestation Girl Pickup Lines (For When She Is Intentional).",
            "title": "Best Manifestation Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche manifestation girl pickup lines that feel intentional, manifestation-focused, and genuinely aligned. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a manifestation girl, she believes in intentional living and law of attraction. She wants someone aligned with her vision. These lines match that energy.",
            "witty_lines": [
                "Your profile has manifestation girl energy — you are intentional and aligned with your goals.",
                "I can tell you believe in creating your own reality through intention.",
                "You seem like someone who manifests what she wants.",
            ],
            "flirty_lines": [
                "Your intentional living approach is really attractive.",
                "Something about your energy tells me you are looking for someone aligned with your vision.",
                "You carry yourself with this purposeful presence that is inspiring.",
            ],
            "cheesy_lines": [
                "Are you a manifestation girl? Because I just manifested you.",
                "Your profile tells me you believe in aligned intentions.",
                "I promise to be aligned with your energy and vision.",
            ],
            "prefill_text": "She is a manifestation girl. Write an opener that celebrates her intentional energy.",
            "upload_hint": "Upload a screenshot of her profile so the alignment is real.",
            "her_info_prefill": "She is a manifestation girl. Intentional, believes in law of attraction, aligned.",
        },
        {
            "slug": "crystal-healing",
            "keyword": "Crystal Healing",
            "h1": "The Best Crystal Healing Girl Pickup Lines (For When She Believes in Energy).",
            "title": "Best Crystal Healing Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche crystal healing girl pickup lines that feel spiritual, energy-aware, and genuinely aligned. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into crystal healing, she believes in energy and spiritual wellness. She is in tune. These lines honor her spiritual awareness.",
            "witty_lines": [
                "Your profile has crystal healing energy — you are spiritually aware and energy-conscious.",
                "I can tell you believe in the power of energy and intention.",
                "You seem like someone who is in tune with herself and the world.",
            ],
            "flirty_lines": [
                "Your spiritual awareness is really attractive.",
                "Something about your energy tells me you are looking for someone similarly aligned.",
                "You carry yourself with this spiritually grounded presence that is beautiful.",
            ],
            "cheesy_lines": [
                "Are you crystal healing? Because your energy just healed my heart.",
                "Your profile tells me you are spiritually aligned and aware.",
                "I promise to match and support your energetic frequency.",
            ],
            "prefill_text": "She is into crystal healing. Write an opener that celebrates her spiritual energy.",
            "upload_hint": "Upload a screenshot of her profile so the spiritual connection is clear.",
            "her_info_prefill": "She is into crystal healing. Spiritual, energy-aware, believes in healing.",
        },
        {
            "slug": "meditation-girl",
            "keyword": "Meditation Girl",
            "h1": "The Best Meditation Girl Pickup Lines (For When She Is Calm and Present).",
            "title": "Best Meditation Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche meditation girl pickup lines that feel calm, present, and genuinely mindful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a meditation girl, she is present, calm, and mindful. She values peace. These lines honor her meditation practice.",
            "witty_lines": [
                "Your profile has meditation girl energy — you are calm, present, and mindful.",
                "I can tell you prioritize peace and inner stillness.",
                "You seem like someone who is genuinely present in every moment.",
            ],
            "flirty_lines": [
                "Your calm, present energy is really attractive.",
                "Something about your energy tells me you are looking for someone equally mindful.",
                "You carry yourself with this serene presence that is genuinely peaceful.",
            ],
            "cheesy_lines": [
                "Are you a meditation girl? Because you are my zen.",
                "Your profile tells me you value peace and presence.",
                "I promise to be present and peaceful with you.",
            ],
            "prefill_text": "She is a meditation girl. Write an opener that celebrates her calm presence.",
            "upload_hint": "Upload a screenshot of her profile so the mindfulness is shared.",
            "her_info_prefill": "She is a meditation girl. Calm, present, mindful, values peace.",
        },
        {
            "slug": "cold-plunge-girl",
            "keyword": "Cold Plunge Girl",
            "h1": "The Best Cold Plunge Girl Pickup Lines (For When She Is Brave and Into Biohacking).",
            "title": "Best Cold Plunge Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche cold plunge girl pickup lines that feel brave, biohack-focused, and genuinely intense. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she does cold plunges, she is brave, into biohacking, and willing to do hard things. She is intense. These lines honor her physical courage.",
            "witty_lines": [
                "Your profile has cold plunge girl energy — you are brave and into biohacking.",
                "I can tell you face discomfort head-on and use it for growth.",
                "You seem like someone who pushes her body for optimization.",
            ],
            "flirty_lines": [
                "Your brave intensity and commitment to growth are really attractive.",
                "Something about your energy tells me you are looking for someone equally willing to push.",
                "You carry yourself with this physically courageous presence that is impressive.",
            ],
            "cheesy_lines": [
                "Are you a cold plunge girl? Because you just gave me chills.",
                "Your profile tells me you are brave and committed to optimization.",
                "I promise to push myself alongside you.",
            ],
            "prefill_text": "She is a cold plunge girl. Write an opener that celebrates her brave intensity.",
            "upload_hint": "Upload a screenshot of her profile so the commitment is mutual.",
            "her_info_prefill": "She is a cold plunge girl. Brave, into biohacking, willing to do hard things.",
        },
        {
            "slug": "sauna-girl",
            "keyword": "Sauna Girl",
            "h1": "The Best Sauna Girl Pickup Lines (For When She Loves Wellness Rituals).",
            "title": "Best Sauna Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche sauna girl pickup lines that feel wellness-focused, ritual-oriented, and genuinely self-care-driven. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is a sauna girl, she values wellness rituals and self-care. She is intentional about recovery. These lines honor her wellness commitment.",
            "witty_lines": [
                "Your profile has sauna girl energy — you prioritize wellness rituals and recovery.",
                "I can tell you understand the importance of self-care and restoration.",
                "You seem like someone who invests in her health seriously.",
            ],
            "flirty_lines": [
                "Your commitment to wellness and self-care is really attractive.",
                "Something about your energy tells me you are looking for someone equally health-conscious.",
                "You carry yourself with this well-maintained, intentional presence that is impressive.",
            ],
            "cheesy_lines": [
                "Are you a sauna girl? Because you are making me hot.",
                "Your profile tells me you prioritize wellness and recovery.",
                "I promise to support your wellness journey.",
            ],
            "prefill_text": "She is a sauna girl. Write an opener that celebrates her wellness commitment.",
            "upload_hint": "Upload a screenshot of her profile so the self-care is mutual.",
            "her_info_prefill": "She is a sauna girl. Values wellness rituals, self-care, recovery-focused.",
        },
        {
            "slug": "clean-beauty",
            "keyword": "Clean Beauty",
            "h1": "The Best Clean Beauty Girl Pickup Lines (For When She Cares About What Goes On Her Skin).",
            "title": "Best Clean Beauty Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche clean beauty girl pickup lines that feel ingredient-aware, intentional, and genuinely health-conscious. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into clean beauty, she cares about ingredients and values health. She is thoughtful. These lines honor her ingredient awareness.",
            "witty_lines": [
                "Your profile has clean beauty energy — you care about what goes on your skin.",
                "I can tell you are thoughtful about ingredients and health.",
                "You seem like someone who invests in quality beauty products.",
            ],
            "flirty_lines": [
                "Your ingredient awareness and health consciousness are really attractive.",
                "Something about your energy tells me you are looking for someone equally thoughtful.",
                "You carry yourself with this intentional, health-conscious presence that is impressive.",
            ],
            "cheesy_lines": [
                "Are you clean beauty? Because you are naturally beautiful.",
                "Your profile tells me you care about what you put on your skin.",
                "I promise to be as pure and intentional with you.",
            ],
            "prefill_text": "She is into clean beauty. Write an opener that celebrates her ingredient awareness.",
            "upload_hint": "Upload a screenshot of her profile so the health consciousness is shared.",
            "her_info_prefill": "She is into clean beauty. Ingredient-aware, intentional, health-conscious.",
        },
        {
            "slug": "intermittent-fasting",
            "keyword": "Intermittent Fasting",
            "h1": "The Best Intermittent Fasting Girl Pickup Lines (For When She Is Disciplined).",
            "title": "Best Intermittent Fasting Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche intermittent fasting girl pickup lines that feel disciplined, health-optimized, and genuinely committed. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she practices intermittent fasting, she is disciplined and health-optimized. She is committed. These lines honor her metabolic discipline.",
            "witty_lines": [
                "Your profile has intermittent fasting girl energy — you are disciplined and health-optimized.",
                "I can tell you have serious commitment to your health habits.",
                "You seem like someone who understands nutrition and discipline.",
            ],
            "flirty_lines": [
                "Your discipline and health commitment are really attractive.",
                "Something about your energy tells me you are looking for someone equally committed.",
                "You carry yourself with this optimized, intentional presence that is impressive.",
            ],
            "cheesy_lines": [
                "Are you intermittent fasting? Because I want to feast on your company.",
                "Your profile tells me you have serious discipline.",
                "I promise to support your health goals.",
            ],
            "prefill_text": "She practices intermittent fasting. Write an opener that celebrates her discipline.",
            "upload_hint": "Upload a screenshot of her profile so the health commitment is mutual.",
            "her_info_prefill": "She practices intermittent fasting. Disciplined, health-optimized, committed.",
        },
        {
            "slug": "gratitude-practice",
            "keyword": "Gratitude Practice",
            "h1": "The Best Gratitude Practice Girl Pickup Lines (For When She Appreciates Life).",
            "title": "Best Gratitude Practice Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche gratitude practice girl pickup lines that feel appreciative, abundance-focused, and genuinely grateful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she practices gratitude, she appreciates life and focuses on abundance. She is optimistic. These lines honor her gratitude practice.",
            "witty_lines": [
                "Your profile has gratitude practice girl energy — you appreciate and focus on abundance.",
                "I can tell you find things to be grateful for constantly.",
                "You seem like someone whose optimism is genuinely grounded.",
            ],
            "flirty_lines": [
                "Your gratitude and appreciation for life are really attractive.",
                "Something about your energy tells me you find the good in everything.",
                "You carry yourself with this abundant, appreciative presence that is beautiful.",
            ],
            "cheesy_lines": [
                "Are you a gratitude practice? Because I am grateful for you.",
                "Your profile tells me you appreciate the good things in life.",
                "I promise to be someone you are grateful for.",
            ],
            "prefill_text": "She practices gratitude. Write an opener that celebrates her appreciation.",
            "upload_hint": "Upload a screenshot of her profile so the gratitude is mutual.",
            "her_info_prefill": "She practices gratitude. Appreciative, abundance-focused, optimistic.",
        },
        {
            "slug": "reiki",
            "keyword": "Reiki",
            "h1": "The Best Reiki Girl Pickup Lines (For When She Is Spiritually Healing).",
            "title": "Best Reiki Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche reiki girl pickup lines that feel spiritually healing, energy-work-focused, and genuinely sacred. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she does reiki, she is spiritually attuned and focused on healing energy. She is sacred. These lines honor her healing work.",
            "witty_lines": [
                "Your profile has reiki girl energy — you are spiritually attuned and healing.",
                "I can tell you work with energy and understand its power.",
                "You seem like someone whose presence alone heals.",
            ],
            "flirty_lines": [
                "Your healing energy and spiritual attunement are really attractive.",
                "Something about your energy tells me you are looking for someone spiritually aligned.",
                "You carry yourself with this sacred, healing presence that is beautiful.",
            ],
            "cheesy_lines": [
                "Are you reiki? Because you just healed my broken heart.",
                "Your profile tells me your hands have healing power.",
                "I promise to absorb and reciprocate your healing energy.",
            ],
            "prefill_text": "She does reiki. Write an opener that celebrates her healing energy.",
            "upload_hint": "Upload a screenshot of her profile so the spiritual connection is real.",
            "her_info_prefill": "She does reiki. Spiritually attuned, healing energy-focused, sacred.",
        },
        {
            "slug": "self-care-sunday",
            "keyword": "Self-Care Sunday",
            "h1": "The Best Self-Care Sunday Girl Pickup Lines (For When She Prioritizes Rest).",
            "title": "Best Self-Care Sunday Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche self-care Sunday girl pickup lines that feel restorative, rest-focused, and genuinely intentional. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she does self-care Sundays, she prioritizes rest and restoration. She is balanced. These lines honor her self-care commitment.",
            "witty_lines": [
                "Your profile has self-care Sunday girl energy — you prioritize rest and restoration.",
                "I can tell you understand the importance of taking care of yourself.",
                "You seem like someone who actually rests and recharges intentionally.",
            ],
            "flirty_lines": [
                "Your commitment to rest and restoration is really attractive.",
                "Something about your energy tells me you are looking for someone who also prioritizes balance.",
                "You carry yourself with this well-rested, intentional presence that is beautiful.",
            ],
            "cheesy_lines": [
                "Are you a self-care Sunday? Because you make me want to slow down.",
                "Your profile tells me you are intentional about rest.",
                "I promise to be someone you want to rest with.",
            ],
            "prefill_text": "She practices self-care Sundays. Write an opener that celebrates her rest commitment.",
            "upload_hint": "Upload a screenshot of her profile so the balance is mutual.",
            "her_info_prefill": "She practices self-care Sundays. Prioritizes rest, balanced, intentional.",
        },
        {
            "slug": "wellness-app-girl",
            "keyword": "Wellness App Girl",
            "h1": "The Best Wellness App Girl Pickup Lines (For When She Tracks Her Health).",
            "title": "Best Wellness App Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche wellness app girl pickup lines that feel data-driven, health-tracking-focused, and genuinely optimized. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she uses wellness apps, she tracks her health and is data-driven about wellness. She is organized. These lines honor her optimization focus.",
            "witty_lines": [
                "Your profile has wellness app girl energy — you track and optimize your health.",
                "I can tell you are data-driven about your wellness and take it seriously.",
                "You seem like someone who knows exactly how to optimize her life.",
            ],
            "flirty_lines": [
                "Your data-driven approach to wellness is really attractive.",
                "Something about your energy tells me you are looking for someone equally optimized.",
                "You carry yourself with this intentional, organized presence that is impressive.",
            ],
            "cheesy_lines": [
                "Are you a wellness app? Because my heart rate just went up.",
                "Your profile tells me you track and optimize everything.",
                "I promise to be worth tracking.",
            ],
            "prefill_text": "She uses wellness apps. Write an opener that celebrates her optimization focus.",
            "upload_hint": "Upload a screenshot of her profile so the health tracking is real.",
            "her_info_prefill": "She uses wellness apps. Data-driven, health-tracking-focused, optimized.",
        },
        {
            "slug": "sound-bath",
            "keyword": "Sound Bath",
            "h1": "The Best Sound Bath Girl Pickup Lines (For When She Heals Through Vibration).",
            "title": "Best Sound Bath Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche sound bath girl pickup lines that feel vibrationally aligned, spiritually healing, and genuinely peaceful. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she does sound baths, she heals through vibration and is spiritually aligned. She is peaceful. These lines honor her vibrational healing.",
            "witty_lines": [
                "Your profile has sound bath girl energy — you heal through vibration and frequency.",
                "I can tell you are attuned to the healing power of sound.",
                "You seem like someone whose presence resonates healing.",
            ],
            "flirty_lines": [
                "Your vibrational healing and spiritual attunement are really attractive.",
                "Something about your energy tells me you are looking for someone at your frequency.",
                "You carry yourself with this resonant, peaceful presence that is beautiful.",
            ],
            "cheesy_lines": [
                "Are you a sound bath? Because your frequency is healing me.",
                "Your profile tells me your vibration is pure and healing.",
                "I promise to resonate at your healing frequency.",
            ],
            "prefill_text": "She does sound baths. Write an opener that celebrates her vibrational healing.",
            "upload_hint": "Upload a screenshot of her profile so the frequency match is real.",
            "her_info_prefill": "She does sound baths. Heals through vibration, spiritually aligned, peaceful.",
        },
        {
            "slug": "plant-medicine",
            "keyword": "Plant Medicine",
            "h1": "The Best Plant Medicine Girl Pickup Lines (For When She Is Spiritually Conscious).",
            "title": "Best Plant Medicine Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche plant medicine girl pickup lines that feel spiritually conscious, healing-focused, and genuinely transformative. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is into plant medicine, she is spiritually conscious and open to transformation. She is brave. These lines honor her spiritual openness.",
            "witty_lines": [
                "Your profile has plant medicine girl energy — you are spiritually conscious and open.",
                "I can tell you are willing to go deep and transform.",
                "You seem like someone who understands the healing power of nature.",
            ],
            "flirty_lines": [
                "Your spiritual consciousness and openness to transformation are really attractive.",
                "Something about your energy tells me you are looking for deep spiritual connection.",
                "You carry yourself with this transformed, spiritually aware presence that is beautiful.",
            ],
            "cheesy_lines": [
                "Are you plant medicine? Because you are healing me on a cellular level.",
                "Your profile tells me you are spiritually awake and transforming.",
                "I promise to support your spiritual evolution.",
            ],
            "prefill_text": "She is into plant medicine. Write an opener that celebrates her spiritual consciousness.",
            "upload_hint": "Upload a screenshot of her profile so the transformation is mutual.",
            "her_info_prefill": "She is into plant medicine. Spiritually conscious, open to transformation, brave.",
        },
        {
            "slug": "morning-routine-girl",
            "keyword": "Morning Routine Girl",
            "h1": "The Best Morning Routine Girl Pickup Lines (For When She Starts Strong).",
            "title": "Best Morning Routine Girl Pickup Lines | TryAgainText",
            "meta_description": "Use niche morning routine girl pickup lines that feel intentional, routine-focused, and genuinely disciplined. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she has a strong morning routine, she is disciplined and intentional about starting her day right. She is consistent. These lines honor her routine commitment.",
            "witty_lines": [
                "Your profile has morning routine girl energy — you start strong and intentional.",
                "I can tell you have discipline and know the power of morning rituals.",
                "You seem like someone who owns her mornings.",
            ],
            "flirty_lines": [
                "Your discipline and intention around mornings are really attractive.",
                "Something about your energy tells me you are looking for someone equally committed to growth.",
                "You carry yourself with this intentional, strong presence that is impressive.",
            ],
            "cheesy_lines": [
                "Are you a morning routine girl? Because you are making my morning better.",
                "Your profile tells me you start every day with intention.",
                "I promise to support your morning ritual.",
            ],
            "prefill_text": "She has a strong morning routine. Write an opener that celebrates her discipline.",
            "upload_hint": "Upload a screenshot of her profile so the morning commitment is real.",
            "her_info_prefill": "She has a strong morning routine. Disciplined, intentional, consistent.",
        },
    ],
}
