DATA = {
    "category_slug": "zodiac-signs",
    "category_name": "Zodiac Signs",
    "sort_order": 1,
    "topics": [
        {
            "slug": "aries",
            "keyword": "Aries",
            "h1": "The Best Aries Pickup Lines (For When the Energy Is Fire Sign).",
            "title": "Best Aries Pickup Lines | TryAgainText",
            "meta_description": "Use niche Aries pickup lines that feel bold, flirty, and confident. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "If she is an Aries, she values directness and confidence. Generic openers will not cut it. These lines match that bold fire-sign energy without being try-hard. Use one as a starting point, then personalize it.",
            "witty_lines": [
                "You give off main character energy and I am here to audition for the love interest.",
                "I can tell you are an Aries because your profile has more confidence than most people's entire personality.",
                "Something tells me you are the type who texts back fast and says exactly what you mean. I respect that.",
            ],
            "flirty_lines": [
                "Your energy is magnetic and I am not even going to pretend I was not immediately drawn in.",
                "I like that your profile does not try too hard. That effortless confidence is genuinely attractive.",
                "You seem like someone who knows what she wants. I would love to find out if that includes coffee with me.",
            ],
            "cheesy_lines": [
                "Are you an Aries? Because you just charged straight into my thoughts and took over.",
                "Mars rules your sign and you just ruled my entire feed. Coincidence? I think not.",
                "I must be a moth because your fire sign energy is pulling me right in.",
            ],
            "prefill_text": "Her bio mentions Aries or fire sign energy. Write a bold, playful opener that matches her confident vibe.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her sign.",
            "her_info_prefill": "She is an Aries. Her profile has confident, high-energy photos. She seems direct and fun.",
        },
        {
            "slug": "taurus",
            "keyword": "Taurus",
            "h1": "The Best Taurus Pickup Lines (For When She Appreciates the Finer Things).",
            "title": "Best Taurus Pickup Lines | TryAgainText",
            "meta_description": "Use niche Taurus pickup lines that feel grounded, flirty, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Taurus energy is all about comfort, loyalty, and sensory pleasure. She probably loves good food, cozy settings, and people who are genuine. These lines lean into that without being generic.",
            "witty_lines": [
                "You seem like someone who has strong opinions about restaurants and I find that incredibly attractive.",
                "Your profile has this grounded, effortless quality that makes me think you actually know what you like. Rare.",
                "I can tell you are a Taurus because your aesthetic is too intentional to be accidental.",
            ],
            "flirty_lines": [
                "Something about your energy says you appreciate someone who shows up with a real plan, not just vibes. So here is mine: dinner.",
                "Your profile feels warm, unhurried, and very easy on the eyes. I would love to match that energy in person.",
                "I get the sense a date with you would involve great food, better conversation, and zero awkward silences.",
            ],
            "cheesy_lines": [
                "Are you a Taurus? Because I am already emotionally invested and we have not even talked yet.",
                "Venus rules your sign and honestly, looking at your profile, that checks out completely.",
                "They say Taurus is the most stubborn sign. I am stubbornly refusing to not message you.",
            ],
            "prefill_text": "Her bio mentions Taurus or earth sign energy. Write a warm, grounded opener that feels genuine and unhurried.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her sign.",
            "her_info_prefill": "She is a Taurus. Her photos have cozy, aesthetic vibes. She seems loyal, grounded, and into good food.",
        },
        {
            "slug": "gemini",
            "keyword": "Gemini",
            "h1": "The Best Gemini Pickup Lines (For When the Conversation Needs to Be Sharp).",
            "title": "Best Gemini Pickup Lines | TryAgainText",
            "meta_description": "Use niche Gemini pickup lines that feel witty, playful, and quick. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Geminis thrive on wit, variety, and mental stimulation. A boring opener is dead on arrival. These lines match her dual energy and keep things interesting from the first message.",
            "witty_lines": [
                "I was going to pick just one thing from your profile to comment on, but you are a Gemini so I know you can handle multitasking.",
                "Your profile gives off the vibe of someone who can hold three conversations at once and win all of them.",
                "I can tell you are a Gemini because your bio has more layers than most people's entire personality.",
            ],
            "flirty_lines": [
                "You seem like the kind of person who makes everyone around her funnier. I want to test that theory.",
                "Your energy is playful and sharp and I am immediately interested in where this conversation goes.",
                "I like that your profile keeps me guessing. That is way more attractive than predictable.",
            ],
            "cheesy_lines": [
                "Are you a Gemini? Because I feel like I just matched with two amazing people at once.",
                "Mercury rules your sign, which explains why your profile moves at the speed of interesting.",
                "They warned me about Geminis. They did not warn me I would enjoy it this much.",
            ],
            "prefill_text": "Her bio mentions Gemini or air sign energy. Write a witty, fast-paced opener that keeps up with her energy.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her sign.",
            "her_info_prefill": "She is a Gemini. Her profile is playful and quick-witted. She seems social, curious, and hard to bore.",
        },
        {
            "slug": "cancer",
            "keyword": "Cancer",
            "h1": "The Best Cancer Pickup Lines (For When She Values Real Connection).",
            "title": "Best Cancer Pickup Lines | TryAgainText",
            "meta_description": "Use niche Cancer pickup lines that feel warm, genuine, and emotionally tuned in. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Cancers value emotional depth, loyalty, and sincerity. Surface-level openers will not land. These lines show genuine warmth and interest without being overwhelming.",
            "witty_lines": [
                "Your profile has this warm, inviting energy that makes me want to actually say something real instead of something clever.",
                "I can tell you are a Cancer because your vibe is cozy, emotionally intelligent, and slightly guarded. I respect all three.",
                "You seem like someone who remembers the small details. So here is mine: I liked your profile enough to write this from scratch.",
            ],
            "flirty_lines": [
                "Something about your profile makes me want to skip the small talk and go straight to the good conversation.",
                "You give off the kind of warmth that makes people feel comfortable immediately. That is a genuinely rare quality.",
                "I like that your profile feels honest. It makes me want to be honest too \u2014 I think you are really interesting.",
            ],
            "cheesy_lines": [
                "Are you a Cancer? Because I am already feeling emotionally attached and we have not even spoken.",
                "The moon rules your sign, and you just became the center of my emotional orbit.",
                "They say Cancers have hard shells and soft hearts. I am ready to earn my way past the shell.",
            ],
            "prefill_text": "Her bio mentions Cancer or water sign energy. Write a warm, sincere opener that feels emotionally genuine.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her sign.",
            "her_info_prefill": "She is a Cancer. Her profile has cozy photos and thoughtful details. She seems nurturing, loyal, and emotionally intelligent.",
        },
        {
            "slug": "leo",
            "keyword": "Leo",
            "h1": "The Best Leo Pickup Lines (For When She Deserves the Spotlight).",
            "title": "Best Leo Pickup Lines | TryAgainText",
            "meta_description": "Use niche Leo pickup lines that feel confident, admiring, and fun. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Leos love attention, but they love earned attention even more. A lazy compliment will not work. These lines show real appreciation for her energy while keeping things playful.",
            "witty_lines": [
                "Your profile has more charisma than most people's entire social media presence. That takes talent.",
                "I can tell you are a Leo because you turned a dating app profile into a personal highlight reel and it works.",
                "You seem like the kind of person who walks into a room and changes the energy. I noticed.",
            ],
            "flirty_lines": [
                "Your photos have this glow that makes the rest of my feed look dull. That is meant as a sincere compliment.",
                "I like that you are clearly confident and still approachable. That combination is extremely attractive.",
                "You deserve a message that actually matches your energy, so here is me trying my best.",
            ],
            "cheesy_lines": [
                "Are you a Leo? Because you are absolutely the main character of this app right now.",
                "The Sun rules your sign, and honestly, your profile is the brightest thing I have seen today.",
                "They say Leos love attention. Consider this message my formal application for your attention.",
            ],
            "prefill_text": "Her bio mentions Leo or fire sign energy. Write a confident, admiring opener that does not feel generic.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her sign.",
            "her_info_prefill": "She is a Leo. Her photos are bold and well-curated. She seems charismatic, confident, and fun.",
        },
        {
            "slug": "virgo",
            "keyword": "Virgo",
            "h1": "The Best Virgo Pickup Lines (For When She Notices Every Detail).",
            "title": "Best Virgo Pickup Lines | TryAgainText",
            "meta_description": "Use niche Virgo pickup lines that feel thoughtful, specific, and grounded. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Virgos notice everything, so sloppy openers are an instant turnoff. These lines are specific, well-crafted, and demonstrate real effort \u2014 exactly what a Virgo appreciates.",
            "witty_lines": [
                "I can tell you are a Virgo because your profile is organized, intentional, and better than ninety percent of what is on here.",
                "You seem like someone who proofreads her texts before sending. I respect that energy deeply.",
                "Your profile is so well put together that I rewrote this opener twice before sending it. You set the standard.",
            ],
            "flirty_lines": [
                "Something about how carefully you built your profile tells me you are thoughtful about everything. I find that really attractive.",
                "You have this quiet confidence that makes me want to say something worth your attention.",
                "I like that your profile is specific. It makes me think a conversation with you would actually go somewhere.",
            ],
            "cheesy_lines": [
                "Are you a Virgo? Because you just analyzed my heart and found it available.",
                "Mercury rules your sign, which explains why your profile communicates more in six photos than most people do in six paragraphs.",
                "They say Virgos are perfectionists. Your profile is the evidence.",
            ],
            "prefill_text": "Her bio mentions Virgo or earth sign energy. Write a clean, thoughtful opener that feels intentional and specific.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her sign.",
            "her_info_prefill": "She is a Virgo. Her profile is clean and well-organized. She seems smart, observant, and detail-oriented.",
        },
        {
            "slug": "libra",
            "keyword": "Libra",
            "h1": "The Best Libra Pickup Lines (For When the Aesthetic Is Everything).",
            "title": "Best Libra Pickup Lines | TryAgainText",
            "meta_description": "Use niche Libra pickup lines that feel charming, balanced, and aesthetically aware. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Libras value harmony, beauty, and good conversation. They want someone who can match their social grace and bring genuine charm. These lines hit that balance.",
            "witty_lines": [
                "Your profile has this effortless balance of style and substance that most people cannot pull off. You clearly can.",
                "I can tell you are a Libra because your aesthetic game is immaculate and you probably spent an hour choosing those photos.",
                "You seem like someone who makes everything around her more beautiful. That includes my match list.",
            ],
            "flirty_lines": [
                "Venus rules your sign and I can see why \u2014 your profile is genuinely lovely to look at.",
                "You have this warm, graceful energy that makes me want to be at my most charming for you.",
                "I like that your profile feels curated without trying too hard. That balance is really attractive.",
            ],
            "cheesy_lines": [
                "Are you a Libra? Because I have been weighing my options and you just tipped the scales completely.",
                "They say Libras cannot make decisions. But matching with you was the easiest decision I have made all week.",
                "Your sign is represented by scales, and your profile just balanced out my entire day.",
            ],
            "prefill_text": "Her bio mentions Libra or air sign energy. Write a charming, balanced opener that feels polished and warm.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her sign.",
            "her_info_prefill": "She is a Libra. Her photos are aesthetic and well-composed. She seems charming, social, and style-conscious.",
        },
        {
            "slug": "scorpio",
            "keyword": "Scorpio",
            "h1": "The Best Scorpio Pickup Lines (For When the Vibes Are Intense).",
            "title": "Best Scorpio Pickup Lines | TryAgainText",
            "meta_description": "Use niche Scorpio pickup lines that feel magnetic, intense, and specific. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Scorpios are intense, perceptive, and allergic to anything fake. Surface-level charm will not work. These lines lean into that magnetic energy without being too heavy.",
            "witty_lines": [
                "I can tell you are a Scorpio because your profile has this magnetic pull that is hard to explain but impossible to ignore.",
                "You seem like someone who can read people in about thirty seconds. I am hoping I survived the scan.",
                "Your profile has layers. Most people do not have layers. I am intrigued.",
            ],
            "flirty_lines": [
                "There is something about your energy that makes me want to skip the games and just be real with you.",
                "Your profile has this intensity that is genuinely attractive. I wanted to match that with my opener.",
                "I like that you do not try to be approachable. That makes you more interesting, not less.",
            ],
            "cheesy_lines": [
                "Are you a Scorpio? Because you have been living in my subconscious since I saw your profile.",
                "Pluto rules your sign, which explains why your profile just rearranged my entire emotional landscape.",
                "They warned me about Scorpios. They forgot to mention I would enjoy the danger this much.",
            ],
            "prefill_text": "Her bio mentions Scorpio or water sign energy. Write an intense, honest opener that does not feel surface-level.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her sign.",
            "her_info_prefill": "She is a Scorpio. Her photos have a dark, magnetic aesthetic. She seems intense, perceptive, and selective.",
        },
        {
            "slug": "sagittarius",
            "keyword": "Sagittarius",
            "h1": "The Best Sagittarius Pickup Lines (For When She Lives for Adventure).",
            "title": "Best Sagittarius Pickup Lines | TryAgainText",
            "meta_description": "Use niche Sagittarius pickup lines that feel adventurous, fun, and free-spirited. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Sagittarius energy is all about freedom, adventure, and big ideas. She does not want to be tied down by boring conversation. These lines match her explorer spirit.",
            "witty_lines": [
                "Your profile reads like a travel blog I actually want to follow. Where to next?",
                "I can tell you are a Sagittarius because your bio has more passport stamps than most people's entire photo library.",
                "You seem like someone who says yes to spontaneous plans and no to boring conversations. I am here for both.",
            ],
            "flirty_lines": [
                "Your adventurous energy is contagious and I would love to be the person you text from your next trip.",
                "I like that your profile feels free and unfiltered. That kind of energy is really hard to find.",
                "You seem like someone who turns a random Tuesday into an adventure. I want that energy in my life.",
            ],
            "cheesy_lines": [
                "Are you a Sagittarius? Because you just shot an arrow straight through my dating app defenses.",
                "Jupiter rules your sign, which explains why your personality feels larger than this entire app.",
                "They say Sagittarius never stays in one place. Stay in my messages and I will make it worth it.",
            ],
            "prefill_text": "Her bio mentions Sagittarius or fire sign energy. Write an adventurous, free-spirited opener that feels fun.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her sign.",
            "her_info_prefill": "She is a Sagittarius. Her photos involve travel and outdoor adventures. She seems spontaneous, fun, and independent.",
        },
        {
            "slug": "capricorn",
            "keyword": "Capricorn",
            "h1": "The Best Capricorn Pickup Lines (For When She Has Her Life Together).",
            "title": "Best Capricorn Pickup Lines | TryAgainText",
            "meta_description": "Use niche Capricorn pickup lines that feel ambitious, grounded, and real. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Capricorns are goal-oriented, practical, and unimpressed by lazy effort. She wants someone who shows up with intention. These lines demonstrate that.",
            "witty_lines": [
                "Your profile has the energy of someone who has a five-year plan and somehow still makes it look fun.",
                "I can tell you are a Capricorn because your life looks like it runs on a spreadsheet and honestly that is attractive.",
                "You seem like someone who does not waste time on things that are not worth it. I hope this message qualifies.",
            ],
            "flirty_lines": [
                "There is something about someone who clearly has her life together and still chooses to be on here that I find very appealing.",
                "Your profile has this quiet ambition that makes me want to bring my best to this conversation.",
                "I like that you seem grounded. It makes me think a date with you would actually be worth getting dressed up for.",
            ],
            "cheesy_lines": [
                "Are you a Capricorn? Because you just climbed to the top of my match list with zero effort.",
                "Saturn rules your sign, which explains why you seem wise beyond your profile photos.",
                "They say Capricorns are hard to impress. Consider this message my best attempt at the job interview.",
            ],
            "prefill_text": "Her bio mentions Capricorn or earth sign energy. Write a grounded, intentional opener that respects her time.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her sign.",
            "her_info_prefill": "She is a Capricorn. Her profile is polished and intentional. She seems ambitious, grounded, and no-nonsense.",
        },
        {
            "slug": "aquarius",
            "keyword": "Aquarius",
            "h1": "The Best Aquarius Pickup Lines (For When She Thinks Different).",
            "title": "Best Aquarius Pickup Lines | TryAgainText",
            "meta_description": "Use niche Aquarius pickup lines that feel original, intellectual, and unconventional. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Aquarians value originality, intellect, and authenticity. Cookie-cutter openers are an instant skip. These lines match her unconventional energy and show you actually think.",
            "witty_lines": [
                "Your profile has this vibe that says you have opinions about things most people have never even considered. I am into it.",
                "I can tell you are an Aquarius because your bio reads like it was written by someone from the future.",
                "You seem like the kind of person who would rather have a weird, honest conversation than a polite, boring one.",
            ],
            "flirty_lines": [
                "Something about your profile tells me you see the world differently. I would love to hear how.",
                "Your energy is unique in a way that makes me want to actually think before I message. So here I am, thinking.",
                "I like that your profile does not follow the formula. That kind of originality is really attractive.",
            ],
            "cheesy_lines": [
                "Are you an Aquarius? Because you just disrupted my entire swiping pattern.",
                "Uranus rules your sign, which explains why your profile feels like it is from a completely different dimension.",
                "They say Aquarius is the rebel of the zodiac. You just rebelled against every boring profile on this app.",
            ],
            "prefill_text": "Her bio mentions Aquarius or air sign energy. Write an original, intellectual opener that does not follow the typical formula.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her sign.",
            "her_info_prefill": "She is an Aquarius. Her profile is unconventional and interesting. She seems intellectual, independent, and original.",
        },
        {
            "slug": "pisces",
            "keyword": "Pisces",
            "h1": "The Best Pisces Pickup Lines (For When She Lives in Her Own World).",
            "title": "Best Pisces Pickup Lines | TryAgainText",
            "meta_description": "Use niche Pisces pickup lines that feel dreamy, creative, and emotionally aware. Then generate a custom opener from her exact profile vibe.",
            "seo_intro": "Pisces are creative, empathetic, and deeply intuitive. They want someone who can match their emotional depth without being overbearing. These lines hit that sweet spot.",
            "witty_lines": [
                "Your profile has this dreamy, creative energy that makes me think you see beauty in things most people walk right past.",
                "I can tell you are a Pisces because your vibe is part artist, part empath, and entirely magnetic.",
                "You seem like someone whose playlist would change my entire mood. I mean that as the highest compliment.",
            ],
            "flirty_lines": [
                "Something about your profile feels like a poem I want to read more than once. That is rare.",
                "You have this gentle, creative warmth that makes me want to say something real instead of something smooth.",
                "I like that your profile feels like it was made from the heart. It makes me want to be genuine with you.",
            ],
            "cheesy_lines": [
                "Are you a Pisces? Because I am already swimming in feelings and we have not even talked.",
                "Neptune rules your sign, which explains why your profile feels like a beautiful, hazy dream.",
                "They say Pisces live in their own world. Can I visit? Yours looks way better than mine.",
            ],
            "prefill_text": "Her bio mentions Pisces or water sign energy. Write a dreamy, emotionally genuine opener that feels creative.",
            "upload_hint": "Upload a screenshot of her profile so the opener matches her actual vibe, not just her sign.",
            "her_info_prefill": "She is a Pisces. Her profile has dreamy, artistic photos. She seems creative, empathetic, and emotionally deep.",
        },
    ],
}
