# Generated by Django 5.2.4 on 2026-03-04 06:53

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def set_published_at_from_created_at(apps, schema_editor):
    CommunityPost = apps.get_model('community', 'CommunityPost')
    CommunityPost.objects.filter(created_at__isnull=False).update(
        published_at=models.F('created_at')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitypost',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='communitypost',
            name='community_c_categor_98a26b_idx',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='author_display_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='published_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.RunPython(
            set_published_at_from_created_at,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['category', 'is_deleted', '-published_at'], name='community_c_categor_da2252_idx'),
        ),
    ]
