# Generated by Django 5.2.4 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_communitypost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='author_display_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
