# Generated by Django 5.2.4 on 2026-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_communitycomment_author_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='category',
            field=models.CharField(
                choices=[
                    ('help_me_reply', 'Help Me Reply'),
                    ('dating_advice', 'Dating Advice'),
                    ('rate_my_profile', 'Rate My Profile'),
                    ('wins', 'Wins'),
                ],
                max_length=20,
            ),
        ),
    ]
