# Generated by Django 5.2.4 on 2026-03-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_communitypost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
