# Generated by Django 5.2.4 on 2025-07-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='what_happened',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
