# Generated by Django 5.2.4 on 2025-08-02 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversation_platform_conversation_what_happened'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditPurchase',
        ),
    ]
