# Generated by Django 5.2.4 on 2025-08-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_delete_creditpurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='what_happened',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='platform',
            new_name='tone',
        ),
    ]
