# Generated by Django 5.2.4 on 2025-08-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_rename_what_happened_conversation_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='tone',
        ),
        migrations.AddField(
            model_name='conversation',
            name='her_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='situation',
            field=models.CharField(default='h', max_length=150),
            preserve_default=False,
        ),
    ]
