# Generated by Django 5.2.4 on 2025-08-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_remove_conversation_goal_remove_conversation_tone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcredit',
            name='balance',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
