# Generated by Django 5.2.4 on 2025-09-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0007_copyevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('bug', 'Bug Report'), ('payment', 'Payments'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrialIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('trial_used', models.BooleanField(default=False)),
                ('credits_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='chatcredit',
            name='signup_bonus_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatcredit',
            name='total_earned',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='chatcredit',
            name='total_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatcredit',
            name='balance',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
