# Generated by Django 5.2.4 on 2026-01-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0013_daily_usage_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesttrial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
