# Generated by Django 5.2.4 on 2026-02-07 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0014_alter_guesttrial_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_daily_credit_limit', models.PositiveIntegerField(default=3, help_text='Daily shared credit pool for free registered users (replies + openers)')),
                ('guest_lifetime_credits', models.PositiveIntegerField(default=3, help_text='Lifetime credits for guest (unauthenticated) users')),
                ('sub_opener_tier1', models.PositiveIntegerField(default=8, help_text='Openers 1 to N: Pro model (High thinking)')),
                ('sub_opener_tier2', models.PositiveIntegerField(default=50, help_text='Openers N+1 to M: Flash model (High thinking). M+ uses GPT fallback')),
                ('sub_reply_tier1', models.PositiveIntegerField(default=50, help_text='Replies 1 to N: Flash model (High thinking)')),
                ('sub_reply_tier2', models.PositiveIntegerField(default=100, help_text='Replies N+1 to M: Flash model (Low thinking). M+ uses GPT fallback')),
                ('subscriber_weekly_limit', models.PositiveIntegerField(default=400, help_text='Legacy weekly fair-use cap for subscribers')),
                ('free_reply_model', models.CharField(default='gemini-3-flash-preview', help_text='AI model for free user replies', max_length=100)),
                ('free_opener_model', models.CharField(default='gemini-3-flash-preview', help_text='AI model for free user openers', max_length=100)),
                ('fallback_model', models.CharField(default='gpt-4.1-mini-2025-04-14', help_text='Fallback model (GPT) used after tier2 threshold', max_length=100)),
                ('free_reply_thinking', models.CharField(default='high', help_text='Thinking level for free user replies (low/medium/high)', max_length=20)),
                ('free_opener_thinking', models.CharField(default='high', help_text='Thinking level for free user openers (low/medium/high)', max_length=20)),
                ('ocr_thinking', models.CharField(default='low', help_text='Thinking level for OCR extraction (low/medium/high)', max_length=20)),
                ('blur_preview_word_count', models.PositiveIntegerField(default=3, help_text='Number of visible words shown before the locked block')),
            ],
            options={
                'verbose_name': 'Mobile App Config',
                'verbose_name_plural': 'Mobile App Config',
            },
        ),
        migrations.AddField(
            model_name='chatcredit',
            name='free_daily_credits_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatcredit',
            name='free_daily_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LockedReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_json', models.TextField(help_text='Full AI-generated JSON array of suggestions')),
                ('preview', models.JSONField(help_text='List of first N words per suggestion (sent to client)')),
                ('reply_type', models.CharField(choices=[('reply', 'Reply'), ('opener', 'Opener')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unlocked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
