# Generated by Django 5.2.4 on 2026-02-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0015_mobileappconfig_chatcredit_free_daily_credits_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappconfig',
            name='sub_opener_tier1_model',
            field=models.CharField(default='gemini-3-pro-preview', help_text='Model for opener Tier 1', max_length=100),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='sub_opener_tier1_thinking',
            field=models.CharField(default='high', help_text='Thinking level for opener Tier 1 (low/medium/high)', max_length=20),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='sub_opener_tier2_model',
            field=models.CharField(default='gemini-3-flash-preview', help_text='Model for opener Tier 2', max_length=100),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='sub_opener_tier2_thinking',
            field=models.CharField(default='high', help_text='Thinking level for opener Tier 2 (low/medium/high)', max_length=20),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='sub_reply_tier1_model',
            field=models.CharField(default='gemini-3-flash-preview', help_text='Model for reply Tier 1', max_length=100),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='sub_reply_tier1_thinking',
            field=models.CharField(default='high', help_text='Thinking level for reply Tier 1 (low/medium/high)', max_length=20),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='sub_reply_tier2_model',
            field=models.CharField(default='gemini-3-flash-preview', help_text='Model for reply Tier 2', max_length=100),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='sub_reply_tier2_thinking',
            field=models.CharField(default='low', help_text='Thinking level for reply Tier 2 (low/medium/high)', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobileappconfig',
            name='sub_opener_tier1',
            field=models.PositiveIntegerField(default=8, help_text='Openers 1..N use Tier 1 model/thinking'),
        ),
        migrations.AlterField(
            model_name='mobileappconfig',
            name='sub_opener_tier2',
            field=models.PositiveIntegerField(default=50, help_text='Openers N+1..M use Tier 2 model/thinking. Beyond M uses fallback'),
        ),
        migrations.AlterField(
            model_name='mobileappconfig',
            name='sub_reply_tier1',
            field=models.PositiveIntegerField(default=50, help_text='Replies 1..N use Tier 1 model/thinking'),
        ),
        migrations.AlterField(
            model_name='mobileappconfig',
            name='sub_reply_tier2',
            field=models.PositiveIntegerField(default=100, help_text='Replies N+1..M use Tier 2 model/thinking. Beyond M uses fallback'),
        ),
    ]
