# Generated by Django 5.2.4 on 2026-02-07 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0016_mobileappconfig_sub_opener_tier1_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileappconfig',
            name='sub_opener_tier1',
        ),
        migrations.RemoveField(
            model_name='mobileappconfig',
            name='sub_opener_tier1_model',
        ),
        migrations.RemoveField(
            model_name='mobileappconfig',
            name='sub_opener_tier1_thinking',
        ),
        migrations.RemoveField(
            model_name='mobileappconfig',
            name='sub_opener_tier2',
        ),
        migrations.RemoveField(
            model_name='mobileappconfig',
            name='sub_opener_tier2_model',
        ),
        migrations.RemoveField(
            model_name='mobileappconfig',
            name='sub_opener_tier2_thinking',
        ),
        migrations.RemoveField(
            model_name='mobileappconfig',
            name='sub_reply_tier1',
        ),
        migrations.RemoveField(
            model_name='mobileappconfig',
            name='sub_reply_tier1_model',
        ),
        migrations.RemoveField(
            model_name='mobileappconfig',
            name='sub_reply_tier1_thinking',
        ),
        migrations.RemoveField(
            model_name='mobileappconfig',
            name='sub_reply_tier2',
        ),
        migrations.RemoveField(
            model_name='mobileappconfig',
            name='sub_reply_tier2_model',
        ),
        migrations.RemoveField(
            model_name='mobileappconfig',
            name='sub_reply_tier2_thinking',
        ),
        migrations.CreateModel(
            name='DegradationTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_type', models.CharField(choices=[('opener', 'Opener'), ('reply', 'Reply')], max_length=10)),
                ('threshold', models.PositiveIntegerField(help_text='Use this model/thinking for requests 1..N (cumulative daily count)')),
                ('model', models.CharField(help_text='e.g. gemini-3-pro-preview, gemini-3-flash-preview', max_length=100)),
                ('thinking_level', models.CharField(blank=True, default='high', help_text='minimal/low/medium/high. Leave blank for GPT models.', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower = used first')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='conversation.mobileappconfig')),
            ],
            options={
                'verbose_name': 'Degradation Tier',
                'ordering': ['tier_type', 'sort_order', 'threshold'],
            },
        ),
    ]
