# Generated by Django 5.2.4 on 2026-02-07 16:34

from django.db import migrations


def seed_tiers(apps, schema_editor):
    MobileAppConfig = apps.get_model('conversation', 'MobileAppConfig')
    DegradationTier = apps.get_model('conversation', 'DegradationTier')

    cfg, _ = MobileAppConfig.objects.get_or_create(pk=1)

    defaults = [
        # Opener tiers
        {'tier_type': 'opener', 'sort_order': 0, 'threshold': 8, 'model': 'gemini-3-pro-preview', 'thinking_level': 'high'},
        {'tier_type': 'opener', 'sort_order': 1, 'threshold': 50, 'model': 'gemini-3-flash-preview', 'thinking_level': 'high'},
        # Reply tiers
        {'tier_type': 'reply', 'sort_order': 0, 'threshold': 50, 'model': 'gemini-3-flash-preview', 'thinking_level': 'high'},
        {'tier_type': 'reply', 'sort_order': 1, 'threshold': 100, 'model': 'gemini-3-flash-preview', 'thinking_level': 'low'},
    ]

    for tier_data in defaults:
        DegradationTier.objects.create(config=cfg, **tier_data)


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0017_remove_mobileappconfig_sub_opener_tier1_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_tiers, migrations.RunPython.noop),
    ]
