# Generated by Django 5.2.4 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0018_seed_default_tiers"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceDailyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_hash", models.CharField(db_index=True, max_length=64)),
                ("day", models.DateField(db_index=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device_hash", "day"),
                        name="unique_device_hash_day_usage",
                    ),
                ],
            },
        ),
    ]
