# Generated by Django 5.2.4 on 2026-02-27 20:55

from django.db import migrations, models


def copy_registered_defaults_from_free(apps, schema_editor):
    MobileAppConfig = apps.get_model('conversation', 'MobileAppConfig')
    for cfg in MobileAppConfig.objects.all():
        cfg.registered_reply_model = cfg.free_reply_model
        cfg.registered_reply_thinking = cfg.free_reply_thinking
        cfg.registered_opener_model = cfg.free_opener_model
        cfg.registered_opener_thinking = cfg.free_opener_thinking
        cfg.save(
            update_fields=[
                'registered_reply_model',
                'registered_reply_thinking',
                'registered_opener_model',
                'registered_opener_thinking',
            ]
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0019_devicedailyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappconfig',
            name='registered_opener_model',
            field=models.CharField(default='gemini-3-flash-preview', help_text='AI model for signed-in non-subscriber openers', max_length=100),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='registered_opener_thinking',
            field=models.CharField(default='high', help_text='Thinking level for signed-in non-subscriber openers (minimal/low/medium/high)', max_length=20),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='registered_reply_model',
            field=models.CharField(default='gemini-3-flash-preview', help_text='AI model for signed-in non-subscriber replies', max_length=100),
        ),
        migrations.AddField(
            model_name='mobileappconfig',
            name='registered_reply_thinking',
            field=models.CharField(default='high', help_text='Thinking level for signed-in non-subscriber replies (minimal/low/medium/high)', max_length=20),
        ),
        migrations.RunPython(copy_registered_defaults_from_free, noop_reverse),
        migrations.AlterField(
            model_name='mobileappconfig',
            name='free_opener_model',
            field=models.CharField(default='gemini-3-flash-preview', help_text='AI model for guest (unauthenticated) openers', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobileappconfig',
            name='free_opener_thinking',
            field=models.CharField(default='high', help_text='Thinking level for guest openers (minimal/low/medium/high)', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobileappconfig',
            name='free_reply_model',
            field=models.CharField(default='gemini-3-flash-preview', help_text='AI model for guest (unauthenticated) replies', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobileappconfig',
            name='free_reply_thinking',
            field=models.CharField(default='high', help_text='Thinking level for guest replies (minimal/low/medium/high)', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobileappconfig',
            name='ocr_thinking',
            field=models.CharField(default='low', help_text='Thinking level for OCR extraction (minimal/low/medium/high)', max_length=20),
        ),
    ]
