# Generated by Django 5.2.4 on 2026-03-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0020_mobileappconfig_registered_opener_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedopener',
            name='vault_unblurred_priority',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Optional admin priority for unlocked vault openers (1 = highest).', null=True),
        ),
    ]
