# Generated by Django 5.2.4 on 2026-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0021_recommendedopener_vault_unblurred_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappconfig',
            name='community_default_sort',
            field=models.CharField(
                choices=[('new', 'New'), ('hot', 'Hot'), ('top', 'Top')],
                default='new',
                help_text='Default community feed sort when clients do not pass a sort query param',
                max_length=10,
            ),
        ),
    ]
