# Generated by Django 5.2.4 on 2026-03-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0023_webappconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='webappconfig',
            name='guest_reply_limit',
            field=models.PositiveIntegerField(default=5, help_text='Free reply generations for unauthenticated web users.'),
        ),
        migrations.AddField(
            model_name='webappconfig',
            name='signup_bonus_credits',
            field=models.PositiveIntegerField(default=3, help_text='Free credits granted to newly signed-up web users.'),
        ),
    ]
