# Generated by Django 6.0.3 on 2026-03-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0024_webappconfig_guest_reply_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestWebConversationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_key_hash', models.CharField(db_index=True, max_length=64)),
                ('endpoint', models.CharField(choices=[('conversations_ajax_reply', 'Conversations Ajax Reply'), ('ajax_reply_home', 'Ajax Reply Home')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('validation_error', 'Validation Error'), ('credits_blocked', 'Credits Blocked'), ('ai_error', 'AI Error'), ('parse_error', 'Parse Error'), ('request_error', 'Request Error')], db_index=True, max_length=32)),
                ('http_status', models.PositiveSmallIntegerField()),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', 'status', 'created_at'], name='conversatio_endpoin_6eba38_idx')],
            },
        ),
    ]
