# Generated by Django 5.2.4 on 2026-09-23 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0025_guestwebconversationattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='guest_draft_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='latest_generation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='latest_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='WebConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('journey_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('generated', 'Successful generation'), ('copied', 'Copy action'), ('offer_shown', 'Continuation displayed'), ('offer_clicked', 'Continuation clicked'), ('signup', 'Completed signup'), ('checkout', 'Checkout redirect')], db_index=True, max_length=24)),
                ('generation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('dedupe_key', models.CharField(max_length=160, unique=True)),
                ('was_guest', models.BooleanField(default=True)),
                ('origin_path', models.CharField(blank=True, max_length=255)),
                ('situation', models.CharField(blank=True, max_length=150)),
                ('offer_kind', models.CharField(blank=True, max_length=16)),
                ('credit_pack', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['journey_id', 'created_at'], name='web_journey_created_idx')],
            },
        ),
    ]
