# Generated by Django 5.2.4 on 2026-10-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0026_conversation_guest_draft_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webappconfig',
            name='gemini_ocr_model',
            field=models.CharField(default='gemini-3-flash-preview', help_text='Image-capable Gemini model for web screenshot extraction.', max_length=100),
        ),
        migrations.AddField(
            model_name='webappconfig',
            name='gemini_reply_model',
            field=models.CharField(default='gemini-3-flash-preview', help_text='Gemini model for web replies and openers, e.g. gemini-3.8-flash.', max_length=100),
        ),
        migrations.AddField(
            model_name='webappconfig',
            name='gpt_ocr_model',
            field=models.CharField(default='gpt-4.1-mini-2025-04-14', help_text='Image-capable GPT model for web screenshot extraction.', max_length=100),
        ),
        migrations.AddField(
            model_name='webappconfig',
            name='gpt_reply_model',
            field=models.CharField(default='gpt-4.1-mini-2025-04-14', help_text='GPT model for web replies and openers, used in the configured provider order.', max_length=100),
        ),
        migrations.AddField(
            model_name='webappconfig',
            name='ocr_thinking',
            field=models.CharField(default='minimal', help_text='Gemini OCR thinking (minimal/low/medium/high). Gemini 3.8 uses low for minimal.', max_length=20),
        ),
        migrations.AddField(
            model_name='webappconfig',
            name='reply_thinking',
            field=models.CharField(default='minimal', help_text='Gemini reply thinking (minimal/low/medium/high). Gemini 3.8 uses low for minimal.', max_length=20),
        ),
    ]
