# Generated by Django 5.2.4 on 2026-02-27 22:29

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('conversation', '0020_mobileappconfig_registered_opener_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppConfigProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Mobile App Config',
                'verbose_name_plural': 'Mobile App Config',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('conversation.mobileappconfig',),
        ),
        migrations.CreateModel(
            name='MobileDeviceDailyUsage',
            fields=[
            ],
            options={
                'verbose_name': 'Device Daily Usage',
                'verbose_name_plural': 'Device Daily Usage',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('conversation.devicedailyusage',),
        ),
        migrations.CreateModel(
            name='MobileGuestTrial',
            fields=[
            ],
            options={
                'verbose_name': 'Guest Trial',
                'verbose_name_plural': 'Guest Trials',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('conversation.guesttrial',),
        ),
        migrations.CreateModel(
            name='MobileLockedReply',
            fields=[
            ],
            options={
                'verbose_name': 'Locked Reply',
                'verbose_name_plural': 'Locked Replies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('conversation.lockedreply',),
        ),
        migrations.CreateModel(
            name='MobileRecommendedOpener',
            fields=[
            ],
            options={
                'verbose_name': 'Recommended Opener',
                'verbose_name_plural': 'Recommended Openers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('conversation.recommendedopener',),
        ),
        migrations.CreateModel(
            name='MobileSignupUser',
            fields=[
            ],
            options={
                'verbose_name': 'Mobile Signup User',
                'verbose_name_plural': 'Mobile Signup List',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MobileGenerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guest_id_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_type', models.CharField(choices=[('free', 'Free'), ('authenticated_non_subscribed', 'Authenticated Non-Subscribed'), ('subscribed', 'Subscribed')], db_index=True, max_length=32)),
                ('action_type', models.CharField(choices=[('reply', 'Reply'), ('opener', 'Opener')], db_index=True, max_length=16)),
                ('source_type', models.CharField(choices=[('ai', 'AI'), ('recommended_static', 'Recommended Static')], db_index=True, max_length=32)),
                ('model_used', models.CharField(max_length=120)),
                ('thinking_used', models.CharField(blank=True, max_length=20, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('thinking_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('generated_json', models.TextField()),
                ('reply_ocr_text', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_generation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileCopyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guest_id_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_type', models.CharField(choices=[('free', 'Free'), ('authenticated_non_subscribed', 'Authenticated Non-Subscribed'), ('subscribed', 'Subscribed')], db_index=True, max_length=32)),
                ('copy_type', models.CharField(choices=[('reply', 'Reply'), ('opener', 'Opener')], db_index=True, max_length=16)),
                ('copied_text', models.TextField()),
                ('reply_context_ocr_text', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_copy_events', to=settings.AUTH_USER_MODEL)),
                ('generation_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copy_events', to='mobileapi.mobilegenerationevent')),
            ],
            options={
                'verbose_name': 'Copy Event',
                'verbose_name_plural': 'Copy Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mobilegenerationevent',
            index=models.Index(fields=['user', 'created_at'], name='mobileapi_m_user_id_306bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilegenerationevent',
            index=models.Index(fields=['guest_id_hash', 'created_at'], name='mobileapi_m_guest_i_cecb51_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilegenerationevent',
            index=models.Index(fields=['user_type', 'action_type', 'created_at'], name='mobileapi_m_user_ty_bdfb3b_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilegenerationevent',
            index=models.Index(fields=['source_type', 'created_at'], name='mobileapi_m_source__451aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilecopyevent',
            index=models.Index(fields=['user', 'created_at'], name='mobileapi_m_user_id_1daf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilecopyevent',
            index=models.Index(fields=['guest_id_hash', 'created_at'], name='mobileapi_m_guest_i_d2a92f_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilecopyevent',
            index=models.Index(fields=['user_type', 'copy_type', 'created_at'], name='mobileapi_m_user_ty_14a69d_idx'),
        ),
    ]
