# Generated by Django 5.2.4 on 2026-03-01 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reignitehome", "0003_marketingclickevent"),
        ("mobileapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileInstallAttributionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("guest_id_hash", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("install_referrer_raw", models.TextField(blank=True, default="")),
                ("utm_source", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("utm_medium", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("utm_campaign", models.CharField(blank=True, db_index=True, default="", max_length=160)),
                ("utm_content", models.CharField(blank=True, default="", max_length=160)),
                ("utm_term", models.CharField(blank=True, default="", max_length=160)),
                ("ffclid", models.UUIDField(blank=True, db_index=True, null=True)),
                ("install_begin_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("referrer_click_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_organic", models.BooleanField(db_index=True, default=False)),
                ("app_version", models.CharField(blank=True, default="", max_length=50)),
                ("idempotency_key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "click_event",
                    models.ForeignKey(
                        blank=True,
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mobile_install_events",
                        to="reignitehome.marketingclickevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mobile_install_attribution_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Install Attribution Event",
                "verbose_name_plural": "Install Attribution Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mobileinstallattributionevent",
            index=models.Index(
                fields=["created_at", "utm_source", "utm_campaign"],
                name="mobileapi_mi_created_utm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mobileinstallattributionevent",
            index=models.Index(
                fields=["guest_id_hash", "created_at"],
                name="mobileapi_mi_guest_created_idx",
            ),
        ),
    ]
