# Generated by Django 5.2.4 on 2026-03-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapi', '0002_mobileinstallattributionevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilegenerationevent',
            name='action_type',
            field=models.CharField(choices=[('reply', 'Reply'), ('opener', 'Opener'), ('ocr', 'OCR')], db_index=True, max_length=16),
        ),
    ]
