# Generated by Django 5.2.4 on 2026-03-27 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobileapi", "0003_alter_mobilegenerationevent_action_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileReplyThread",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(max_length=140)),
                ("stitched_transcript", models.TextField()),
                ("latest_replies", models.JSONField(blank=True, default=list)),
                ("thumbnail_url", models.TextField(blank=True, default="")),
                (
                    "latest_generation_event",
                    models.ForeignKey(
                        blank=True,
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reply_threads",
                        to="mobileapi.mobilegenerationevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_reply_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile Reply Thread",
                "verbose_name_plural": "Mobile Reply Threads",
                "ordering": ["-updated_at", "-id"],
                "indexes": [models.Index(fields=["user", "updated_at"], name="mobileapi_m_user_id_95c350_idx")],
            },
        ),
    ]
