# Generated by Django 5.2.4 on 2026-03-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapi', '0004_mobilereplythread'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mobilereplythread',
            new_name='mobileapi_m_user_id_a36857_idx',
            old_name='mobileapi_m_user_id_95c350_idx',
        ),
    ]
