# Generated by Django 5.2.4 on 2025-08-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrialIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('trial_used', models.BooleanField(default=False)),
            ],
        ),
    ]
