# Generated by Django 5.2.4 on 2025-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reignitehome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('bug', 'Bug Report'), ('payment', 'Payments'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
