# Generated by Django 5.2.4 on 2026-03-01 12:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reignitehome", "0002_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingClickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("route_key", models.CharField(db_index=True, max_length=50)),
                (
                    "click_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("utm_source", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("utm_medium", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("utm_campaign", models.CharField(blank=True, db_index=True, default="", max_length=160)),
                ("utm_content", models.CharField(blank=True, default="", max_length=160)),
                ("utm_term", models.CharField(blank=True, default="", max_length=160)),
                ("referrer_host", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("ip_hash", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("user_agent", models.CharField(blank=True, default="", max_length=255)),
                ("target_url", models.URLField(max_length=500)),
                ("raw_query", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="marketingclickevent",
            index=models.Index(fields=["route_key", "created_at"], name="rh_mclick_route_created_idx"),
        ),
        migrations.AddIndex(
            model_name="marketingclickevent",
            index=models.Index(
                fields=["utm_source", "utm_campaign", "created_at"],
                name="rh_mclick_src_campaign_idx",
            ),
        ),
    ]
