# Generated by Django 5.2.4 on 2026-03-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'pickup categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PickupTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('keyword', models.CharField(max_length=200)),
                ('h1', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('meta_description', models.TextField()),
                ('seo_intro', models.TextField()),
                ('witty_lines', models.JSONField(default=list)),
                ('flirty_lines', models.JSONField(default=list)),
                ('cheesy_lines', models.JSONField(default=list)),
                ('prefill_text', models.TextField()),
                ('upload_hint', models.TextField()),
                ('her_info_prefill', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='seoapp.pickupcategory')),
            ],
            options={
                'ordering': ['category__sort_order', 'sort_order', 'keyword'],
                'constraints': [models.UniqueConstraint(fields=('category', 'slug'), name='unique_category_topic_slug')],
            },
        ),
    ]
